### ISSUE TITLE
The finalizer for failed AWXBackup resource cannot be completed

### ISSUE THREAD

**Issue by kurokobo** [ansible/tower-operator#1003]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The finalizer for failed AWXBackup resource cannot be completed and the resource cannot be deleted.

### AWX Operator version

0.25.0

### AWX version

21.3.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

K3s v1.24.3+k3s1

### Modifications

no

### Steps to reproduce

1. Create AWXBackup resource with incorrect configuration to force to fail the backup role. In this case, use incorrect `postgres_image` and `postgres_image_version`.
   ```yaml
   ---
   apiVersion: awx.ansible.com/v1beta1
   kind: AWXBackup
   metadata:
     name: awxbackup-failed
     namespace: awx
   spec:
     deployment_name: awx
     backup_pvc: awx-backup-claim
     postgres_image: dummy
     postgres_image_version: dummy
   ```
   ```bash
   kubectl apply -f awxbackup.yml
   ```
2. Ensure the backup role cannot be completed as expected.
   ```bash
   kubectl -n awx logs -f deployments/awx-operator-controller-manager -c awx-manager
   ```
4. Try to delete failed AWXBackup resouce and ensure `delete` command does not complete and does not return a prompt.
   ```bash
   $ kubectl -n awx delete awxbackup awxbackup-failed
   awxbackup.awx.ansible.com "awxbackup-failed" deleted
   ^C
   ```
5. Ensure the log shows `FAILED` in the task in `finalizer.yml` (`\n` are replaced with new line).
   ```text
   task path: /opt/ansible/roles/backup/tasks/finalizer.yml:11
   fatal: [localhost]: FAILED! => {"msg": "The conditional check 'clean_backup_on_delete and backup_dir is defined' failed.    The error was: error while evaluating conditional (clean_backup_on_delete and backup_dir is defined): {{ this_backup   ['resources'][0]['status']['backupDirectory'] }}: 'dict object' has no attribute 'backupDirectory'
   
   The error appears to be in '/opt/ansible/roles/backup/tasks/finalizer.yml': line 11, column 7, but may
   be elsewhere in the file depending on the exact syntax problem.
   
   The offending line appears to be:
   
   - block:
       - include_tasks: init.yml
         ^ here
   "}
   ```

### Expected results

The failed AWXBackup resource can be deleted.

### Actual results

The failed AWXBackup resource cannot be deleted.

### Additional information

This issue came from [here](https://github.com/ansible/awx-operator/blob/0.25.0/roles/backup/tasks/finalizer.yml#L10-L19).

```yaml
- block:
  ...
  vars:
    backup_dir: "{{ this_backup['resources'][0]['status']['backupDirectory'] }}"
  when:
    - clean_backup_on_delete and backup_dir is defined
```

The `status.backupDirectory` is saved after the backup completes, so a _failed_ AWXBackup resource will not have this field.

Therefore, when deleting a failed AWXBackup, the evaluation for the `vars` will fail and the finalizer will never complete. The finalizer continues to retry.

As a workaround, removing the `finalizers` will proceed to delete the resource.

```bash
$ kubectl -n awx patch awxbackup awxbackup-failed --type=json -p='[{"op": "remove", "path": "/metadata/finalizers"}]'
```

### Operator Logs

See the log in the "Steps to reproduce".
