### ISSUE TITLE
Team is not appearing in templates to use

### ISSUE THREAD

**Issue by sincorchetes** [ansible/tower-operator#1042]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### AWX Operator version

0.28.0

### AWX version

21.5.0

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

k3s

### Modifications

no

### Steps to reproduce

1. Deploy Rocky Linux 8 server
2. Setup the pre-setup tools (git, curl, make)
3. Install k3s without traefik
4. Deploy nginx-ingress
5. Deploy cert-manager
6. Clone awx-operator repo
7. checkout 0.28.0 tag
8. make deploy
9. Wait to finish
10. Deploy AWX
```
cat <<EOF | kubectl apply -f -
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: clusterip
  projects_persistence: false
  projects_storage_class: local-path
  postgres_storage_class: local-path
EOF
```
12. Wait to create
13. Generate ingress
14. Get the AWX admin password
15. Access to the web
16. Add users
17. Add a team
18. Add machine credentials 
19. Add a host
20. Add a template and set up the host, credentials, and so on
21. Modify the template to add a team
22. Confirm it
23. Team added.
26. You don't see the team users

However, if you go to the "Teams -> Roles->Role you created"  you can see all templates you matched. 

Little crazy...

### Expected results

See the team users

### Actual results

No team users showed the users could not run templates.

### Additional information

If you add users (no teams), these users are displayed and these users can execute playbooks.
