### ISSUE TITLE
Add ability to specify annotation for postgres

### ISSUE THREAD

**Issue by rparree** [ansible/tower-operator#1043]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

I would like to use k8up to perform the backup of AWX. First because i would like to have one consistent way to perform all backups (we use k8up). Second because i can't get the built-in backup working yet.

Backups for k8up work by adding an annotation to a pod. I would need to add the following annotations:

```yaml
annotations:
  k8up.io/backupcommand: |
    /bin/bash -c 'pg_dump -U $POSTGRES_USER $POSTGRES_DB '
  k8up.io/file-extension: .sql
```

However there's currently no way of adding this to the postrgres pod(s). There are options to add annotations (`service_account_annotations`, `ingress_annotations`, `service_annotations` and `annotations` for all pods. 

I could add `postgres_annotations`

If this seems like a good idea, then i could add it and submit a PR.
