### ISSUE TITLE
CRD Lacks Input for Ingress Class Names

### ISSUE THREAD

**Issue by ghost** [ansible/tower-operator#1050]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Sometimes there may be multiple ingresses installed, so use of IngressClasses is necessary. This operator doesn't seem to provide a way to set `.spec.ingressClassName` for `ingresses.networking.k8s.io/v1` resources. 

The workaround is to just set `ingress_type: none` and manage the ingress manually. 

### AWX Operator version

0.28.0

### AWX version

unsure, issue is operator related though

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.24.x

### Modifications

no

### Steps to reproduce

```
helm install -n ingress-nginx ingress-nginx ingress-nginx --create-namespace --set controller.kind="DaemonSet" --set prometheus.enabled=false --set controller.ingressClassResource.default=true --repo https://kubernetes.github.io/ingress-nginx

helm install -n awx awx-operator awx-operator --repo https://ansible.github.io/awx-operator

cat <<'EOF' | kubectl apply -f -
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-deployment
  namespace: awx
spec:
  service_type: ClusterIP
  ingress_type: ingress
  ingress_tls_secret: awx-deployment-tls
  ingress_annotations: |
    cert-manager.io/cluster-issuer: letsencrypt-production
  hostname: YOUR HOSTNAME HERE
EOF
```

### Expected results

I don't even think ingresses work without the class defined.

### Actual results

I don't even think ingresses work without the class defined.
