### ISSUE TITLE
Init container unable to start

### ISSUE THREAD

**Issue by happytreees** [ansible/tower-operator#1054]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

During init phase for the redis container it is failing to start due to permissions issues in the init container.

Pulled the following from logs:
```
chmod: changing permissions of '/var/lib/awx/projects': Operation not permitted
chgrp: changing group of '/var/lib/awx/projects': Operation not permitted
```

### AWX Operator version

0.29.0

### AWX version

21.6.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.22.8

### Modifications

no

### Steps to reproduce

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  admin_user: newadmin
  postgres_storage_requirements:
    requests:
      storage: 100Gi
  projects_persistence: true
  projects_storage_size: 100Gi
  projects_storage_access_mode: ReadWriteOnce
```

### Expected results

Init container successfully starts without issue

### Actual results

Init container fails with provided output
```
chmod: changing permissions of '/var/lib/awx/projects': Operation not permitted
chgrp: changing group of '/var/lib/awx/projects': Operation not permitted
```

**Comment by happytreees** [comment]
Found this in the helm chart:
```
  security_context_settings:
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
```

Added it to manifest and it started without issue
