### ISSUE TITLE
Awx-operator Helm upgrade fails due to version labels in selector

### ISSUE THREAD

**Issue by andriktr** [ansible/tower-operator#1057]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi, 
If we try to run `helm upgrade` for awx-operator for example from 0.28.0 to 0.29.0 version update is failing with the following error: 
```
Error: UPGRADE FAILED: release awx-operator failed, and has been rolled back due to atomic being set: cannot patch "awx-operator-controller-manager" with kind Deployment: Deployment.apps "awx-operator-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"control-plane":"controller-manager", "helm.sh/chart":"awx-operator-0.29.0"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
The reason for this is a version label used in deployment selector:

```
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      helm.sh/chart: awx-operator-0.29.0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        helm.sh/chart: awx-operator-0.29.0
```

Deployment selector labels are immutable and can't be changed during upgrade [https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#label-selector-updates)
In our case this selector changes from one version to another

### AWX Operator version

0.28.0

### AWX version

21.5.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.23.5

### Modifications

no

### Steps to reproduce

run helm upgrade for awx-operator

### Expected results

deployment upgraded

### Actual results

upgrade fails with 
```
Error: UPGRADE FAILED: release awx-operator failed, and has been rolled back due to atomic being set: cannot patch "awx-operator-controller-manager" with kind Deployment: Deployment.apps "awx-operator-controller-manager" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"control-plane":"controller-manager", "helm.sh/chart":"awx-operator-0.29.0"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
