### ISSUE TITLE
$ character in admin password secret > login failed

### ISSUE THREAD

**Issue by janorn** [ansible/tower-operator#1080]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Creating a secret like this.
```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secret-password
  namespace: awx
stringData:
  password: "Te$t1$3"
```
And put it in the spec config:
```yaml
      spec:
        admin_user: admin
        admin_password_secret: admin-secret-password
```

Will yield this result when trying to login:
"Invalid username or password. Please try again."

### AWX Operator version

0.30.0

### AWX version

21.7.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.23.5

### Modifications

no

### Steps to reproduce

Using helm setting it up with the secret described in the summary.

### Expected results

Be able to login to the GUI as admin.

### Actual results

"Invalid username or password. Please try again."

### Additional information

```yaml
      spec:
        admin_user: admin
        admin_password_secret: admin-secret-password
```

### Operator Logs

Have the deployment log saved but don't know what part could be intersting. Belive this to be a quotation bug somewhere in the code.

**Comment by jameshearttech** [comment]
Same issue here. Removed the $ and the admin password works. Thanks you @janorn! You likely just saved me a lot of time and frustration.

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - https://www.github.com/ansible/awx-operator/config/default?ref=1.1.0

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 1.1.0

# Specify a custom namespace in which to install AWX.
namespace: awx
```

```
$ kubectl get nodes -o wide
NAME          STATUS   ROLES           AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
dev-master0   Ready    control-plane   23d   v1.25.3   10.69.2.30    <none>        Ubuntu 22.04.1 LTS   5.15.0-52-generic   containerd://1.6.9
dev-master1   Ready    control-plane   23d   v1.25.3   10.69.2.31    <none>        Ubuntu 22.04.1 LTS   5.15.0-52-generic   containerd://1.6.9
dev-master2   Ready    control-plane   23d   v1.25.3   10.69.2.32    <none>        Ubuntu 22.04.1 LTS   5.15.0-52-generic   containerd://1.6.9
dev-worker0   Ready    <none>          23d   v1.25.3   10.69.2.33    <none>        Ubuntu 22.04.1 LTS   5.15.0-53-generic   containerd://1.6.9
dev-worker1   Ready    <none>          23d   v1.25.3   10.69.2.34    <none>        Ubuntu 22.04.1 LTS   5.15.0-53-generic   containerd://1.6.9
dev-worker2   Ready    <none>          23d   v1.25.3   10.69.2.35    <none>        Ubuntu 22.04.1 LTS   5.15.0-53-generic   containerd://1.6.9
```
