### ISSUE TITLE
Awx notification doesn't take the hostname

### ISSUE THREAD

**Issue by craph** [ansible/tower-operator#1085]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After I setup the ingress_type to ingress and the hostname. When I receive notification from AWX in Mattermost the URL is always set to "towerhost"...

### AWX Operator version

21.7.0

### AWX version

awx-ee 

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.20.15

### Modifications

no

### Steps to reproduce

awx-demo.yml
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  ingress_type: ingress
  hostname: awx.server.com
  postgres_storage_class: longhorn
```

Then setup notification for Mattermost
![image](https://user-images.githubusercontent.com/14820052/195772531-b09ad285-564c-4427-a508-f4075d4779a8.png)

### Expected results

When I receive a notification in Mattermost, the URL should be correct to my awx hostname.

example : https://awx.server.com/#/jobs/playbook/14

### Actual results

I receive this : https://towerhost/#/jobs/playbook/14
