### ISSUE TITLE
awx-operator crashing on GKE Autopilot

### ISSUE THREAD

**Issue by kogarastu** [ansible/tower-operator#1115]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hello,

We deployed AWX-OPERATOR v 1.0.0 on a GCP GKE Autopilot cluster with a version of K8S V1.23.8-gke.1900. We encountered the following errors while deploying the operator:
   CrashLoopBackOff on awx-operator-controller-manager-5457cf7b4c-pod

We believe that GKE's Autopilot feature, which among other things redefines the CPU and memory resources of pods, is to blame:
annotations:
    autopilot.gke.io/resource-adjustment 

**Before autopilot resource adjustment**

```
name: kube-rbac-proxy
  ports:
    - containerPort: 8443
      name: https
      protocol: TCP
  resources:
    limits:
      cpu: 200m
      ephemeral-storage: 1Gi
      memory: 480Mi
    requests:
      cpu: 200m
      ephemeral-storage: 1Gi
      memory: 480Mi

name: awx-manager
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /readyz
      port: 6789
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    limits:
      cpu: 50m
      ephemeral-storage: 1Gi
      memory: 32Mi
    requests:
      cpu: 50m
      ephemeral-storage: 1Gi
      memory: 32Mi
```
After Autopilot resource-adjustment    
  
```
name: kube-rbac-proxy
  ports:
    - containerPort: 8443
      name: https
      protocol: TCP
  resources:
    limits:
      cpu: 500m
      ephemeral-storage: 1Gi
      memory: 128Mi <-
    requests:
      cpu: 5m   <-
      ephemeral-storage: 1Gi
      memory: 64Mi  <-

name: awx-manager
  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /readyz
      port: 6789
      scheme: HTTP
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  resources:
    limits:
      cpu: '2'
      ephemeral-storage: 1Gi
      memory: 4Gi
    requests:
      cpu: 50m
      ephemeral-storage: 1Gi
      memory: 32Mi
```

Have you encountered this type of problem on GCP GKE Autopilot. For information, the installation of the operator on standard GKE does not pose a problem.

Thank you for your reply.

Regards
