### ISSUE TITLE
ee image tag can not be set

### ISSUE THREAD

**Issue by weironz** [ansible/tower-operator#1119]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

install 
```
helm upgrade -i awx charts/awx-operator -n awx --create-namespace --set AWX.enabled=true,AWX.spec.service_type=NodePort,AWX.spec.ee_images[0].name=awx-ee,AWX.spec.ee_images[0].image=quay.io/ansible/awx-ee:0.6.0
```
```
# helm -n awx get values awx
USER-SUPPLIED VALUES:
AWX:
  enabled: true
  spec:
    ee_images:
    - image: quay.io/ansible/awx-ee:0.6.0
      name: awx-ee
    service_type: NodePort
```
it still use latest image tag

```
# kubectl -n awx get pods -o yaml |grep image: |grep awx-ee
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
```

### AWX Operator version

1.0.0

### AWX version

21.8.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.25.3

### Modifications

no

### Steps to reproduce

install 
```
helm upgrade -i awx awx-operator/awx-operator -n awx --create-namespace --set AWX.enabled=true,AWX.spec.service_type=NodePort,AWX.spec.ee_images[0].name=awx-ee,AWX.spec.ee_images[0].image=quay.io/ansible/awx-ee:0.6.0
```

### Expected results

awx-ee image should be 0.6.0

### Actual results

it still use latest image tag

```
# kubectl -n awx get pods -o yaml |grep image: |grep awx-ee
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
      image: quay.io/ansible/awx-ee:latest
```

**Comment by djyasin** [comment]
Hello, 
At this time Helm is community supported. @miles-w-3 Can you shed any light on this situation?

**Comment by miles-w-3** [comment]
@djyasin, in most cases, the helm chart just adds any configurations from the values file into an awx resource. This is the output from his values file when using the helm chart. Can you confirm whether this is a valid AWX spec for what @willzhang is trying to accomplish, assuming he used kustomize? 

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: default
spec:
  admin_user: admin
  ee_images:
  - image: quay.io/ansible/awx-ee:0.6.0
    name: awx-ee
  service_type: NodePort
  security_context_settings:
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
```
