### ISSUE TITLE
BUG on Receptor configuration - No verifysignature param

### ISSUE THREAD

**Issue by tanganellilore** [ansible/tower-operator#1132]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Good Morning Team,

I dicover a bug on Receptor configuration ConfigMap during the deployment of AWX. 
This bug can be refferred to AWX commit: [84f2b91105c959c4d89a63063cca441f3d67fc0f](https://github.com/ansible/awx/commit/84f2b91105c959c4d89a63063cca441f3d67fc0f) this [PR](https://github.com/ansible/awx/pull/13200) where introduced the  `sign_work` variable and `work_signing_enabled(config_data)` fuction that check if `work-verification` section is preset in the `/etc/receptor/receptor.conf` .

To align `awx-operator` to this commint we need to add [awx-operator/roles/installer/templates/configmaps/config.yaml.j2](https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/configmaps/config.yaml.j2), in `receptor_conf ` section the following part:
Adding  on key `work-command`, `work-kubernetes`, `work-kubernetes`
```yaml
verifysignature: true
```
Adding this section
```yaml
- work-verification:
    publickey: /etc/receptor/work_public_key.pem
```

Moreover, another issue is realted the installation bundle of execution_node. Due to the fact that `sign_work` is not poulated, the respective `verifysignature` key in the bundle is empty, and this create issue on the receptor configuration.

I will try to propose you a PR to fix this issue in a short time and I will try tro introduce a variable to enable/disable the `sign_work`.

### AWX Operator version

1.1.0

### AWX version

21.9.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.23.2

### Modifications

no

### Steps to reproduce

Update or install 21.9.0 and add new execution node.

Download the instalaltion bundle and you will se that verifysignature is missing.
If you enable it, execution node not work, because controller node not have the same setting

### Expected results

verifysignature enabled and working

### Actual results

Remote error: ERROR: could not parse response: ERROR: could not verify signature: signature is empty

**Comment by AlanCoding** [comment]
There is a promising fix at https://github.com/ansible/awx/pull/13253, and that will likely make any operator changes a mute point.

The installer bundle for remote execution nodes were always intended to have verifywork set to True, and it appears that it was set to False simply as a recent regression.

**Comment by tanganellilore** [comment]
This will cover only bundle installation, but not the verification   key on awx side.

Due to this commit: https://github.com/ansible/awx/commit/84f2b91105c959c4d89a63063cca441f3d67fc0f
If we don't add `work-verification` on the receptor side in EE container (on k8s deployment) and we don't bind the sign key,  I think this will not resolve, because receptor on EE will not have a bind key to sign and backend will not run a job with sign key.
Tomorrow i will send you the error of 21.9.0 k8s deployment with verifysignature a true on external execution node.

**Comment by tanganellilore** [comment]
Below, the info promised:

AWX: 21.9.0
receptor.conf
```yaml
---
- node:
    id: XX.XX.XX.XX

- work-verification:
    publickey: /etc/receptor/work_public_key.pem

- log-level: info

- control-service:
    service: control
    filename: /var/run/receptor/receptor.sock
    permissions: 0660
    tls: tls_server
- tls-server:
    name: tls_server
    cert: /etc/receptor/tls/XX.XX.XX.XX.crt
    key: /etc/receptor/tls/XX.XX.XX.XX.key
    clientcas: /etc/receptor/tls/ca/mesh-CA.crt
    requireclientcert: true
    mintls13: False

- tls-client:
    name: tls_client
    cert: /etc/receptor/tls/XX.XX.XX.XX.crt
    key: /etc/receptor/tls/XX.XX.XX.XX.key
    rootcas: /etc/receptor/tls/ca/mesh-CA.crt
    insecureskipverify: false
    mintls13: False
- tcp-listener:
    port: 27199
    tls: tls_server

- work-command:
    worktype: ansible-runner
    command: ansible-runner
    params: worker
    allowruntimeparams: True
    verifysignature: True
```

If i run the healthcheck on awx side, If i run the healthcheck 
AWXside:
`Remote error: ERROR: could not parse response: ERROR: could not verify signature: signature is empty`

Receptor Side:
```
INFO 2022/12/02 13:26:57 Connection established with awx-54c6f6fbf5-6pmqf
INFO 2022/12/02 13:26:57 Known Connections:
INFO 2022/12/02 13:26:57    XX.XX.XX.XX: awx-54c6f6fbf5-6pmqf
INFO 2022/12/02 13:26:57    awx-54c6f6fbf5-6pmqf:  XX.XX.XX.XX
INFO 2022/12/02 13:26:57 Routing Table:
INFO 2022/12/02 13:26:57    awx-54c6f6fbf5-6pmqf via awx-54c6f6fbf5-6pmqf
ERROR 2022/12/02 13:27:19 could not verify signature: signature is empty
ERROR 2022/12/02 13:27:40 could not verify signature: signature is empty
```

You can see that with `verifysignature` we still have the issue, due to the fact that on AWX side we don't have the `work-verification` key on K8s Configmap.
Please see this line of code: https://github.com/ansible/awx/blob/devel/awx/main/tasks/receptor.py#L175
If `work-verification` in not present on awx side, everything will be runned without signkey from AWX side, but receptor expect to have signed command.

So we are in a loop also with the PR proposed.
