### ISSUE TITLE
Use custom CA for external Postgres encrypted

### ISSUE THREAD

**Issue by nbisson** [ansible/tower-operator#1134]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hi all,

I would like to connect AWX to external Postgres with `ssl_mode: require` and internal certificate authority.
Here my config files : 

```
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx-operator
stringData:
  host: default-db-cluster
  database: awx
  username: postgres
  password: ****
  sslmode: require
  type: unmanaged
type: Opaque
```

```
---
spec:
  ...
  postgres_configuration_secret: awx-postgres-configuration
```

I use bundle_cacert_secret to mount my internal CA.

```
---
spec:
  ...
  bundle_cacert_secret: ca-custom-certs
```

But it's not possible to override the file credentials.py with `sslrootcert` value.

It will be nice to add `sslrootcert` attribute to have : 
 ```
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx-operator
stringData:
  host: default-db-cluster
  database: awx
  username: postgres
  password: ****
  sslmode: require
  sslrootcert: /etc/pki/ca-trust/source/anchors/bundle-ca.crt
  type: unmanaged
type: Opaque
```

Thanks.

**Comment by nbisson** [comment]
I find a workaround. If you want to use your own CA, you can apply this solution : 

The Postgres configuration trust the `/etc/pki/tls/certs/ca-bundle.crt` file 
https://github.com/ansible/awx-operator/blob/dbd1e59a55cd7f9be1afa1ca3cf3ebbfd9267011/roles/installer/defaults/main.yml#L276

With `web_extra_volume_mounts` and `task_extra_volume_mounts`, you can overwrite the trust file with your own CA.

1 - add your own CA (doc https://github.com/ansible/awx-operator#trusting-a-custom-certificate-authority)
```
---
spec:
  ...
  bundle_cacert_secret: ca-custom-certs
```

2 - overwrite the `ca-bundle.crt` file
```
---
metadata:
  name: awx-demo
spec:
  ...
  web_extra_volume_mounts: |
    - name: awx-demo-bundle-cacert
      mountPath: /etc/pki/tls/certs/ca-bundle.crt
      readOnly: true
      subPath: bundle-ca.crt  
  task_extra_volume_mounts: |
    - name: awx-demo-bundle-cacert
      mountPath: /etc/pki/tls/certs/ca-bundle.crt
      readOnly: true
      subPath: bundle-ca.crt
```
