### ISSUE TITLE
`node_selector` does not apply to `controller-manager` pod

### ISSUE THREAD

**Issue by pat-s** [ansible/tower-operator#1237]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

With 

```ym
spec:
    node_selector: |
      kubernetes.io/arch: amd64
```

only the `awx` pod is altered but not the `controller-manager` pod. 

### AWX Operator version

1.1.4

### AWX version

21.11.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.24

### Modifications

no

### Steps to reproduce

Deploy AWX with the setting from above and inspect the `controller-manager` deployment. 

### Expected results

Setting `node_selector` applies to both `awx` and `controller-manager` pods.

### Actual results

`node_selector` was not applied to the `controller-manager` deployment.

**Comment by zachross1414** [comment]
I just spent a while struggling with this trying to use helm to install to an existing cluster. This should definitely be the intended behavior. To get around this, you have to install with kustomize, and include a patch in the kustomize.yaml file:
```
patches:
  - path: patch.yaml
```

patch.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-operator-controller-manager
  namespace: awx
spec:
  template:
    spec:
      nodeSelector:
        kubernetes.io/os: linux
```
