### ISSUE TITLE
Publish a build of the Operator on quay.io after each merge

### ISSUE THREAD

**Issue by Spredzy** [ansible/tower-operator#124]
As a new user lands on the README today, she it pointed to go and run the following command:

```
#> kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml
```

This file currently, makes the operator image points to 

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: awx-operator
  template:
    metadata:
      labels:
        name: awx-operator
    spec:
      serviceAccountName: awx-operator
      containers:
        - name: awx-operator
          image: "quay.io/ansible/awx-operator:0.6.0"
          imagePullPolicy: "Always"
```

They have been drastic changes between `0.6.0` and current operator in `devel` leading to some uncompatible deployment scenarios.

Having a post-merge build developer/contributor could point to in order to be able to deploy latest everything would offer a better experience.
