### ISSUE TITLE
[web/task split] delete old deployment when upgrading validate upgrade scenario

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/tower-operator#1242]
## instruction for replication a upgrade scenario 

deploy awx-operator from devel (make sure image_tag_base is set)
```
make docker-build docker-push deploy IMAGE_TAG_BASE=quay.io/<quay user>/awx-operator
```

create awx resource
```
ansible-playbook ansible/instantiate-awx-deployment.yml -e image_pull_policy=Always -e service_type=nodeport
```

VALIDATE that awx works by logging in the instance

set `auto_upgrade` to `false` in awx resource (this is so that we can change the image and image_version to prep for upgrade without the operator actually deployments)

build and deploy awx-operator from feature branch
```
make docker-build docker-push deploy IMG=quay.io/<username>/awx-operator:web-task-split
```

in `awx` resource update `image` and `image_version` to image built from feature branch and set `auto_upgrade` to `true`

## expected outcome 

awx-web and awx-task deployment is created
awx deployment is deleted 
awx become functional and is able to test e2e tests

**Comment by rooftopcellist** [comment]
After completing the above "vanilla" upgrade scenario, please do the same steps by with custom fields populated for the AWX spec that will exercise the templating changes that  have been made in the web-task split work.  

For example, for NodeSelector, you would want a section like this in the spec:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo-2
spec:
  no_log: false
   node_selector: |
     disktype: ssd
     kubernetes.io/arch: amd64
     kubernetes.io/os: linux
```

> Check to make sure that after the upgrade those node_selector values are set on both the web and task deployments.  

For fresh installs, we similarly need to deploy with settings, for example:

```
spec:
  web_node_selector: |
    disktype: ssd
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux

   task_node_selector: |
     disktype: ssd
     kubernetes.io/arch: amd64
     kubernetes.io/os: linux
```
