### ISSUE TITLE
Persistent storage not persistent

### ISSUE THREAD

**Issue by Anthirian** [ansible/tower-operator#1244]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Instances of AWX running on a single node k3s cluster don't correctly mount the `/var/lib/awx/projects` folder as a persistent volume and claim, but instead use the `emptyDir` mount type. The k3s cluster uses the `local-path` storage class which serves as a `hostPath` mount. The running AWX instance data is not saved on a folder that is mounted on the host node.

### AWX Operator version

1.1.4

### AWX version

21.11.0

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

k3s version v1.22.3+k3s1 (61a2aab2)

### Modifications

no

### Steps to reproduce

Below are the steps taken in order to be able to reproduce the problem.

#### Install k3s

I installed k3s on my server to form a single node cluster [by using this Ansible role](https://github.com/k3s-io/k3s-ansible).

```
$ ansible-playbook site.yml -i inventory/my-cluster/hosts.ini --ask-become-pass
```

#### Install Helm chart

```
$ helm install -n awx --create-namespace awx-operator awx-operator/awx-operator --values awx-operator-values.yaml
```

#### Helm chart values

I used the default values provided by the Helm chart and made one modification

```yaml
AWX:
  # enable use of awx-deploy template
  enabled: true  # <--- set to true, left the remainder alone
  name: awx
  spec:
    admin_user: admin

  # configurations for external postgres instance
  postgres:
    enabled: false
    host: Unset
    port: 5678
    dbName: Unset
    username: admin
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: Unset
    sslmode: prefer
    type: unmanaged
```

#### AWX resource definition

Then I defined my AWX resource as follows.

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  projects_persistence: true
  projects_storage_size: 20Gi
```

#### Operator logs

The operator logs show the AWX instance was successfully deployed and I am able to log into the web interface.

```
$ kubectl -n awx logs -f deployments/awx-operator-controller-manager -c awx-manager --follow
...
-------------------------------------------------------------------------------
{"level":"info","ts":1676471075.9897542,"logger":"runner","msg":"Ansible-runner exited successfully","job":"3195741824100079487","name":"awx","namespace":"awx"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx/awx) -----


PLAY RECAP *********************************************************************
localhost                  : ok=75   changed=0    unreachable=0    failed=0    skipped=71   rescued=0    ignored=1
```

#### `awx-web` container file systems

In the web container however there is no mention of the `/var/lib/awx/projects` directory.

```
$ kubectl exec -n awx -it awx-54696666c5-fn5pb -c awx-web -- bash
bash-5.1# df -h
Filesystem                         Size  Used Avail Use% Mounted on
overlay                             20G   16G  3.3G  83% /
tmpfs                               64M     0   64M   0% /dev
tmpfs                              2.0G     0  2.0G   0% /sys/fs/cgroup
/dev/mapper/ubuntu--vg-ubuntu--lv   20G   16G  3.3G  83% /etc/hosts
shm                                 64M  312K   64M   1% /dev/shm
tmpfs                              3.9G  4.0K  3.9G   1% /etc/tower/SECRET_KEY
tmpfs                              3.9G   12K  3.9G   1% /etc/tower/conf.d/ldap.py
tmpfs                              3.9G  8.0K  3.9G   1% /etc/receptor/signing/work-public-key.pem
tmpfs                              3.9G   12K  3.9G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                              3.9G  8.0K  3.9G   1% /etc/receptor/tls/ca/receptor-ca.key
tmpfs                              2.0G     0  2.0G   0% /proc/acpi
tmpfs                              2.0G     0  2.0G   0% /proc/scsi
tmpfs                              2.0G     0  2.0G   0% /sys/firmware
```

#### master node file system

On the master (and only) node, there is no folder provisioned using k3s' `local-path` provisioner for the project folder, but there is one for the Postgres database.

```
# ls -laFh /var/lib/rancher/k3s/storage/
total 12K
drwx-----x 3 root root 4.0K Feb 15 14:16 ./
drwxr-xr-x 6 root root 4.0K Feb 13 22:42 ../
drwxrwxrwx 3 root root 4.0K Feb 15 14:16 pvc-18f3b488-57f7-437c-afd7-e3f87f23a2bc_awx_postgres-13-awx-postgres-13-0/
```

#### Pod definition

The pod definition also shows that the `awx-projects` volume is of type `emptyDir` instead of an actual PVC.

```
$ kubectl describe -n awx pod awx-54696666c5-fn5pb
Name:         awx-54696666c5-fn5pb
Namespace:    awx
Priority:     0
Node:         rundeck/80.69.80.183
Start Time:   Wed, 15 Feb 2023 14:16:49 +0000
Labels:       app.kubernetes.io/component=awx
              app.kubernetes.io/managed-by=awx-operator
              app.kubernetes.io/name=awx
              app.kubernetes.io/operator-version=1.1.4
              app.kubernetes.io/part-of=awx
              app.kubernetes.io/version=21.11.0
              pod-template-hash=54696666c5
Annotations:  <none>
Status:       Running
IP:           10.42.0.40
IPs:
  IP:           10.42.0.40
Controlled By:  ReplicaSet/awx-54696666c5
...
Volumes:
  awx-projects:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
...
```

### Expected results

The `local-path` provisioner should be used to create a persistent volume and claim, just like is done for the Postgres database.

### Actual results

The `/var/lib/awx/projects` folder is mounted as `emptyDir` type.

### Additional information

Even when manually creating a PV and PVC and then supplying them in the AWX resource definition spec, the output remains the same.

**Comment by kurokobo** [comment]
@Anthirian 
If you have deployed AWX Operator via Helm with `AWX.enabled: true`, your AWX is deployed with spec `AWX.spec`.
Since your `AWX.spec` for Helm only contains `admin_user`, `projects_persistence` is `false` by default, causes `emptyDir`.

In addition, `local-path` on K3s only supports `ReadWriteOnce` and the default access mode for project volume is `ReadWriteMany` for HA deployment. Thus, you have to explicitly specify `ReadWriteOnce` to use `local-path` for project volume.

So, there are two things to consider,

- Merge your AWX resource definition into Helm values if you want to use `AWX.enabled: true`
- Specify `projects_storage_access_mode: ReadWriteOnce` to use `local-path` for project volume

This is example values file for your Helm chart:

```yaml
AWX:
  # enable use of awx-deploy template
  enabled: true  # <--- set to true, left the remainder alone
  name: awx
  spec:
    admin_user: admin
    projects_persistence: true     👈👈👈
    projects_storage_size: 20Gi     👈👈👈
    projects_storage_access_mode: ReadWriteOnce     👈👈👈

  # configurations for external postgres instance
  postgres:
    enabled: false
    host: Unset
    port: 5678
    dbName: Unset
    username: admin
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: Unset
    sslmode: prefer
    type: unmanaged
```

**Comment by Anthirian** [comment]
Thanks for your reply. I'm not sure I understand the use of the `enabled` flag in the Helm chart. I didn't see the AWX being deployed unless I set this to `true` and deployed my custom YAML definition:

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  projects_persistence: true
  projects_storage_size: 20Gi
```

I've read the documentation a couple of times, but I may have gotten the wrong idea about the operator?
