### ISSUE TITLE
External Database undefined variable on Store Database Configuration

### ISSUE THREAD

**Issue by eugchen** [ansible/tower-operator#1245]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I am trying to install via helm and it is failing at the Store Database Configuration step saying it can't find the username attribute. Still figuring out as I go so not sure if I have all the correct helm chart values yet for our environment but I don't see anything wrong with the external db values.

 The awx-postgres-configuration exists in the awx namespace and has values

```
kubectl -n awx get secrets
NAME                                    TYPE                 DATA   AGE
awx-admin-password                      Opaque               1      18h
awx-broadcast-websocket                 Opaque               1      18h
awx-postgres-configuration              Opaque               7      18h
awx-secret-key                          Opaque               1      18h
redhat-operators-pull-secret            Opaque               1      18h
sh.helm.release.v1.my-awx-operator.v1   helm.sh/release.v1   1      18h
```

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  database: YXd4ZGI==
  host: YXd4ZGIuYWJjZGVmZy51cy1lYXN0LTIucmRzLmFtYXpvbmF3cy5jb20==
  password: cGFzc3dvcmQ=
  port: NTQzMg==
  sslmode: cHJlZmVy
  type: dW5tYW5hZ2Vk
  username: YWRtaW4==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-awx-operator
    meta.helm.sh/release-namespace: awx
  creationTimestamp: "2023-02-14T20:17:17Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: awx-postgres-configuration
  namespace: awx
  resourceVersion: "7822537"
  uid: 73ddc4e7-4dc7-4c1e-aa90-7e5bbff96b46
type: Opaque
```

### AWX Operator version

0.30.0

### AWX version

21.7.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.24

### Modifications

yes

### Steps to reproduce

awx_helm_value.yaml

```
AWX:
  enabled: true
  name: awx
  spec:
    admin_user: admin
    admin_email: root@localhost
    admin_password_secret: awxsecret

    service_type: ClusterIP
    service_labels: |
      name: awx-web-svc
    service_annotations: |
      test.com/app-prefix: "AWX"
      test.com/support-email: "test@test.com"

    ingress_type: ingress
    ingress_annotations: |
      test.com/app-prefix: "AWX"
      test.com/support-email: "test@test.com"
    hostname: us-east-2.awx.test.com
    ingress_path: /
    ingress_path_type: Prefix
    ingress_class_name: kong

    image: vdocker.artifactory.opst.c1.test.com/ansible/awx
    image_version: 21.7.0
    image_pull_policy: Always
    ee_images: 
      - name: awx-ee
        image: vdocker.artifactory.opst.c1.test.com/ansible/awx-ee:0.6.0
    redis_image: vdocker.artifactory.opst.c1.test.com/redis
    redis_image_version: '7.0'
    redis_capabilities:
      - CHOWN
      - SETUID
      - SETGID

    task_privileged: true

    web_resource_requirements:
      requests:
        cpu: 500m
        memory: 2Gi
    task_resource_requirements:
      requests:
        cpu: 1500m
        memory: 2Gi
    ee_resource_requirements:
      requests:
        cpu: 250m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 2Gi

    postgres_configuration_secret: awx-secret-key

    service_account_annotations: |
      eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/AwxAccountRole

    no_log: 'false'


  # configurations for external postgres instance
  postgres:
    enabled: true
    host: awxdb.abcdefg.us-east-2.rds.amazonaws.com
    port: 5432
    dbName: awxdb
    username: admin
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: password
    sslmode: prefer
    type: unmanaged
```

### Expected results

The task to pass and store the configuration facts successfully

### Actual results

It cannot find the username attribute 

### Additional information

running from a local awx operator where i updated the deployment awx-operator image and kube-rbac-proxy image to grab from our artifactory. still using same versions that were in original so 0.30.0 for awx-operator and 0.13.0 for kube-rbac-proxy

### Operator Logs

TASK [installer : Store Database Configuration] ********************************\r\ntask path: /opt/ansible/roles/installer/tasks/database_configuration.yml:95\nfatal: [localhost]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'username'\\n\\nThe error appears to be in '/opt/ansible/roles/installer/tasks/database_configuration.yml': line 95, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n- name: Store Database Configuration\\n  ^ here\\n\"}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=43   changed=5    unreachable=0    failed=1    skipped=11   rescued=0    ignored=0   \r\n\n","job":"8702942926998778752","name":"awx","namespace":"awx","error":"exit status 2"}

----- Ansible Task Status Event StdOut (awx.ansible.com/v1beta1, Kind=AWX, awx/awx) -----

PLAY RECAP *********************************************************************
localhost                  : ok=43   changed=5    unreachable=0    failed=1    skipped=11   rescued=0    ignored=0
