### ISSUE TITLE
Custom awx ee image not being set from helm values

### ISSUE THREAD

**Issue by eugchen** [ansible/tower-operator#1254]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I am trying to use a custom image from our docker to set the awx-ee image but it is still trying to use the default one from quay.io. Our company doesn't allow external images so im getting an error. I'm not sure if i'm setting it wrong or maybe some other value in the spec is causing issues as I'm still figuring out what values will be needed. It doesn't seem to be a formatting issue from what I see.

```
kubectl get events -n awx
LAST SEEN   TYPE      REASON         OBJECT                      MESSAGE
82s         Warning   FailedCreate   replicaset/awx-7b9485d68d   Error creating: admission webhook "validation.gatekeeper.sh" denied the request: [repo-is-artifactory] container <awx-ee> has an invalid image repo <quay.io/ansible/awx-ee:latest> container <init> has an invalid image repo <quay.io/ansible/awx-ee:latest>, allowed repos are 
```

### AWX Operator version

21.7.0

### AWX version

0.30.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.24

### Modifications

yes

### Steps to reproduce

awx_helm_values.yaml

```
AWX:
  enabled: true
  name: awx
  spec:
    admin_user: admin
    admin_email: root@localhost
    admin_password_secret: awxsecret

    service_type: ClusterIP
    service_labels: |
      name: awx-web-svc
    service_annotations: |
      test.com/app-prefix: "AWX"
      test.com/support-email: "test@test.com"

    ingress_type: ingress
    ingress_annotations: |
      test.com/app-prefix: "AWX"
      test.com/support-email: "test@test.com"
    hostname: us-east-2.awx.test.com
    ingress_path: /
    ingress_path_type: Prefix
    ingress_class_name: kong

    image: vdocker.artifactory.opst.c1.test.com/ansible/awx
    image_version: 21.7.0
    image_pull_policy: Always
    ee_images: 
      - name: awx-ee
        image: vdocker.artifactory.opst.c1.test.com/ansible/awx-ee:0.6.0
    redis_image: vdocker.artifactory.opst.c1.test.com/redis
    redis_image_version: '7.0'
    redis_capabilities:
      - CHOWN
      - SETUID
      - SETGID

    task_privileged: true

    web_resource_requirements:
      requests:
        cpu: 500m
        memory: 2Gi
    task_resource_requirements:
      requests:
        cpu: 1500m
        memory: 2Gi
    ee_resource_requirements:
      requests:
        cpu: 250m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 2Gi

    service_account_annotations: |
      eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/AwxAccountRole

    no_log: 'false'


  # configurations for external postgres instance
  postgres:
    enabled: true
    host: awxdb.abcdefg.us-east-2.rds.amazonaws.com
    port: 5432
    dbName: awxdb
    username: admin
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: password
    sslmode: prefer
    type: unmanaged
```

### Expected results

no error and use custom awx-ee image

### Actual results

error because it is trying to use default image
