### ISSUE TITLE
k8s_info "Check for presence of Deployment "ansible task return KeyError: 'kind'

### ISSUE THREAD

**Issue by guillaumelfv** [ansible/tower-operator#1282]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

We are trying to deploy a simple AWX setup following the documentation example on our internal Kubernetes cluster.
Deployment failed at the first k8s_info Ansible module the playbook encounter with the following error: `KeyError: 'kind'`

### AWX Operator version

1.3.0

### AWX version

v21.13.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.21.6

### Modifications

no

### Steps to reproduce

Deploy the Operator 1.3.0 and a simple AWX resource with `kubectl apply -k .` :
```yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=1.3.0
  - awx-stg.yaml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 1.3.0

namespace: awx
```

```yml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-stg
  namespace: awx
spec:
  service_type: nodeport
  no_log: false
```

### Expected results

AWX env is deployed

### Actual results

The deployement fail on the task https://github.com/ansible/awx-operator/blob/1.3.0/roles/installer/tasks/main.yml#L2 
```yml
- name: Check for presence of Deployment
  k8s_info:
    api_version: v1
    kind: Deployment
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: tower_deployment
```
with the error 
```
kind = instance['kind']\nKeyError: 'kind'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

### Additional information

I also tested with an older version of the operator before https://github.com/ansible/awx-operator/blob/1.3.0/roles/installer/tasks/main.yml#L2 was introduced.

I used the operator version `0.23.0` but then it still fail on the first occurrence of the Ansible module `k8s_info` which is https://github.com/ansible/awx-operator/blob/86043361c62917439ebc0868699ed3782eeccdcd/roles/installer/tasks/secret_key_configuration.yml#L2

### Operator Logs

```
-------------------------------------------------------------------------------
{"level":"error","ts":1678444564.86179,"logger":"logging_event_handler","msg":"","name":"awx-stg","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"runner_on_failed","job":"5584954478239487189","EventData.Task":"Check for presence of Deployment","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/roles/installer/tasks/main.yml:2","error":"[playbook task failed]","stacktrace":"github.com/operator-framework/operator-sdk/internal/ansible/events.loggingEventHandler.Handle\n\t/workspace/internal/ansible/events/log_events.go:111"}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [Check for presence of Deployment] ********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'kind'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1678444564.2485483-66-118411466943602/AnsiballZ_k8s_info.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1678444564.2485483-66-118411466943602/AnsiballZ_k8s_info.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/opt/ansible/.ansible/tmp/ansible-tmp-1678444564.2485483-66-118411466943602/AnsiballZ_k8s_info.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s_info', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py\", line 217, in <module>\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py\", line 211, in main\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py\", line 173, in execute_module\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/service.py\", line 228, in find\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/service.py\", line 90, in find_resource\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/client.py\", line 306, in resource\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/k8s/client.py\", line 286, in _find_resource_with_prefix\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/client/discovery.py\", line 159, in get\n  File \"/usr/local/lib/python3.8/site-packages/kubernetes/dynamic/discovery.py\", line 242, in search\n    results = self.__search(self.__build_search(**kwargs), self.__resources, [])\n  File \"/usr/local/lib/python3.8/site-packages/kubernetes/dynamic/discovery.py\", line 290, in __search\n    matches.extend(self.__search([key] + parts[1:], resources, reqParams))\n  File \"/usr/local/lib/python3.8/site-packages/kubernetes/dynamic/discovery.py\", line 276, in __search\n    return self.__search(parts[1:], resourcePart, reqParams + [part] )\n  File \"/usr/local/lib/python3.8/site-packages/kubernetes/dynamic/discovery.py\", line 290, in __search\n    matches.extend(self.__search([key] + parts[1:], resources, reqParams))\n  File \"/usr/local/lib/python3.8/site-packages/kubernetes/dynamic/discovery.py\", line 276, in __search\n    return self.__search(parts[1:], resourcePart, reqParams + [part] )\n  File \"/usr/local/lib/python3.8/site-packages/kubernetes/dynamic/discovery.py\", line 265, in __search\n    resourcePart.resources = self.get_resources_for_api_version(\n  File \"/tmp/ansible_k8s_info_payload_qugpf1lc/ansible_k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/client/discovery.py\", line 106, in get_resources_for_api_version\n  File \"/usr/local/lib/python3.8/site-packages/kubernetes/dynamic/client.py\", line 62, in inner\n    return serializer(self, json.loads(resp.data.decode('utf8')))\n  File \"/usr/local/lib/python3.8/site-packages/kubernetes/dynamic/resource.py\", line 291, in __init__\n    kind = instance['kind']\nKeyError: 'kind'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by guillaumelfv** [comment]
After few debugging steps and replacing `api_version: v1` to `api_version: apps/v1` it seems this task pass then:
```yaml
- name: Check for presence of Deployment
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
  register: tower_deployment
```

I am not sure why it work in minikube with `api_version: v1` using: 
```sh
minikube start --kubernetes-version=v1.21.6
```

but in our production cluster which is also `v1.21.6`  we need `api_version: apps/v1`.
