### ISSUE TITLE
SAML documentation

### ISSUE THREAD

**Issue by nickjmv** [ansible/tower-operator#1284]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I'm trying to launch AWX Operator right away with the SAML configuration provided through the extra_settings parameter.
I couldn't find much information about how to construct the extra_settings parameter while adding maps etc.
@rooftopcellist tagging you as you answered my questions in the AWX Office hours.

### AWX Operator version

1.1.3

### AWX version

21.10.2

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.22

### Modifications

no

### Steps to reproduce

Add my settings to the extra_settings parameter above

### Expected results

SAML configuration is present in the GUI

### Actual results

No SAML configuration is to be seen 

### Additional information

My spec:
```
    spec:
      no_log: false
      admin_user: XXX
      ingress_type: ingress
      ingress_tls_secret: awx.mas.example.com
      hostname: awx.mas.example.com
      ingress_annotations: |
        cert-manager.io/cluster-issuer: letsencrypt-mas-dns
```

My postgress:
```
    # configurations for external postgres instance
    postgres:
      enabled: true
      host: AWS Aurora V2
      port: 5432
      dbName: XXX
      username: XXX
      # for secret management, pass in the password independently of this file
      # at the command line, use --set AWX.postgres.password
      password: XXXXXX
      sslmode: prefer
      type: unmanaged
```

My extra_settings:
```
      # Extra settings found in /etc/tower/settings.py
      extra_settings:
        - setting: TOWER_URL_BASE
          value: "'https://awx.mas.example.com'"
        - setting: SOCIAL_AUTH_SAML_SP_ENTITY_ID
          value: "'https://awx.mas.example.com'"
        - setting: SOCIAL_AUTH_SAML_SP_PUBLIC_CERT
          value: "'-----BEGIN CERTIFICATE-----VERY_LONG_CERTIFICATE_ON_A_SINGLE_LINE-----END CERTIFICATE-----'"
        - setting: SOCIAL_AUTH_SAML_SP_PRIVATE_KEY
          value: "'-----BEGIN RSA PRIVATE KEY-----VERY_LONG_PRIVATE_KEY_ON_A_SINGLE_LINE-----END RSA PRIVATE KEY-----'"
        - setting: SOCIAL_AUTH_SAML_ORG_INFO
          value: {
            "en-US": {
              "name": "awx-tower",
              "url": "https://awx.mas.example.com",
              "displayname": "AWXTower"
            }
          }
        - setting: SOCIAL_AUTH_SAML_TECHNICAL_CONTACT
          value: {
            "emailAddress": "technical@example.com",
            "givenName": "Tech"
          }
        - setting: SOCIAL_AUTH_SAML_SUPPORT_CONTACT
          value: {
            "emailAddress": "technical@example.com",
            "givenName": "Tech"
          }
        - setting: SOCIAL_AUTH_SAML_ENABLED_IDPS
          value: {
            "google": {
              "attr_first_name": "User.FirstName",
              "x509cert": "GOOGLE_SIDE_SAML_CERTIFICATE",
              "entity_id": "https://accounts.google.com/o/saml2?idpid=GOOGLE_ORG_ID",
              "attr_email": "User.email",
              "url": "https://accounts.google.com/o/saml2/idp?idpid=GOOGLE_ORG_ID",
              "attr_last_name": "User.LastName",
              "attr_username": "User.email",
              "attr_user_permanent_id": "User.email"
            }
          }
        - setting: SOCIAL_AUTH_SAML_ORGANIZATION_MAP
          value: {
            "Mobile Vikings": {
              "admins": [
                "one@example.com",
                "two@example.com"
              ],
              "remove_admins": true
            },
            "Mobile Vikings - DWH": {
              "admins": [
                "three@example.com",
                "four@example.com"
              ],
              "remove_admins": true
            }
          }
        - setting: SOCIAL_AUTH_SAML_ORGANIZATION_ATTR
          value: {}
        - setting: SOCIAL_AUTH_SAML_TEAM_MAP
          value: {
            "team_cni": {
              "remove": true,
              "users": [
                "one@example.com",
                "two@example.com"
              ],
              "organization": "Mobile Vikings"
            },
            "team_datawarehouse": {
              "remove": true,
              "users": [
                "three@example.com",
                "four@example.com"
              ],
              "organization": "Mobile Vikings"
            }
          }
        - setting: SOCIAL_AUTH_SAML_TEAM_ATTR
          value: {}
        - setting: SOCIAL_AUTH_SAML_USER_FLAGS_BY_ATTR
          value: {
            "is_system_auditor_role": [
              "awx_auditors"
            ],
            "is_superuser_role": [
              "awx_admins"
            ],
            "is_superuser_value": [
              "true"
            ],
            "is_system_auditor_value": [
              "Auditor"
            ],
            "is_superuser_attr": "awx_super_user",
            "is_system_auditor_attr": "is_system_auditor"
          }
        - setting: SOCIAL_AUTH_SAML_SECURITY_CONFIG
          value: {
            "requestedAuthnContext": false
          }
        - setting: SOCIAL_AUTH_SAML_SP_EXTRA
          value: {}
        - setting: SOCIAL_AUTH_SAML_EXTRA_DATA
          value: []
```

After deploying this via Helm, I DO see all these settings in the /etc/tower/settings file.
It also seems AWX is unable to boot as I'm not able to see the GUI anymore.

**Comment by Chamssiddine** [comment]
I have the same problem, dis you find any solution?

**Comment by nickjmv** [comment]
No, I was asked to create an issue here for further follow up but I'm also still waiting..

**Comment by Chamssiddine** [comment]
Did you add spec field to kustomization.yaml or awx-demo.yaml?

**Comment by nickjmv** [comment]
@Chamssiddine, the spec field is part of my values.yaml file

**Comment by nickjmv** [comment]
When I go to my AWX instance I see an error box:

```
Failed to fetch custom login configuration settings. System defaults will be shown instead.
GET api/v2/auth/ 500
A server error has occurred.
```

and in the logs of the awx-web pod I see this:
```
[awx-web-f95b5dfcb-xd7b6 awx-web]     assert not (read_only and required), NOT_READ_ONLY_REQUIRED
[awx-web-f95b5dfcb-xd7b6 awx-web] AssertionError: May not set both `read_only` and `required`
```

**Comment by druesendieb** [comment]
Hey @Chamssiddine and @nickjmv,
have you managed to solve your problem?

**Comment by nickjmv** [comment]
@druesendieb, unfortunately not. I tried reaching out to someone who had the same problem. In this GitHub issue: https://github.com/ansible/awx/issues/12238#issuecomment-1545896854

But they did not answer my email :(

**Comment by druesendieb** [comment]
I was having issues just when setting the TOWER_BASE_URL.
Through https://github.com/ansible/awx-operator/issues/599 I just found the solution to my problem. Double Quoting. 

## Works for me
```YAML
  extra_settings:
    - setting: TOWER_URL_BASE
      value: '"https://foo.bar"'
```
which results in the following entry in the config-map:
```YAML
     TOWER_URL_BASE = "https://foo.bar"
```

and whats most important, a working config without 500 errors.

I guess the issue with your @nickjmv config could lie in formatting as well, it seems AWX is quite picky here.

**Comment by nickjmv** [comment]
@druesendieb could you share your full configuration (without critical info) please?

**Comment by druesendieb** [comment]
@nickjmv Besides these two settings everything was configured in the GUI:

```
  extra_settings:
    - setting: TOWER_URL_BASE
      value: '"https://foo.bar"'
    - setting: CSRF_TRUSTED_ORIGINS
      value:
        - https://foo.bar
 ```
Sorry to not be more help here.

If you're not sure about the formatting, I guess there would be the other way around: Set the minimal settings via the CRD, configure SAML via the GUI, reverse engineer by having a look at the running config.

**Comment by chuegel** [comment]
Anyone got this working?The TOWER_URL_BASE value is quoted correctly and is written in `/etc/tower/settings.py` of the awx-web pod
However, some values are single quoted like:
`SOCIAL_AUTH_SAML_ORGANIZATION_MAP = {'Default': {'users': True}, 'ACME: {'admins': ['user1@example.com'], 'remove_admins': True, 'users': False}}`

![grafik](https://github.com/ansible/awx-operator/assets/6955465/ed1a84b0-ffaf-4678-b137-e6fc53bd5e80)

I'm not quite sure which values needs to be double quoted.

@druesendieb can you share your working SAML config?

**Comment by druesendieb** [comment]
@chuegel neither in `/etc/tower/settings.py` nor on any `/etc/tower/conf.d/*` files show me the settings. Looks like my  guess with `configure in GUI, look at the config in the pod` doesn't work out in the end :( 
If there are other files I can have a look at let me know. 

Maybe this similar setting from my colleagues who use LDAP declared via the Operator CRD helps you?
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: acme-awx
spec:
(...)
  extra_settings:
    - setting: AUTH_LDAP_ORGANIZATION_MAP
      value: {
        "acme": {
          "admins": "CN=ACME_Admins,OU=Groups,OU=Users,DC=ACME,DC=com",
          "remove_admins": false,
          "remove_users": false,
          "users": [
            "CN=ACME_Users,OU=Groups,OU=Users,DC=ACME,DC=com"
          ]
        }
      }
```

**Comment by chuegel** [comment]
> I was having issues just when setting the TOWER_BASE_URL. Through #599 I just found the solution to my problem. Double Quoting.
> ## Works for me
> 
> ```yaml
>   extra_settings:
>     - setting: TOWER_URL_BASE
>       value: '"https://foo.bar"'
> ```
> 
> which results in the following entry in the config-map:
> 
> ```yaml
>      TOWER_URL_BASE = "https://foo.bar"
> ```
> 
> and whats most important, a working config without 500 errors.
> 
> I guess the issue with your @nickjmv config could lie in formatting as well, it seems AWX is quite picky here.

@druesendieb I was refering to your post above. That suggested that you got the SAML settings working.

**Comment by druesendieb** [comment]
> @nickjmv Besides these two settings everything was configured in the GUI:

@chuegel as mentioned in this post, besides the `TOWER_URL_BASE` the instance using SAML was solely configured via the UI.

**Comment by neevnuv** [comment]
I am also facing this issue.
It seems that the issue is due to `SOCIAL_AUTH_SAML_SP_PRIVATE_KEY` being set through the API. When removing this option it worked for me. I guess AWX does not allow setting the private key through the api. I haven't found another way to set the private key yet..

**Comment by nickjmv** [comment]
@neevnuv could you provide me with your spec configuration? Even when commenting the SOCIAL_AUTH_SAML_SP_PRIVATE_KEY it still gives me the same error:
```
assert not (read_only and required), NOT_READ_ONLY_REQUIRED
AssertionError: May not set both `read_only` and `required
```

**Comment by neevnuv** [comment]
@nickjmv I noticed I don't have all the  settings you added, I added them manual. I have tried and found out you can deploy awx like this without the AssertionError:
``` yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  service_type: nodeport
  no_log: false
  extra_settings:
    - setting: TOWER_URL_BASE
      value: '''https://awx.mas.example.com'''
    - setting: SOCIAL_AUTH_SAML_SP_ENTITY_ID
      value: '''https://awx.mas.example.com'''
    - setting: SOCIAL_AUTH_SAML_ENABLED_IDPS
      value:
        google:
          attr_email: User.email
          attr_first_name: User.FirstName
          attr_last_name: User.LastName
          attr_user_permanent_id: User.email
          attr_username: User.email
          entity_id: 'https://accounts.google.com/o/saml2?idpid=GOOGLE_ORG_ID'
          url: 'https://accounts.google.com/o/saml2/idp?idpid=GOOGLE_ORG_ID'
          x509cert: GOOGLE_SIDE_SAML_CERTIFICATE
    - setting: SOCIAL_AUTH_SAML_ORGANIZATION_MAP
      value:
        Mobile Vikings:
          admins:
            - one@example.com
            - two@example.com
          remove_admins: true
        Mobile Vikings - DWH:
          admins:
            - three@example.com
            - four@example.com
          remove_admins: true
    - setting: SOCIAL_AUTH_SAML_ORGANIZATION_ATTR
      value: {}
    - setting: SOCIAL_AUTH_SAML_TEAM_MAP
      value:
        team_cni:
          organization: Mobile Vikings
          remove: true
          users:
            - one@example.com
            - two@example.com
        team_datawarehouse:
          organization: Mobile Vikings
          remove: true
          users:
            - three@example.com
            - four@example.com
    - setting: SOCIAL_AUTH_SAML_TEAM_ATTR
      value: {}
    - setting: SOCIAL_AUTH_SAML_USER_FLAGS_BY_ATTR
      value:
        is_superuser_attr: awx_super_user
        is_superuser_role:
          - awx_admins
        is_superuser_value:
          - 'true'
        is_system_auditor_attr: is_system_auditor
        is_system_auditor_role:
          - awx_auditors
        is_system_auditor_value:
          - Auditor
    - setting: SOCIAL_AUTH_SAML_SECURITY_CONFIG
      value:
        requestedAuthnContext: false
    - setting: SOCIAL_AUTH_SAML_SP_EXTRA
      value: {}
    - setting: SOCIAL_AUTH_SAML_EXTRA_DATA
      value: []
```

The issue seems in the settings:
- SOCIAL_AUTH_SAML_SP_PUBLIC_CERT
- SOCIAL_AUTH_SAML_SP_PRIVATE_KEY
- SOCIAL_AUTH_SAML_ORG_INFO
- SOCIAL_AUTH_SAML_TECHNICAL_CONTACT
- SOCIAL_AUTH_SAML_SUPPORT_CONTACT

I tried writing them the way you tried and other different way, but the error still rose. I am not sure what is the proper way to insert them. I am still testing.

**Comment by jon-nfc** [comment]
G'Day Legends!!!

I can confirm the same issue of the `SOCIAL_AUTH_SAML_` variables. Initially through testing I thought it may have been any variable that contained a `:`, however this turned out not to be true.

[Searching the whole of the ansible org](https://github.com/search?q=org%3Aansible+SOCIAL_AUTH_SAML_&type=code) and viewing related issues including [code diving yields the mandatory fields](https://github.com/ansible/awx/blob/0057c8daf6c0e4077458384cc8ee5c4543d48f8f/awx/sso/fields.py#L190-L196). Again to no avail if defined.

Things tried and still fails:
- defined the values as a string. _enclosed in `'`_. This yielded the json to keep it's double quotes
- One by one setting of variables, if deploy fails remove the variable and move to the next one. _This was what made me think it was any value that contained a `:`, however other values that were url's worked._
- Pythonically declaring as a string and multiline. _enclosing the value in `'''`_
- Setting any value that was json as yaml dict under the value variable. _no change, declaration works however still get the error_ 

    ``` text
    assert not (read_only and required), NOT_READ_ONLY_REQUIRED
    AssertionError: May not set both `read_only` and `required
    ```
What does work, is defining the extra settings in the AWX or Helmchart manifests  and having the operator update the configmap. Again however, this is no good as the settings fail when the AWX container tries to use the settings.
 
Across both the AWX and AWX-Operator projects SAML configuration via the operator is clearly broken somewhere. Although I tentatively state this as there may have been [one person](https://github.com/ansible/awx/issues/12238#issuecomment-1545896854) since this issue has been noticed (last 2-3 years) that got it working. 

@Moumoutaru care to chime in with a configuration that works or share what you did to [get it working](https://github.com/ansible/awx/issues/12238#issuecomment-1545896854)? 
Whether this is a bug or not hangs on confirmation of what you did to get this working when dozens of others within this fine community can't get it working!!

In the mean time I'm going to use a [playbook](https://gitlab.com/nofusscomputing/projects/ansible/ansible_playbooks/-/blob/open-sourcing/awx.yaml) to [configure AWX](https://gitlab.com/nofusscomputing/projects/ansible/ansible_playbooks/-/merge_requests/28/diffs?commit_id=0700e276fc18e9ee93571bd74de42ddb744ab740#57821f88ac9f602b3472551790237b9f6c9957b2). This works for us as no one has access to change settings via the UI and configuration is still within SCM. Feel free to help yourselves to any of the work I've just mentioned. Settings can be found [here](https://github.com/ansible/awx/blob/0057c8daf6c0e4077458384cc8ee5c4543d48f8f/tools/docker-compose/ansible/templates/saml_settings.json.j2) or via `axw_url/api/v2/settings`

@Moumoutaru we anxiously await your response. to everyone else happy ansibling!!!!

**Comment by nickjmv** [comment]
@jon-nfc, I already tried emailing @Moumoutaru back in June, but without any luck :(

**Comment by jon-nfc** [comment]
> @jon-nfc, I already tried emailing @Moumoutaru back in June, but without any luck :(

awesome.... one asked and expected the community to help, now the shoe is on the other foot-no where to be seen

**Comment by tylergmuir** [comment]
@nickjmv and @jon-nfc I opened a PR in [ansible/awx](https://github.com/ansible/awx/pull/14666) that I believe will address this issue. In my testing, the "required" flags I removed in that PR is what was causing that `NOT_READ_ONLY_REQUIRED` error.

My thought is these `required` flags aren't needed for the SAML attributes for 2 reasons. First is they aren't used for any other authentication backend, so while the intention may have been good originally, it wasn't consistent. And second, there is logic in the loading of the SAML backend to check for all of the appropriate fields to be filled in prior to loading so the required check was really only impacting using filling in the info from the GUI and it was stopping users from settings those options in the settings.py file.

**Comment by jon-nfc** [comment]
@tylergmuir, top-notch. the question I have is the code path different for the operator and using the API? Asking as the API configuration does work for configuring SAML. Including CRT/KEY.

> check for all of the appropriate fields to be filled in prior to loading so the required check was really only impacting using filling in the info from the GUI and it was stopping users from settings those options in the settings.py file

That's the best thing about development. Create a number field in 2 mins, spend 5 hours stopping a user from loading a picture into said field!!!

**Comment by tylergmuir** [comment]
@jon-nfc The difference between the API/GUI and modifying the settings file (either directly in the file system or indirectly via the extra settings in operator) is the setting changes made via the API/GUI are stored in the database and are modifiable. But the settings in the settings file made read-only. So if you set any setting in the settings file, you can see it from the API/GUI but you can't modify it from there. That's what ends up returning that assert failure because there are fields that are marked as required but are also read-only due to them being defined in the settings file.

**Comment by tylergmuir** [comment]
@nickjmv and @jon-nfc The PR in the AWX repo to remove the required tags from the SAML fields was merged and was included in the 2.10.0 release of operator. I just tested it and I was able to include all of the SAML config in the extra settings via operator now.

**Comment by nickjmv** [comment]
@tylergmuir, could you share your values.yaml file with me? I think I'm missing how the quotes around everything need to be.

Error I'm getting:
```
TASK [installer : Apply Resources] *********************************************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:203\nfatal: [localhost]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'value'. 'dict object' has no attribute 'value'. 'dict object' has no attribute 'value'. 'dict object' has no attribute 'value'\\n\\nThe error appears to be in '/opt/ansible/roles/installer/tasks/resources_configuration.yml': line 203, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n- name: Apply Resources\\n  ^ here\\n\"}\n\r\n
```

So I assume I'm doing something wrong in my extra_settings.

**Comment by jon-nfc** [comment]
> @tylergmuir, could you share your values.yaml file with me? I think I'm missing how the quotes around everything need to be.
> 
> Error I'm getting:
> 
> ```
> TASK [installer : Apply Resources] *********************************************\r\ntask path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:203\nfatal: [localhost]: FAILED! => {\"msg\": \"The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'value'. 'dict object' has no attribute 'value'. 'dict object' has no attribute 'value'. 'dict object' has no attribute 'value'\\n\\nThe error appears to be in '/opt/ansible/roles/installer/tasks/resources_configuration.yml': line 203, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n- name: Apply Resources\\n  ^ here\\n\"}\n\r\n
> ```
> 
> So I assume I'm doing something wrong in my extra_settings.

@nickjmv  ensure it's formated as a list of dict, from the appearances of your error it's not

``` yaml
extra_settings:
  - setting: "KEY HERE"
    value: "value_here"

```
