### ISSUE TITLE
Add support for authentication configuration via CR

### ISSUE THREAD

**Issue by tylerauerbeck** [ansible/tower-operator#13]
It would be nice to be able to configure your authentication system of choice via the tower/awx custom resource. This could look something like:

```yaml
tower_authentcation:
  ldap:
    .... some set of ldap settings/filters ....
    .... potentially some custom CA if necessaryy ....
```
