### ISSUE TITLE
Helm install fails for current version 1.4.0

### ISSUE THREAD

**Issue by flyinggreenfrog** [ansible/tower-operator#1306]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

With the new version 1.4.0 of awx-operator the created helmchart `index.yml` seems to contain a wrong link in a wrongly duplicated entry.

The first two entries seem both to point to version 1.4.0, but the link for the first entry `https://github.com/ansible/awx-operator/releases/download/awx-operator-1.4.0.tgz` is not working since it's missing the `download/1.4.0` subdirectory.

https://github.com/ansible/awx-operator/blob/gh-pages/index.yaml

```
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2023-03-28T01:10:43.291704398Z"
    description: A Helm chart for the AWX Operator
    digest: 9bf17eb8cc6901de43e9432deafec1b09db122916fd91e818da2280b08281d39
    name: awx-operator
    type: application
    urls:
    - https://github.com/ansible/awx-operator/releases/download/awx-operator-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2023-03-28T01:10:43.314779075Z"
    description: A Helm chart for the AWX Operator
    digest: 9bf17eb8cc6901de43e9432deafec1b09db122916fd91e818da2280b08281d39
    name: awx-operator
    type: application
    urls:
    - https://github.com/ansible/awx-operator/releases/download/1.4.0/awx-operator-1.4.0.tgz
    version: 1.4.0
```
 

### AWX Operator version

1.4.0

### AWX version

21.14.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

-

### Modifications

no

### Steps to reproduce

```
$ helm repo add awx-operator https://ansible.github.io/awx-operator
$ helm repo update
$ helm install awx-operator awx-operator/awx-operator --version 1.4.0
```
Without specific version 1.4.0 it fails too:

```
$ helm install awx-operator awx-operator/awx-operator
```

### Expected results

Successful install of awx-operator via helm

### Actual results

```
$ helm install awx-operator awx-operator/awx-operator --version 1.4.0
Error: INSTALLATION FAILED: failed to fetch https://github.com/ansible/awx-operator/releases/download/awx-operator-1.4.0.tgz : 404 Not Found
```
