### ISSUE TITLE
Not working installation new modules

### ISSUE THREAD

**Issue by renatovieiraarmac** [ansible/tower-operator#1319]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After run this command: ansible-galaxy collection install community.general in POD AWX with success, not possible run the playbook below:
```

    - name: Create a Github repository
      community.general.github_repo:
        access_token: "ghp_redacted"
        organization: armacloc
        name: myrepo
        description: "Just for fun"
        private: true
        state: present
        force_defaults: false
      register: result
```

I receive this error:
```

ERROR! couldn't resolve module/action 'community.general.github_repo'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/hello-awx.yaml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - name: Create a Github repository
      ^ here
```

### AWX Operator version

1.4.0

### AWX version

1.4.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.24

### Modifications

no

### Steps to reproduce

Install module community.general.github_repo:
Create playbook
Install playbook

### Expected results

Created repo github

### Actual results

```
ERROR! couldn't resolve module/action 'community.general.github_repo'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/runner/project/hello-awx.yaml': line 9, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - name: Create a Github repository
      ^ here
```
