### ISSUE TITLE
Duplicate entry in awx-operator helm index

### ISSUE THREAD

**Issue by TheRealHaoLiu** [ansible/tower-operator#1322]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

in 2.0.0 release 
```
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2023-04-03T19:50:15.652172355Z"
    description: A Helm chart for the AWX Operator
    digest: 27fbf2babd7678950db8a280fa0a5b32faa2b63c4ab8da58b17f9715aa9d7c1d
    name: awx-operator
    type: application
    urls:
    - https://github.com/ansible/awx-operator/releases/download/awx-operator-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2023-04-03T19:50:15.665627065Z"
    description: A Helm chart for the AWX Operator
    digest: 27fbf2babd7678950db8a280fa0a5b32faa2b63c4ab8da58b17f9715aa9d7c1d
    name: awx-operator
    type: application
    urls:
    - https://github.com/ansible/awx-operator/releases/download/2.0.0/awx-operator-2.0.0.tgz
    version: 2.0.0
```

### AWX Operator version

2.0.0

### AWX version

22.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

N/A

### Modifications

no

### Steps to reproduce

release awx-operator

### Expected results

index.html in gh-pages branch does not have duplicate entry

### Actual results

index.html in gh-pages branch have duplicate entry
