### ISSUE TITLE
awx does not start on Openshift after Operator Update to 2.0

### ISSUE THREAD

**Issue by astolzen** [ansible/tower-operator#1340]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After switching to Operator 2.0, AWX-Rollouts fail with Database Connection issues

### AWX Operator version

2.0

### AWX version

unknown, since it doesn't come up

### Kubernetes platform

openshift

### Kubernetes/Platform version

Single Node Openshift 4.11

### Modifications

no

### Steps to reproduce

Roll out AWX through Ansible, as done before with Operator 1.3

```
  - name: Create AWX
    kubernetes.core.k8s:
      kubeconfig: "{{ cfg_file }}"
      state: present
      definition:
        apiVersion: awx.ansible.com/v1beta1
        kind: AWX
        metadata:
          name: "{{ awxsetup.name }}"
          namespace: "{{ awxsetup.namespace }}"
```
          

### Expected results

Running AWX-Setup

### Actual results

All Pods start, but AWX does not work. The Postgress Container logs Connection issues:
```
2023-04-06 12:28:16.875 UTC [168] DETAIL:  Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"
2023-04-06 12:28:24.475 UTC [169] FATAL:  password authentication failed for user "awx"
2023-04-06 12:28:24.475 UTC [169] DETAIL:  Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"
2023-04-06 12:28:25.467 UTC [170] FATAL:  password authentication failed for user "awx"
```
while the web-container inside the web pods loops on:
```
[wait-for-migrations] Attempt 24 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 25 of 30
[wait-for-migrations] Waiting 30 seconds before next attempt
```

**Comment by astolzen** [comment]
Found a possible source: 
If you remove an awx-Setup using oc, kubectl or Ansible, the operator does not completely delete all assets. 
If you create an environment like this with 'oc create -f' 
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: two
  namespace: ast-aap2
```
it works for the 1st time. If you remove the environment with oc delete -f, these secrets are not removed:

- two-admin-password
- two-broadcast-websocket
- two-postgres-configuration
- two-receptor-ca
- two-receptor-work-signing
- two-secret-key

When you roll the setup again with the same name, some of the stored secrets seem to conflig with the fresh rollout and the awx-password for the postgres DB does no longer work.

**Comment by thedoubl3j** [comment]
@astolzen can you share the logs from the operator during this time?

**Comment by thedoubl3j** [comment]
also could you be a bit more descriptive in how you are actually deploying just so we can reproduce as best we can.

**Comment by djwhatle** [comment]
Same result on 2.0 for me with a fresh install. Using the sample install I think from the README. I'm on k3s, not sure if that is relevant.

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-test
  namespace: awx
spec:
  service_type: nodeport
```

**Comment by astolzen** [comment]
[awx-operator-controller-manager-75fb878b9f-msdfk-awx-manager.zip](https://github.com/ansible/awx-operator/files/11197722/awx-operator-controller-manager-75fb878b9f-msdfk-awx-manager.zip)

Added the Operator Log

**Comment by astolzen** [comment]
>> a bit more descriptive in how you are actually deploying

I use an Ansible-Playbook that:
- Rolls Out AWX on Openshift
- Waits for the WebUI to come up
- uses axw.axw to preconfigure the AWX-Session.

This Playbook runs without problems up to Operator 1.3. 
- On 1.4 the Web-UI stays white in the Browser, but the API is accessible
- On 2.0 the rollout fails (see logs)


The Playbook "awx.yml" looks like this:
```
---
- name: Roll Out AWX and configure it
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - secrets.yml
    - vars.yml

  tasks:
  - name: Rollout AWX on OCP
    include_tasks: awx_rollout.yml

  - name: Wait for Rollout to respond
    ansible.builtin.uri:
      url: "http://{{ awxsetup.name }}.{{ awxsetup.baseurl }}"
    register: result
    until: "result.status == 200"
    retries: 8
    delay: 20

  - name: Configure AWX on OCP
    include_tasks: awx_configure.yml
```

And this playbook includes the awx_rollout.yml-Playbook that actually rolls out the AWX-Instance:
(BTW: The "sleep"-Step is not necessary with Operator 1.3, but 2.0 is way slower, so the playbook needs to wait for it)
```
- name: Create AWX
  kubernetes.core.k8s:
    kubeconfig: "{{ cfg_file }}"
    state: present
    definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: "{{ awxsetup.name }}"
        namespace: "{{ awxsetup.namespace }}"

- name: Sleep for 60 seconds and continue with play
  ansible.builtin.wait_for:
    timeout: 60

- name: Create AWX Route
  kubernetes.core.k8s:
    kubeconfig: "{{ cfg_file }}"
    state: present
    definition:
      kind: Route
      apiVersion: route.openshift.io/v1
      metadata:
        name: "{{ awxsetup.name }}-route"
        namespace: "{{ awxsetup.namespace }}"
      spec:
        host: "{{ awxsetup.name }}.{{ awxsetup.baseurl }}"
        to:
          kind: Service
          name: "{{ awxsetup.name }}-service"
        port:
          targetPort: http
        wildcardPolicy: None

- name: Get Admin PW
  kubernetes.core.k8s_info:
    kubeconfig: "{{ cfg_file }}"
    api_version: v1
    kind: Secret
    name: "{{ awxsetup.name }}-admin-password"
    namespace: "{{ awxsetup.namespace }}"
  register: awxadmin
  # Password will be in: {{ awxadmin.resources[0].data.password | b64decode }}

- name: AWX-Password
  debug: 
    msg: "Password: {{ awxadmin.resources[0].data.password | b64decode }}"
#    verbosity: 3

- name: Set AWX-Password-Fact 
  ansible.builtin.set_fact:
    awx_admin_pwd: "{{ awxadmin.resources[0].data.password | b64decode }}"
```
And after that, awx_configure.yml uploads a base-configuration to the AWX-instance:
```
- name: Create Organization
  awx.awx.organization:
    controller_host: "http://{{ awxsetup.name }}.{{ awxsetup.baseurl }}"
    controller_username: "admin"
    controller_password: "{{ awx_admin_pwd }}"
    validate_certs: false
    name: "{{ org.name }}"
    description: "{{ org.desc }}"
    state: present
...
```

**Comment by fosterseth** [comment]
the issue seems to be that the postgres_configuration_secret is not being protected from deletion. So when awx resource is reapplied, a new postgres password is generated that won't match what is in the PVC.
this PR hopefully addresses it https://github.com/ansible/awx-operator/pull/1353

**Comment by ahmedwarsama** [comment]
I had the same problem. The workaround for me was to create a separate postgres pod and adding the following to the specs:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: ClusterIP
  postgres_configuration_secret: awx-postgres-configuration
  projects_storage_class: <name of storage class that postgres uses>
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: <postgres pods clusterIP>
  port: "5432"
  database: awx
  username: <username>
  password: <password>
  type: umanaged
type: Opaque
```
