### ISSUE TITLE
Possible documentation update for #1218

### ISSUE THREAD

**Issue by adpavlov** [ansible/tower-operator#1345]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Since #1218 implemented 2 separate deployments for awx-task and awx-web it's not clear how to deploy AWX using example 
as the metadata.name you provide will be the name of the resulting AWX deployment

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
```

### AWX Operator version

2.0.0

### AWX version

22.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

k3s

### Modifications

no

### Steps to reproduce

not clear

### Expected results

deployed AWX

### Actual results

not clear
