### ISSUE TITLE
Clean install of awx-operator does not result in running AWX

### ISSUE THREAD

**Issue by lknite** [ansible/tower-operator#1348]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Clean installation, expected AWX to be running but it fails, logs show:
localhost                  : ok=58   changed=0    unreachable=0    failed=1    skipped=63   rescued=0    ignored=0

### AWX Operator version

2.0.0

### AWX version

2.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.25.5

### Modifications

no

### Steps to reproduce

helm deployment using the following values:

```
awx-operator:

  AWX:
    enabled: true
    name: "awx"
    spec:
      no_log: false
      bundle_cacert_secret: ca-bundle
#      task_privileged: true
      admin_user: admin
      ingress_type: ingress
      ingress_class_name: nginx
      ingress_tls_secret: "awx.k.home.net-tls"
      hostname: "awx.k.home.net"
      ingress_path: /
      ingress_path_type: Prefix
      ingress_api_version: 'networking.k8s.io/v1'
      ingress_annotations: |
        cert-manager.io/issuer: "cluster-adcs-issuer" #use specific name of issuer
        cert-manager.io/issuer-kind: "ClusterAdcsIssuer" #or AdcsClusterIssuer
        cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"
```

### Expected results

Expected working AWX installation.

### Actual results

ingress shows 503, using kube port-forward results in dropped connection, doesn't appear the service running in the pod

### Additional information

localhost                  : ok=58   changed=0    unreachable=0    failed=1    skipped=63   rescued=0    ignored=0

### Operator Logs

I'm not sure what to look for in the logs, there is so much there.  Maybe this?

```
Failed to apply object: b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"RoleBinding.rbac.authorization.k8s.io \\\\\\\\\\\"awx\\\\\\\\\\\" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:\\\\\\\\\\\"rbac.authorization.k8s.io\\\\\\\\\\\", Kind:\\\\\\\\\\\"Role\\\\\\\\\\\", Name:\\\\\\\\\\\"awx\\\\\\\\\\\"}: cannot change roleRef\\\",\\\"reason\\\":\\\"Invalid\\\",\\\"details\\\":{\\\"name\\\":\\\"awx\\\",\\\"group\\\":\\\"rbac.authorization.k8s.io\\\",\\\"kind\\\":\\\"RoleBinding\\\",\\\"causes\\\":[{\\\"reason\\\":\\\"FieldValueInvalid\\\",\\\"message\\\":\\\"Invalid value: rbac.RoleRef{APIGroup:\\\\\\\\\\\"rbac.authorization.k8s.io\\\\\\\\\\\", Kind:\\\\\\\\\\\"Role\\\\\\\\\\\", Name:\\\\\\\\\\\"awx\\\\\\\\\\\"}: cannot change roleRef\\\",\\\"field\\\":\\\"roleRef\\\"}]},\\\"code\\\":422}\\\\n'\", \"reason\": \"Unprocessable Entity\"}
```
Is there a way to see what rbac yaml it's attempting to apply there?
