### ISSUE TITLE
AWX migration to external postgres fails

### ISSUE THREAD

**Issue by jonathon2nd** [ansible/tower-operator#1407]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When attempting to migrate from AWX on vm to AWX in k8s with an [externally managed postgres cluster](https://github.com/ansible/awx-operator#external-postgresql-service), it fails.

### AWX Operator version

awx-operator:2.1.0

### AWX version

latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.24.8 +rke2r1

### Modifications

no

### Steps to reproduce

Deploy
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  secret_key_secret: awx-secret-key
  old_postgres_configuration_secret: awx-old-postgres-configuration
  postgres_configuration_secret: awx-postgres-configuration
  projects_persistence: true
  projects_storage_class: linstor-replica-three
  projects_storage_size: 10Gi
  projects_storage_access_mode: ReadWriteOnce
  admin_password_secret: awx-admin-password
  admin_user: admin
  ingress_annotations: |
    "kubernetes.io/ingress.class": "traefik"
    "traefik.ingress.kubernetes.io/router.entrypoints": "websecure"
    "traefik.ingress.kubernetes.io/router.tls": "true"
  ingress_path: /
  ingress_path_type: Prefix
  ingress_tls_secret: example-com-cf
  hostname: awx.example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: acid-awx-pooler.awx-postgres
  port: "5432"
  database: awx
  username: awx
  password: password
  type: unmanaged
  sslmode: require
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-old-postgres-configuration
  namespace: awx
stringData:
  host: "ip"
  port: "5432"
  database: awx
  username: awx
  password: password
type: Opaque
```

### Expected results

I expect it to use the already deployed postgres cluster

### Actual results

Fails to work. See log file

Which leads me to: https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/migrate_data.yml#L31

It seems like when you migrate, it is expecting to manage postgres?

### Additional information

https://github.com/ansible/awx-operator/issues/1240

Creating new issue as requested

### Operator Logs

[awx-operator-controller-manager-58b5b7698b-4c2x6_awx-manager.log](https://github.com/ansible/awx-operator/files/11446259/awx-operator-controller-manager-58b5b7698b-4c2x6_awx-manager.log)
