### ISSUE TITLE
[0.7.0] password authentication failed for user "awx"

### ISSUE THREAD

**Issue by MaximilianMeister** [ansible/tower-operator#142]
Trying the new 0.7.0 release with awx 18.0.0 and running into this issue, any ideas? Haven't changed the config:

Here's the generated spec of the `awx` resource:

```yaml
spec:
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_garbage_collect_secrets: false
  tower_image: [ private_registry_image based on 18.0.0 ]
  tower_image_pull_policy: Always
  tower_ingress_type: Ingress
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_replicas: 1
  tower_route_tls_termination_mechanism: Edge
```

## postgres container logs

```
2021-03-24 11:58:32.233 UTC [7796] DETAIL:  Password does not match for user "awx".                                                                                                            Connection matched pg_hba.conf line 99: "host all all all md5"
```

## awx-web container logs

```
django.db.utils.OperationalError: FATAL:  password authentication failed for user "awx"
```
