### ISSUE TITLE
Supervisord cannot start in scenario when k8s prohibits write access to pod's file system

### ISSUE THREAD

**Issue by marekzebro** [ansible/tower-operator#1432]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### AWX Operator version

2.2.1

### AWX version

22.3.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.24.10

### Modifications

no

### Steps to reproduce

- Prohibit write access to container's root file system
- Run standard installation. 

### Expected results

Container should start normally in such scenario. Ideally there would be a mount point where container can freely write. 

### Actual results

Supervisord on both task & web container will fail due to inability to write into: /var/run/supervisor/

```
cat /etc/supervisord_web.conf
...
[unix_http_server]
file=/var/run/supervisor/supervisor.web.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor/supervisor.web.sock ; use a unix:// URL  for a unix socket
```

### Additional information

There are number of emptyDir mounted already, this looks like has been forgotten. Such change would fix this problem right away. 

```
volumes:
  - name: {{ ansible_operator_meta.name }}-supervisord-socket
     emptyDir: {}
       
volumeMounts:
  - name: {{ ansible_operator_meta.name }}-supervisord-socket
     mountPath: "/var/run/supervisor"
```
