### ISSUE TITLE
ca-bundle not getting mapped in pod, 'bundle_cacert_secret: ca-bundle'

### ISSUE THREAD

**Issue by lknite** [ansible/tower-operator#1470]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Am troubleshooting the issue that a ca-bundle does not appear to be getting mapped via the awx deployment.

### AWX Operator version

2.3.0

### AWX version

22.4.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.25.8

### Modifications

no

### Steps to reproduce

Method used to add a ca-bundle:
```
awx-operator:

  AWX:
    enabled: true
    name: "awx"
    spec:
      no_log: false
      bundle_cacert_secret: ca-bundle
```

Then you also include a secret named 'ca-bundle' with a key called 'bundle-ca.crt':
```
apiVersion: v1
kind: Secret
metadata:
  name: ca-bundle
data:
  bundle-ca.crt: LS0tLS1CRUdJTiBD...
```

### Expected results

Expected to see the bundle-ca.crt to end up mapped in the pod where needed.

### Actual results

I see something in the awx-web deployment:
```
        volumeMounts:
        ...
        - mountPath: /etc/pki/ca-trust/source/anchors/bundle-ca.crt
          name: awx-bundle-cacert
          readOnly: true
          subPath: bundle-ca.crt
```
But I don't see that path inside the pod:
```
$ k exec -it awx-web-649dd6ddf6-d627d -- bash
Defaulted container "redis" out of: redis, awx-web, awx-rsyslog, init (init)
root@awx-web-649dd6ddf6-d627d:/data# ls /etc/pki/ca-trust/source/anchors/bundle-ca.crt
ls: cannot access '/etc/pki/ca-trust/source/anchors/bundle-ca.crt': No such file or directory
root@awx-web-649dd6ddf6-d627d:/data# ls /etc/pki/ca-trust/source/anchors/             
ls: cannot access '/etc/pki/ca-trust/source/anchors/': No such file or directory
```

### Additional information

I'm open to the possibility that the way to configure a ca-bundle has changed, but so far in my searches I'm still finding the same method I'm using here.
