### ISSUE TITLE
awx-operator-controller-manager reduce limits

### ISSUE THREAD

**Issue by klml** [ansible/tower-operator#1479]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

The resources limits of the awx-operator-controller-manager pod consist of the following two containers:

* a well known kube-rbac-proxy `CPU: 500M, memory: 128Mi `
* a very huge [AWX-Manager](https://github.com/ansible/awx-operator/blob/1bddb984766c91998991db475f3ecbfb34c47b4c/config/manager/manager.yaml#L75C1-L77C25): `CPU: 2000M, memory: 4096Mi`

That's together: cpu: 2500m, memory: 4224Mi

Our cluster has set a limit range of maximum cpu: 2, memory: 4Gb for all pods. So awx-manager is the only deployment that exceeds this global limit.

Currently we have given the AWX namespace a dedicated limit-range with slightly increased values.

But maybe it would make sense to lower the limits of awx-operator-controller-manager? Most pods in deployments in the wild (e.g. AMQ streams) have a maximum limit of cpu: "1", memory: 500Mi.

Also, our productive awx-operator-controller-manager shows a minimal usage of resources (mostly cpu: 2m, memory: 50Mi over 2 weeks) 

Would you accept a PR with this?

**Comment by thedoubl3j** [comment]
@klml change to resource limits would likely not be accepted just on the basis that it can vary across deployments. Since your stats are reporting lower well below those limits and you have specific guidelines around limits on your cluster, I would suggest editing those specifically for the manager and then rebuilding the operator image for your own environment. cc @rooftopcellist for further context if he has time (and made these changes)

**Comment by klml** [comment]
@thedoubl3j thanks for your help

> rebuilding the operator image for your own environment

we are very happy using this operator from shelf, so I would stick to my "dedicated limit-range with slightly increased values."...

> (and made these changes)

... This hint took me to @rooftopcellist|s change #962 and there is my solution , just  config. resources ;) works like charm

thx for this 🙏 


But #962 leads to https://sdk.operatorframework.io/docs/best-practices/managing-resources/#how-to-compute-default-values

> However, you are able to benchmark your Operator by [Monitoring the resource usage](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#monitoring-compute-memory-resource-usage) to ensure good and reasonable values for the general cases. Kubebuilder and SDK provide some [metrics](https://book.kubebuilder.io/reference/metrics.html) which can help you with.

so I would still vote for a decrease, so other users don't have to set this config

>  can vary across deployments.

imho these resources are only for the deployment controller-manager, or did I misunderstand you.

**Comment by klml** [comment]
## kube-rbac-proxy is also overridden

> The resources field defines Resource Constraints for all the containers in the Pod created by OLM.
> Note: Resource Constraints defined here will overwrite existing resource constraints.

https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md#resources

unfortunately kube-rbac-proxy is also raised to CPU 1. So `config. resources` is resolving my problem, but with this sideeffect.

That's why I still think that a basic reduction makes sense;)

**Comment by rooftopcellist** [comment]
@klml Agreed, the limits are artificially high at the moment for the awx-operator manager.  This was intentional as I wanted to make sure that the operator pod would not get OOMkilled and there did not seem to be a downside to putting high limits.  

Now that you point out that some folks may have a LimitRange on a namespace, it makes sense to want to avoid the extra step of setting limits lower. I had just erred on the side of caution until now. 

Memory limits don't block other pods from using that memory, only memory _requests_ do that.  But after doing some performance tests, if the operator pod is using more than 1Gi of Memory, odds are it is failing in a catastrophic way, or the user is asking too much of it (ddos-ing by creating hundreds of awxbackup CR's for example).  

---------------------------------------------

If you need to override the resource_requirements of the operator pod, you can do so via the subscription object like you mentioned in your last comment.  If you are using the kustomization.yaml install, you can do something like the following:

`kustomization.yaml`
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.7.2

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.7.2

# Specify a custom namespace in which to install AWX
namespace: awx

patchesStrategicMerge:
  - manager-resources-patch.yaml  # Path to your resource requirements patch
```

`manager-resources-patch.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-manager
  namespace: your-namespace  # Replace with actual namespace if needed
spec:
  template:
    spec:
      containers:
        - name: awx-manager
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
```


Then apply
```
kubectl apply -k .
```
