### ISSUE TITLE
database migrations never start when Generic OIDC settings have been configured on a new cluster w/ existing data

### ISSUE THREAD

**Issue by rkbennett** [ansible/tower-operator#1496]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Platform: AWX Operator
Kubernetes Version: 1.27.2

When starting an AWX resource, if the database is persisted from a previous deployment and Generic OIDC settings were set, the web and rsyslog services both get stuck waiting for database migrations. I'm not really sure why this happens, but I know that if you delete all the SOCIAL rows out of the conf_settings table, these services will immediately proceed to the next phase of start up. 

### AWX version

22.3.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [x] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Web browser

Chrome

### Steps to reproduce

- Deploy an AWX resource in kubernetes
- Log into the instance and add Generic OIDC configurations (keycloak in my instance)
- Delete AWX resource and all related resources (secrets, storageclasses, PVs, PVCs, etc)
- Remove AWX operator
- Re-add AWX operator
- Re-apply AWX resource and wait for awx-web pod to be created
- View logs of the awx-web pod's awx-web container (it should be stuck on waiting for migrations)
- Open a shell on the postgres pod and enter a psql terminal (psql -U awx)
- Remove entries in the conf_setting table (DELETE FROM conf_setting WHERE id > 0;)
- Within 2-3 migration waits the awx-web container will continue to the next phase of start up.

### Expected results

The deployment would continue as normal with the existing database files mounted via a storageclass/pvc

### Actual results

web and rsync containers get stuck waiting for database migrations

**Comment by fosterseth** [comment]
@rkbennett can you share your AWX spec file? are you using an external DB?

**Comment by rkbennett** [comment]
This what you're looking for?

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-dev
  namespace: awx
spec:
  service_type: clusterip
  ingress_type: ingress
  hostname: awx.local
  ingress_class_name: nginx
  postgres_image: postgres:13
  postgres_storage_class: awx-smb-postgres
  projects_persistence: true
  projects_existing_claim: awx-smb
  ingress_annotations: |
    cert-manager.io/issuer: local-issuer
    cert-manager.io/issuer-kind: ClusterIssuer
  ingress_tls_secret: local-awx-tls
  bundle_cacert_secret: local-ca
```
