### ISSUE TITLE
Failed to restore AWX

### ISSUE THREAD

**Issue by sohwaje** [ansible/tower-operator#1498]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

```
{
  "message": "Could not find or access '/tmp/ansible.2jbp76dy' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option",
  "ansible_included_var_files": [],
  "ansible_facts": {},
  "_ansible_no_log": false,
  "changed": false
}
```

The playbook below warns of the above error. I don't know what the problem is. Ask for help.

- import_vars.yml
```
---

- name: Import awx_object variables
  block:

  - name: Create temp file for spec dict
    tempfile:
      state: file
    register: tmp_spec

  - name: Permission temp
    shell: chmod +rwx "{{ tmp_spec.path }}"

  - name: Get AWX object definition from pvc
    k8s_cp:
      namespace: "{{ backup_pvc_namespace }}"
      pod: "{{ ansible_operator_meta.name }}-db-management"
      remote_path: "{{ backup_dir  }}/awx_object"
      local_path: "{{ tmp_spec.path }}"
      state: from_pod

  - name: Include spec vars to save them as a dict
    include_vars: "{{ tmp_spec.path }}"

```

### AWX Operator version

latest

### AWX version

2.4.0

### Kubernetes platform

minikube

### Kubernetes/Platform version

latest

### Modifications

yes

### Steps to reproduce

nothing

### Expected results

Restore succeeded

### Actual results

Restore succeeded
