### ISSUE TITLE
No AWX backups are created.

### ISSUE THREAD

**Issue by sohwaje** [ansible/tower-operator#1502]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

No AWX backups are created.

The playbook seems to be running well, but all the rest of the work procedures seem to be skiped.

No backups are created other than the first one you run.

![스크린샷 2023-07-27 오전 10 02 38](https://github.com/ansible/awx-operator/assets/19942049/c4bcd071-2934-4c2f-986c-c78071a4b04b)

```
/usr/local/lib/python3.8/site-packages/paramiko/transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
SSH password: 
BECOME password[defaults to SSH password]: 
[WARNING]: Found variable using reserved name: no_log
[WARNING]: Found variable using reserved name: hosts

PLAY [Backup AWX] **************************************************************

TASK [common : Get information about the cluster] ******************************
skipping: [172.30.11.254]

TASK [common : Determine the cluster type] *************************************
skipping: [172.30.11.254]

TASK [common : debug] **********************************************************
ok: [172.30.11.254] => {
    "msg": "CLUSTER TYPE: is_openshift=False; is_k8s=True"
}

TASK [backup : Run creation tasks] *********************************************
included: /runner/project/awx/roles/backup/tasks/creation.yml for 172.30.11.254

TASK [backup : Patching labels to AWXBackup kind] ******************************
ok: [172.30.11.254]

TASK [backup : Look up details for this backup object] *************************
ok: [172.30.11.254]

TASK [backup : Build `additional_labels_items` labels from `additional_labels`] ***
skipping: [172.30.11.254]

TASK [backup : include_tasks] **************************************************
skipping: [172.30.11.254]

TASK [backup : include_tasks] **************************************************
skipping: [172.30.11.254]

TASK [backup : include_tasks] **************************************************
skipping: [172.30.11.254]

TASK [backup : include_tasks] **************************************************
skipping: [172.30.11.254]

TASK [backup : Set flag signifying this backup was successful] *****************
skipping: [172.30.11.254]

TASK [backup : include_tasks] **************************************************
skipping: [172.30.11.254]

TASK [backup : Update status variables] ****************************************
included: /runner/project/awx/roles/backup/tasks/update_status.yml for 172.30.11.254

TASK [backup : Update CR Backup status] ****************************************
skipping: [172.30.11.254]

TASK [backup : Run finalizer tasks] ********************************************
skipping: [172.30.11.254]

PLAY RECAP *********************************************************************
172.30.11.254              : ok=5    changed=0    unreachable=0    failed=0    skipped=11   rescued=0    ignored=0   

```

### AWX Operator version

2.4.0

### AWX version

22.5.0

### Kubernetes platform

minikube

### Kubernetes/Platform version

latest

### Modifications

yes

### Steps to reproduce

Backups must perform well

### Expected results

Backups must perform well

### Actual results

Backups must perform well

**Comment by fosterseth** [comment]
which steps did you follow to do the backup?

**Comment by sohwaje** [comment]
The only modifications to backup/default/main.yml are as follows.
```
---
ansible_port: '2222'
ansible_operator_meta:
  name: 'awx'
  namespace: 'awx'
# Required: specify name of tower deployment to backup from
deployment_name: 'awx'
kind: 'AWXBackup'
api_version: '{{ deployment_type }}.ansible.com/v1beta1'

# Specify a pre-created PVC (name) to backup to
backup_pvc: 'awx-backup-claim'
backup_pvc_namespace: "{{ ansible_operator_meta.namespace }}"

# Size of backup PVC if created dynamically
backup_storage_requirements: '10Gi'

# Set no_log settings on certain tasks
no_log: true

# Variable to set when you want backups to be cleaned up when the CRD object is deleted
clean_backup_on_delete: false


# Add a nodeSelector for the Postgres pods to backup.
# Specify as literal block. E.g.:
# db_management_pod_node_selector: |
#   kubernetes.io/arch: amd64
#   kubernetes.io/os: linux
db_management_pod_node_selector: ''

# Variable to signal that this role is being run as a finalizer
finalizer_run: false

# Default resource requirements
backup_resource_requirements:
  limits:
    cpu: "1000m"
    memory: "4096Mi"
  requests:
    cpu: "25m"
    memory: "32Mi"
# Allow additional parameters to be added to the pg_dump backup command
pg_dump_suffix: ''

# Labels defined on the resource, which should be propagated to child resources
additional_labels: []

# Maintain some of the recommended `app.kubernetes.io/*` labels on the resource (self)
set_self_labels: true
...
```

However, every time you perform a backup, a backup of the same date is performed. The backup date does not change to today. Of course, no backup files are created.

<img width="925" alt="스크린샷 2023-08-10 오전 10 37 15" src="https://github.com/ansible/awx-operator/assets/19942049/918a0eb8-da24-4b83-bc7b-e01aee896f6b">
