### ISSUE TITLE
Helm: Creating AWX with external postgres currently not working.

### ISSUE THREAD

**Issue by jonathon2nd** [ansible/tower-operator#1524]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Enabling awx in the operator as described [here](https://github.com/ansible/awx-operator/tree/devel/.helm/starter), does not work. Gets stuck at `Waiting for database migrations`

Operator is installed with helm.

### AWX Operator version

Chart: awx-operator:2.5.1

### AWX version

default to chart

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.25.9

### Modifications

no

### Steps to reproduce

Add the following values to operator

```
AWX:
  # enable use of awx-deploy template
  enabled: true
  name: awx
  spec:
    secret_key_secret: awx-secret-key
    # no change if I remove the next line.
    postgres_configuration_secret: awx-postgres-configuration
    admin_password_secret: awx-admin-password
    admin_user: admin
    hostname: awx.example.com

  # configurations for external postgres instance
  postgres:
    enabled: true
    host: master.awx-postgres
    port: 5678
    dbName: awx
    username: awx
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: password
    sslmode: prefer
    type: unmanaged
```

### Expected results

Basic, empty AWX to be up and running to validate values so far.

### Actual results

Loops at pending migrations
(ignore weird timestamp placements, latest rancher update added this lol)
![image](https://github.com/ansible/awx-operator/assets/52681917/9add8b95-828a-4f81-b28a-f21903974de7)
![image](https://github.com/ansible/awx-operator/assets/52681917/88e52c43-37cb-4a26-bd64-9e4670911610)
![image](https://github.com/ansible/awx-operator/assets/52681917/85249462-7fcd-4a35-93ff-5a56ddd0e391)

### Additional information

I was wanting to get this working before retying migrating from an existing AWX installation: https://github.com/ansible/awx-operator/issues/1407 

EDIT: To ensure it was not the DB from my various attempts, I just nuked the postgres cluster, pv's and backups. Created fresh postgres cluster. Exact same problem though.

### Operator Logs

[awx-operator-controller-manager-786757464d-vfw22_awx-manager.log](https://github.com/ansible/awx-operator/files/12361675/awx-operator-controller-manager-786757464d-vfw22_awx-manager.log)
[awx-web-85ddbf9c6c-4plq5_awx-web.log](https://github.com/ansible/awx-operator/files/12361676/awx-web-85ddbf9c6c-4plq5_awx-web.log)
[awx-task-6f4fc4bcd-rrfm4_awx-ee.log](https://github.com/ansible/awx-operator/files/12361677/awx-task-6f4fc4bcd-rrfm4_awx-ee.log)
[awx-task-6f4fc4bcd-rrfm4_awx-task.log](https://github.com/ansible/awx-operator/files/12361678/awx-task-6f4fc4bcd-rrfm4_awx-task.log)

**Comment by jonathon2nd** [comment]
[awx-operator-controller-manager-786757464d-4kztc_awx-manager.log](https://github.com/ansible/awx-operator/files/12362890/awx-operator-controller-manager-786757464d-4kztc_awx-manager.log)
Big messy log that should show multiple loops of it getting hung up. Includes the attempt after nuking the DB.

![image](https://github.com/ansible/awx-operator/assets/52681917/01c3261b-2402-4453-bdf1-96a01f971727)

**Comment by jonathon2nd** [comment]
Just ran and confirmed that AWX gets built properly with the following values:
Works with built-in postgres, but not external postgrest.

The external postgres is needed for HA and disaster recovery.
```
AWX:
  # enable use of awx-deploy template
  enabled: true
  name: awx
  spec:
    secret_key_secret: awx-secret-key
    admin_password_secret: awx-admin-password
    admin_user: admin
    hostname: awx.example.com
```
![image](https://github.com/ansible/awx-operator/assets/52681917/7de4490e-709c-42c9-a208-79ccde0b072f)
[awx-web-65fc56d9b7-stls2_awx-web.log](https://github.com/ansible/awx-operator/files/12363584/awx-web-65fc56d9b7-stls2_awx-web.log)
[awx-postgres-13-0_postgres.log](https://github.com/ansible/awx-operator/files/12363585/awx-postgres-13-0_postgres.log)
[awx-task-589cbf97c4-rklw2_awx-task.log](https://github.com/ansible/awx-operator/files/12363586/awx-task-589cbf97c4-rklw2_awx-task.log)
[awx-operator-controller-manager-786757464d-8mmql_awx-manager.log](https://github.com/ansible/awx-operator/files/12363587/awx-operator-controller-manager-786757464d-8mmql_awx-manager.log)

**Comment by Peter1295** [comment]
Facing absolutely same issue, just with 2.5.0 chart. Deployment is done by argocd.

**Comment by naxreo** [comment]
i've got same issue. the error made by 'awx-manage check' in /usr/local/bin/wait-for-migrations

```shell
File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/checks/compatibility/django_4_0.py", line 9, in check_csrf_trusted_origins
    for origin in settings.CSRF_TRUSTED_ORIGINS:
TypeError: 'NoneType' object is not iterable
```

I'm using bitnami/postgresql-ha-11.7.6 for postgresql-13 and awx-operator-2.5.1
I don't have idea about this error

**Comment by Peter1295** [comment]
No update about this issue?

**Comment by fosterseth** [comment]
@Peter1295 @jonathon2nd 

Just to narrow down the problem a bit, were you able to get AWX up with an external DB, but _without_ using helm chart?

**Comment by jonathon2nd** [comment]
Have not attempted, we manage our deployments with argo-cd, so helm is a requirement.

**Comment by jonathon2nd** [comment]
I was wondering if there has been any change or update on this?

**Comment by Peter1295** [comment]
Sorry for a late reply. My situation is resolved. 
It was with postgres dump from the old minikube awx instance, where I had to deploy first matching AWX version and also with creation of **<resourcename>-old-postgres-configuration** https://github.com/ansible/awx-operator/blob/devel/docs/migration/migration.md . When it started to run with old version, I was able to do upgrade and continue to use dumped database on external postgres cluster.

**Comment by jonathon2nd** [comment]
This issue is for a new awx without migration from old awx. I had attempted that first, which resulted in this separate issue: https://github.com/ansible/awx-operator/issues/1407

**Comment by jonathon2nd** [comment]
Just retest with 2.5.3, no change. Fresh awx and external postgres

**Comment by AJB78** [comment]
same here with Helm Chart version 2.6.0. Also fresh awx and external postgress-ha still stuck on "wait-for-migrations" .

**Comment by kaveh6161** [comment]
Are there any updates on this. A workaround fix or planned permeant fix?

**Comment by Peter1295** [comment]
Workaround fix would be to create 1st local postgres awx database, dump it from cluster into external postgres and do migration process like from this manual. https://github.com/ansible/awx-operator/blob/devel/docs/migration/migration.md 
Pretty painful process but will work.

**Comment by jonathon2nd** [comment]
I am closing this as I was able to get a fresh AWX install with external postgres working. What wound up being the issue was the secret key `secret_key_secret: awx-secret-key`. I had included that originally so that the DB migration would be picked up and use properly. But having it defined had some negative effect.

I am including all values for my setup, so the next poor soul who falls upon this may not despair. 

AWX-operator values
awx-operator:2.6.0
```
AWX:
  enabled: true
  name: awx
  spec:
    admin_password_secret: awx-admin-password
    admin_user: admin
    hostname: awx.example.com
    postgres_configuration_secret: awx-postgres-operator-configuration
```
All other yamls
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-operator-configuration
  namespace: awx-operator
stringData:
  host: master.awx-postgres
  port: "5432"
  database: awx
  username: postgres
  password: password
  type: unmanaged
  sslmode: allow
type: Opaque
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  labels:
    team: acid
  name: acid-awx
  namespace: awx-postgres
spec:
  spiloFSGroup: 103
  allowedSourceRanges:
  - 10.0.0.0/8
  databases:
    awx: awx

  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  enableConnectionPooler: false # enable/disable connection pooler deployment
  enableReplicaConnectionPooler: false # set to enable connectionPooler for replica service

  enableLogicalBackup: true
  logicalBackupSchedule: 0 0 1 * *
  numberOfInstances: 3
  postgresql:
    version: "14"
    parameters:  # Expert section
      hot_standby_feedback: "on"
      log_statement: "all"
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  users:
    awx: []
  volume:
    size: 10Gi

  patroni:
    synchronous_mode: true
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: spilo
    cluster-name: acid-awx
    spilo-role: master
    team: acid
  name: master
  namespace: awx-postgres
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    application: spilo
    cluster-name: acid-awx
    spilo-role: master
```
