### ISSUE TITLE
awx operator organization

### ISSUE THREAD

**Issue by Mostafakhedri** [ansible/tower-operator#1555]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello professionals.
I setup and config AWX on my cluster with AWX operator. In the LDAP integration section when I add extra_setting for creating an organization in AWX, It doesn't work and no organization is created in AWX. All other extra_settings working correctly, except organization and teams. my settings are as below:
```
extra_settings:
- setting: AUTH_LDAP_ORGANIZATION_MAP
          value: {
            "TEST": {
            "admins": "cn=awx-admins,dc=abc,dc=tech",
            "remove_admins": false,
            "users": [
              "cn=awx-admins,dc=abc,dc=tech"
            ],
            "remove_users": false
           }
          }```

I didn't have any logs about this in my awx-web pod too.

### AWX Operator version

2.5.2

### AWX version

v23.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.23

### Modifications

no

### Steps to reproduce

These are my complete values parameters:

``
AWX:
  enabled: true
  name: awx
  spec:
    admin_user: admin
    postgres_resource_requirements:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: '1'
          memory: 4Gi
    postgres_storage_requirements:
        requests:
          storage: 8Gi
        limits:
          storage: 50Gi
    postgres_storage_class: rawfile-btrfs
    postgres_extra_args:
        - '-c'
        - 'max_connections=1000'
    ingress_type: ingress
    hostname: awx.abc.tech
    ingress_class_name: nginx
    ingress_annotations: |
      cert-manager.io/cluster-issuer: letsencrypt
    web_resource_requirements:
      requests:
        cpu: 250m
        memory: 2Gi
        ephemeral-storage: 100M
      limits:
        cpu: 1000m
        memory: 4Gi
        ephemeral-storage: 500M
    task_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
        ephemeral-storage: 100M
      limits:
        cpu: 2000m
        memory: 2Gi
        ephemeral-storage: 500M
    ee_resource_requirements:
      requests:
        cpu: 250m
        memory: 100Mi
        ephemeral-storage: 100M
      limits:
        cpu: 500m
        memory: 2Gi
        ephemeral-storage: 500M   
    extra_settings:
        - setting: AUTH_LDAP_SERVER_URI
          value: >-
            "ldaps://ldap.abc.tech:636"

        - setting: AUTH_LDAP_BIND_DN
          value: >-
            "cn=xreadonly,dc=abc,dc=tech"

        - setting: AUTH_LDAP_BIND_PASSWORD
          value: >-
            "wYXprFHA5ErrPpdXKS28nbGyXCBkurqw"

        - setting: AUTH_LDAP_USER_SEARCH
          value: 'LDAPSearch("DC=abc,DC=tech",ldap.SCOPE_SUBTREE,"(cn=%(user)s)",)'

        - setting: AUTH_LDAP_GROUP_SEARCH
          value: 'LDAPSearch("DC=abc,DC=tech",ldap.SCOPE_SUBTREE,"(objectClass=groupOfUniqueNames)",)'

        - setting: AUTH_LDAP_GROUP_TYPE
          value: 'GroupOfUniqueNamesType()'

        - setting: AUTH_LDAP_USER_ATTR_MAP
          value: '{"first_name": "givenName","last_name": "sn","email": "mail"}'

        - setting: AUTH_LDAP_REQUIRE_GROUP
          value: >-
            "CN=awx-admins,DC=abc,DC=tech"

        - setting: AUTH_LDAP_USER_FLAGS_BY_GROUP
          value: {
            "is_superuser": [
              "CN=awx-admins,DC=abc,DC=tech"
            ]
          }

        - setting: AUTH_LDAP_START_TLS
          value: >-
            "false"


        - setting: AUTH_LDAP_ORGANIZATION_MAP
          value: {
            "LDAP Organization": {
            "admins": "cn=awx-admins,dc=abc,dc=tech",
            "remove_admins": false,
            "users": [
              "cn=awx-admins,dc=abc,dc=tech"
            ],
            "remove_users": false
           }
          }
``

### Expected results

I want to see my TEST organization in AWX Organization Panel as below:

![image](https://github.com/ansible/awx-operator/assets/56105950/9b158021-61f0-439f-80ca-86f228626046)

the 

### Actual results

But I see just Default Organization built-in AWX:
![image](https://github.com/ansible/awx-operator/assets/56105950/be03f740-487d-4924-85c1-40bfc8e6795a)


### Additional information

I didn't see any relevant logs in either the awx-web pod or the awx-operator pod.

### Operator Logs

this is my awx-web pod logs:
```
redis 1:M 11 Sep 2023 10:24:36.038 * 100 changes in 300 seconds. Saving...
redis 1:M 11 Sep 2023 10:24:36.038 * Background saving started by pid 26
redis 26:C 11 Sep 2023 10:24:36.043 * DB saved on disk
redis 26:C 11 Sep 2023 10:24:36.043 * Fork CoW for RDB: current 0 MB, peak 0 MB, average 0 MB
redis 1:M 11 Sep 2023 10:24:36.139 * Background saving terminated with success
awx-web [pid: 39|app: 0|req: 10/23] 10.0.10.163 () {62 vars in 1138 bytes} [Mon Sep 11 10:21:40 2023] OPTIONS /api/v2/instance_groups/ => generated 13949 bytes in 108 msecs (HTTP/1.1 200) 14 headers in 586 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:40,188 DEBUG    [bb3e321707ec44ccbc86f12d82342662] awx.main.scheduler ******************INSTANCE GROUP QUERYSET PASSED -- FILTERING TASKS ****************************
awx-web 2023-09-11 10:21:40,222 DEBUG    [bb3e321707ec44ccbc86f12d82342662] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/instance_groups/?order_by=name&page=1&page_size=5'>, response_time: 0.145s
awx-web 10.0.3.17 - - [11/Sep/2023:10:21:40 +0000] "GET /api/v2/instance_groups/?order_by=name&page=1&page_size=5 HTTP/1.1" 200 2180 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 36|app: 0|req: 4/24] 10.0.3.17 () {60 vars in 1158 bytes} [Mon Sep 11 10:21:40 2023] GET /api/v2/instance_groups/?order_by=name&page=1&page_size=5 => generated 2180 bytes in 146 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:48,887 DEBUG    [6c68f728f5de43709fcb5c45f44a2f19] awx.analytics.performance request: <WSGIRequest: OPTIONS '/api/v2/execution_environments/'>, response_time: 0.135s
awx-web 10.0.10.163 - - [11/Sep/2023:10:21:48 +0000] "OPTIONS /api/v2/execution_environments/ HTTP/1.1" 200 10972 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 11/25] 10.0.10.163 () {62 vars in 1152 bytes} [Mon Sep 11 10:21:48 2023] OPTIONS /api/v2/execution_environments/ => generated 10972 bytes in 184 msecs (HTTP/1.1 200) 14 headers in 586 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:49,126 DEBUG    [bd58c2cc7f6a4698991c3304d406b72f] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/execution_environments/?or__organization__isnull=True&order_by=name&page=1&page_size=5'>, response_time: 0.374s
awx-web [pid: 38|app: 0|req: 6/26] 10.0.3.17 () {60 vars in 1232 bytes} [Mon Sep 11 10:21:48 2023] GET /api/v2/execution_environments/?or__organization__isnull=True&order_by=name&page=1&page_size=5 => generated 1271 bytes in 378 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
awx-web 10.0.3.17 - - [11/Sep/2023:10:21:49 +0000] "GET /api/v2/execution_environments/?or__organization__isnull=True&order_by=name&page=1&page_size=5 HTTP/1.1" 200 1271 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web 2023-09-11 10:21:53,423 DEBUG    [543a20bfcaed4ad5bee2b057bb8bbc0d] awx.analytics.performance request: <WSGIRequest: POST '/api/v2/organizations/'>, response_time: 0.510s
awx-web 10.0.3.17 - - [11/Sep/2023:10:21:53 +0000] "POST /api/v2/organizations/ HTTP/1.1" 201 3654 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 12/27] 10.0.3.17 () {66 vars in 1213 bytes} [Mon Sep 11 10:21:52 2023] POST /api/v2/organizations/ => generated 3654 bytes in 519 msecs (HTTP/1.1 201) 15 headers in 626 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:53,464 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:21:53,764 DEBUG    [95cd7bd3e6d848568a1565062dab0a60] awx.analytics.performance request: <WSGIRequest: POST '/api/v2/organizations/3/instance_groups/'>, response_time: 0.212s
awx-web 10.0.3.17 - - [11/Sep/2023:10:21:53 +0000] "POST /api/v2/organizations/3/instance_groups/ HTTP/1.1" 204 0 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 13/28] 10.0.3.17 () {66 vars in 1243 bytes} [Mon Sep 11 10:21:53 2023] POST /api/v2/organizations/3/instance_groups/ => generated 0 bytes in 215 msecs (HTTP/1.1 204) 13 headers in 558 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:54,003 DEBUG    [bcb51d9cb6bf4e3fa4ab2303c857f86b] awx.analytics.performance request: <WSGIRequest: POST '/api/v2/organizations/3/galaxy_credentials/'>, response_time: 0.174s
awx-web [pid: 39|app: 0|req: 14/29] 10.0.3.17 () {66 vars in 1249 bytes} [Mon Sep 11 10:21:53 2023] POST /api/v2/organizations/3/galaxy_credentials/ => generated 0 bytes in 177 msecs (HTTP/1.1 204) 13 headers in 558 bytes (1 switches on core 0)
awx-web 10.0.3.17 - - [11/Sep/2023:10:21:54 +0000] "POST /api/v2/organizations/3/galaxy_credentials/ HTTP/1.1" 204 0 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web 2023-09-11 10:21:54,653 DEBUG    [e27fe9336ce54a5ebb8d22103735eff4] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/3/'>, response_time: 0.483s
awx-web 10.0.3.17 - - [11/Sep/2023:10:21:54 +0000] "GET /api/v2/organizations/3/ HTTP/1.1" 200 3664 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 15/30] 10.0.3.17 () {60 vars in 1093 bytes} [Mon Sep 11 10:21:54 2023] GET /api/v2/organizations/3/ => generated 3664 bytes in 486 msecs (HTTP/1.1 200) 14 headers in 599 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:54,660 DEBUG    [bc2ac826d5494a6f9142abfc73f6469e] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/?page_size=1&role_level=notification_admin_role'>, response_time: 0.487s
awx-web 10.0.12.170 - - [11/Sep/2023:10:21:54 +0000] "GET /api/v2/organizations/?page_size=1&role_level=notification_admin_role HTTP/1.1" 200 3565 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 38|app: 0|req: 7/31] 10.0.12.170 () {60 vars in 1184 bytes} [Mon Sep 11 10:21:54 2023] GET /api/v2/organizations/?page_size=1&role_level=notification_admin_role => generated 3565 bytes in 491 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:54,667 DEBUG    [851af26fe4d44ef3b40e2df2504134d8] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/?id=3&role_level=auditor_role'>, response_time: 0.495s
awx-web [pid: 40|app: 0|req: 5/32] 10.0.6.172 () {60 vars in 1147 bytes} [Mon Sep 11 10:21:54 2023] GET /api/v2/organizations/?id=3&role_level=auditor_role => generated 52 bytes in 498 msecs (HTTP/1.1 200) 14 headers in 583 bytes (1 switches on core 0)
awx-web 10.0.6.172 - - [11/Sep/2023:10:21:54 +0000] "GET /api/v2/organizations/?id=3&role_level=auditor_role HTTP/1.1" 200 52 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web 2023-09-11 10:21:54,842 DEBUG    [e3e9a9bc14f947b7bed3ddf56cbcbf57] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/?id=3&role_level=admin_role'>, response_time: 0.654s
awx-web 10.0.6.172 - - [11/Sep/2023:10:21:54 +0000] "GET /api/v2/organizations/?id=3&role_level=admin_role HTTP/1.1" 200 3664 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" "x.x.x.x"
awx-web [pid: 36|app: 0|req: 5/33] 10.0.6.172 () {60 vars in 1143 bytes} [Mon Sep 11 10:21:54 2023] GET /api/v2/organizations/?id=3&role_level=admin_role => generated 3664 bytes in 656 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:54,992 DEBUG    [df2c8c31f007472cb866fc0313467b30] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/3/galaxy_credentials/'>, response_time: 0.821s
awx-web [pid: 37|app: 0|req: 2/34] 10.0.10.163 () {60 vars in 1133 bytes} [Mon Sep 11 10:21:54 2023] GET /api/v2/organizations/3/galaxy_credentials/ => generated 1513 bytes in 823 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
awx-web 10.0.10.163 - - [11/Sep/2023:10:21:54 +0000] "GET /api/v2/organizations/3/galaxy_credentials/ HTTP/1.1" 200 1513 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web 2023-09-11 10:21:55,028 DEBUG    [6f245bbcf7c34d6bab4a1aedbb6deaf0] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/3/'>, response_time: 0.318s
awx-web [pid: 39|app: 0|req: 16/35] 10.0.12.170 () {60 vars in 1095 bytes} [Mon Sep 11 10:21:54 2023] GET /api/v2/organizations/3/ => generated 3664 bytes in 325 msecs (HTTP/1.1 200) 14 headers in 599 bytes (1 switches on core 0)
awx-web 10.0.12.170 - - [11/Sep/2023:10:21:55 +0000] "GET /api/v2/organizations/3/ HTTP/1.1" 200 3664 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web 2023-09-11 10:21:55,227 DEBUG    [821ba31054df4825a70d441bb379a8fa] awx.main.scheduler ******************INSTANCE GROUP QUERYSET PASSED -- FILTERING TASKS ****************************
awx-web 2023-09-11 10:21:55,268 DEBUG    [821ba31054df4825a70d441bb379a8fa] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/3/instance_groups/'>, response_time: 0.205s
awx-web [pid: 37|app: 0|req: 3/36] 10.0.10.163 () {60 vars in 1127 bytes} [Mon Sep 11 10:21:55 2023] GET /api/v2/organizations/3/instance_groups/ => generated 1120 bytes in 206 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
awx-web 10.0.10.163 - - [11/Sep/2023:10:21:55 +0000] "GET /api/v2/organizations/3/instance_groups/ HTTP/1.1" 200 1120 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web 2023-09-11 10:21:55,314 DEBUG    [edb5150ce7024ff9b56a1f164558844a] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/3/galaxy_credentials/'>, response_time: 0.250s
awx-web 10.0.6.172 - - [11/Sep/2023:10:21:55 +0000] "GET /api/v2/organizations/3/galaxy_credentials/ HTTP/1.1" 200 1513 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 17/37] 10.0.6.172 () {60 vars in 1132 bytes} [Mon Sep 11 10:21:55 2023] GET /api/v2/organizations/3/galaxy_credentials/ => generated 1513 bytes in 253 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:57,468 DEBUG    [3e25350c6f6e4041b8cb6f846664b821] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/?order_by=name&page=1&page_size=20'>, response_time: 0.253s
awx-web 10.0.6.172 - - [11/Sep/2023:10:21:57 +0000] "GET /api/v2/organizations/?order_by=name&page=1&page_size=20 HTTP/1.1" 200 10739 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 18/38] 10.0.6.172 () {60 vars in 1157 bytes} [Mon Sep 11 10:21:57 2023] GET /api/v2/organizations/?order_by=name&page=1&page_size=20 => generated 10739 bytes in 263 msecs (HTTP/1.1 200) 14 headers in 586 bytes (1 switches on core 0)
awx-web 2023-09-11 10:21:57,588 DEBUG    [641d4584f91847f3864ef76fa620a57f] awx.analytics.performance request: <WSGIRequest: OPTIONS '/api/v2/organizations/'>, response_time: 0.374s
awx-web 10.0.10.163 - - [11/Sep/2023:10:21:57 +0000] "OPTIONS /api/v2/organizations/ HTTP/1.1" 200 10075 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 37|app: 0|req: 4/39] 10.0.10.163 () {62 vars in 1134 bytes} [Mon Sep 11 10:21:57 2023] OPTIONS /api/v2/organizations/ => generated 10075 bytes in 378 msecs (HTTP/1.1 200) 14 headers in 586 bytes (1 switches on core 0)
awx-web 2023-09-11 10:22:08,480 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:22:23,660 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:22:38,676 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:22:53,696 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:23:08,716 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:23:24,063 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:23:30,646 DEBUG    [1e632ee81db84e86913434da82b66d2a] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/projects/?organization=3'>, response_time: 0.440s
awx-web 10.0.12.170 - - [11/Sep/2023:10:23:30 +0000] "GET /api/v2/projects/?organization=3 HTTP/1.1" 200 52 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 19/40] 10.0.12.170 () {60 vars in 1110 bytes} [Mon Sep 11 10:23:30 2023] GET /api/v2/projects/?organization=3 => generated 52 bytes in 442 msecs (HTTP/1.1 200) 14 headers in 583 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:30,740 DEBUG    [0d050ecdebf84e98ac64e309a722182f] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/credentials/?organization=3'>, response_time: 0.534s
awx-web 10.0.10.163 - - [11/Sep/2023:10:23:30 +0000] "GET /api/v2/credentials/?organization=3 HTTP/1.1" 200 52 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 38|app: 0|req: 8/41] 10.0.10.163 () {60 vars in 1116 bytes} [Mon Sep 11 10:23:30 2023] GET /api/v2/credentials/?organization=3 => generated 52 bytes in 536 msecs (HTTP/1.1 200) 14 headers in 583 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:30,756 DEBUG    [2d9c10cf0fa6480ab5b0198ff9e164f6] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/notification_templates/?organization=3'>, response_time: 0.550s
awx-web [pid: 37|app: 0|req: 5/42] 10.0.3.17 () {60 vars in 1136 bytes} [Mon Sep 11 10:23:30 2023] GET /api/v2/notification_templates/?organization=3 => generated 52 bytes in 552 msecs (HTTP/1.1 200) 14 headers in 583 bytes (1 switches on core 0)
awx-web 10.0.3.17 - - [11/Sep/2023:10:23:30 +0000] "GET /api/v2/notification_templates/?organization=3 HTTP/1.1" 200 52 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web 2023-09-11 10:23:30,846 DEBUG    [5d6d9b847423421aa259dfec677e7446] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/teams/?organization=3'>, response_time: 0.640s
awx-web 10.0.12.170 - - [11/Sep/2023:10:23:30 +0000] "GET /api/v2/teams/?organization=3 HTTP/1.1" 200 52 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 36|app: 0|req: 6/43] 10.0.12.170 () {60 vars in 1104 bytes} [Mon Sep 11 10:23:30 2023] GET /api/v2/teams/?organization=3 => generated 52 bytes in 642 msecs (HTTP/1.1 200) 14 headers in 583 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:30,947 DEBUG    [669928597b854e40a0a33bd234e8b949] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/inventories/?organization=3'>, response_time: 0.297s
awx-web 10.0.6.172 - - [11/Sep/2023:10:23:30 +0000] "GET /api/v2/inventories/?organization=3 HTTP/1.1" 200 52 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 20/44] 10.0.6.172 () {60 vars in 1115 bytes} [Mon Sep 11 10:23:30 2023] GET /api/v2/inventories/?organization=3 => generated 52 bytes in 300 msecs (HTTP/1.1 200) 14 headers in 583 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:30,960 DEBUG    [f00447a9e419451d97ae8e6a2b657718] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/execution_environments/?organization=3'>, response_time: 0.752s
awx-web 10.0.10.163 - - [11/Sep/2023:10:23:30 +0000] "GET /api/v2/execution_environments/?organization=3 HTTP/1.1" 200 52 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 40|app: 0|req: 6/45] 10.0.10.163 () {60 vars in 1138 bytes} [Mon Sep 11 10:23:30 2023] GET /api/v2/execution_environments/?organization=3 => generated 52 bytes in 755 msecs (HTTP/1.1 200) 14 headers in 583 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:30,980 DEBUG    [4643239ce3954775af5a9a6e21783b83] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/applications/?organization=3'>, response_time: 0.236s
awx-web 10.0.12.170 - - [11/Sep/2023:10:23:30 +0000] "GET /api/v2/applications/?organization=3 HTTP/1.1" 200 52 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 38|app: 0|req: 9/46] 10.0.12.170 () {60 vars in 1118 bytes} [Mon Sep 11 10:23:30 2023] GET /api/v2/applications/?organization=3 => generated 52 bytes in 239 msecs (HTTP/1.1 200) 14 headers in 583 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:32,983 DEBUG    [3597034e17d24fe0b1de07b8c92412fd] awx.analytics.performance request: <WSGIRequest: DELETE '/api/v2/organizations/3/'>, response_time: 0.738s
awx-web 10.0.12.170 - - [11/Sep/2023:10:23:32 +0000] "DELETE /api/v2/organizations/3/ HTTP/1.1" 204 0 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 37|app: 0|req: 6/47] 10.0.12.170 () {62 vars in 1137 bytes} [Mon Sep 11 10:23:32 2023] DELETE /api/v2/organizations/3/ => generated 0 bytes in 741 msecs (HTTP/1.1 204) 13 headers in 572 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:33,285 DEBUG    [4e710a4c208549df8a2a188a7f3c61d9] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/organizations/?order_by=name&page=1&page_size=20'>, response_time: 0.221s
awx-web 10.0.10.163 - - [11/Sep/2023:10:23:33 +0000] "GET /api/v2/organizations/?order_by=name&page=1&page_size=20 HTTP/1.1" 200 7126 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 39|app: 0|req: 21/48] 10.0.10.163 () {60 vars in 1158 bytes} [Mon Sep 11 10:23:33 2023] GET /api/v2/organizations/?order_by=name&page=1&page_size=20 => generated 7126 bytes in 223 msecs (HTTP/1.1 200) 14 headers in 585 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:33,395 DEBUG    [19bc14e5b6fb4453917370843f9d72a1] awx.analytics.performance request: <WSGIRequest: OPTIONS '/api/v2/organizations/'>, response_time: 0.331s
awx-web 10.0.12.170 - - [11/Sep/2023:10:23:33 +0000] "OPTIONS /api/v2/organizations/ HTTP/1.1" 200 10075 "http://awx.abc.tech/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" ""
awx-web [pid: 38|app: 0|req: 10/49] 10.0.12.170 () {62 vars in 1134 bytes} [Mon Sep 11 10:23:33 2023] OPTIONS /api/v2/organizations/ => generated 10075 bytes in 335 msecs (HTTP/1.1 200) 14 headers in 586 bytes (1 switches on core 0)
awx-web 2023-09-11 10:23:39,084 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:23:54,100 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:24:09,116 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:24:24,293 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:24:39,308 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:24:54,324 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:25:09,340 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:25:24,580 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:25:39,600 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:25:54,616 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:26:09,628 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:26:24,796 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
awx-web 2023-09-11 10:26:39,816 DEBUG    [-] awx.main.commands.run_ws_heartbeat Sending heartbeat
```
