### ISSUE TITLE
"security_context_settings" required

### ISSUE THREAD

**Issue by kaveh6161** [ansible/tower-operator#1568]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

I see from older issues that below features used to be supported for the AWX deployment (nowadays AWX instance):
```
security_context_settings:
    runAsUser: 1001
    runAsGroup: 1001
    allowPrivilegeEscalation: true
```
I need these for the Postgres Pod, but there's no way to set them. Or am I missing something!?
