### ISSUE TITLE
Operator created ingress not routing traffic

### ISSUE THREAD

**Issue by AlistairMaccallum** [ansible/tower-operator#1569]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When using the operator to create an ingress with Kong ingress controller the service is not accessible with error
`failure to get a peer from the ring-balancer.`

### AWX Operator version

2.5.3

### AWX version

23.1.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.27.6

### Modifications

no

### Steps to reproduce

Deploy operator and then apply awx yaml as follows.

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  
  replicas: 1
  
  admin_user: admin
  admin_password_secret: awx-admin-password
  
  ingress_type: ingress
  ingress_annotations: | 
    cert-manager.io/cluster-issuer: letsencrypt-staging
    konghq.com/https-redirect-status-code: "308"
    konghq.com/protocols: https
  ingress_class_name: kong
  ingress_tls_secret: awx-op-vaarst-io
  ingress_path: /
  ingress_path_type: Prefix
  ingress_api_version: networking.k8s.io/v1
  hostname: awx.op.vaarst.io

  projects_persistence: true
  projects_existing_claim: awx-projects-claim
```

### Expected results

To be able to access the login web ui from the browser.

### Actual results

Error `failure to get a peer from the ring-balancer.` when browsing to the page.

### Additional information

**Service Description**
```yaml
❯ k describe svc awx-service
Name:              awx-service
Namespace:         awx
Labels:            app.kubernetes.io/component=awx
                   app.kubernetes.io/managed-by=awx-operator
                   app.kubernetes.io/operator-version=2.5.3
                   app.kubernetes.io/part-of=awx
Annotations:       <none>
Selector:          app.kubernetes.io/component=awx,app.kubernetes.io/managed-by=awx-operator,app.kubernetes.io/name=awx-web
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.109.5.52
IPs:               10.109.5.52
Port:              http  80/TCP
TargetPort:        8052/TCP
Endpoints:         10.254.3.87:8052
Session Affinity:  None
Events:            <none>
```

**Ingress description**

```yaml
❯ k describe ingresses.networking.k8s.io awx-ingress
Name:             awx-ingress
Labels:           app.kubernetes.io/component=awx
                  app.kubernetes.io/managed-by=awx-operator
                  app.kubernetes.io/operator-version=2.5.3
                  app.kubernetes.io/part-of=awx
Namespace:        awx
Address:          
Ingress Class:    kong
Default backend:  <default>
TLS:
  awx-op-vaarst-io terminates awx.op.vaarst.io
Rules:
  Host              Path  Backends
  ----              ----  --------
  awx.op.vaarst.io  
                    /   awx-service:80 (10.254.3.87:8052)
Annotations:        cert-manager.io/cluster-issuer: letsencrypt-staging
                    konghq.com/https-redirect-status-code: 308
                    konghq.com/protocols: https
Events:
  Type     Reason                              Age                 From                       Message
  ----     ------                              ----                ----                       -------
  Normal   CreateCertificate                   46m                 cert-manager-ingress-shim  Successfully created Certificate "awx-op-vaarst-io"
  Warning  KongConfigurationTranslationFailed  36m (x25 over 37m)  kong-client                can't add target for backend awx-service: no kubernetes service found
  Warning  KongConfigurationTranslationFailed  36m (x25 over 37m)  kong-client                can't add target for backend awx-service: no kubernetes service found
  Warning  KongConfigurationTranslationFailed  36m (x25 over 37m)  kong-client                can't add target for backend awx-service: no kubernetes service found
```
