### ISSUE TITLE
Create and use custom admin password

### ISSUE THREAD

**Issue by gdelanoe** [ansible/tower-operator#158]
Hello,

I tried to deploy an awx in a green field environment using awx-operator. As I am waiting for a newer docker image of awx-operator, I had to create manually a loadbalancer service to fix [this issue](https://github.com/ansible/awx-operator/issues/151). Once the service is up I can access to my awx instance's login page, unfortunately, I can't log in awx using the admin/mypassword values.

I used this YAML code to describe the AWX CR :
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: ${K8S_AWX_NAMESPACE}
spec:
  tower_hostname: ${INTERNAL_AWX_HOST}
  tower_admin_user: admin
  tower_admin_email: ${AWX_EMAIL}
  tower_admin_password_secret: mypassword
  tower_broadcast_websocket_secret: awx-broadcast-websocket
  tower_postgres_configuration_secret: awx-postgres-configuration
  tower_ingress_type: LoadBalancer
  tower_loadbalancer_annotations: "networking.gke.io/load-balancer-type: Internal"
  tower_loadbalancer_protocol: http
  tower_loadbalancer_port: 80
```

The k8s secret that must contains my admin login is correctly created : 
```
kubectl -n staging-awx get secret                                                        
NAME                         TYPE                                  DATA   AGE
awx-admin-password           Opaque                                1      76m    <- LOOKS LIKE GOOD
awx-app-credentials          Opaque                                2      75m
awx-broadcast-websocket      Opaque                                1      75m
awx-operator-token-zznjk     kubernetes.io/service-account-token   3      82m
awx-postgres-configuration   Opaque                                5      76m
awx-secret-key               Opaque                                1      76m
awx-token-lcn6n              kubernetes.io/service-account-token   3      75m
default-token-9qgfw          kubernetes.io/service-account-token   3      82m
```

When I look in the secret "awx-admin-password", I found that password field is not "mypassword" but another one (I am aware that I must decode this secret using base64).
I tried to understand why AWX-operator do not use the password given with the "tower_admin_password_secret" value and I land here : [tower_admin_password_secret.yaml.j2](https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_admin_password_secret.yaml.j2#L8). It looks like that awx-operator generate a new password and do not use the tower_admin_password_secret variable.

I also tried to use the base64 decoded autogenerated password in the "awx-admin-password" but I can't login on awx with admin/{base64 decoded autogenerated password}, I have no logs in the containers of awx-operator. I only have this error message on the login page "Invalid username or password. Please try again.".
 
My questions : 
- How can I log in the AWX ? Where I should find the admin password ?
- Is there a way to set my own admin custom password ?

Thank you for your help :)

**Comment by tylerauerbeck** [comment]
@gdelanoe I agree. That template looks like the culprit there. 

@Spredzy I see you made this change. Would it be alright to make this template a bit smarter and apply the given password if it is provided and then only autogenerate if it hasn't been provided?

**Comment by Spredzy** [comment]
The description you made of the behaviour `tower_admin_password_secret` is accurate and working as expected.

`tower_admin_password_secret` is not supposed to be a password, but a secret *containing* your password. As per the documentation https://github.com/ansible/awx-operator#admin-user-account-configuration

> I also tried to use the base64 decoded autogenerated password in the "awx-admin-password" but I can't login on awx with admin/{base64 decoded autogenerated password

This is what worries me a bit. If you run the command (`kubectl get secret <resourcename>-admin-password -o jsonpath="{.data.password}" | base64 --decode`) listed in the doc (as per above link) you should be able to log in - I have seen no issue in that area so far with multiple deployments a day - Can you make sure you remove all the secret related to a deployment (name) and retry.

>  Would it be alright to make this template a bit smarter and apply the given password if it is provided and then only autogenerate if it hasn't been provided?

@tylerauerbeck the secure answer is: no. We don't want to let people provide passwords as direct parameters to the operator (because then they are available in the clear) We won't every sensitive information to be stored and passed through secrets.

Hope that helps,

**Comment by tylerauerbeck** [comment]
@Spredzy Ahh. I missed the update on this needing to be specified in a secret beforehand otherwise it creates the random password. Completely agree then. This addresses the security concerns that you mention and some of the sharp edges I had in mind that pop up around not being able to specify your password.

**Comment by gdelanoe** [comment]
Hello,

Thank you both for your help. I really appreciate.

To resume what you said :
 - the tower_admin_password_secret variable is not the clear text password but a k8s secret, if set awx-operator create the awx-admin-password secret using the value of tower_admin_password_secret
 - if tower_admin_password_secret is not set or invalid, awx-operator generate a password

Does this summary is correct ?

Thank you @tchellomello for updating the documentation, I think it will helps.

So if I want to specify the admin password I must set tower_admin_password_secret as a base64 encoded password ? In my case "mypassword" should become "bXlwYXNzd29yZAo=". Is it correct ?

**Comment by Spredzy** [comment]
> the tower_admin_password_secret variable is not the clear text password but a k8s secret

Yes, this is correct.

> if set awx-operator create the awx-admin-password secret using the value of tower_admin_password_secret

No. If set, the awx-operator will look for the password field within that secret and use that value as the admin password.

> if tower_admin_password_secret is not set or invalid, awx-operator generate a password

Correct. It generates a secret that embed the password that is used for that deployment.

> So if I want to specify the admin password I must set tower_admin_password_secret as a base64 encoded password ?

No.

You should create a Secret within your namespace (example below) and use the name of this secret as the value of `tower_admin_password_secret`

```
---
apiVersion: v1
kind: Secret
metadata:
  name: <resourcename>-admin-password
  namespace: <target namespace>
stringData:
  password: mysuperlongpassword
```

**Comment by gdelanoe** [comment]
Ok, I get it.

Thank you for your help. I create a k8s secret with my clear password inside and change the tower_admin_password_secret variable to the name of the k8s secret.

**Comment by shubhamsaroj** [comment]
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: clusterip
  admin_password_secret: awx-demo-admin-password
  ```
  
  
  ```
  ---
apiVersion: v1
kind: Secret
metadata:
  name: awx-demo-admin-password
  namespace: awx
stringData:
  password: superstrongsecret
 ```
 
 
For me my password to login as admin user doesn't work.
