### ISSUE TITLE
Creating Custom Volumes to each containers get mounted to all pods regardless

### ISSUE THREAD

**Issue by CitizenKlu** [ansible/tower-operator#1583]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When using Custom Volumes as explained in the documentation, The volumes are supposed to be mounted only to the pods that contain the respective container but what happens is that all volumes are mounted to all pods regardless of the container that was assigned to, and that cause multi-attach error and failing of one of the pods to start which usually web pod.

I have modified the Chart to:- 
- create PVCs for etc directories in ee, task, and web containers and add the respective values in the values file.
- Create multiple AWX instances are required instead of only one.
- Add HAProxy to act as a load balancer between instances for High Availability when using external PostgreSQL database
- Configured to accept global labels to be added to all AWX resources.

### AWX Operator version

2.5.1 and 2.5.3

### AWX version

2.5.1 and 2.5.3 of Helm charts

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.21 and 1.25

### Modifications

yes

### Steps to reproduce

create custom volumes for ee, task, and web and mount each to its respective container using the values provided in the documentation and you will meet the same result in both version 2.5.1 and 2.5.3

### Expected results

All Resources are up and running properly and working well.

### Actual results

pods are in the init state because of the failed mount.

**Comment by fosterseth** [comment]
can you copy and paste your AWX CR file so we can take a look at the extra volumes and mounts you have defined?

**Comment by CitizenKlu** [comment]
@fosterseth The following is the Template for AWX, etc PVCs added 

### awx-deploy.yaml
```
{{- range $AWX := .Values.AWX }}
{{- if $AWX.enabled }}
{{- with $AWX }}
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: {{ $AWX.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- toYaml $AWX.labels | nindent 4 }}
spec:
{{- /* Include raw map from the values file spec */}}
{{ $AWX.spec | toYaml | indent 2 }}
{{- /* Provide security context defaults */}}
  {{- if not (hasKey $AWX.spec "security_context_settings") }}
  security_context_settings:
    runAsGroup: 0
    runAsUser: 0
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
  {{- end }}
{{- /* Postgres configs if enabled and not already present */}}
  {{- if and $AWX.postgres.enabled (not (hasKey $AWX.spec "postgres_configuration_secret")) }}
  postgres_configuration_secret: {{ include "postgres.secretName" $ }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
```


### awx-ee-etc-pvc.yaml
```
{{- range $AWX := .Values.AWX }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $AWX.name }}-ee-etc
spec:
  {{- if $.Values.storageClassName }}
  storageClassName: {{ $.Values.storageClassName }}
  {{- end }}
  accessModes:
    - {{ $.Values.accessMode }}
  resources:
    requests:
      storage: 50Gi
---
{{- end }}
```


### awx-task-etc-pvc.yaml
```
{{- range $AWX := .Values.AWX }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $AWX.name }}-task-etc
spec:
  {{- if $.Values.storageClassName }}
  storageClassName: {{ $.Values.storageClassName }}
  {{- end }}
  accessModes:
    - {{ $.Values.accessMode }}
  resources:
    requests:
      storage: 50Gi
---
{{- end }}
```

### awx-web-etc-pvc.yaml
```
{{- range $AWX := .Values.AWX }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $AWX.name }}-web-etc
spec:
  {{- if $.Values.storageClassName }}
  storageClassName: {{ $.Values.storageClassName }}
  {{- end }}
  accessModes:
    - {{ $.Values.accessMode }}
  resources:
    requests:
      storage: 50Gi
---
{{- end }}
```

###values.yaml
```
storageClassName: efs
accessMode: ReadWriteMany
AWX:
  # enable use of awx-deploy template
- enabled: true
  name: awx-cluster-1
  labels:
    companyName: XXX
  spec:
    image_version: 23.2.0
    auto_upgrade: false
    redis_image: public.ecr.aws/docker/library/redis
    postgres_configuration_secret: production-awx-postgresql-config
    csrf_cookie_secure: 'True'
    session_cookie_secure: 'True'
    web_replicas: 1
    task_replicas: 1
    service_type: ClusterIP
    task_privileged: true
    extra_settings:
      - setting: LOG_AGGREGATOR_LEVEL
        value: "'DEBUG'"
    admin_user: admin
    admin_password_secret: awx-admin-secret
    ipv6_disabled: true
    additional_labels:
      - companyName
    web_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    task_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    ee_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    extra_volumes: |
      - name: awx-cluster-1-ee-etc
        persistentVolumeClaim:
          claimName: awx-cluster-1-ee-etc
      - name: awx-cluster-1-task-etc
        persistentVolumeClaim:
          claimName: awx-cluster-1-task-etc
      - name: awx-cluster-1-web-etc
        persistentVolumeClaim:
          claimName: awx-cluster-1-web-etc
    ee_extra_volume_mounts: |
      - name: awx-cluster-1-ee-etc
        mountPath: /etc
    task_extra_volume_mounts: |
      - name: awx-cluster-1-task-etc
        mountPath: /etc
    web_extra_volume_mounts: |
      - name: awx-cluster-1-web-etc
        mountPath: /etc
  # configurations for external postgres instance
  postgres:
    enabled: false
    host: Unset
    port: Unset
    dbName: Unset
    username: Unset
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: Unset
    sslmode: prefer
    type: unmanaged

- enabled: true
  name: awx-cluster-2
  labels:
    companyName: XXX
  spec:
    image_version: 23.2.0
    redis_image: public.ecr.aws/docker/library/redis
    auto_upgrade: false
    postgres_configuration_secret: production-awx-postgresql-config
    csrf_cookie_secure: 'True'
    session_cookie_secure: 'True'
    web_replicas: 1
    task_replicas: 1
    service_type: ClusterIP
    task_privileged: true
    extra_settings:
      - setting: LOG_AGGREGATOR_LEVEL
        value: "'DEBUG'"
    admin_user: admin
    admin_password_secret: awx-admin-secret
    ipv6_disabled: true
    additional_labels:
      - companyName
    web_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    task_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    ee_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    extra_volumes: |
      - name: awx-cluster-2-ee-etc
        persistentVolumeClaim:
          claimName: awx-cluster-2-ee-etc
      - name: awx-cluster-2-task-etc
        persistentVolumeClaim:
          claimName: awx-cluster-2-task-etc
      - name: awx-cluster-2-web-etc
        persistentVolumeClaim:
          claimName: awx-cluster-2-web-etc
    ee_extra_volume_mounts: |
      - name: awx-cluster-2-ee-etc
        mountPath: /etc
    task_extra_volume_mounts: |
      - name: awx-cluster-2-task-etc
        mountPath: /etc
    web_extra_volume_mounts: |
      - name: awx-cluster-2-web-etc
        mountPath: /etc
  # configurations for external postgres instance
  postgres:
    enabled: false
    host: Unset
    port: Unset
    dbName: Unset
    username: Unset
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: Unset
    sslmode: prefer
    type: unmanaged

- enabled: true
  name: awx-cluster-3
  labels:
    companyName: XXX
  spec:
    image_version: 23.2.0
    redis_image: public.ecr.aws/docker/library/redis
    auto_upgrade: false
    postgres_configuration_secret: production-awx-postgresql-config
    csrf_cookie_secure: 'True'
    session_cookie_secure: 'True'
    web_replicas: 1
    task_replicas: 1
    service_type: ClusterIP
    task_privileged: true
    extra_settings:
      - setting: LOG_AGGREGATOR_LEVEL
        value: "'DEBUG'"
    admin_user: admin
    admin_password_secret: awx-admin-secret
    ipv6_disabled: true
    additional_labels:
      - companyName
    web_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    task_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    ee_resource_requirements:
      requests:
        cpu: 250m
        memory: 1Gi
      limits:
        memory: 4Gi
    extra_volumes: |
      - name: awx-cluster-3-ee-etc
        persistentVolumeClaim:
          claimName: awx-cluster-3-ee-etc
      - name: awx-cluster-3-task-etc
        persistentVolumeClaim:
          claimName: awx-cluster-3-task-etc
      - name: awx-cluster-3-web-etc
        persistentVolumeClaim:
          claimName: awx-cluster-3-web-etc
    ee_extra_volume_mounts: |
      - name: awx-cluster-3-ee-etc
        mountPath: /etc
    task_extra_volume_mounts: |
      - name: awx-cluster-3-task-etc
        mountPath: /etc
    web_extra_volume_mounts: |
      - name: awx-cluster-3-web-etc
        mountPath: /etc
  # configurations for external postgres instance
  postgres:
    enabled: false
    host: Unset
    port: Unset
    dbName: Unset
    username: Unset
    # for secret management, pass in the password independently of this file
    # at the command line, use --set AWX.postgres.password
    password: Unset
    sslmode: prefer
    type: unmanaged
```
