### ISSUE TITLE
awx-operator restore from PVC is not working

### ISSUE THREAD

**Issue by romankuzmik** [ansible/tower-operator#1586]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

awx-operator/roles/restore/tasks/init.yml has wrong conditions on "Set variables from awxbackup object statuses if provided" block.

instead of:
```
  when:
    - backup_name != '' or backup_name is defined
```

it should be
```
  when:
    - backup_name is defined and backup_name != '' 
```

otherwise restore from PVC will fail with:
```
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'backup_name != '' or backup_name is defined' failed. The error was: error while evaluating conditional (backup_name != '' or backup_name is defined): 'backup_name' is undefined. 'backup_name' is undefined
``` 

### AWX Operator version

2.7.0

### AWX version

23.3.0

### Kubernetes platform

other (please specify in additional information)

### Kubernetes/Platform version

v1.24.9

### Modifications

no

### Steps to reproduce

1. Create restore from PVC manifest 
```
apiVersion: awx.ansible.com/v1beta1
kind: AWXRestore
metadata:
  name: somebackup
  namespace: awx
spec:
  backup_dir: mybackupishere
  backup_pvc: mypvc
  backup_source: PVC
  deployment_name: awx
  image_pull_policy: IfNotPresent
  no_log: false
  set_self_labels: true
```
3. Observe an error on operator pod

### Expected results

AWX restore to complete successfully from PVC and folder within PVC specified

### Actual results

AWX restore is in error loop
