### ISSUE TITLE
wrong indent on task.yaml.j2 for security_context_settings section

### ISSUE THREAD

**Issue by romankuzmik** [ansible/tower-operator#1588]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

cc-awx-operator/roles/installer/templates/deployments/task.yaml.j2
```
{% if security_context_settings|length %}
        {{ security_context_settings | to_nice_yaml | indent(10) }}
{% endif %}
```
->
```
{% if security_context_settings|length %}
        {{ security_context_settings | to_nice_yaml | indent(8) }}
{% endif %}
```

### AWX Operator version

2.7.0

### AWX version

23.3.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.24.9

### Modifications

no

### Steps to reproduce

Perform fresh install with AWX manifest containing security_context_settings:
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
 ...
  security_context_settings:
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 0
    runAsUser: 0
```

### Expected results

aws-task deployment to be created

### Actual results

```
TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:248
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:                                  ^
failed: [localhost] (item=task) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"item\": \"task\", \"msg\": \"Failed to load resource definition: mapping values are not allowed here\
  in \\\"<unicode string>\\\", line 211, column 30:\
              fsGroupChangePolicy: OnRootMismatch\
                                 ^\"}
ok: [localhost] => (item=web) => {\"ansible_loop_var\": \"item\", \"c
```
