### ISSUE TITLE
Cannot install AWX, stuck on "Waiting for database migrations..."

### ISSUE THREAD

**Issue by GreenCappuccino** [ansible/tower-operator#1593]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When deploying AWX on a 3-node v1.26 k3s cluster, the AWX containers become stuck in a loop of waiting for migrations, while the Postgres become flooded with errors about how *relation "django_migrations" does not exist*.

### AWX Operator version

2.7.0

### AWX version

23.3.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.26.0+k3s1

### Modifications

no

### Steps to reproduce

Both the operator and the AWX resource are deployed via an ArgoCD application. My manifests for my lab cluster are public:

- [`external/awx/kustomization.yaml`](https://github.com/ShamrockTeam/kubernetes/blob/main/external/awx/kustomization.yaml) (Automatically built to `generated/awx` with repo tooling)
- [`releases/awx`](https://github.com/ShamrockTeam/kubernetes/tree/main/releases/awx) (Directory used by the ArgoCD application, references `generated/awx`)

### Expected results

Expected database to be initialized, and for the web service to become ready.

### Actual results

AWX containers become stuck in a "Waiting for database migrations...", "Waiting 30 seconds before next attempt" loop.

Postgres complains that "ERROR:  relation "django_migrations" does not exist at character 124".

### Operator Logs

[awx-manager.txt](https://github.com/ansible/awx-operator/files/12910811/awx-manager.txt)
[postgres.txt](https://github.com/ansible/awx-operator/files/12910812/postgres.txt)
[awx-metal-task.txt](https://github.com/ansible/awx-operator/files/12910813/awx-metal-task.txt)
[awx-metal-web.txt](https://github.com/ansible/awx-operator/files/12910814/awx-metal-web.txt)

**Comment by jonathon2nd** [comment]
Same. I had given up trying to [migrate](https://github.com/ansible/awx-operator/issues/1524), and went to just setup a clean install and just manually set it up.

Reverted back to 2.5.2 to get around this.

```
AWX:
  enabled: true
  name: awx
  spec:
    secret_key_secret: awx-secret-key
    admin_password_secret: awx-admin-password
    admin_user: admin
    hostname: awx.example.com
```

**Comment by dahendel** [comment]
I am having the same issue with 2.4.0, 2.5.0, 2.5.2, 2.6.0, and 2.7.0 on a fresh install and installing via helm chart.

Deleted the postgres volume each deploy to make sure it was a fresh postgres instance each time.

I also tried with an external DB and the default postgres k8s deployment.

```
  AWX:
    enabled: true
    name: awx
    spec:
      admin_user: user
      admin_email: user@email.com
      admin_password_secret: "{{ awx_admin_secret_name }}"
      image_pull_policy: Always
      projects_persistence: true
      projects_storage_class: openebs-hostpath
      projects_storage_access_mode: ReadWriteOnce
      projects_storage_size: 30Gi
      no_log: false
      service_type: ClusterIP
      ingress_type: ingress
      ingress_annotations: |
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hostname: "ansible.{{ domain }}"
```

**Comment by GreenCappuccino** [comment]
Ok, I think I've worked around my specific issue:

Currently testing on the `awx-operator` 2.5.2 and `awx` 23.0.0. From a fresh deploy, this presents the same issue (albeit in this version's case the spam is `relation "conf_setting" does not exist`).

The operator is responsible for performing database migrations, and in the task, it first checks [whether migrations are needed first](https://github.com/ansible/awx-operator/blob/2.5.2/roles/installer/tasks/install.yml#L83), and then [runs the migration](https://github.com/ansible/awx-operator/blob/2.5.2/roles/installer/tasks/install.yml#L94). It gets stuck at the second step, but by then `awx-manage showmigrations` already shows that all migrations are checked off (`[X]`). Simply deleting the operator pod to start a new run of the install task skips the migrate step and completes the installation.

I am going to test a fresh install w/ 2.7.0 with this workaround.

---

Additional notes:

It looks from in the latest `devel` branch a recent [commit](https://github.com/ansible/awx-operator/commit/019fa3d356c70c0c3a0eab5765a36af566ea08ea) was added that [modifies the migrate step](https://github.com/ansible/awx-operator/blob/019fa3d356c70c0c3a0eab5765a36af566ea08ea/roles/installer/tasks/install.yml#L94). This is to fix [this issue](https://github.com/ansible/awx/issues/14314). It might be related?

**Comment by GreenCappuccino** [comment]
Fresh install. Migrations took about 15 minutes for `awx-manage showmigrations` to report as complete. The task did not stall out this time. Successful installation. Issue may be intermittent?

**Comment by janorn** [comment]
I am also experiencing similar errors. If I create a new install "2.7.0" it get stuck installing somewhere before finishing db migrations. `awx-manage showmigrations` show no migrations to be finished after a long wait. I also notice that the task pod fails to launch. I only get the operator, postgres and web pods.

Postgres stdout keeps printing this:
```
2023-10-20 12:33:20.353 UTC [541] ERROR:  relation "django_migrations" does not exist at character 124
12:33:55.458 UTC [551] STATEMENT:  SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" WHERE ("django....
```

However if I do clean installs of either 2.5.3 or 2.6.0 they both come up fine. Trying to upgrade either of these installs to 2.7.0 will come up with migrations finished but no task pod. And not functional.

A part of the error message from the operator sort of hints to me that incorrect yaml is causing this.
```json
{
  "level": "error",
  "ts": "2023-10-20T11:32:23Z",
  "logger": "logging_event_handler",
  "msg": "",
  "name": "awx-prod",
  "namespace": "awx",
  "gvk": "awx.ansible.com/v1beta1, Kind=AWX",
  "event_type": "runner_on_failed",
  "job": "1570818909884888639",
  "EventData.Task": "Apply deployment resources",
  "EventData.TaskArgs": "",
  "EventData.FailedTaskPath": "/opt/ansible/roles/installer/tasks/resources_configuration.yml:248",
  "error": "[playbook task failed]",
  "stacktrace": "github.com/operator-framework/operator-sdk/internal/ansible/events.loggingEventHandler.Handle\n\t/workspace/internal/ansible/events/log_events.go:111"
}
{
  "level": "error",
  "ts": "2023-10-20T11:32:23Z",
  "logger": "runner",
  "msg": "ansible-playbook [core 2.15.2]\r\n  config file = /etc/ansible/ansible.cfg\r\n  configured module search path = ['/usr/share/ansible/openshift']\r\n  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible\r\n  ansible collection location = /opt/ansible/.ansible/collections:/usr/share/ansible/collections\r\n  executable location = /usr/local/bin/ansible-playbook\r\n  python version = 3.9.16 (main, May 31 2023, 12:21:58) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/usr/bin/python3)\r\n  jinja version = 3.1.2\r\n  libyaml = True\r\nUsing /etc/ansible/ansible.cfg as config file\r\nSkipping callback 'awx_display', as we already have a stdout callback.\nSkipping callback 'default', as we already have a stdout callback.\nSkipping callback 'minimal', as we already have a stdout callback.\nSkipping callback 'oneline', as we already have a stdout callback.\n\r\nPLAYBOOK: awx.yml **************************************************************\n1 plays in /opt/ansible/playbooks/awx.yml\n[WARNING]: Found variable using reserved name: no_log\n\r\nPLAY [localhost]"
}
```
Observe the log statement is truncated due to a huge stacktrace.

**Comment by janorn** [comment]
This is my helm spec values
```yaml
      AWX:
        enabled: true
        name: awx-prod
        spec:
          admin_user: admin
          ingress_type: ingress
          hostname: awx.test.com
          postgres_storage_class: trident
          postgres_keep_pvc_after_upgrade: false
```

**Comment by janorn** [comment]
A try to decrypt the whole msg from the last json log:
https://gist.github.com/janorn/c79ad68e0305f57ee70ca0b94c0deb4e

**Comment by janorn** [comment]
Looks like this is the place it fails:
```
TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:248
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:                                  ^
failed: [localhost] (item=task) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"item\": \"task\", \"msg\": \"Failed to load resource definition: mapping values are not allowed here\
  in \\\"<unicode string>\\\", line 209, column 30:\
              fsGroupChangePolicy: OnRootMismatch\
                                 ^\"}
```

**Comment by dahendel** [comment]
After starting from a fresh install and using an external DB, I was able to successfully get 2.6.0 installed without error. I had one issue, but it turned out to be user error. sslmode was set to none which is invalid and causing the django admin tasks to fail. I changed it to allow and everything is great.

**Comment by jonathon2nd** [comment]
@dahendel 

Can you tell me what external postgres you are using, and share your values for it and awx-operator?

**Comment by dahendel** [comment]
@jonathon2nd 
Postgres 14

the secret I generate is templated
```
  - name: "{{ awx_postgres_secret_name }}"
    namespace: "{{ awx_namespace }}"
    type: Opaque
    data:
      host: "{{ postgres_host | b64encode }}"
      port: "{{ '5432' | b64encode }}"
      database: "{{ 'awx' | b64encode }}"
      username: "{{ 'awx' | b64encode }}"
      password: "{{ awx_pg_password | b64encode }}"
      sslmode: "{{ 'allow' | b64encode }}"
      type: "{{ 'unmanaged' | b64encode }}"
```

Values:
```
  AWX:
    enabled: true
    name: sa-awx
    spec:
      admin_user: Admin_user
      admin_email: email@email.com
      admin_password_secret: "{{ awx_admin_secret_name }}"
      image_pull_policy: Always
      projects_persistence: true
      projects_storage_class: openebs-hostpath
      projects_storage_access_mode: ReadWriteOnce
      projects_storage_size: 30Gi
      no_log: false
      service_type: ClusterIP
      ingress_type: ingress
      ingress_annotations: |
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hostname: "ansible.{{ domain }}"
      postgres_configuration_secret:  "{{ awx_postgres_secret_name }}"
```
