### ISSUE TITLE
Task Replicas value is not working

### ISSUE THREAD

**Issue by intdel** [ansible/tower-operator#1596]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Two issues:

- Setting a values for "replicas" works only for web deployment (task deployment does not change)
- Settings task_replicas has no effect (whereas web_replicas works)

AWX Spec:

```
spec:
  admin_user: admin
  auto_upgrade: true
  create_preload_data: true
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  ipv6_disabled: false
  loadbalancer_ip: ''
  loadbalancer_port: 80
  loadbalancer_protocol: http
  no_log: true
  postgres_keepalives: true
  postgres_keepalives_count: 5
  postgres_keepalives_idle: 5
  postgres_keepalives_interval: 5
  projects_persistence: false
  projects_storage_access_mode: ReadWriteMany
  projects_storage_size: 8Gi
  replicas: 1
  route_tls_termination_mechanism: Edge
  security_context_settings:
    fsGroup: 0
    fsGroupChangePolicy: OnRootMismatch
    runAsGroup: 0
    runAsUser: 0
  set_self_labels: true
  task_privileged: false
```

### AWX Operator version

2.7.0

### AWX version

23.3.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

k3s

### Modifications

no

### Steps to reproduce

Change replica numbers in AWX spec

### Expected results

Task replica number is being set in task deployment

### Actual results

Task replica number is not being set in task deployment

**Comment by intdel** [comment]
After further troubleshooting the issue comes from here:

```
TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:248
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:                                  ^
failed: [localhost] (item=task) => {"ansible_loop_var": "item", "changed": false, "item": "task", "msg": "Failed to load resource definition: mapping values are not allowed here
  in \<unicode string>\, line 209, column 30:
              fsGroupChangePolicy: OnRootMismatch
 
    ^"}
 
```
which is 


```
- name: Apply deployment resources
  k8s:
    apply: yes
    definition: "{{ lookup('template', 'deployments/{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ (120 * replicas) or 120 }}"
  loop:
    - task
    - web
  register: this_deployment_result

```

so there seems to be something wrong with the generation of the deployment yaml of the task one.
