### ISSUE TITLE
Documentation: AWX backup secheduled job

### ISSUE THREAD

**Issue by fritz0011** [ansible/tower-operator#1605]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hello, 
I'd like to know if there is an automated way (cronjob) for creating backups using awxbackup 

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup-2023-10-18
  namespace: awx
spec:
  deployment_name: awx
  clean_backup_on_delete: True
  backup_pvc: backupawx
  postgres_image: postgres
  postgres_image_version: "14"
```
This manual approach is working flawless, but let's say that I would like to have scheduled every 6hours?

**Comment by fuggla** [comment]
Something like this perhaps? Dunno if it's best practice though.

Backup with todays date and time:

```
#!/usr/bin/env bash
manifest="
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup-$(date +%Y-%m-%d-%H%M)
  namespace: awx
spec:
  deployment_name: awx
  clean_backup_on_delete: True
  backup_pvc: backupawx
  postgres_image: postgres
  postgres_image_version: "14"
"
kubectl apply -f - <<< $manifest
```

Run script every six hours,

```
0 */6 * * * /path/to/awx-backup.bash
```
