### ISSUE TITLE
Service label selector are not unique and conflict when 2 or more `AWX`  deployments share the same namespace

### ISSUE THREAD

**Issue by tchellomello** [ansible/tower-operator#161]
Service label selector is not unique and conflict when 2 or more `AWX`  deployments share the same namespace, which can conflict when using an `IngressRoute` kind from `Traefik` for instance.

Recipe to reproduce the problem:

1. Create 2 `awx` instances on the same namespace
```sh
kubectl get awx -n default
NAME       AGE
awx-lab    11m
awx-toca   24h
```

2. Verify the service selector attribute is not unique
```sh
kubectl get service -l app=awx
NAME               TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
awx-lab-service    ClusterIP   10.233.7.163    <none>        80/TCP    11m
awx-toca-service   ClusterIP   10.233.48.164   <none>        80/TCP    24h
```
So now we have a problem if we expose this via an Ingress rule as the traffic will be split between the 2 different services

```yaml
$ kubectl get service awx-lab-service -o yaml | kubectl neat
apiVersion: v1
kind: Service
metadata:
  labels:
    app: awx
  name: awx-lab-service
  namespace: default
spec:
  clusterIP: 10.233.7.163
  ports:
  - name: http
    port: 80
    targetPort: 8052
  selector:
    app: awx
```
```yaml
kubectl get service awx-toca-service -o yaml | kubectl neat 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: awx
  name: awx-toca-service
  namespace: default
spec:
  clusterIP: 10.233.48.164
  ports:
  - name: http
    port: 80
    targetPort: 8052
  selector:
    app: awx
```

We should use unique labels and maybe follow the standard mentioned at https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**SAMPLE**
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-abcxzy
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm
```

I'm working on a PR for it
