### ISSUE TITLE
Errors in postgres pod

### ISSUE THREAD

**Issue by dkoci** [ansible/tower-operator#1610]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I have installed the latest version of the AWX operator. I noticed some errors in postgres pod.

`2023-10-24 14:18:58.204 UTC [1] LOG:  starting PostgreSQL 13.12 (Debian 13.12-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2023-10-24 14:18:58.204 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-10-24 14:18:58.204 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-10-24 14:18:58.205 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-10-24 14:18:58.216 UTC [64] LOG:  database system was shut down at 2023-10-24 14:18:58 UTC
2023-10-24 14:18:58.222 UTC [1] LOG:  database system is ready to accept connections
2023-10-24 14:19:07.450 UTC [71] FATAL:  password authentication failed for user "postgres"
2023-10-24 14:19:07.450 UTC [71] DETAIL:  Role "postgres" does not exist.
	Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"
2023-10-24 14:19:07.454 UTC [72] **FATAL:  password authentication failed for user "postgres"**
2023-10-24 14:19:07.454 UTC [72] **DETAIL:  Role "postgres" does not exist.**
	Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"`

There are also some django related errors:
`ERROR: relation "django_migrations" does not exist at character 124`
`STATEMENT: SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" WHERE ("django_migrations"."app" = 'main' AND NOT ("django_migrations"."name"::text LIKE '%squashed%')) ORDER BY "django_migrations"."id" DESC LIMIT 1
`

### AWX Operator version

2.7.0

### AWX version

23.3.0

### Kubernetes platform

openshift

### Kubernetes/Platform version

4.13

### Modifications

yes

### Steps to reproduce

Install 2.7.0 version of AWX operator. Check postgres pod logs.

### Expected results

I assume there should be no errors.

### Actual results

`2023-10-24 14:19:07.454 UTC [72] FATAL:  password authentication failed for user "postgres"
2023-10-24 14:19:07.454 UTC [72] DETAIL:  Role "postgres" does not exist.
	Connection matched pg_hba.conf line 99: "host all all all scram-sha-256"`

There are also some django related errors:
`ERROR: relation "django_migrations" does not exist at character 124`
`STATEMENT: SELECT "django_migrations"."id", "django_migrations"."app", "django_migrations"."name", "django_migrations"."applied" FROM "django_migrations" WHERE ("django_migrations"."app" = 'main' AND NOT ("django_migrations"."name"::text LIKE '%squashed%')) ORDER BY "django_migrations"."id" DESC LIMIT 1
`

### Additional information

I set my own admin_password_secret.

**Comment by fosterseth** [comment]
are you using external DB or allowing operator to create one?

can you paste your AWX manifest spec file?

is your postgres pod in a ready state?

**Comment by dkoci** [comment]
**are you using external DB or allowing operator to create one?**
Operator managed

**can you paste your AWX manifest spec file?**
<img width="366" alt="image" src="https://github.com/ansible/awx-operator/assets/5565897/f7890591-28cc-4ee9-8b74-10097865e2f2">

**is your postgres pod in a ready state?**
Yes, pod is ready and running

**Comment by Aaron199** [comment]
i have same issue

**Comment by djyasin** [comment]
Hello @dkoci,
Thank you for your reply and for the additional information. Were you able to resolve this issue on your end? If not, are you running off of a fresh install of AWX? Can you give us a bit more information regarding your configuration? Could you provide us with instructions on how to reproduce this as well?

Thank you so much for your time!

**Comment by dkoci** [comment]
> Hello @dkoci, Thank you for your reply and for the additional information. Were you able to resolve this issue on your end? If not, are you running off of a fresh install of AWX? Can you give us a bit more information regarding your configuration? Could you provide us with instructions on how to reproduce this as well?
> 
> Thank you so much for your time!

Hi @djyasin. I have not been able to resolve this issue. I have tried to install a fresh AWX cluster with kustomize:

**admin-password-secret.yaml**
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
stringData:
  password:******
```

**rolebinding.yaml**
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dk-any
subjects:
  - kind: ServiceAccount
    name: awx-demo
    namespace: awx-test
  - kind: ServiceAccount
    name: default
    namespace: awx-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:anyuid'
```

**awx-demo.yaml**
```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  namespace: awx-test
  ingress_type: Route
  admin_password_secret: awx-admin-password
```

**kustomization.yaml**
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.7.0
  - awx-demo.yaml
  - admin-password-secret.yaml
  - rolebinding.yaml

namespace: awx-test

images:
  - name: quay.io/ansible/awx-operator
     newTag: 2.7.0
```

`oc apply -k .`
