### ISSUE TITLE
Ingress_hosts not implemented in CRD

### ISSUE THREAD

**Issue by miguelgmedina** [ansible/tower-operator#1691]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When defining ingress, cannot use "ingress_hosts", only deprecated "ingress_tls_secret" and "hostname"

### AWX Operator version

2.10.0

### AWX version

latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

RKE2 1.26.4

### Modifications

no

### Steps to reproduce

After successfull AWX operator deployment, try to create the following AWX instance with ingress_type=ingress:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  bundle_cacert_secret: awx-custom-certs
  service_type: ClusterIP
  ingress_type: ingress
  ingress_hosts:
    - hostname: awx.demo.XXXX.com
      tls_secret: tls-awx-secret
  ingress_annotations: |
    cert-manager.io/cluster-issuer: ca-XXXX
```

Running kubectl apply:
```
Error from server (BadRequest): error when creating "awx-demo.yaml": AWX in version "v1beta1" cannot be handled as a AWX: strict decoding error: unknown field "spec.ingress_hosts"
```
AWX ingress documentation [here](https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/network-and-tls-configuration.html#ingress-type) includes that `ingress` host parameter but it is not defined in the CRD:

```
$ k get crds awxs.awx.ansible.com -o yaml | grep -i ingress
              ingress_annotations:
                description: Annotations to add to the Ingress Controller
              ingress_api_version:
                description: The Ingress API version to use
              ingress_class_name:
                description: The name of ingress class to use instead of the cluster
              ingress_controller:
                description: Special configuration for specific Ingress Controllers
              ingress_path:
                description: The ingress path used to reach the deployed service
              ingress_path_type:
                description: The ingress path type for the deployed service
              ingress_tls_secret:
                description: Secret where the Ingress TLS secret can be found
              ingress_type:
                description: The ingress type to use to reach the deployed instance
                - Ingress
                - ingress
```
Only deprecated `hostname` and `ingress_tls_secret` are present in the CRD.

### Expected results

Be able to use `ingress_hosts` as documented [here](https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/network-and-tls-configuration.html#ingress-type)

### Actual results

Not implemented new parameters in CRD.
