### ISSUE TITLE
how to manage high availability and disaster recovery with awx 

### ISSUE THREAD

**Issue by birb57** [ansible/tower-operator#1698]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hi

What is the preferred way to enable high availability and disaster recovery during  awx deployment  ?

Thanks for your help

### AWX Operator version

2.10.0

### AWX version

23.6.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.28

### Modifications

no

### Steps to reproduce

deploy awx

### Expected results

HA and DR capabilities

### Actual results

default awx operator install

**Comment by Tfinn92** [comment]
As far as HA is concerned, if using the helm chart, it's simple to specify the amount of replicas for both task and web you would like. For example, a snippet from our values.yml
```yaml
AWX:
  enabled: true
  name: awx
  namespace: awx
  spec:
    ## User creation 
    admin_user: admin
    admin_email: admin@admin.com

    ## Replica Settings for web/task pods
    replicas: 3
```

For DR, that's a very loaded question depending on your environment. For us, we have a cronjob that goes into the postgres pod and takes a pg_dump of the db and exports it out of the pod and onto offsite storage.  That being said, I do not believe there is any official documentation for DR, but I would be happy to be proven wrong :)
