### ISSUE TITLE
no matches for AWXMeshIngress upgrading to 2.11.0

### ISSUE THREAD

**Issue by dylex** [ansible/tower-operator#1701]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I just tried upgrading awx-operator from 2.10.0 to 2.11.0 using helm, and the operator fails.

### AWX Operator version

2.11.0

### AWX version

23.7.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.28.6

### Modifications

no

### Steps to reproduce

With a running 2.10.0 install, upgrade to 2.11.0 with helm.
Our deployment looks like this:
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  namespace: awx
  name: awx
spec:
  admin_email: admin@domain.com
  admin_password_secret: awx-admin-password
  service_type: ClusterIP
  ingress_type: ingress
  hostname: awx.domain.com
  ingress_class_name: nginx
  ingress_tls_secret: tls
  postgres_storage_class: mayastor
  postgres_storage_requirements:
    requests:
      storage: 64Gi
  postgres_extra_args:
    - '-c'
    - 'huge_pages=off'
```

### Expected results

Previous upgrades have worked, and this one seems to have too, except the operator keeps failing.

### Actual results

After errors, operator exits and is restarted by k8s. However, it does seem to have successfully upgraded everything and awx 23.7.0 is running successfully without issue as far as I can tell.

### Operator Logs

```
{"level":"error","ts":"2024-02-01T04:19:00Z","logger":"controller-runtime.source","msg":"if kind is a CRD, it should be installed before calling Start","kind":"AWXMeshIngress.awx.ansible.com","error":"no matches for kind \"AWXMeshIngress\" in version \"awx.ansible.com/v1alpha1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1.1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:143\nk8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:235\nk8s.io/apimachinery/pkg/util/wait.WaitForWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:662\nk8s.io/apimachinery/pkg/util/wait.poll\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:596\nk8s.io/apimachinery/pkg/util/wait.PollImmediateUntilWithContext\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.26.2/pkg/util/wait/wait.go:547\nsigs.k8s.io/controller-runtime/pkg/source.(*Kind).Start.func1\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/source/source.go:136"}
```
This is repeated a few times before it finally exits.
