### ISSUE TITLE
Upgrading from 2.12.2 to 2.13.1; awx-postgres-15-0 stuck in pending 

### ISSUE THREAD

**Issue by cpilton** [ansible/tower-operator#1772]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

awx-postgres-15-0 is stuck in pending after upgrading to 2.13.1.
```
Warning  FailedScheduling  14m (x2 over 19m)  default-scheduler  0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
```

PVs:
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                               STORAGECLASS          REASON   AGE
awx-projects-volume                        2Gi        RWO            Retain           Bound    awx/awx-projects-claim              awx-projects-volume            547d
awx-postgres-13-volume                     6Gi        RWO            Retain           Bound    awx/postgres-13-awx-postgres-13-0   awx-postgres-volume            547d
auto-pv                                    2Gi        RWO            Retain           Bound    awx/auto-pvc                        auto-storage                   274d
pvc-8fb18ecb-5b74-4f8e-af88-172c1cddab15   5Gi        RWO            Delete           Bound    awx/awx-backup-claim                local-path                     59m
```

PVCs:
```
NAME                            STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
awx-projects-claim              Bound     awx-projects-volume                        2Gi        RWO            awx-projects-volume   547d
postgres-13-awx-postgres-13-0   Bound     awx-postgres-13-volume                     6Gi        RWO            awx-postgres-volume   547d
auto-pvc                        Bound     auto-pv                                    2Gi        RWO            auto-storage          274d
awx-backup-claim                Bound     pvc-8fb18ecb-5b74-4f8e-af88-172c1cddab15   5Gi        RWO            local-path            59m
postgres-15-awx-postgres-15-0   Pending                                                                        awx-postgres-volume   26m
```

The awx-operator-controller-manager loops around here:
```
--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Create Database if no database is specified] *****************
task path: /opt/ansible/roles/installer/tasks/upgrade_postgres.yml:33

-------------------------------------------------------------------------------
{"level":"info","ts":"2024-03-14T11:31:52Z","logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/apps/v1/namespaces/awx/statefulsets/awx-postgres-15","Verb":"get","APIPrefix":"apis","APIGroup":"apps","APIVersion":"v1","Namespace":"awx","Resource":"statefulsets","Subresource":"","Name":"awx-postgres-15","Parts":["statefulsets","awx-postgres-15"]}}
{"level":"info","ts":"2024-03-14T11:31:54Z","logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/api/v1/namespaces/awx/pods","Verb":"list","APIPrefix":"api","APIGroup":"","APIVersion":"v1","Namespace":"awx","Resource":"pods","Subresource":"","Name":"","Parts":["pods"]}}
```

Eventually - this times out:
```
 TASK [Create Database if no database is specified] ******************************** 
fatal: [localhost]: FAILED! => {"changed": false, "duration": 120, "method": "apply", "msg": "\"StatefulSet\" \"awx-postgres-15\": Timed out waiting on resource"
```

The task and web pods never get created.

### AWX Operator version

2.13.1

### AWX version

24.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

k3s version v1.28.7+k3s1 (051b14b2)

### Modifications

no

### Steps to reproduce

`./kustomize` build . | kubectl apply -f -`

with:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.13.1

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.13.1

# Specify a custom namespace in which to install AWX
namespace: awx
```

### Expected results

The new PVC is created and and binded to the new postgres pod

### Actual results

The new PVC is created and but not binded to the new postgres pod. 
The installation bails out.

**Comment by cpilton** [comment]
PVC config is as follows:  

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: awx-projects-volume
```

PV config is as follows:

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-13-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 6Gi
  storageClassName: awx-postgres-volume
  hostPath:
    path: /mqawx/postgres-13

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  storageClassName: awx-projects-volume
  hostPath:
    path: /mqawx/projects
```

**Comment by kunkanon** [comment]
I have the same issue.

Kubernets v1.25.6+k3s1
Kustomize Version: v4.5.7

[operator.log.zip](https://github.com/ansible/awx-operator/files/14601416/operator.log.zip)

![Captura de Tela 2024-03-14 às 08 36 11](https://github.com/ansible/awx-operator/assets/23107622/42b4cd1b-dbcb-4342-955f-4bfdda756899)

**Comment by cpilton** [comment]
I have created a new PV in the PV config as follows: 

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-15-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 6Gi
  storageClassName: awx-postgres-volume
  hostPath:
    path: /mqawx/postgres-15

---
```

The PVC is automatically binding to this now...

However, the pod is crashing upon start:
```
  Normal   SandboxChanged    23s                    kubelet            Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled            3s (x2 over 21s)       kubelet            Container image "quay.io/sclorg/postgresql-15-c9s:latest" already present on machine
  Normal   Created           3s (x2 over 21s)       kubelet            Created container postgres
  Normal   Started           3s (x2 over 20s)       kubelet            Started container postgres
  Warning  BackOff           2s (x3 over 18s)       kubelet            Back-off restarting failed container postgres in pod awx-postgres-15-0_awx(70c2d5aa-6689-4985-a5c1-d42cedee8eb5)
```

The pod logs are no longer empty: 
`mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied`
