### ISSUE TITLE
Upgrade from 2.12.2 to 2.13.1 failed - mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied

### ISSUE THREAD

**Issue by craph** [ansible/tower-operator#1775]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Unable to upgrade from 2.12.2 to 2.13.1
```
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

CrashLoopBackOff in the Postgres container.

### AWX Operator version

2.13.1

### AWX version

24.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.25.16+rke2r1

### Modifications

no

### Steps to reproduce

upgrade from 2.12.2 to 2.13.1

### Expected results

migration from postgres 13 to 15 should work without any permissions issues

### Actual results

Unable to upgrade from 2.12.2 to 2.13.1
```
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

CrashLoopBackOff in the Postgres container.

**Comment by craph** [comment]
Looks similar to https://github.com/ansible/awx-operator/issues/1770

**Comment by craph** [comment]
In the documentation from [here](https://quay.io/repository/sclorg/postgresql-15-c9s) there is this paragraph : 

> Notice: When mouting a directory from the host into the container, ensure that the mounted directory has the appropriate permissions and that the owner and group of the directory matches the user UID or name which is running inside the container.
> 
> Typically processes in container run under UID 26, so -- on GNU/Linux 

is there any reason to change container image from official postgres to sclorg one ? 

Thank you very much for your help.

**Comment by craph** [comment]
In the Dockerfile [here](https://github.com/sclorg/postgresql-container/blob/master/15/Dockerfile.c9s) we can see :
```
# This image must forever use UID 26 for postgres user so our volumes are
# safe in the future. This should *never* change, the last test is there
# to make sure of that.
RUN  { yum -y module enable postgresql:15 || :; } && \
    INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper postgresql-server postgresql-contrib" && \
    INSTALL_PKGS="$INSTALL_PKGS pgaudit" && \
    yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS && \
    rpm -V $INSTALL_PKGS && \
    postgres -V | grep -qe "$POSTGRESQL_VERSION\." && echo "Found VERSION $POSTGRESQL_VERSION" && \
    yum -y clean all --enablerepo='*' && \
    localedef -f UTF-8 -i en_US en_US.UTF-8 && \
    test "$(id postgres)" = "uid=26(postgres) gid=26(postgres) groups=26(postgres)" && \
    mkdir -p /var/lib/pgsql/data && \
    /usr/libexec/fix-permissions /var/lib/pgsql /var/run/postgresql
``` 

So if I understand it correctly, by default in the postgres 15 container the postgres user have it's uid equals to 26.

So, I don't understand why, by default during the installation of postgres 15 we have this kind of issue : 
```
mkdir: cannot create directory '/var/lib/pgsql/data/userdata': Permission denied
```

to run the installation of awx or upgrade awx I'm using this script : 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.13.1
  # Add this extra line:
  - awx-demo.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.13.1

# Specify a custom namespace in which to install AWX
namespace: awx
```
and here is the `awx-demo.yml` file : 
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx
spec:
  ingress_type: ingress
  hostname: myawxserver
  postgres_storage_class: longhorn
```

And to apply : 
```
kustomize build . | kubectl apply -f -
```
