### ISSUE TITLE
Unable to create manual projects on 2.13.1

### ISSUE THREAD

**Issue by fopson** [ansible/tower-operator#1789]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Unable to create manual project on AWX deployed through Operator. I have attempted to make `/var/lib/awx/projects` persistent and link it to `/op/awx/projects` locally on the node. I have followed instructions given in the community forum https://forum.ansible.com/t/awx-change-project-base-path-kubernetes/2473/8 but I still get the same error message. 
<img width="410" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/da5e0519-56b3-4308-a89b-97313c7cfc93">

I have been googling solutions for the past 2 days but no luck.

### AWX Operator version

2.13.1

### AWX version

24

### Kubernetes platform

minikube

### Kubernetes/Platform version

 v1.32.0

### Modifications

no

#### Install AWX Operator 2.13.1  
  
<img width="520" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/5f8e7d86-3b13-4966-84dc-ba22436774f1">

#### Setup Projects Dir
```
mkdir /opt/awx/projects
sudo chmod 775 /opt/awx/projects
sudo chown 1000:0 /opt/awx/projects
```

#### Create Persistent Volume
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-projects-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  storageClassName: awx-projects-volume
  hostPath:
    path: /opt/awx/projects
```

#### Create Persistent Volume Claim
```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: awx-projects-volume
```
#### Checks
<img width="803" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/5295f000-3f54-437d-a32b-9e66c691e9d0">

#### Create TLS Secret
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-tls-cert
  namespace: certificate
type: kubernetes.io/tls
data:
  tls.crt: <Base64-of-the-Cert>
  tls.key: <Base64-of-the-Key>
```

#### Deploy AWX
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  # Service
  service_type: clusterip
  
  # Persisten Storage
  projects_persistence: true
  projects_existing_claim: awx-projects-claim

  # HTTPS
  ingress_type: ingress
  ingress_hosts:
    - hostname: fqdn-1
    - hostname: fqdn-2
      tls_secret: awx-tls-cert
```

#### Checks
<img width="429" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/ac29f900-e611-4239-80bb-1ebaacd51f58">

<img width="528" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/88277f7a-37b7-49c4-825a-6847e1522b82">

<img width="999" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/5c2f1d18-af2a-4986-ad34-b6bd15719462">

<img width="442" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/a5391165-505b-420e-b36a-c7638e24d878">

<img width="485" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/0e9d4002-4418-47b4-a294-80a47670b362">

#### Check
<img width="410" alt="image" src="https://github.com/ansible/awx-operator/assets/46285552/dfbea24f-28b2-4daf-9f25-449d05d59c21">

### Expected results

Being able to create manual/persistent projects.

### Actual results

AWX `/var/lib/awx/projects/` doesn't seem to be linked to `/opt/awx/projects/` on the local host.
