### ISSUE TITLE
Unable to set custom postgres_image

### ISSUE THREAD

**Issue by Raptus1** [ansible/tower-operator#1793]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When adding the spec postgres_image and postegres_image_version i expected to be able to keep postgres on version 13 instead of the operator updating to postgres 15, but that seems to not be the case as the tasks are nowhere to be found in the operator logs

As you can read, it goes from the task on line 28, and skipped all the tasks inbetween and then goes to create the new database config as if postgres_image and postgres_image_version is not set or as if the tasks are not even there.

Am I missing to change some other default variable or config setting?

### AWX Operator version

2.13.1

### AWX version

24.0.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.28.5

### Modifications

no

### Steps to reproduce

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-dev
  namespace: awx
spec:
  service_type: clusterip
  admin_password_secret: awx-admin-password
  admin_user: admin
  secret_key_secret: awx-secret-key
  image: {{ awx_image }}
  image_version: {{ awx_image_version }}
  image_pull_secrets: 
    - awx-image-pull-secret
  ee_images:
  - name: AWX-EE (LATEST)
    image: {{ awx_ee_image }}:{{ awx_ee_version }}
  - name: AWX-CUSTOM-EE (LATEST)
    image: {{ custom_ee_image }}:{{ custom_ee_version }}
  ee_pull_credentials_secret: awx-dev-ee-pull-credentials
  control_plane_ee_image: {{ control_plane_ee_image }}:{{ awx_control_plane_ee_version }}
  postgres_image: postgres
  postgres_image_version: "13"
  postgres_configuration_secret: awx-dev-postgres-configuration

```
Secret:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-dev-postgres-configuration
  namespace: awx
stringData:
  host: "{{ external_postgres_host }}"
  port: "{{ external_postgres_port }}"
  database: awx
  username: "{{ external_postgres_admin_user }}"
  password: "{{ lookup('env','POSTGRES_ADMIN_PASSWORD') }}"
  sslmode: "{{ external_postgres_sslmode }}"
  type: managed
type: Opaque

```

### Expected results

For the operator to set and respect the fact that I set and want to use postgres 13 instead of the latest 15

### Actual results

postgres_image is not pushed into fact and therefore it will use _postgres_image defaults instead using the newly added postgres 15

### Operator Logs

```
--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Check for specified old PostgreSQL configuration secret] *****
task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:19

-------------------------------------------------------------------------------
{"level":"info","ts":"2024-03-25T20:34:47Z","logger":"logging_event_handler","msg":"[playbook task start]","name":"awx-dev","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"8718054308259173113","EventData.Name":"installer : Check for specified old PostgreSQL configuration secret"}
{"level":"info","ts":"2024-03-25T20:34:47Z","logger":"logging_event_handler","msg":"[playbook task start]","name":"awx-dev","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"8718054308259173113","EventData.Name":"installer : Check for default old PostgreSQL configuration"}

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Check for default old PostgreSQL configuration] **************
task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:28

-------------------------------------------------------------------------------
{"level":"info","ts":"2024-03-25T20:34:47Z","logger":"proxy","msg":"Cache miss: /v1, Kind=Secret, awx/awx-dev-old-postgres-configuration"}
{"level":"info","ts":"2024-03-25T20:34:48Z","logger":"logging_event_handler","msg":"[playbook task start]","name":"awx-dev","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"8718054308259173113","EventData.Name":"installer : Create Database configuration"}

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Create Database configuration] *******************************
task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:71

-------------------------------------------------------------------------------
{"level":"info","ts":"2024-03-25T20:34:48Z","logger":"logging_event_handler","msg":"[playbook task start]","name":"awx-dev","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"8718054308259173113","EventData.Name":"installer : Read Database Configuration"}
```
