### ISSUE TITLE
Clean deployment on K3s with 2.14.0 fails with postgres 15

### ISSUE THREAD

**Issue by apiening** [ansible/tower-operator#1806]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The deployment of `awx-postgres-15-0` fails with a `CrashLoopBackOff`.
This is a new K3s deployment with nothing else running, no upgrade.

### AWX Operator version

2.14.0

### AWX version

v24.1.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

K3S Client Version: v1.28.7+k3s1, Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3, Server Version: v1.28.7+k3s1

### Modifications

no

### Steps to reproduce

Deploy using `kustomization.yaml`:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.14.0
  - awx.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.14.0

# Specify a custom namespace in which to install AWX
namespace: awx
```
and `awx.yaml`:
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  nodeport_port: 3000
```
with
```bash
kubectl kustomize | kubectl apply -f -
```

### Expected results

Successful deployment.

### Actual results

Postgres is in a CrashLoop:
```bash
# kubectl get pods -n awx
NAME                                               READY   STATUS             RESTARTS         AGE
awx-operator-controller-manager-6458cd4798-w6vwx   2/2     Running            0                91m
awx-postgres-15-0                                  0/1     CrashLoopBackOff   20 (4m40s ago)   82m
```

### Additional information

This is a clean deployment with nothing else running.
