### ISSUE TITLE
Support specifying a custom registry for all sources

### ISSUE THREAD

**Issue by daneov** [ansible/tower-operator#1811]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

## Idea
Is there a 'global' field that I can use to override all references to `quay.io`? 

## Use-case: 

In a corporate environment we make use of Artifactory as a pull-through-cache (for a variety of reasons).  
We want to make sure AWX uses this same mechanism, but it's been quite a journey on how to achieve this.

## Reasoning
So far I've found the following required fields when attempting to do this:

```yml
redis_image: docker.private.registry.com/redis
redis_image_version: latest # -- required, but it shouldn't be imo: #1441 
control_plane_ee_image: docker.private.registry.com/ansible/awx-ee:24.1.0
init_container_image: docker.private.registry.com/ansible/awx-ee
init_container_image_version: 24.1.0 # -- required, but it shouldn't be imo: #1441 
image: docker.private.registry.com/ansible/awx
image_version: 24.1.0 # -- required, but it shouldn't be imo: #1441 
ee_images:
  - name: Cached-EE
    image: docker.private.registry.com/ansible/awx-ee
postgres_image: docker.private.registry.com/sclorg/postgresql-15-c9s
postgres_image_version: latest
```

Aside from #1441, this leaves me with the following questions:

1. Are there any I missed?
2. Would it be possible to define a global 'registry' somehow, to ensure I don't miss anything?
