### ISSUE TITLE
Please add instructions on how to update awx via awx-operator with kubertenetes without loosing data

### ISSUE THREAD

**Issue by OneHappyForever** [ansible/tower-operator#182]
I have only seen instructions on how to install it the first time. 

Unless I run minikube delete, which will delete the files as well, is there a way to update awx via awx operator that will keep all the configs, postgresql database, etc. intact?

If there is, please direct me to the page, as I cannot find any easy way to do so, in any wiki/docs, either on github on or the ansible website.

I believe this will be immensely useful not just for me, but for all users.

**Comment by shanemcd** [comment]
This is kind of already documented here: https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx

But I would caution against doing this. Certain versions of AWX will inherently require a new version of the operator. I think we may want to consider versioning the operator and awx together to make this more apparent.

@Spredzy thoughts?

**Comment by MrAmbiG** [comment]
@shanemcd What you are suggesting is build and maintain our own custom image, we were hoping something like mentioning the version in the my-awx.yaml file itself. I do understand that an older version of operator may not support an awx release which got released after the operator but from an end user perspective, a backward compatibility with 3-4 versions do make a lot of sense..
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
 version: 18
```
`kubectl apply -f my-awx.yaml`

**Comment by shanemcd** [comment]
@MrAmbiG 

- This would not require you to build your own image. Just point to a different tag like `quay.io/ansible/awx:<whatever>`.
- We cannot ever guarantee any kind of backwards compatibility. This is a fast moving upstream project, and you will need to assume the risk of using bleeding edge software.

**Comment by MrAmbiG** [comment]
@shanemcd 
branch tag: 0.8.0
file: awx-operator.yaml line 118 onwards
```
                # tower_ee_images:
                  # description: Registry path to the Execution Environment container to use
                  # type: array
                  # items:
                  #   type: object
                  #   properties:
                  #     name:
                  #       type: string
                  #     image:
                  #       type: string
                tower_ee_images:
                  - name: awx19
                     image: quay.io/ansible/awx
```
result:
error: error validating "awx-operator.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.tower_image): unknown field "tower_ee_images" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps; if you choose to ignore these errors, turn validation off with --validate=false
a tiny suggestion: 
It is cool to have a one yaml file does it all and ditch the helm chart but in this scenario a helm chart with configurable values is a clean win. I hope some day there will be an official helm chart with configurable values.yaml or where i can just do `--set key=value`. Less hassle. A helm chart reduces the entry barriers.


**Documentation correction**:
Irrespective of which release branch you go to your .md file asks to install only the operator in the devel branch. ex:- In 0.8.0 release branch the documentation asks us to use `https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml` but shouldn't we be using `https://raw.githubusercontent.com/ansible/awx-operator/0.8.0/deploy/awx-operator.yaml` ? 
[plz ignore the indentation, multiple attempts but github formatting is screwing it up]

**Comment by MrAmbiG** [comment]
never mind..
it is to be updated in the in the awx.yaml not operator.yaml and it wasnt clear from the documentation.
2 suggestion for the documentation:

1. update the operator url as per the release branch i am in, it always shows the operator from devel branch even though i am at a release branch
2. At the beginning of the advanced configuration heading, please mention that the options can be configured at awx.yaml (otherwise for an uninitiated person, it can be either operator or awx.yaml)
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  tower_ingress_type: Ingress
  tower_ee_images:
  - name: awx19
    image: quay.io/ansible/awx:19.0.0
```
