### ISSUE TITLE
Add ee_image description directly from déployment files

### ISSUE THREAD

**Issue by JSGUYOT** [ansible/tower-operator#1861]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hello Teams, 

Can you add possibility to add description on ee_images directly from deployment files ?

Actually, specs ars : 

```
spec:
  ...
  image: myorg/my-custom-awx
  image_version: latest
  image_pull_policy: Always
  image_pull_secrets:
    - pull_secret_name
  ee_images:
    - name: my-custom-awx-ee
      image: myorg/my-custom-awx-ee
  control_plane_ee_image: myorg/my-custom-awx-ee:latest
  init_container_image: myorg/my-custom-awx-ee
  init_container_image_version: latest
  init_projects_container_image: myorg/my-mirrored-centos:stream9
```

Add description like this :
```
 ee_images:
    - name: my-custom-awx-ee
      image: myorg/my-custom-awx-ee
      description: my best description for this awx-ee image
```

Result of this must be add description of awx-ee image in AWX GUI execution enviromenent : 

Thanks in adavance.

Best regards
