### ISSUE TITLE
Pull the operator without building the local awx-postgres-0 db

### ISSUE THREAD

**Issue by ac-obair** [ansible/tower-operator#187]
I've had no trouble standing up a k8s instance of awx using an external postgres db, locally and in azure but pulling the `awx-operator.yaml` as per the readme still created the local postgres pod even though it's not being used. 
```
awx-postgres-0                 1/1     Running   0          3h20m
```
This pod is taking up cluster resources by existing, I've been through the awx and tower docs but I can't seem to figure out how to pull the operator without it building this local db. Is there a procedure for dealing with this buried in the docs somewhere or are you just expected to delete the resources manually? Any time I touch the pod the reconciliation loop fires.

**Comment by shanemcd** [comment]
The Operator should only deploy the Postgres StatefulSet under a very specific condition:

https://github.com/ansible/awx-operator/blob/0043c375d89f27d164519efc4a3bfac641002e39/roles/installer/tasks/database_configuration.yml#L67-L72

You should have a secret named `{{ meta.name }}-postgres-configuration`.

Can you look at it and see if you see `type: managed`? If so, delete that key/value and see what happens.

**Comment by ac-obair** [comment]
Thanks for the reply. Managed was indeed the type, specifying the secret `awx-postgres-configuration` as in the definition below only brings up the `awx-` and `awx-operator-` pods so that's exactly what I wanted to happen. The awx-task container seems to be failing in django with bad username for my "managed" postgres instance with username `psqladminun` but the username is `psqladminun@awx-external-postgres` which I can connect with outside of awx. 

I was still using the local db due to that misunderstanding. You can see the confusion, I took `managed` to mean cloud managed instance i.e. use some kind of ` sslmode: <required/preferred>` and expect an `@` in the name, but that was my mistake. I've had to disable tls on the connection because there seems to be no way to set that in the `awx-postgres-configuration`. It's an inventory setting I believe? Once I disabled tls I got the username error. I'm only connecting as psqladminun for testing the connection but that's definitely not the username.

```python
2021-04-08 13:25:13,818 ERROR    [-] awx.conf.settings Database settings are not available, using defaults.
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
    self.connect()
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "psqladminun"
FATAL:  password authentication failed for user "psqladminun"
```

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: default
spec:
  tower_hostname: <hostname>
  tower_admin_user: admin
  tower_admin_password_secret: awx-admin-password
  tower_admin_email: <email>
  tower_ingress_type: Ingress
  tower_web_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  tower_task_resource_requirements:
    requests:
      cpu: 250m
      memory: 500Mi
    limits:
      cpu: 500m
      memory: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: default
stringData:
  host: "<host>"
  port: "5432"
  database: "awx"
  username: "psqladminun@awx-external-postgres"
  password: "<pass>"
type: Opaque
```

**Comment by tchellomello** [comment]
@ac-obair  could you please send us the information below:

1. From your `awx-task`  container, what do you have below: (please obfuscate the pwd)
```sh
# cat /etc/tower/conf.d/credentials.py
```
2. Still at the `awx-task`  container, what happens if you do:
```sh
psql -h "<host>" awx -U 'psqladminun@awx-external-postgres' 
```

**Comment by ac-obair** [comment]
I was just looking at that file it exists in both the `awx-task` and `awx-web` containers. Oddly, the password is quoted more than once singles `'` inside double `"`.  The tls config`'sslmode': 'prefer'`.  I connected to a `postgres` db since I've removed the awx db for now. The quotes seem to be causing the issue same error from the traceback.

```bash
# trying with <password>

bash-4.4$ psql -h <host> postgres -U 'psqladminun@awx-external-postgres'
Password for user psqladminun@awx-external-postgres:
psql (12.5, server 11.6)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=> exit

# trying with '<password>'

bash-4.4$ psql -h <host> postgres -U 'psqladminun@awx-external-postgres'
Password for user psqladminun@awx-external-postgres:
psql: error: FATAL:  password authentication failed for user "psqladminun"
FATAL:  password authentication failed for user "psqladminun"
```

```python
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx",
        'USER': "psqladminun@awx-external-postgres",
        'PASSWORD': "'<password>'",
        'HOST': '<host>',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "<some_secret>"
```
I redeployed with the deploy definition below using a naked string, no quoting but the `credentials.py` was templated the same and I don't have privs to edit the file on disk. 
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: default
stringData:
  host: "<host>"
  port: "5432"
  database: awx
  username: "psqladminun@awx-external-postgres"
  password: <password>
type: Opaque
```
The offending line appears to be here
https://github.com/ansible/awx-operator/blob/9503d3cf485224c90b18f6c514dc3713781eb6e9/roles/installer/templates/credentials.py.j2#L7
There's a general mix of quotes in this file that I guess were intended to avoid escape characters, I'm not sure but .j2 files will literally interpret the quotes and template them I'm sure this would do it:

```
 'PASSWORD': {{ awx_postgres_pass | quote }}, 
```
I built a new operator with the change above 
```yaml
TASK [Verify there is one AWX kind] ********************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Get AWX Pod data] ********************************************************
ok: [localhost]

TASK [Verify there is one AWX pod] *********************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
```
Everything has connected and is working now.

**Comment by tchellomello** [comment]
@ac-obair thanks for the troubleshooting. I performed a few tests here and none of my `secrets`  password were created with the `single-quote`, but indeed, I can confirm that adding the `quote` will throw the password error. 

For example, here are 2 `auto-generated-secrets`  for a `auto-managed`  db instance:

```yaml
kubectl modify-secret awx-ssl-disable-postgres-configuration
database: awx
host: example4-awx-postgres
password: XyKu8gc65Ks2xd2Bwmx90RUg2NZkO4mS
port: "5432"
type: managed
username: awx
```

```yaml
kubectl modify-secret awx-localdb-postgres-configuration
 database: awx 
 host: awx-ssl-disable-postgres
 password: 5puCoNewQEC5xoR2KIUvwrEzvVpKP458
 port: "5432"
 type: managed
 username: awx 
``` 

As you can see above, `none` of the password strings had `quotes`  added to it, as we will rely on the `jinja2` template to quote it for us. 

So I believe the problem was due to the nature of being an external `secret` created by hand, if the user adds the `quotes`  on the `secret` itself, it then will end up with `quotes` twice as you mentioned.  So look at the test below:
```yaml
#  kubectl iexec localdb /bin/bash
Namespace: default | Pod: ✔ awx-localdb-b9748fd44-qs8zk
Container: ✔ awx-localdb-web
bash-4.4$ cat /etc/tower/conf.d/credentials.py 
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx",
        'USER': "awx",
        'PASSWORD': "CXZtSTuyJoAH0M4rASSG0EYpFCh6p0c8",  <=== added quotes by jinja2 
        'HOST': 'awx-localdb-postgres',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "SZyZxQSk8vwFMljjMTE5mVRdzJCE6Awq"
```

Trying to connect:

```sh
bash-4.4$ PGPASSWORD="CXZtSTuyJoAH0M4rASSG0EYpFCh6p0c8" psql -h awx-localdb-postgres -U awx
psql (12.5, server 12.6 (Debian 12.6-1.pgdg100+1))
Type "help" for help.

awx=# \q
bash-4.4$ PGPASSWORD="'CXZtSTuyJoAH0M4rASSG0EYpFCh6p0c8'" psql -h awx-localdb-postgres -U awx
psql: error: FATAL:  password authentication failed for user "awx"
```

In order to attempt to avoid this issue in the future, I have added https://github.com/ansible/awx-operator/pull/199 to alert for this problem.

**Comment by ac-obair** [comment]
@tchellomello I had `type: managed` postgres-0 container working with my original config. I set up a postgres container locally on my laptop outside of k8s to mimic an external connection and that also worked. I also rebuilt my current setup with connection to azure with unquoted password and it was double quote templated resulting in the same issue.

Each time with or without quotes without issue until spinning up a db instance in azure then the problem appeared. Now that I'm more familiar with the code I don't see how that could be happening if it's working local. I'll double check those results tonight and confirm but there seems to be a very specific condition that's causing this outwith whether my user specified password is quoted or not since even if it's _not_ the jinja in this line _will_ wrap it twice. 
https://github.com/ansible/awx-operator/blob/9503d3cf485224c90b18f6c514dc3713781eb6e9/roles/installer/templates/credentials.py.j2#L7
Unless something is stripping a the outside quote for `type: managed`.

**Comment by ac-obair** [comment]
@tchellomello As I suspected it has nothing to do with whether the yaml value for key `password:` is initially commented or not. The fix to the jinja I provided above is the correct was to template a string when quotes are required. I'm not sure why the `!` is breaking the templating but it most definitely is. Special characters are required when creating a password for a postgres db in azure. I'll assume from your example the auto-generated passwords are alphanumeric and that this password case isn't tested for. 

Here is a my secret yaml again with tested password cases followed by the templated result of `credentials.py`. The password in azure I was using was `LetjIma1o3uQYbs2cq1GJYkI!`. These tests were run against a local docker postgres instance, outside of k8s in which awx is running to simulate an external connection hence the host is `kubernetes.docker.internal`.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: default
stringData:
  host: kubernetes.docker.internal
  port: "5432"
  database: awx
  username: awx
  password: "1234!"    # <--         'PASSWORD': "'1234!'",  templating broken by ! 
  password: "1234"     # <--         'PASSWORD': "1234",     templating fine
  password: 1234!      # <--         'PASSWORD': "'1234!'",  templating broken by !
  password: "12!34"    # <--          'PASSWORD': "'12!34'",  templating broken by !
  password: 1234       # <--          cannot convert int64 to string -- (so needs to be quoted)
  password: '1234!'    # <--         'PASSWORD': "'1234!'",  templating broken by ! 
  password: '1234'     # <--         'PASSWORD': "1234",     templating fine
  password: "LetjIma1o3uQYbs2cq1GJYkI!"   # <--         'PASSWORD': "'LetjIma1o3uQYbs2cq1GJYkI!'",  templating broken by ! 
  password: "LetjIma1o3uQYbs2cq1GJYkI"    # <--         'PASSWORD': "LetjIma1o3uQYbs2cq1GJYkI",   templating fine
type: Opaque
```
At least for my ansible version, the `quote` filter behaviour is consistent.
```
ansible 2.10.7
  config file = None
  configured module search path = ['/Users/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/<user>/opt/anaconda3/lib/python3.8/site-packages/ansible
  executable location = /Users/<user>/opt/anaconda3/bin/ansible
  python version = 3.8.5 (default, Sep  4 2020, 02:22:02) [Clang 10.0.0 ]
```
More interesting I think is the result of `12!34` which shows it doesn't matter where the `!` is just that there is one. Further testing using this template and playbook
```j2
'PASSWORD': "{{ awx_postgres_pass_with_bang | quote }}",
'PASSWORD': "{{ awx_postgres_pass_without_bang | quote }}",
```
```yaml
---
# ansible-playbook test-playbook.yaml
- hosts: localhost
  gather_facts: no
  name:  test playbook
  tasks:
    - name: set awx_postgres_pass facts
      set_fact:
        awx_postgres_pass_with_bang: hello, world!
        awx_postgres_pass_without_bang: hello, world
    - name: test quote filter
      template:
        src:  credentials.py.j2
        dest: credentials.py
```
The result is to be expected, it nests the quotes. Since the template shouldn't have quotes in it unless they're expect to be templated.
```
'PASSWORD': "'hello, world!'",
'PASSWORD': "'hello, world'",
```
I haven't checked the quote filter behaviour for the ansible version running on the operator. 
```
'PASSWORD': {{ awx_postgres_pass_with_bang | quote }},
'PASSWORD': {{ awx_postgres_pass_without_bang | quote }},
```

**Comment by tchellomello** [comment]
@ac-obair I gave it a shot and configured 2 instances using an external database. Look at the secrets below:

1. Creating users and database
```sh
postgres=# create user awx_special password 's3cret@!_p4ss';
CREATE ROLE
postgres=# create user awx_complex password 's3cret@_p4ss';
CREATE ROLE

postgres=# create database "awx_special" owner "awx_special";
CREATE DATABASE
postgres=# create database "awx_complex" owner "awx_complex";
CREATE DATABASE
```

2. Creating `secret`  for **awx-special** instance
```yaml
$ kubectl create secret generic awx-special-postgres-configuration  \
    --from-literal=username=awx_special \
    --from-literal=database=awx_special \
    --from-literal=host=toca.pgo.svc \
    --from-literal=port=5432\
    --from-literal=password='s3cret@!_p4ss'\
    --dry-run -o yaml
apiVersion: v1
data:
  database: YXd4X3NwZWNpYWw=
  host: dG9jYS5wZ28uc3Zj
  password: czNjcmV0QCFfcDRzcw==
  port: NTQzMg==
  username: YXd4X3NwZWNpYWw=
kind: Secret
metadata:
  creationTimestamp: null
  name: awx-special-postgres-configuration
```

3. Creating `secret`  for **awx-complex** instance
```yaml
kubectl create secret generic awx-complex-postgres-configuration \
    --from-literal=username=awx_complex \
    --from-literal=database=awx_complex \
    --from-literal=host=toca.pgo.svc \
    --from-literal=port=5432 \
    --from-literal=password='s3cret@_p4ss' \
    --dry-run -o yaml
apiVersion: v1
data:
  database: YXd4X2NvbXBsZXg=
  host: dG9jYS5wZ28uc3Zj
  password: czNjcmV0QF9wNHNz
  port: NTQzMg==
  username: YXd4X2NvbXBsZXg=
kind: Secret
metadata:
  name: awx-complex-postgres-configuration
```

4. Launching `awx-complex` and testing it
```yaml
$ kubectl get awx awx-complex -o yaml | kubectl neat 
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-complex
    app.kubernetes.io/part-of: awx-complex
  name: awx-complex
  namespace: default
spec:
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_garbage_collect_secrets: true
  tower_image: quay.io/ansible/awx:19.0.0
  tower_image_pull_policy: IfNotPresent
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_postgres_sslmode: prefer
  tower_projects_persistence: false
  tower_projects_storage_access_mode: ReadWriteMany
  tower_projects_storage_size: 8Gi
  tower_replicas: 1
  tower_route_tls_termination_mechanism: Edge
  tower_task_privileged: false
```
4.1 - Checking database communication
```sh
kubectl iexec awx-complex /bin/bash      22:32:39
Container: ✔ awx-complex-web
bash-4.4$ cat /etc/tower/conf.d/credentials.py 
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx_complex",
        'USER': "awx_complex",
        'PASSWORD': "s3cret@_p4ss",
        'HOST': 'toca.pgo.svc',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "kVvROthFVdR9L0gP0oFrCJdzYNoutEPe"

---- testing db (works)
bash-4.4$ awx-manage  dbshell
psql (12.5, server 13.1)
WARNING: psql major version 12, server major version 13.
         Some psql features might not work.
Type "help" for help.

awx_complex=> 
```

5. Launching `awx-special` and testing it
```sh
$ kubectl iexec awx /bin/bash                                                                                              
Namespace: default | Pod: ✔ awx-special-67bddbf5f8-xlkkl
Container: ✔ awx-special-web
bash-4.4$ cat /etc/tower/conf.d/credentials.py 
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx_special",
        'USER': "awx_special",
        'PASSWORD': "'s3cret@!_p4ss'",
        'HOST': 'toca.pgo.svc',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "loYNDzQ8bwnzYWWwAnriodrEjLhUlM8I"

----- testing db
bash-4.4$ awx-manage dbshell
psql: error: FATAL:  password authentication failed for user "awx_special"
password retrieved from file "/tmp/tmptrs1zxpo"
Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 8, in <module>
    sys.exit(manage())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/__init__.py", line 164, in manage
    execute_from_command_line(sys.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/core/management/commands/dbshell.py", line 22, in handle
    connection.client.runshell()
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/client.py", line 71, in runshell
    DatabaseClient.runshell_db(self.connection.get_connection_params())
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/django/db/backends/postgresql/client.py", line 61, in runshell_db
    subprocess.check_call(args)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['psql', '-U', 'awx_special', '-h', 'toca.pgo.svc', '-p', '5432', 'awx_special']' returned non-zero exit status 2.

---- as we can see the problem is with the `double-quotes` combined with the `single-quotes` as mentioned
bash-4.4$ PGPASSWORD='s3cret@!_p4ss' psql  -h toca.pgo.svc -U awx_special awx_special
psql (12.5, server 13.1)
WARNING: psql major version 12, server major version 13.
         Some psql features might not work.
Type "help" for help.

awx_special=> 
```

To test it,  I dropped the `quotes` tag from the template and tested it again. 
```sh
$ kubectl iexec awx /bin/bash               23:15:48
Namespace: default | Pod: ✔ awx-special-67bddbf5f8-6vwd4
Container: ✔ awx-special-web
bash-4.4$ cat /etc/tower/conf.d/credentials.py 
DATABASES = {
    'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'awx.main.db.profiled_pg',
        'NAME': "awx_special",
        'USER': "awx_special",
        'PASSWORD': "s3cret@!_p4ss",
        'PASSWORD2': "'s3cret@!_p4ss'",    <=== this one still the old code 
        'HOST': 'toca.pgo.svc',
        'PORT': "5432",
        'OPTIONS': { 'sslmode': 'prefer',
                     'sslrootcert': '/etc/pki/tls/certs/ca-bundle.crt',
        },
    }
}

BROADCAST_WEBSOCKET_SECRET = "qsTbVzCBTzrIxK0GpVEmdlnRaqaliKDw"

---- testing db 
bash-4.4$ awx-manage  dbshell
psql (12.5, server 13.1)
WARNING: psql major version 12, server major version 13.
         Some psql features might not work.
Type "help" for help.

awx_special=> 
```

```diff
diff --git a/roles/installer/templates/credentials.py.j2 b/roles/installer/templates/credentials.py.j2
index 986ebe6..9a64551 100644
--- a/roles/installer/templates/credentials.py.j2
+++ b/roles/installer/templates/credentials.py.j2
@@ -4,7 +4,8 @@ DATABASES = {
         'ENGINE': 'awx.main.db.profiled_pg',
         'NAME': "{{ awx_postgres_database }}",
         'USER': "{{ awx_postgres_user }}",
-        'PASSWORD': "{{ awx_postgres_pass | quote }}",
+        'PASSWORD': "{{ awx_postgres_pass }}",
+        'PASSWORD2': "{{ awx_postgres_pass | quote }}",
         'HOST': '{{ awx_postgres_host }}',
         'PORT': "{{ awx_postgres_port }}",
         'OPTIONS': { 'sslmode': '{{ pg_sslmode|default("prefer") }}',
```

So yes, we will need to drop the jinja2 filter quotes it seems. @shanemcd  @Spredzy any thoughts?
