### ISSUE TITLE
Failing Install new or upgrade to version 2.13.x and higher (with pg15) on existing EKS cluster

### ISSUE THREAD

**Issue by yyosha** [ansible/tower-operator#1870]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Using Kustomize to install/update.
Using EFS for persistent volumes (csi driver installed).

When using CDR and image up-to version 2.12.2 in kustomize.yaml, installation works perfect.
Every attempt to install version 2.13.x or to update to such version and higher fails.

#### When installing from scratch:
awx-operator-controller-manager pod starts OK.
postgres-15 pod starts ok. So is the stateful set.
awx-task starts and stays at Init:0/3
awx-web seems to starts OK, but after about 2 minutes and few restarts is NotReady and finally CrashLoopBackOff.

Logs:
```
$ kc logs -f pod/awx-dev-task-6bf9f4b76b-pmlpx -c init-database -n awx
[wait-for-migrations] Waiting for database migrations...
[wait-for-migrations] Attempt 1
[wait-for-migrations] Waiting 0.5 seconds before next attempt
[wait-for-migrations] Attempt 2
[wait-for-migrations] Waiting 1 seconds before next attempt
[wait-for-migrations] Attempt 3
[wait-for-migrations] Waiting 2 seconds before next attempt
[wait-for-migrations] Attempt 4
[wait-for-migrations] Waiting 4 seconds before next attempt
[wait-for-migrations] Attempt 5
[wait-for-migrations] Waiting 8 seconds before next attempt
[wait-for-migrations] Attempt 6
[wait-for-migrations] Waiting 16 seconds before next attempt
[wait-for-migrations] Attempt 7
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 8
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 9
[wait-for-migrations] Waiting 30 seconds before next attempt
[wait-for-migrations] Attempt 10
```

```
$ kc logs -f pod/awx-dev-web-7db9ddd54d-qlk2l -c awx-dev-web -n awx
```
[awx-dev-web-2.16.1.txt](https://github.com/ansible/awx-operator/files/15398514/awx-dev-web-2.16.1.txt). (Too long for quoting)

#### When updating version with pg13 (2.10.0 or 2.12.2):
Changing only CDR and Image versins in kustomize.yaml.
``` kc apply -k .```
New awx-operator-controller-manager pod starts OK.
awx-task and awx-web are terminated.
postgres-15 pod starts ok.
After some time postgres-13 is terminated (migration/conversion ?).
awx-task starts and gets to status 'Running'
awx-web starts and gets to status 'Running'
awx-migration-24.3.1 starts and after some time gets to status 'Completed' but remains in Ready 0/1 (not terminated).
All seems to be running for about 1 minute, but then new awx-task and awx-web pods are launched.
Old awx-web is terminated.
Old awx-task is running.
New awx-task and awx-web behave like in new installation described above.

### AWX Operator version

2.16.1

### AWX version

24.3.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

EKS 1.29

### Modifications

yes

### Steps to reproduce

New installation with kustomize.yaml:
(see full kustomize.yaml file in "additional information")
```
resources:
  ## Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.16.1
  - awx-secrets.yaml
  - awx-custom-ee-docker-reg-secret.yaml
  - awx-coredns-cm.yaml
  - awx-gp3-sc-retain.yaml
#  - awx-efs-pg13.yaml
  - awx-efs-pg15.yaml
  - awx-efs-projects.yaml
  - awx-efs-backups.yaml
  - awx-with-postgres.yaml

## Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.16.1
```

```kc apply -k .```

Update with kustomize.yaml:
(see full kustomize.yaml file in "additional information")
```
resources:
  ## Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.12.2
  - awx-secrets.yaml
  - awx-custom-ee-docker-reg-secret.yaml
  - awx-coredns-cm.yaml
  - awx-gp3-sc-retain.yaml
  - awx-efs-pg13.yaml
#  - awx-efs-pg15.yaml
  - awx-efs-projects.yaml
  - awx-efs-backups.yaml
  - awx-with-postgres.yaml

## Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.12.2
```

```kc apply -k .```

```
resources:
  ## Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.16.1
  - awx-secrets.yaml
  - awx-custom-ee-docker-reg-secret.yaml
  - awx-coredns-cm.yaml
  - awx-gp3-sc-retain.yaml
  - awx-efs-pg13.yaml
  - awx-efs-pg15.yaml
  - awx-efs-projects.yaml
  - awx-efs-backups.yaml
  - awx-with-postgres.yaml

## Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.16.1
```

```kc apply -k .```

### Expected results

Runnig awx version 24.3.1

### Actual results

awx not runnning

### Additional information

kustomize.yaml for new installation of version 2.16.1:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## Specify a custom namespace in which to install AWX
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
### Postgesql secret was moved to awx-secrets.yaml which is included in resources

  - name: awx-admin-password
    type: Opaque
    literals:
      - password=MyPassword

  - name: my-ca-bundle
    type: Opaque
    files:
      - bundle-ca.crt

resources:
  ## Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=2.16.1
  - awx-secrets.yaml
  - awx-custom-ee-docker-reg-secret.yaml
  - awx-coredns-cm.yaml
  - awx-gp3-sc-retain.yaml
#  - awx-efs-pg13.yaml
  - awx-efs-pg15.yaml
  - awx-efs-projects.yaml
  - awx-efs-backups.yaml
  - awx-with-postgres.yaml

## Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.16.1
```

### Operator Logs

[awx-operator-2.16.1.log](https://github.com/ansible/awx-operator/files/15398921/awx-operator-2.16.1.log)
