### ISSUE TITLE
Cannot change Postgres SSL mode from operator

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [ansible/tower-operator#188]
It's currently not possible to change `pg_sslmode` from the operator spec, which is causing trouble when trying to connect to an external Azure managed Postgres instance

**Comment by tchellomello** [comment]
@01100010011001010110010101110000 what kind of modification is looking for here? Could you provide us an example so can be easier to identify the best way to address this issue?

**Comment by 01100010011001010110010101110000** [comment]
Definitely, I'm looking for a way, from the `AWX` CRD, to change `pg_sslmode` in [credentials.py](https://github.com/ansible/awx-operator/blob/a860b0f459eff689239bd662890533d3baaf6d7d/roles/installer/templates/credentials.py.j2)

The other settings in that file derive from a setting in the CRD, but that one isn't set, so it just gets the default value of `prefer`.

**Comment by tchellomello** [comment]
@01100010011001010110010101110000 yes, I get that.. could you show how the configuration would like in this case so we can see how to change the jinja2?

**Comment by 01100010011001010110010101110000** [comment]
Oh, I was imaging something like this would be added to the CRD:

```
tower_postgres_sslmode:
  description: The PostgreSQL SSL mode used when connecting to the database
  type: string
  default: prefer
  enum:
    - disable
    - allow
    - prefer
    - require
    - verify-ca
    - verify-full
```

As for how to wire that up to the Jinja template, I'm not entirely certain. I started working on a PR yesterday, but I've not worked with Ansible based operators before so it wasn't immediately clear to me how to do it
