### ISSUE TITLE
Enable extra volume mounts for DB migration Job

### ISSUE THREAD

**Issue by sasvari-attila-bosch** [ansible/tower-operator#1896]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

As of now, AWX Operator enables various extra volume mounts for web, task, ee, etc. [Custom Volume and Volume Mount Options](https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/custom-volume-and-volume-mount-options.html)

I would like to request the same for the DB migration Job so I can mount a customized /etc/resolv.conf file in order to specify Azure nameserver IP in there.

**Comment by erhhung** [comment]
I would also like this ability in order to mount a client certificate for my external Postgres connection.

I'm able to do this for web and task pods like the following, but then the migration Job runs and fails.

```yaml
extra_volumes: |
  - name: postgres-tls
    secret:
      secretName: awx-postgres-tls
      defaultMode: 416

web_extra_volume_mounts: &extra-mounts |
  - name: database-tls
    mountPath: /tls
    readOnly: true
task_extra_volume_mounts: *extra-mounts

web_extra_env: &extra-envs |
  - name: PGSSLCERT
    value: /tls/tls.crt
  - name: PGSSLKEY
    value: /tls/tls.key
  - name: PGSSLROOTCERT
    value: /tls/ca.crt
task_extra_env: *extra-envs
```
