### ISSUE TITLE
Support https backend when ingress_type = ingress

### ISSUE THREAD

**Issue by HarishAmeen** [ansible/tower-operator#1898]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Hi Team,

The ingress today supported in awx-operator only allows http-based backend (except for when type is route). As most of the ingress controllers support https backend, the ingress manifests should also support it to route the traffic over https to the backend awx service.

Example service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: '{{ ansible_operator_meta.name }}-service'
  namespace: '{{ ansible_operator_meta.namespace }}'
spec:
  selector:
    app.kubernetes.io/name: '{{ ansible_operator_meta.name }}-web'
    app.kubernetes.io/managed-by: '{{ deployment_type }}-operator'
    app.kubernetes.io/component: '{{ deployment_type }}'
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8053
```

Ingress definition:
cat << EOF | kubectl apply -f -
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: website-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/backend-protocol: "https"
    appgw.ingress.kubernetes.io/backend-hostname: "backend"
    appgw.ingress.kubernetes.io/appgw-trusted-root-certificate: "backend-tls"
spec:
  tls:
    - secretName: frontend-tls
      hosts:
        - awx.com
  rules:
    - host: awx.com
      http:
        paths:
        - path: /
          backend:
            service:
              name: '{{ ansible_operator_meta.name }}-service'
              port:
                number: 443
          pathType: Exact
EOF
```

Currently its not possible to turn on https backend without setting ingress_type = route.
