### ISSUE TITLE
values.yaml being ignored

### ISSUE THREAD

**Issue by castaway2000** [ansible/tower-operator#1910]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

the myValues.yaml file as below: 

```
AWX:
  # enable use of awx-deploy template
  enabled: true
  spec:
    admin_user: admin
    image_version: 2.13.1
    service_type: NodePort
    nodeport_port: 30004

  # configurations for external postgres instance
  postgres:
    enabled: false

  customSecrets:
    enabled: true
    admin:
      enabled: true
      password: FooBArPAssw0rd1NotMyRE@1PW
      secretName: awx-admin-password
    secretKey:
      enabled: true
      key: test1234567890~!
      secretName: my-awx-secret-key
```

commands to deploy: 
```

    # Install AWX
    - name: "Install AWX"
      shell: bash
      run: |
        gcloud config set project anthos-kubernetes-dev
        gcloud container aws clusters get-credentials itd-dev-uswest2-anthos-aws-kyberno-cluster --location us-west1
        helm repo add awx-operator https://ansible.github.io/awx-operator/
        helm upgrade --install awx awx-operator/awx-operator --create-namespace --namespace awx -f myValues.yaml
```

please clarify a few things: first is spec in the right format and condition for the myValues.yaml file. is NodePort and its configuration correctly positioned in the myValues.yaml file. 2nd how do i declare the permissions group or userID for postgress to avoid the known issue with the pgsql path permission error? how/where do i declare what version of AWX seperate from Ansible-operator? is it all just lumped under AWX.spec? this seems to be all one option under "spec" but it is unclear what section spec this should be in. is this a global spec?

lastly the values i input into myValues.yaml do not look to be taking at all this is based on the documentation showin in the starter directory where a few examples are given along with the read the docs where it is very confusing how the configs in values.yaml are supposed to be deployed with helm.

final comments a lot of the proposed solutions to my issue are that i run a seperate net-svc.yml in the cli to fix the service. this is unacceptable as using helm to deploy all in for DR purposes would have best practices be all configs in one proceedure not two. 

can i get some clarification on all the above and can someone confirm that values.yaml data is or is not registering in deployments? 

### AWX Operator version

2.19.0

### AWX version

24.6.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

K8s managed Anthos using latest

### Modifications

no

### Steps to reproduce

use the values.yaml as shown above. 

run  `helm upgrade --install awx awx-operator/awx-operator --create-namespace --namespace awx -f myValues.yaml`

watch as the NodePort does not take as NodePort and instead deploys cluster IP, watch as the image version is ignored and instead deploys latest

### Expected results

deployment should deploy version specified and NodePort should show up as the service type. 

### Actual results

ClusterIP shows up in service type and latest version of each image is deployed. 

### Additional information

I also noticed that on top of the NodePort not being created this known issue is also persisting: https://github.com/ansible/awx-operator/issues/1770. 

Additionally i get no errors from helm during git actions deployment and having tried this 4-5 times now i notice that the web interface does not always deploy as well.
