### ISSUE TITLE
Add to ee_image more options to add support azure workload identity

### ISSUE THREAD

**Issue by galibozek** [ansible/tower-operator#1913]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

Can you add possibility to add additionally labels to `metadata.labels` and custom `spec.serviceAccountName` to specyfied pod using `ee_images` directly, to add permissions to azure resources for specific execution environments using workload identity on azure?

Example description like this:
```
 ee_images:
    - name: my-custom-awx-ee
      image: myorg/my-custom-awx-ee
      pod_labels: 
        azure.workload.identity/use: "true"
      pod_annotations:
        azure.workload.identity/service-account-token-expiration: 3600
      pod_service_account_name: awx-azure-dns
```
As for the service account, we assume that I do it myself.

Unless there is another option to add your own serviceAccountName and labels to the execution environments? Or create your own deployment of such pods and somehow add them to execution environments in AWX?
