### ISSUE TITLE
AWX ee_extra_env not working

### ISSUE THREAD

**Issue by rsdoherty** [ansible/tower-operator#1948]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

I've just deployed a very basic AWX install via helm, and I have this as my spec:

```
- name: Deploy AWX
  kubernetes.core.helm:
    name: awx
    chart_ref: awx-operator/awx-operator
    release_namespace: default
    values:
      AWX:
        enabled: true
        spec:
          ee_extra_env: |
            - name: MYCUSTOMVAR
              value: foo
```

Yet whenever the globally available EE is launched, I do not see MYCUSTOMVAR populated in the pod spec - the environment is blank.

Is this expected? I cannot seem to find a way to have the AWX crd pass environment variables to the globally available EE's.

I do see the config when I do `k get awxs -o yaml`, and as a test I set `ee_extra_volume_mounts` with no `extra_volumes` and things still worked - suggesting this isn't getting passed to the container at all.

### AWX Operator version

2.19.1

### AWX version

24.6.1

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.29.7

### Modifications

no

### Steps to reproduce

- Deploy AWX via helm
- Add ee_extra_env (https://ansible.readthedocs.io/projects/awx-operator/en/latest/user-guide/advanced-configuration/exporting-environment-variables-to-containers.html)
- Run a job in that EE, and it doesn't show the environment variables as expected

### Expected results

Environment variables show in globally available EE as expected

### Actual results

Container starts with no environment set
