### ISSUE TITLE
Install instructions for LoadBalancer include reference to undefined variable

### ISSUE THREAD

**Issue by RylandDeGregory** [ansible/tower-operator#195]
Within the default "basic install" instructions, if one chooses to use a LoadBalancer for ingress, the deployment fails due to an undefined variable. See [Ingress Type](https://github.com/ansible/awx-operator#ingress-type).

The documentation currently says to use:

```yaml
---
spec:
  ...
  tower_ingress_type: LoadBalancer
  tower_ingress_protocol: http
```

But, `tower_ingress_protocol` is not a valid variable.

It should (based on the list of configurable LoadBalancer variables) be:

```yaml
---
spec:
  ...
  tower_ingress_type: LoadBalancer
  tower_loadbalancer_protocol: http
```
