### ISSUE TITLE
Support for Configuring Container Groups in awx-operator Spec

### ISSUE THREAD

**Issue by jangel97** [ansible/tower-operator#1976]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

I would like to propose an enhancement to the **awx-operator** to enable configuring container groups directly within the AWX Custom Resource Definition (CRD) specification. This feature would allow AWX instances to be deployed with predefined container groups, facilitating out-of-the-box execution of jobs across multiple Kubernetes clusters.

**Why This Feature Matters**

Implementing this capability would offer significant benefits, especially for disaster recovery strategies:
- **Seamless Recovery**: With an external database and job execution occurring in other Kubernetes clusters via container groups, disaster recovery becomes as straightforward as redeploying the AWX object in a different cluster.
- **Scalability**: It simplifies the scaling of AWX instances in multi-cluster environments.

**Additional Context**

- This feature aligns with Kubernetes' declarative configuration model and promotes infrastructure-as-code practices.
- It streamlines the deployment process in environments that utilize multiple Kubernetes clusters for job execution.
- Below is an example of how the CRD spec might include container group configurations.

**Example CRD Specification**

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  # Other specifications...
  container_groups:
    - name: kubernetes-cluster-1
      credential: kube-cred-1
      namespace: awx-execution-jobs
    - name: kubernetes-cluster-2
      credential: kube-cred-2
      namespace: awx-execution-jobs
```
Team, does this make sense to you? If so, we can discuss implementation details, I would be willing to work on this with you. Thanks!
