### ISSUE TITLE
Error: Unable to determine if virtual resource

### ISSUE THREAD

**Issue by techBeck03** [ansible/tower-operator#203]
I'm attempting to deploy an AWX instance using the operator and i keep seeing this error entry in the operator logs:

` TASK [Create broadcast websocket secret] ******************************** 
fatal: [localhost]: FAILED! => {"changed": false, "error": 500, "msg": "Failed to apply object: b'Unable to determine if virtual resource\\n'", "reason": "Internal Server Error", "status": 500}`

Operator image: `quay.io/ansible/awx-operator:0.8.0`

AWX Yaml:

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-wwdc
  namespace: awx-green
spec:
  tower_hostname: wwdc-awx.auslab.example.com
  tower_admin_user: admin
  tower_ingress_type: ingress
  tower_admin_password_secret: awx-admin
  tower_secret_key_secret: awx-admin
```
