### ISSUE TITLE
upgade AWX to specific version

### ISSUE THREAD

**Issue by dberardo-com** [ansible/tower-operator#2048]
### Please confirm the following

- [x] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [x] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [x] I understand that AWX Operator is open source software provided for free and that I might not receive a timely response.

### Feature Summary

it is not clear how to force AWX to a specific version, say 24.3.1 using the operator ...i only se the auto upgrade option but then what if one wants a specific versione of awx ?

**Comment by ewaldmire** [comment]
I'm not an ansible/AWX dev, but I think you just need this:

https://github.com/ansible/awx-operator/blob/devel/config/crd/bases/awx.ansible.com_awxs.yaml#L1340

You can see these if you run `kubectl explain awx.spec` ... then you can put any of those under the "spec" in your "instance" manifest to modify the behavior.

For example, I was able to deploy Ascender to an OKD cluster like this:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: dev
spec:
  service_type: ClusterIP 
  ingress_type: Route     
  image: ghcr.io/ctrliq/ascender
  image_version: 25.1.0
```
