### ISSUE TITLE
Change imagePullPolicy to use a local redis image

### ISSUE THREAD

**Issue by vipamadi** [ansible/tower-operator#211]
Hi, I'm trying to deploy AWX 18.0.0 using local docker images at a machine without internet connection.

I've some trouble while I'm deploying the awx, postgres and redis containers.

At the awx-operator yaml file I can find some values to change the imagePullPolicy to Never and force minikube to use local docker imagest that I loaded. There're some examples:

https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml

```
tower_image_pull_policy:
  description: The image pull policy
  type: string
  default: IfNotPresent     ----------------------------> I can change it to Never
```

``` 
- name: awx-operator
    image: "quay.io/ansible/awx-operator:0.8.0"
    imagePullPolicy: "Always"    ----------------------------> I can change it to Never
```

But this doesn't work for the redis image:

Output from a 'minikube kubectl -- edit pods' where I can see the config applied to the redis container:

```    containers:
    - args:
      - redis-server
      - /etc/redis.conf
      image: redis:latest
      imagePullPolicy: Always
```
Is there any way to change this value before deploying the awx container?
