### ISSUE TITLE
Waiting for postgres pod even though external postgres is defined

### ISSUE THREAD

**Issue by daenney** [ansible/tower-operator#213]
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  tower_postgres_configuration_secret: awx-postgres-configuration 
  tower_old_postgres_configuration_secret: awx-old-postgres-configuration 
```

```sh
$ kubectl -n awx get secrets
NAME                             TYPE                                  DATA   AGE
[..]
awx-old-postgres-configuration   Opaque                                5      21m
[..]
awx-postgres-configuration       Opaque                                5      21m
[..]
```

Operator logs the following:
```
TASK [installer : Get the postgres pod information] ****************************\r\ntask path: /opt/ansible/roles/installer/tasks/migrate_data.yml:11\nfatal: [localhost]: FAILED! => {\"msg\": \"The conditional check 'postgres_pod['resources'][0]['status']['phase'] == 'Running'' failed. The error was: error while evaluating conditional (postgres_pod['resources'][0]['status']['phase'] == 'Running'): list object has no element 0\"}\n\r\nPLAY RECAP
*********************************************************\r\nlocalhost                  : ok=29   changed=0    unreachable=0    failed=1    skipped=13   rescued=0    ignored=0   \r\n\n","job":"2740376916591569721","name":"awx","namespace":"awx","error":"exit status 2","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/runner.(*runner).Run.func1\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/runner/runner.go:239"}

--------------------------- Ansible Task Status Event StdOut  -----------------

PLAY RECAP *********************************************************************
localhost                  : ok=29   changed=0    unreachable=0    failed=1    skipped=13   rescued=0    ignored=0   


-------------------------------------------------------------------------------
{"level":"error","ts":1618494205.2788725,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awx-controller","request":"awx/awx","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}
```

Given the postgres connection secrets are defined and passed in, why is the operator seemingly waiting (and thus erroring) on a postgres pod being available?

**Comment by tchellomello** [comment]
@daenney  If you look at the code the task " Get the postgres pod information" is part of the https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/migrate_data.yml#L11  which will be imported when these conditions met:

https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/database_configuration.yml#L90
```yaml
 - name: Migrate data from old Openshift instance
   import_tasks: migrate_data.yml
   when:
     - old_pg_config['resources'] is defined
     - old_pg_config['resources'] | length
     - this_awx['resources'][0]['status']['towerMigratedFromSecret'] is not defined
```

So are you trying to upgrade from a locally managed `Postgres` instance to an external instance? If so, do you have a PostgreSQL pod running? Can we get the output `kubectl describe pod <pgsql-managed>`?

If that is the case, it could be your local managed PostgreSQL pod does not the expected labels and since the reconciliation task runs after the `database_configuration` you are hitting this error.
