### ISSUE TITLE
awx postgres connection time out

### ISSUE THREAD

**Issue by lovelife100** [ansible/tower-operator#222]
Hi， I follow the instructions in the README to install awx with awx-operator on my k8s cluster `1.20.4`.

but after I finished all the installation steps, I found I can not access the awx web page.

the log in awx-web container show that it could not connect to the postgres, I also try to telnet the postgres port and also get failed.

my awx yaml is as below:
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_postgres_storage_class: local-pv
```
the image tag for awx operator is `0.8.0`
the image tag for awx is `19.0.0`

I also attach the logs for container awx-web, awx-operator, awx-postgres as below,  any ideas?
[awx-web.log](https://github.com/ansible/awx-operator/files/6335982/awx-web.log)
[awx-operator.log](https://github.com/ansible/awx-operator/files/6335984/awx-operator.log)
[awx-postgres.log](https://github.com/ansible/awx-operator/files/6335985/awx-postgres.log)
