### ISSUE TITLE
Resource request and limit for managed PostgreSQL not defined correctly

### ISSUE THREAD

**Issue by fust** [ansible/tower-operator#225]
According to the Readme the managed PostgreSQL statefulset supports customized resource requests and limits:
```
---
spec:
  ...
  tower_postgres_resource_requirements:
    requests:
      memory: 2Gi
      storage: 8Gi
    limits:
      memory: 4Gi
      storage: 50Gi
  tower_postgres_storage_class: fast-ssd
```

When applying above configuration the memory request and limit is put under the `volumeClaimTemplates` key which obviously doesn't affect the statefulset pods.

The problem is in the [tower_postgres.yaml.j2](https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_postgres.yaml.j2#L80) file.

Splitting the tower_postgres_resource_requirements in two variables like below resolves this problem:
```
---
spec:
  ...
  tower_postgres_resource_requirements:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 4Gi
  tower_postgres_storage_requirements:
    requests:
      storage: 8Gi
    limits:
      storage: 50Gi
  tower_postgres_storage_class: fast-ssd
```

The tower_postgres.yaml.j2 must be changed accordingly accordingly
