### ISSUE TITLE
Use ingress with multiple annotations

### ISSUE THREAD

**Issue by RylandDeGregory** [ansible/tower-operator#233]
I'm not sure how to provide multiple ingress annotations in my `my-awx.yml` spec. I've tried the following:

1. Using YAML map
```yaml
spec:
  tower_ingress_type: Ingress
  tower_hostname: awxdev
  tower_ingress_annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: true
```
2. Using YAML array
```yaml
spec:
  tower_ingress_type: Ingress
  tower_hostname: awxdev
  tower_ingress_annotations:
    - kubernetes.io/ingress.class: azure/application-gateway
    - appgw.ingress.kubernetes.io/use-private-ip: true
```
3. Using folded-block scalar
```yaml
spec:
  tower_ingress_type: Ingress
  tower_hostname: awxdev
  tower_ingress_annotations: >
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: true
```
4. Using literal-block scalar
```yaml
spec:
  tower_ingress_type: Ingress
  tower_hostname: awxdev
  tower_ingress_annotations: |
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: true
```

All of them fail for different reasons. What is the correct way to describe a deployment with multiple annotations?

**Comment by RylandDeGregory** [comment]
I found that I need to specify quotes around the `true` in the annotation, but **Literal Block Scalar** notation is the correct one, apparently. See https://yaml-multiline.info/
```yaml
spec:
  tower_ingress_type: Ingress
  tower_hostname: awxdev
  tower_ingress_annotations: |
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/use-private-ip: "true"
```
