### ISSUE TITLE
Postgres failure when setting requirements

### ISSUE THREAD

**Issue by sean-m-sullivan** [ansible/tower-operator#246]
I tried to edit the requirements on postgress to scale it down for a dev cluster, and found when setting the following part in the awx_def
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  deployment_type: awx
  tower_postgres_resource_requirements:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 400m
      memory: 3Gi
  tower_postgres_storage_requirements:
    requests:
      storage: 2Gi
    limits:
      storage: 5Gi
```
That I get this error in the stateful set
`create Claim postgres-awx-postgres-0 for Pod awx-postgres-0 in StatefulSet awx-postgres failed error: PersistentVolumeClaim "postgres-awx-postgres-0" is invalid: spec.resources[storage]: Required value`

I've tried various ways to change it, looking at the postgres template, I am not sure why it is not picking it up. 
This is using the devel operator.

**Comment by tchellomello** [comment]
Just build a fresh image from `devel` and test the following:

1. Created a fresh `awx` without any special values (worked as expected)
```yaml
kubectl get awx awx-testing-246 -o yaml | kubectl neat                                                                               22:47:29
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-testing-246
    app.kubernetes.io/part-of: awx-testing-246
  name: awx-testing-246
  namespace: default
spec:
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_garbage_collect_secrets: false
  tower_image_pull_policy: IfNotPresent
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_projects_persistence: false
  tower_projects_storage_access_mode: ReadWriteMany
  tower_projects_storage_size: 8Gi
  tower_replicas: 1
  tower_route_tls_termination_mechanism: Edge
  tower_task_privileged: false
```

2. Upgraded the PostgreSQL `statefulset` as mention
```yaml
kubectl get awx awx-testing-246 -o yaml | kubectl neat                                                                               22:49:40
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-testing-246
    app.kubernetes.io/part-of: awx-testing-246
  name: awx-testing-246
  namespace: default
spec:
  deployment_type: awx
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_garbage_collect_secrets: false
  tower_image_pull_policy: IfNotPresent
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_postgres_resource_requirements:
    limits:
      cpu: 400m
      memory: 3Gi
    requests:
      cpu: 300m
      memory: 1Gi
  tower_postgres_storage_requirements:
    limits:
      storage: 5Gi
    requests:
      storage: 2Gi
  tower_projects_persistence: false
  tower_projects_storage_access_mode: ReadWriteMany
  tower_projects_storage_size: 8Gi
  tower_replicas: 1
  tower_route_tls_termination_mechanism: Edge
  tower_task_privileged: false
```

Which throws the error below
```yaml
 awx-operator-65ff65f6d5-w9qsh] TASK [installer : Create Database if no database is specified] *****************
[awx-operator-65ff65f6d5-w9qsh] task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:67 
[awx-operator-65ff65f6d5-w9qsh] fatal: [localhost]: FAILED! => {"changed": false, "error": 422, "msg": "Failed to apply object: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"StatefulSet.apps \\\\\"awx-testing-246-postgres\\\\\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than \\'replicas\\', \\'template\\', and \\'updateStrategy\\' are forbidden\",\"reason\":\"Invalid\",\"details\":{\"name\":\"awx-testing-246-postgres\",\"group\":\"apps\",\"kind\":\"StatefulSet\",\"causes\":[{\"reason\":\"FieldValueForbidden\",\"message\":\"Forbidden: updates to statefulset spec for fields other than \\'replicas\\', \\'template\\', and \\'updateStrategy\\' are forbidden\",\"field\":\"spec\"}]},\"code\":422}\\n'", "reason": "Unprocessable Entity", "status": 422} 
 awx-operator-65ff65f6d5-w9qsh] 
 awx-operator-65ff65f6d5-w9qsh] PLAY RECAP *********************************************************************
 awx-operator-65ff65f6d5-w9qsh] localhost                  : ok=22   changed=0    unreachable=0    failed=1    skipped=15   rescued=0    ignored=0   
```

I believe my error was different because https://github.com/ansible/awx-operator/pull/226, however, since the `statefulset` has some specials fields that can be updated, this error happens. 

Currently, the expected way to fix it is to delete the `awx` kind and then recreate it. 

@shanemcd should we add some logic to remove the `statefulset` and recreate it to be transparent for the user? 

@sean-m-sullivan, could you please check if deleting the `awx` and re-creating works? It worked for me.

**Comment by tchellomello** [comment]
Maybe we could extend the https://github.com/ansible/awx-operator/pull/217 to cover this scenario

**Comment by sean-m-sullivan** [comment]
I'm not able to right now, but will in morning, however, this was in a
github pipeline where it was a fresh mini kube every deploy.

**Comment by andriktr** [comment]
+1. I Have the similar issue if set the following in the awx.yaml
```yaml
spec:
  ...
    tower_postgres_storage_requirements:
    requests:
      storage: 10Gi
    limits:
      storage: 20Gi  
```

Stateful set throws: 
![image](https://user-images.githubusercontent.com/25537180/116075492-b0209880-a69b-11eb-9e3d-1094bcb2c996.png)

I believe that recently `storage` request and limits was under the `tower_postgres_resource_requirements` and when it was changed it started to behave like this.

**Comment by sean-m-sullivan** [comment]
So I tried just from start deploying
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-testing-246
    app.kubernetes.io/part-of: awx-testing-246
  name: awx-testing-246
  namespace: default
spec:
  deployment_type: awx
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_garbage_collect_secrets: false
  tower_image_pull_policy: IfNotPresent
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_postgres_resource_requirements:
    limits:
      cpu: 400m
      memory: 3Gi
    requests:
      cpu: 300m
      memory: 1Gi
  tower_postgres_storage_requirements:
    limits:
      storage: 5Gi
    requests:
      storage: 2Gi
  tower_projects_persistence: false
  tower_projects_storage_access_mode: ReadWriteMany
  tower_projects_storage_size: 8Gi
  tower_replicas: 1
  tower_route_tls_termination_mechanism: Edge
  tower_task_privileged: false
```
and got this postgres error
```
create Claim postgres-awx-testing-246-postgres-0 for Pod awx-testing-246-postgres-0 in StatefulSet awx-testing-246-postgres failed error: PersistentVolumeClaim "postgres-awx-testing-246-postgres-0" is invalid: spec.resources[storage]: Required value
```

But then I deleted minikube entirely, and did the two part starting with this
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-testing-246
    app.kubernetes.io/part-of: awx-testing-246
  name: awx-testing-246
  namespace: default
spec:
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_garbage_collect_secrets: false
  tower_image_pull_policy: IfNotPresent
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_projects_persistence: false
  tower_projects_storage_access_mode: ReadWriteMany
  tower_projects_storage_size: 8Gi
  tower_replicas: 1
  tower_route_tls_termination_mechanism: Edge
  tower_task_privileged: false
  ```
  and then using the other, it looks like postgres is healthy.

**Comment by tchellomello** [comment]
Hello guys, I generated a fresh image from devel and then deployed the following and I cannot reproduce the same error when deploying a new `awx` kind

```yaml
# cat test.yml                                                                         
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-using-resources
  namespace: default
spec:
  deployment_type: awx
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_garbage_collect_secrets: false
  tower_image_pull_policy: IfNotPresent
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_postgres_resource_requirements:
    limits:
      cpu: 400m
      memory: 3Gi
    requests:
      cpu: 300m
      memory: 1Gi
  tower_postgres_storage_requirements:
    limits:
      storage: 5Gi
    requests:
      storage: 2Gi
  tower_projects_persistence: false
  tower_projects_storage_access_mode: ReadWriteMany
  tower_projects_storage_size: 8Gi
  tower_replicas: 1
  tower_route_tls_termination_mechanism: Edge
  tower_task_privileged: false


# kubectl apply -f test.yml                                                                                              12:03:43
awx.awx.ansible.com/awx-using-resources created
```

Then the PostgreSQL `statefulset` worked

```yaml
 kubectl get pod -A -w | grep awx                                                                                       12:04:30
default                awx-operator-5f48c87dd6-bmddn                                     1/1     Running             0          3m24s
default                awx-using-resources-69749c64fd-ztw7r                              0/4     ContainerCreating   0          0s
default                awx-using-resources-postgres-0                                    1/1     Running             0          9s
default                awx-using-resources-69749c64fd-ztw7r                              4/4     Running             0          2s
```

Checking the resources:
```yaml
kubectl get statefulset awx-using-resources-postgres -o yaml | kubectl neat                                            12:07:57
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-using-resources-postgres
    app.kubernetes.io/part-of: awx-using-resources
  name: awx-using-resources-postgres
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/name: awx-using-resources-postgres
  serviceName: awx-using-resources
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/managed-by: awx-operator
        app.kubernetes.io/name: awx-using-resources-postgres
        app.kubernetes.io/part-of: awx-using-resources
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: database
              name: awx-using-resources-postgres-configuration
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: awx-using-resources-postgres-configuration
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: awx-using-resources-postgres-configuration
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_INITDB_ARGS
          value: --auth-host=scram-sha-256
        - name: POSTGRES_HOST_AUTH_METHOD
          value: scram-sha-256
        image: postgres:12
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
        - containerPort: 5432
          name: postgres
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 3Gi
          requests:
            cpu: 300m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
          subPath: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      name: postgres
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        limits:
          storage: 5Gi
        requests:
          storage: 2Gi
      volumeMode: Filesystem
    status:
      phase: Pending


kubectl get pvc postgres-awx-using-resources-postgres-0                                                                12:09:20
NAME                                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
postgres-awx-using-resources-postgres-0   Bound    pvc-0dbc7e29-8e7d-4fa7-9816-395a3d8acaa1   2Gi        RWO            nfs-scratch    5m15s


kubectl get pv pvc-0dbc7e29-8e7d-4fa7-9816-395a3d8acaa1                                                                12:10:09
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                             STORAGECLASS   REASON   AGE
pvc-0dbc7e29-8e7d-4fa7-9816-395a3d8acaa1   2Gi        RWO            Delete           Bound    default/postgres-awx-using-resources-postgres-0   nfs-scratch             5m45s

 kubectl iexec awx /bin/bash                                                                                            12:10:41
Namespace: default | Pod: ✔ awx-using-resources-postgres-0
root@awx-using-resources-postgres-0:/# df -h
Filesystem                                                                                                                         Size  Used Avail Use% Mounted on
overlay                                                                                                                            230G  132G   99G  58% /
tmpfs                                                                                                                               64M     0   64M   0% /dev
tmpfs                                                                                                                               16G     0   16G   0% /sys/fs/cgroup
/dev/mapper/centos_p70-root                                                                                                        230G  132G   99G  58% /etc/hosts
shm                                                                                                                                 64M   16K   64M   1% /dev/shm
192.168.111.46:/volume1/k8s_scratch/default-postgres-awx-using-resources-postgres-0-pvc-0dbc7e29-8e7d-4fa7-9816-395a3d8acaa1/data  3.5T  1.9T  1.7T  52% /var/lib/postgresql/data
tmpfs                                                                                                                               16G   12K   16G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                                                                                                               16G     0   16G   0% /proc/acpi
tmpfs                                                                                                                               16G     0   16G   0% /proc/scsi
tmpfs                                                                                                                               16G     0   16G   0% /sys/firmware
root@awx-using-resources-postgres-0:/# cd /var/lib/postgresql/data/
root@awx-using-resources-postgres-0:/var/lib/postgresql/data# ls
pgdata
root@awx-using-resources-postgres-0:/var/lib/postgresql/data# touch la
root@awx-using-resources-postgres-0:/var/lib/postgresql/data# ls -la la 
-rw-r--r--. 1 root root 0 Apr 26 16:08 la
```
