### ISSUE TITLE
Issue creating persistent storage for /var/lib/awx/projects in awx-task container

### ISSUE THREAD

**Issue by jamesfreeman959** [ansible/tower-operator#259]
Hi there

I have deployed AWX via awx-operator 0.8.0 on microk8s 1.20.6 on Ubuntu 20.04 LTS. All seems to be working well except that I cannot figure out how to get the /var/lib/awx/projects directory to live in a persistent storage volume. Right now this is a simple, single node setup, so I have created a persistent volume claim as follows:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 1Gi
```

I've been playing around with volumes, but my current deployment description for AWX looks like this:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_ingress_tls_secret: awx-secret-tls
  tower_hostname: awx.example.org
  tower_projects_existing_claim: awx-pvc
  tower_extra_volumes: | 
    - name: "data-vol"
      hostPath: 
        path: "/var/lib/awx"
        type: Directory 
  tower_task_extra_volume_mounts: | 
    - name: "data-vol" 
      mountPath: "/data"
```

All pods come up fine, and I can log into AWX just fine - however whenever I go to create a new Project with Source Control Type Manual, it says that there are not available playbook directories in /var/lib/awx/projects, even if I manually copy a playbook directory into the persistent volume I created earlier.

Happy to supply any and all debugging information for this - from the documentation I wasn't really clear how to achieve this, but I had high hopes for "tower_projects_existing_claim". 

Any help appreciated!

Many thanks

James

**Comment by tchellomello** [comment]
Hello @jamesfreeman959, I think what is missing you to pass the option below:

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_ingress_tls_secret: awx-secret-tls
  tower_hostname: awx.example.org
  tower_projects_existing_claim: awx-pvc
  tower_projects_persistence: true  <--- this
```

For example:
```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-toca
    app.kubernetes.io/part-of: awx-toca
  name: awx-toca
  namespace: default
spec:
  ldap_cacert_secret: awx-toca-ldap-ca-cert
  tower_admin_email: tchello.mello@gmail.com
  tower_admin_password_secret: awx-toca-admin-password
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_ee_extra_volume_mounts: |
    - name: ansible-cfg
      mountPath: /etc/ansible/ansible.cfg
      subPath: ansible.cfg
  tower_extra_volumes: |
    - name: ansible-cfg
      configMap:
        defaultMode: 420
        items:
          - key: ansible.cfg
            path: ansible.cfg
        name: awx-toca-extra-config
    - name: custom-py
      configMap:
        defaultMode: 420
        items:
          - key: custom.py
            path: custom.py
        name: awx-toca-extra-config
  tower_garbage_collect_secrets: true
  tower_hostname: awx.tatu.home
  tower_image_pull_policy: IfNotPresent
  tower_ingress_type: none
  tower_projects_persistence: true
  tower_projects_storage_access_mode: ReadWriteMany
  tower_projects_storage_size: 8Gi
  tower_replicas: 1
  tower_task_extra_volume_mounts: |
    - name: custom-py
      mountPath: /etc/tower/conf.d/custom.py
      subPath: custom.py
  tower_task_privileged: false
  tower_task_resource_requirements:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  tower_web_resource_requirements:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
```
Results in this:

```yaml

kubectl get pvc awx-toca-projects-claim                                              23:52:15
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
awx-toca-projects-claim   Bound    pvc-28bfde43-e1e2-44ba-8863-9b4e1f3d1d26   8Gi        RWX            nfs-scratch    47h


kubectl iexec awx-toca /bin/bash                                                                                                         23:53:05
Container: ✔ awx-toca-task
bash-4.4$ df -h /var/lib/awx/projects
Filesystem                                                                                                    Size  Used Avail Use% Mounted on
192.168.111.46:/volume1/k8s_scratch/default-awx-toca-projects-claim-pvc-28bfde43-e1e2-44ba-8863-9b4e1f3d1d26  3.5T  1.9T  1.7T  52% /var/lib/awx/projects

```

 You don't need to use the `extra_volume_mount` as the `/var/lib/awx/projects`  should be cover that using the options above. 

 Check the https://github.com/ansible/awx-operator#persisting-projects-directory and https://github.com/ansible/awx-operator/pull/177 for further information.
