### ISSUE TITLE
Allow for explicitly specifying the service type.

### ISSUE THREAD

**Issue by JoyDistelbrink** [ansible/tower-operator#281]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Service Type for AWX should be ClusterIP when tower_ingress_type=Ingress

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: 0.9.0
* Kubernetes version: 1.19.7
* AWX install method: awx-operator

##### STEPS TO REPRODUCE

```
$ cat my-awx.yml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_hostname: awx.mycompany.com
```
```bash
#> kubectl apply -f my-awx.yml
```
##### EXPECTED RESULTS

service/awx-service should be ClusterIP

##### ACTUAL RESULTS

service/awx-service is NodePort

##### ADDITIONAL INFORMATION
It seems that when type Ingress is set we can't enter the correct condition here : 
https://github.com/shanemcd/awx-operator/blob/c0e164d76338bca35bc496ea01c70f2e866522a9/roles/installer/templates/tower_service.yaml.j2#L47

Refers to : 
https://github.com/ansible/awx-operator/pull/204/commits/e091b32c4b18ea9fc719aaa99648bb1bcbd69063
https://github.com/ansible/awx-operator/issues/202

Thanks for your help.

**Comment by shanemcd** [comment]
We can't change the default here without breaking the nginx ingress controller. This should be a configurable option.

**Comment by tchellomello** [comment]
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-ingress-svc
spec:
  tower_ingress_type: Ingress
  tower_hostname: awx.mycompany.com

----- RESULTS


kubectl get svc awx-ingress-svc-service -o yaml | kubectl neat                      23:53:40
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-ingress-svc
    app.kubernetes.io/part-of: awx-ingress-svc
  name: awx-ingress-svc-service
  namespace: default
spec:
  clusterIP: 10.233.20.64
  clusterIPs:
  - 10.233.20.64
  ports:
  - name: http
    nodePort: 32750
    port: 80
    targetPort: 8052
  selector:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-ingress-svc
  type: NodePort
```
