### ISSUE TITLE
AWX Operator Fails to Install AWX Containers/Instance

### ISSUE THREAD

**Issue by bandwiches** [ansible/tower-operator#284]
##### ISSUE TYPE
AWX Operator fails to perform installation.

##### SUMMARY
Had an instance of 17.0.1 running, don't care if the data persists either.

Performed data migration following [Data Migration](https://github.com/ansible/awx/blob/devel/tools/docker-compose/docs/data_migration.md) instructions.

Performed install of AWX Operator following [INSTALL.md](https://github.com/ansible/awx/blob/devel/INSTALL.md)
  - minikube v1.18.1 was installed during this time following links from INSTALL.md

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.9.0
* Kubernetes version: 1.20.2
* AWX install method: operator

##### STEPS TO REPRODUCE

Follow [INSTALL.md](https://github.com/ansible/awx/blob/devel/INSTALL.md)

##### EXPECTED RESULTS

Expected to see pods/AWX instance

##### ACTUAL RESULTS

`minikube kubectl apply -- -f myawx.yml`

After 30 minutes only the orchestrator is running, tailing the logs shows a looping error.

##### ADDITIONAL INFORMATION

```
xxx@yyy:~$ minikube kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
awx-operator-5595d6fc57-hdj9d   1/1     Running   0          29m
```

```
xxx@yyy:~$ minikube version
minikube version: v1.18.1
```

##### AWX-OPERATOR LOGS

```json
{
  "level": "error",
  "ts": 1620223136.6924627,
  "logger": "logging_event_handler",
  "msg": "",
  "name": "custom.name.awx", 
  "namespace": "default",
  "gvk": "awx.ansible.com/v1beta1,Kind=AWX",
  "event_type": "runner_on_failed",
  "job": "2601737961087659062",
  "EventData.Task": "Create Database if no database is specified",
  "EventData.TaskArgs": "",
  "EventData.FailedTaskPath": "/opt/ansible/roles/installer/tasks/database_configuration.yml:68",
  "error": "[playbook task failed]",
  "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/operator-framework/operator-sdk/pkg/ansible/events.loggingEventHandler.Handle\n\tsrc/github.com/operator-framework/operator-sdk/pkg/ansible/events/log_events.go:87"
}
```

**Comment by bandwiches** [comment]
Blew the entire thing away and restarted fresh.  Service pods are stuck 0/4 pending.  It's been an additional 45 minutes now.

This is the exact task that continuously fails over and over again with no real output/log.
```
TASK [installer : Apply deployment resources] **********************************
task path: /opt/ansible/roles/installer/tasks/resources_configuration.yml:34
```

Output
```json
{
    "level":"error",
    "ts":1620229749.932002,
    "logger":"controller-runtime.controller",
    "msg":"Reconciler error",
    "controller":"awx-controller",
    "request":"default/awx",
    "error":"event runner on failed",
    "stacktrace": 
        "github.com/go-logr/zapr.(*zapLogger).Error
            pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
            pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
            pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232
        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
            pkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
            pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155
        k8s.io/apimachinery/pkg/util/wait.BackoffUntil
            pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156
        k8s.io/apimachinery/pkg/util/wait.JitterUntil
            pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133
        k8s.io/apimachinery/pkg/util/wait.Until
            pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"
}
```

Logs
`awx-web`: stale after image with the following two lines
```
[INFO] SIGTERM: Shutting down servers then terminating
[INFO] plugin/health: Going into lameduck mode for 5s
```
`redis`: stale after image downloads
`awx-task`: nothing
`awx-ee`: nothing

**Comment by tchellomello** [comment]
@bandwiches we will need more information to understand what is going on. 
Please send us the following:

```sh
kubectl get awx -o yaml awx

kubectl describe deployment awx

kubectl describe statefulset awx-postgres

kubectl get pods 

kubectl get events
```

Thanks!

**Comment by exodusprime1337** [comment]
I'm seeing the same thing in minikube. here is the output from mine. Saw the same error in kubernetes on centos7 as well. Fresh install with all latest binaries. 

[describe_awx.txt](https://github.com/ansible/awx-operator/files/6431601/describe_awx.txt)
[describe_stateful.txt](https://github.com/ansible/awx-operator/files/6431602/describe_stateful.txt)
[events.txt](https://github.com/ansible/awx-operator/files/6431603/events.txt)
[get_awx.txt](https://github.com/ansible/awx-operator/files/6431604/get_awx.txt)
[pods.txt](https://github.com/ansible/awx-operator/files/6431605/pods.txt)

**Comment by bandwiches** [comment]
> @bandwiches we will need more information to understand what is going on.
> Please send us the following:
> 
> ```shell
> kubectl get awx -o yaml awx
> 
> kubectl describe deployment awx
> 
> kubectl describe statefulset awx-postgres
> 
> kubectl get pods 
> 
> kubectl get events
> ```
> 
> Thanks!

For the sake of clarity, I feel I should state that I'm using minikube since it is recommended by the AWX install guide.

[get_awx.txt](https://github.com/ansible/awx-operator/files/6435150/get_awx.txt)
[describe_deployment_awx.txt](https://github.com/ansible/awx-operator/files/6435145/describe_deployment_awx.txt)
[describe_statefulset.txt](https://github.com/ansible/awx-operator/files/6435161/describe_statefulset.txt)
[get_pods.txt](https://github.com/ansible/awx-operator/files/6435148/get_pods.txt)
[get_events.txt](https://github.com/ansible/awx-operator/files/6435146/get_events.txt)

(Edit) I see a CPU warning (insufficient CPU) for the AWX pod.  I have to say, this is a dedicated VM w/2 CPU and 2GB RAM.  This VM has had no issues running AWX v15 and v17.  New install method introduced in v19 all of a sudden complains about resources?  Understandable that this could change from version to version, but it would be nice to know minimal system requirements now that it's an issue.

**Comment by exodusprime1337** [comment]
Here is the snippet of the error i'm seeing which i believe is exactly like @bandwiches error. 

{"level":"error","ts":1620310325.2259731,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"awx-controller","request":"default/awx","error":"event runner on failed","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\tpkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.6.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\tpkg/mod/k8s.io/apimachinery@v0.18.2/pkg/util/wait/wait.go:90"}
{"level":"info","ts":1620310327.3738635,"logger":"logging_event_handler","msg":"[playbook task]","name":"awx","namespace":"default","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"261049867304784443","EventData.Name":"installer : Patching labels to AWX kind"}

**Comment by bandwiches** [comment]
@exodusprime1337 

Spot on.

**Comment by abcqwertz** [comment]
I have the exact same error, but on a bare-metal kubernetes cluster:
    AWX version: 19.1.0
    Operator version: 0.9.0
    Kubernetes version: v1.21.0 with containerd 1.4.4
    AWX install method: operator

**Comment by tchellomello** [comment]
> > @bandwiches we will need more information to understand what is going on.
> > Please send us the following:
> > ```shell
> > kubectl get awx -o yaml awx
> > 
> > kubectl describe deployment awx
> > 
> > kubectl describe statefulset awx-postgres
> > 
> > kubectl get pods 
> > 
> > kubectl get events
> > ```
> > 
> > 
> > Thanks!
> 
> For the sake of clarity, I feel I should state that I'm using minikube since it is recommended by the AWX install guide.
> 
> [get_awx.txt](https://github.com/ansible/awx-operator/files/6435150/get_awx.txt)
> [describe_deployment_awx.txt](https://github.com/ansible/awx-operator/files/6435145/describe_deployment_awx.txt)
> [describe_statefulset.txt](https://github.com/ansible/awx-operator/files/6435161/describe_statefulset.txt)
> [get_pods.txt](https://github.com/ansible/awx-operator/files/6435148/get_pods.txt)
> [get_events.txt](https://github.com/ansible/awx-operator/files/6435146/get_events.txt)
> 
> (Edit) I see a CPU warning (insufficient CPU) for the AWX pod. I have to say, this is a dedicated VM w/2 CPU and 2GB RAM. This VM has had no issues running AWX v15 and v17. New install method introduced in v19 all of a sudden complains about resources? Understandable that this could change from version to version, but it would be nice to know minimal system requirements now that it's an issue.

For your case, it looks the issue is related with the CPU (like you mentioned)

```yaml
NAME                            READY   STATUS    RESTARTS   AGE
awx-5b58db49c-9gslf             0/4     Pending   0          7m3s
awx-operator-5595d6fc57-92txg   1/1     Running   0          10m
awx-postgres-0                  1/1     Running   0          7m14s

LAST SEEN   TYPE      REASON                    OBJECT                                          MESSAGE
87s         Warning   FailedScheduling          pod/awx-5b58db49c-9gslf                         0/1 nodes are available: 1 Insufficient cpu.
```

Looking at your deployment, we can see it's using the default `resource` limits:

```yaml
   awx-web:
    Image:      quay.io/ansible/awx:19.1.0
    Port:       8052/TCP
    Host Port:  0/TCP
    Requests:
      cpu:     1
      memory:  2Gi

....

   awx-task:
    Image:      quay.io/ansible/awx:19.1.0
    Port:       <none>
    Host Port:  <none>
    Args:
      /usr/bin/launch_awx_task.sh
    Requests:
      cpu:     500m
      memory:  1Gi

....
```

Please note the suggested values (memory and cpu) are still the same (see https://github.com/ansible/awx-operator/pull/93/files) and you can override it to fulfill your needs.  That should the job for you. Please let us know.

**Comment by tchellomello** [comment]
> I'm seeing the same thing in minikube. here is the output from mine. Saw the same error in kubernetes on centos7 as well. Fresh install with all latest binaries.
> 
> [describe_awx.txt](https://github.com/ansible/awx-operator/files/6431601/describe_awx.txt)
> [describe_stateful.txt](https://github.com/ansible/awx-operator/files/6431602/describe_stateful.txt)
> [events.txt](https://github.com/ansible/awx-operator/files/6431603/events.txt)
> [get_awx.txt](https://github.com/ansible/awx-operator/files/6431604/get_awx.txt)
> [pods.txt](https://github.com/ansible/awx-operator/files/6431605/pods.txt)

Same thing here @exodusprime1337 

```yaml
LAST SEEN   TYPE      REASON                    OBJECT                                          MESSAGE
2s          Warning   FailedScheduling          pod/awx-5b58db49c-bfwnt                         0/1 nodes are available: 1 Insufficient memory.
21m         Normal    SuccessfulCreate          replicaset/awx-5b58db49c                        Created pod: awx-5b58db49c-bfwnt

   awx-web:
    Image:      quay.io/ansible/awx:19.1.0
    Port:       8052/TCP
    Host Port:  0/TCP
    Requests:
      cpu:     1
      memory:  2Gi

    Requests:
      cpu:     500m
      memory:  1Gi
```
If you run `kubectl get nodes  <NODE_NAME> -o yaml`, you shall see the amount of memory for your node:

```yaml
  allocatable:
    cpu: 7800m
    ephemeral-storage: "222240964241"
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 31547268Ki
    pods: "250"
  capacity:
    cpu: "8"
    ephemeral-storage: 235495Mi
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 32173956Ki
    pods: "250"


> kubectl top nodes                                                                                                                                                                                                                                                                       
NAME     CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%     
p70      763m         9%     12685Mi         41%         
```
