### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims

### ISSUE THREAD

**Issue by cscal** [ansible/tower-operator#289]
##### ISSUE TYPE
 - Info Request

##### SUMMARY
With a fresh install of Kubernetes, following the instructions for a fresh install of AWX, the Postgres pod gets stuck in a pending state. 

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.9.0
* Kubernetes version: 1.21
* AWX install method:  Kubernetes AWX Operator with Docker and Flannel

##### STEPS TO REPRODUCE

On a fresh install of k8s:
kubeadm init --pod-network-cidr=10.244.0.0/16
Performed all the steps described in the official kubernetes documentation for installing and creating a cluster. 
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.9.0/deploy/awx-operator.yaml
On a joined worker node, I created, formatted and mounted a 20Gi disk, then created this file for k8s to use it as a persistent volume:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /mnt/disk
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <hostname redacted>
```
Created this storage claim:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```
Applied both of those files and everything looks good with kubectl get pv and pvc. Also flannel looks good.
Here's my my-awx.yml:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_postgres_storage_requirements:
    requests:
      storage: 8Gi
    limits:
      storage: 20Gi
  tower_postgres_storage_class: local-storage
```
When I apply it: I get this output from kubectl get all:
```
NAME                                READY   STATUS    RESTARTS   AGE
pod/awx-5b58db49c-sd6wq             4/4     Running   0          37m
pod/awx-operator-5d9d764bcd-pjzdw   1/1     Running   0          38m
pod/awx-postgres-0                  0/1     Pending   0          37m

NAME                           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)             AGE
service/awx-operator-metrics   ClusterIP   10.107.107.63    <none>        8383/TCP,8686/TCP   38m
service/awx-postgres           ClusterIP   None             <none>        5432/TCP            37m
service/awx-service            ClusterIP   10.102.108.148   <none>        80/TCP              37m
service/kubernetes             ClusterIP   10.96.0.1        <none>        443/TCP             46m

NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx            1/1     1            1           37m
deployment.apps/awx-operator   1/1     1            1           38m

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-5b58db49c             1         1         1       37m
replicaset.apps/awx-operator-5d9d764bcd   1         1         1       38m

NAME                            READY   AGE
statefulset.apps/awx-postgres   0/1     37m
```
Looking at kubectl describe pod awx-postgres-0, I see this:
```
Volumes:
  postgres:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  postgres-awx-postgres-0
    ReadOnly:   false
  kube-api-access-84p9k:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  41m   default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling  41m   default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
```

##### EXPECTED RESULTS

Postgres should be able to use the persistent volume and start up.

##### ACTUAL RESULTS

It doesn't, see above output.

##### ADDITIONAL INFORMATION

The AWX Operator documentation doesn't say much about persistent volumes but it is a critical piece of the puzzle to getting AWX installed and running. Would appreciate better guidance on setting it up properly, written for someone who is new to Kubernetes.

**Comment by tchellomello** [comment]
You created a `pvc` with the name `postgres-pv-claim` which should be bounded to the `PV` `postgres-pv`.  So if you do, `kubectl get pvc postgres-pv-claim` you should this bounded and ready to go. 

However, note that `awx-operator` does not have support for `claimName` and only to specify the expected `storageClassName`. Having said this, it could be the reason for your `local-storage-provisioner` not having the ability to auto-allocate the disk. 

In other words, there is misinformation between which `PVC` to use vs to use the one you created.

I would recommend you do the following:

1. Delete the  PVC `postgres-pv-claim` 
2. Recreate the PVC with the name `postgres-awx-postgres-0`
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-awx-postgres-0
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
 ```
If your storage layer looks correctly, just by doing it your `awx` instance should start.
