### ISSUE TITLE
Wrong node selected for job pods

### ISSUE THREAD

**Issue by emdzej1987** [ansible/tower-operator#290]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Jobs pods are created on wrong node, despite using nodeSelector for Tower

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.9.0
* Kubernetes version: v1.18.14
* AWX install method: Kubernetes on Azure

##### STEPS TO REPRODUCE

Fresh install with below configuration:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_node_selector: |
    agentpool: linux
  tower_postgres_selector: |
    agentpool: linux
```

Pods are deployed correctly on linux node. After starting a Demo job, the job pod is deployed on wrong node.

##### EXPECTED RESULTS

All pods running on the same node.

##### ACTUAL RESULTS

Job pods running on wrong node.

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/79972779/117405841-89b8f380-af0c-11eb-8571-4f17bc0436b5.png)
