### ISSUE TITLE
How to specify NodePort?

### ISSUE THREAD

**Issue by VladoPortos** [ansible/tower-operator#291]
I'm not sure right now how to specify NodePort with AWX operator.  Its not mentioned in documentation.

spec:
  tower_ingress_type: NodePort

Ok, but how to avoid random port assignment,

Usually I can do in service deployment something like:

```
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 443
      nodePort: 30443
      name: https
```

**Comment by tchellomello** [comment]
@VladoPortos currently there is no support to manually specify the `NodePort` via operator (see https://github.com/ansible/awx-operator/blob/devel/roles/installer/templates/tower_service.yaml.j2#L48-L49)

However, that should be fairly simple to add (https://kubernetes.io/docs/concepts/services-networking/service/#nodeport). 

@VladoPortos do want to work on PR?

**Comment by VladoPortos** [comment]
Hello @tchellomello I might have a look but need to finish some additional work first. I got to this while I was working on ansible role that deploys Minikube ( with docker backend ) and then AWX  which I did and it works fine :) just the HTTPS was point of interest. The classical ingress in kubernetes and minikube is more complicated than it needs to be and most people are just used to more to nginx reverse proxy. I was thinking to deploy AWX with tower_ingress_type: none and than just apply custom SVC with nodeport specified. than it can be passed further to role that setup nginx reverse proxy, without parsing the minikube get url command :)

**Comment by VladoPortos** [comment]
Quick fix without me doing PR right now.

Deploy with:
`tower_ingress_type: NodePort` as normal ( or with none ) 

When AWX is deployed create file `awx_svc.yml`

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx
    app.kubernetes.io/part-of: awx
  name: awx-service-custom
  namespace: default
spec:
  ports:
    - name: http
      nodePort: 30444
      port: 80
      protocol: TCP
      targetPort: 8052
  selector:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx
  sessionAffinity: None
  type: NodePort
```

Change nodePort: to number you like in range: 30000-32767

And apply with:
minikube kubectl -- apply -f awx_svc.yml

This will make new service called awx-service-custom binded to port you have chosen. 

Then just get IP with  `minikube ip` adn you have IP and Port to use in nginx reverse proxy.

**Comment by takuan-osho** [comment]
Is there any progress about this issue?
I also hope this issue would be resolved.

@tchellomello Could you proceed with your reviewing #501 to resolve this issue? (though the PR is not mine)
Thanks in advance.

**Comment by tchellomello** [comment]
Thanks for the heads up @takuan-osho

**Comment by LeoSpyke** [comment]
Is there any progress about this issue?

**Comment by fosterseth** [comment]
@LeoSpyke96 seems #501 solved this issue, e.g.,

```yaml
---
spec:
  ...
  service_type: NodePort
  nodeport_port: 30080
```

this issue can probably be closed.

**Comment by LeoSpyke** [comment]
> @LeoSpyke96 seems #501 solved this issue, e.g.,
> 
> ```yaml
> ---
> spec:
>   ...
>   service_type: NodePort
>   nodeport_port: 30080
> ```
> 
> this issue can probably be closed.

As far as I can see, with the following configuration and using the version `0.17.0` the issue is still there:
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  admin_user: admin
  admin_password_secret: [...]

  service_type: NodePort
  nodeport_port: 32262 👈

  [...]
```

Indeed, running the command `kubectl -n awx get service`, I get the following:
                                                                                                                                      
```
NAME                                                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.43.252.72   <none>        8443/TCP       11d
service/awx-postgres                                      ClusterIP   None           <none>        5432/TCP       11d
service/awx-service                                       NodePort    10.43.82.206   <none>        80:31905/TCP   11d  👈
```
