### ISSUE TITLE
Add Ability to add annotations to AWX serviceaccount

### ISSUE THREAD

**Issue by jw-maynard** [ansible/tower-operator#326]
##### ISSUE TYPE
 - Feature Request

##### SUMMARY

There is currently no way to add custom annotations to the Service Account created by the operator. Being able to annotate the service account is critical to being able to use the IAM integration in EKS. [AWS Docs](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#service-account-configuration)

##### ENVIRONMENT
* AWX version: 0.9.0
* Operator version: 19.1.0
* Kubernetes version: EKS 1.19
* AWX install method: k8s manifests

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

##### ADDITIONAL INFORMATION
N/A

##### AWX-OPERATOR LOGS
N/A

**Comment by jw-maynard** [comment]
Thanks you @shanemcd

**Comment by mohamedazouz** [comment]
Hi @tchellomello , 

I have used the new added functionality to reterive secrets from aws secret manager, but it seems like the new job pod (worker container) doesn't have the correct env variables so it resulted with access denied 

I'm not sure if I'm missing any config

Helm chart v: `1.1.4`

Values: 
```yaml
AWX:
  enabled: true
  spec:
    replicas: 1
    ee_extra_env: |
      - name: RECEPTOR_KUBE_SUPPORT_RECONNECT
        value: disabled
    service_account_annotations: |
      eks.amazonaws.com/role-arn: AWS_IAM_ROLE
```
any thoughts?
