### ISSUE TITLE
Adding a custom krb5.conf via operator?

### ISSUE THREAD

**Issue by jurschel** [ansible/tower-operator#337]
##### ISSUE TYPE
 - Question

##### SUMMARY
I need to add a custom krb5.conf to the awx-task container so that it can connect to my Active Directory ldap for kerberos.  How can I do that via the operator?

##### ENVIRONMENT
* AWX version: 19.1
* Operator version: 0.9.0
* Kubernetes version: 1.19.6
* AWX install method: operator

**Comment by tchellomello** [comment]
@jurschel have you tried the options as explained at https://github.com/ansible/awx-operator#custom-volume-and-volume-mount-options?

**Comment by jurschel** [comment]
I did.  Didn't realize that I had to add tower_ to the 0.9.0 values.  Also once I got that changed now I'm getting this when the awx-task container tries to start.

```
Warning  Failed     60s                 kubelet            Error: failed to start container "awx-task": Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:60: mounting "/var/lib/kubelet/pods/79ef3ad2-f30b-4c7f-bdb9-6747a21db6b6/volume-subpaths/krb5-config/awx-task/11" to rootfs at "/var/lib/docker/overlay2/02e61861cc86235f86c114dd9c9caef13b9bec6b5a7cfb71db0168f20480049c/merged/etc/krb5.conf" caused: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```

This is the bit I added to my awx.yaml
```
  tower_task_extra_volume_mounts: |
    - name: krb5-config
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
  tower_extra_volumes: |
    - name: krb5-config
      configmap:
        defaultMode: 420
        items:
          - key: krb5.conf
            path: krb5.conf
        name: awx-task-extra-config-krb5
```
