### ISSUE TITLE
Generated password not working with webui

### ISSUE THREAD

**Issue by evilmonkeyslayer** [ansible/tower-operator#341]
EDIT: This issue only occurs if I set a custom awx-admin-password secret and then try to install awx. It does work with the randomly created password. However, any password I set myself fails to work. (just tried a fresh deploy and it gives me a whole long list of fails related to the password. Am I doing something wrong in creating this secret somehow?)

##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Password not working on webui on basic install.

##### ENVIRONMENT
* AWX version: 19.1
* Operator version: 0.9.0
* Kubernetes version: 1.19.11
* AWX install method: kubectl

##### STEPS TO REPRODUCE

Install with bare minimum install and try to login with admin password generated by:
```
kubectl apply -f awx-operator.yaml
kubectl apply -f my-awx.yaml (with "ingress_type: Ingress")
kubectl apply -f awx-simple-ingress.yaml (see below for contents)
```

**awx-simple-ingress.yaml:**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: awx-service
            port:
              number: 80
```
**Run the below to get the password:**
`kubectl get secret awx-admin-password -o jsonpath="{.data.password}" | base64 --decode`

##### EXPECTED RESULTS

Able to login using the generated password and username of admin.

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/51646009/119968426-5b778280-bfa5-11eb-94c8-2075dc2cf4a8.png)

##### ADDITIONAL INFORMATION

I also generated a simple password too, but had the same result.

For example:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: default
stringData:
  password: password
```

**Comment by evilmonkeyslayer** [comment]
To re-explain:

Edit my-awx.yaml to include the two bottom lines:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  ingress_type: Ingress
  admin_password_secret: awx-admin-password
```

Create a file named secret.yaml with the contents:

```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-admin-password
  namespace: default
stringData:
  password: password123
```

Then run:

kubectl apply -f secret.yaml
kubectl apply -f my-awx.yaml

And include the ingress from the above post.

Looking at the logs with `kubectl logs -f deployments/awx-operator` gives me a whole bunch of fails. And awx doesn't deploy.
