### ISSUE TITLE
Backup is broken

### ISSUE THREAD

**Issue by Zokormazo** [ansible/tower-operator#345]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Backup is broken

##### ENVIRONMENT
* AWX version: 19.1
* Operator version: devel
* Kubernetes version: OCP 4.6
* AWX install method: operator

##### STEPS TO REPRODUCE

1. Install operator
2. Deploy an awx instance
3. Backup

##### EXPECTED RESULTS

Get a backup

##### ACTUAL RESULTS

Operator fails on https://github.com/ansible/awx-operator/blob/devel/roles/backup/tasks/postgres.yml#L30-L41

##### ADDITIONAL INFORMATION

AWX CR:
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: tower
  namespace: backup
spec:
  admin_user: admin
  admin_email: test@example.com
  ingress_type: Route
  hostname: tower
  replicas: 1
```
AWXBackup CR:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup1
  namespace: backup
spec:
  deployment_name: tower
```

##### AWX-OPERATOR LOGS
[awx-operator.log](https://github.com/ansible/awx-operator/files/6568722/awx-operator.log)
