### ISSUE TITLE
ERROR Migrating data from an old AWX instance

### ISSUE THREAD

**Issue by evgenij-vorotnikov** [ansible/tower-operator#350]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After command execution I got error: Secret in version "v1" cannot be handled as a Secret: v1.Secret.StringData: ReadString: expects " or n, but found 5, error found in #10 byte of ...|"

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.9.0
* Kubernetes version: 1.20.2
* AWX install method: minikube

##### STEPS TO REPRODUCE

I follow instruction https://github.com/ansible/awx-operator/blob/devel/docs/migration.md but after running command "minikube kubectl apply -- -f myawx.yml --validate=false" I got error described above

##### EXPECTED RESULTS

Deployed AWX

##### ACTUAL RESULTS

ERROR: Secret in version "v1" cannot be handled as a Secret: v1.Secret.StringData: ReadString: expects " or n, but found 5, error found in #10 byte of ...|"

##### ADDITIONAL INFORMATION

Config file myawx.yml

```
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: default
stringData:
  secret_key: "*********"
  type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-old-postgres-configuration
  namespace: default
stringData:
  host: *********
  port: *********
  database: *********
  username: *********
  password: *********
type: Opaque
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  old_postgres_configuration_secret: awx-old-postgres-configuration
```
