### ISSUE TITLE
Permission denied when using persistent volume AzureDisk

### ISSUE THREAD

**Issue by wohnout** [ansible/tower-operator#357]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am getting permission denied when trying to clone git into /var/lib/awx/projects when using persistent storage over AzureDisk

##### ENVIRONMENT
* AWX version: 19.1.0
* Operator version: 0.10.0
* Kubernetes version: 1.18.14
* AWX install method: Azure Kubernetes services

##### STEPS TO REPRODUCE
1) Create PV and PVC with defined storage class
```
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: azuredisk
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx
  namespace: awx
spec:
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk
  claimRef:
    namespace: awx
    name: pvc-awx
  azureDisk:
    kind: Managed
    diskName: disk-pv-awx
    diskURI: /subscriptions/XXXXXXXX/resourceGroups/RGNAME/providers/Microsoft.Compute/disks/disk-pv-awx

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-awx
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default-retain
  resources:
    requests:
      storage: 64Gi
```

2) Create AWX using this deployment
```
---

apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  ingress_type: Ingress
  hostname: awx.hostname
  ingress_annotations: |
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  ingress_tls_secret:
    awx-le-secret
  projects_existing_claim: pvc-awx
  projects_persistence: true
```

##### EXPECTED RESULTS
Permissions of mounted volume are set properly and clone of git works well

##### ACTUAL RESULTS
I am getting permission denied as projects folder is mounted 755 and owner is root so runtime user is not able to write into that folder

```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 1289, in run
    self.pre_run_hook(self.instance, private_data_dir)
  File "/var/lib/awx/venv/awx/lib64/python3.8/site-packages/awx/main/tasks.py", line 2144, in pre_run_hook
    os.makedirs(project_path)  # used as container mount
  File "/usr/lib64/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/awx/projects/_8__ansible'
```
##### ADDITIONAL INFORMATION
Using azure files doesn't work also as AzureFiles doesn't support chmod.

##### AWX-OPERATOR LOGS
N/A

**Comment by tchellomello** [comment]
I tried to reproduce a similar environment on azure with the following:

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
allowVolumeExpansion: true
metadata:
  name: azuredisk
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-awx
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk
  claimRef:
    name: pvc-awx
  azureDisk:
    kind: Managed
    diskName: disk-pv-awx
    diskURI: /subscriptions/XXXXXXXXXXXX/resourceGroups/XXXXXXXXXXXXXXXXX/providers/Microsoft.Compute/disks/disk-pv-awx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-awx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azuredisk
  resources:
    requests:
      storage: 10Gi
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-az
spec:
  ingress_type: Ingress
  hostname: awx.azure.demo
  ingress_annotations: |
    kubernetes.io/ingress.class: nginx
  projects_existing_claim: pvc-awx
  projects_persistence: true
  web_resource_requirements:
    requests:
      cpu: 1m
      memory: 100Mi
    limits:
  task_resource_requirements:
    requests:
      cpu: 1m
      memory: 100Mi
  ee_resource_requirements:
    requests:
      cpu: 1m
      memory: 100Mi
```

Some of the resources created
```yaml
$ kubectl get storageclasses                                                                                23:33:44
NAME                PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
azuredisk           kubernetes.io/azure-disk   Retain          Immediate              true                   81m
azurefile           kubernetes.io/azure-file   Delete          Immediate              true                   90m
azurefile-premium   kubernetes.io/azure-file   Delete          Immediate              true                   90m
default (default)   kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   90m
managed-premium     kubernetes.io/azure-disk   Delete          WaitForFirstConsumer   true                   90m

$ kubectl get pv                                                                                            23:34:27
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                STORAGECLASS   REASON   AGE
pvc-25fe6cd9-7d00-4b37-95bb-bd3bf2371190   8Gi        RWO            Delete           Bound    default/postgres-awx-az-postgres-0   default                 58m
pvc-c40f2ac5-72e2-460c-a6be-0251ea1d7767   10Gi       RWO            Retain           Bound    default/pvc-awx                      azuredisk               79m

$ kubectl get pvc                                                                                           23:33:14
NAME                         STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
postgres-awx-az-postgres-0   Bound    pvc-25fe6cd9-7d00-4b37-95bb-bd3bf2371190   8Gi        RWO            default        57m
pvc-awx                      Bound    pvc-c40f2ac5-72e2-460c-a6be-0251ea1d7767   10Gi       RWO            azuredisk      78m
```


Then trying to create a directory at `/var/lib/awx/projects`  we got the expected error:

```sh
(py39) mdemello@storm ~/d/P/a/reproducer-357 (devel)> kubectl iexec awx-az /bin/bash                                       22:39:54
Namespace: default | Pod: ✔ awx-az-84dd57946f-855mn
Container: ✔ awx-az-web
bash-4.4$ df -h /var/lib/awx/projects/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc        9.8G   37M  9.8G   1% /var/lib/awx/projects
bash-4.4$ ls -lah /var/lib/awx/projects/
total 24K
drwxr-xr-x 3 root root 4.0K Jun 18 02:26 .
drwxrwxr-x 1 root root 4.0K Jun 18 02:39 ..
drwx------ 2 root root  16K Jun 18 02:26 lost+found
bash-4.4$ id awx
uid=1000(awx) gid=0(root) groups=0(root)
bash-4.4$ whoami 
awx
bash-4.4$ touch /var/lib/awx/projects/test
touch: cannot touch '/var/lib/awx/projects/test': Permission denied
```

Then I made the following modification and tried again

```diff
diff --git a/roles/installer/templates/deployment.yaml.j2 b/roles/installer/templates/deployment.yaml.j2
index 293fda1..95460cf 100644
--- a/roles/installer/templates/deployment.yaml.j2
+++ b/roles/installer/templates/deployment.yaml.j2
@@ -240,6 +240,8 @@ spec:
       tolerations:
         {{ tolerations | indent(width=8) }}
 {% endif %}
+      securityContext:
+        fsGroup: 1000
       volumes:
 {% if ingress_type | lower == 'route' and route_tls_termination_mechanism | lower == 'passthrough' %}
         - name: "{{ meta.name }}-nginx-certs"
```
Reconciliation happed a new deployment was launched. Then tests worked as expected:


```sh
$ kubectl iexec awx-az /bin/bash                                                                            23:39:31
Namespace: default | Pod: ✔ awx-az-5fc5dd5767-lc48z
Container: ✔ awx-az-web
bash-4.4$ ls -lad /var/lib/awx/projects/
drwxrwsr-x 5 root 1000 4096 Jun 18 03:09 /var/lib/awx/projects/
bash-4.4$ df -h /var/lib/awx/projects/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdc        9.8G   37M  9.8G   1% /var/lib/awx/projects
bash-4.4$ touch /var/lib/awx/projects/test_works && echo $?
0
```

And then we will have the project sync working as expected. 

![image](https://user-images.githubusercontent.com/809840/122502956-93328280-cfc5-11eb-923c-2ae88b7a3aaf.png)

@wohnout can you try on your end and report the results? You can use the image hosted at quay.io/tchellomello/awx-operator:devel to test it.
