### ISSUE TITLE
AWX - Setup with external Postgress - Fresh installation.

### ISSUE THREAD

**Issue by psreddy22** [ansible/tower-operator#359]
Hi Experts,

I'm able to use old postgress DB with new setup, but not able to to fresh setup. Getting below error, while connecting to awx web. Can anyone look into issue please !!

Error!
Failed to fetch custom login configuration settings. System defaults will be shown instead.
GET /api/ 404
404 page not found

**Comment by tchellomello** [comment]
@psreddy22 we will need more information to assist you. Could you share your `awx` spec?

**Comment by mkayontour** [comment]
Hi, I got the same issue. I'm behind a traefik ingress and I get this message. 

```
Failed to fetch custom login configuration settings. System defaults will be shown instead.

Details
GET /api/v2/auth/ 404
404 page not found
```

I use a fresh database, my specs are the following:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  ingress_type: none
  hostname: awx-test.****
  postgres_storage_class: manual
```

In Addition if I click close on the message and try to log in with the generated secret, the login fails.
