### ISSUE TITLE
Image versions are really confusing and not well documented.

### ISSUE THREAD

**Issue by BrandonALXEllisSS** [ansible/tower-operator#373]
It's not well documented how operator versions correlate to versions of awx.

There's variables like `image` and `image_version` leading me (and probably many others) to think that you can deploy any version of AWX using the operator (which clearly isn't the case, as 0.6.0 could deploy 17.1.0 and below whereas 0.8.0 could deploy 18.0.0, etc.)

But even more confusing is this line:

>Note: The image and image_version are intended for local mirroring scenarios. Please note that using a version of AWX other than the one bundled with the awx-operator is not supported. For the default values, check the main.yml file.

What is the "version bundled with awx-operator"? I can't find this information anywhere.

**Comment by metabsd** [comment]
You can find all the answers in the code. You are right, the documentation is not complete. With each release I have to rewrite my deployments, because there are still changes in the core of this operator. But it is described at the beginning of the documentation. This Operator is Alpha. I think it works well for an alpha operator.

For version 0.10.0 the default AWX version is 19.2.0.

The default `image_version` variables is described in this file at line 105

`https://github.com/ansible/awx-operator/blob/0.10.0/roles/installer/defaults/main.yml#L105`

You can override it by defining your own values in the deployment.

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: yournamespace
spec:
  admin_email: You@email.domain
  image: quay.io/ansible/awx
  image_version: "19.1.0"
```

Enjoy your deployment!
