### ISSUE TITLE
Mounting extra volumes on Pods

### ISSUE THREAD

**Issue by felipe4334** [ansible/tower-operator#380]
I need help figuring this out, I have spent over a day troubleshooting this and can't seem to make any progress. I'm trying to mount a volume claim into AWX as shown below and when I go into the pods I notice that even though the mount path is there, its actually mounted to the primary volume instead of the external one. I have verified that my volume is created and volume claim is spelled correctly. I tried creating a test pod on the awx namespace with "oke-fsspvc-awx-scratch" volume mount claim and it works as expected.

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  tower_ingress_type: NodePort
  tower_hostname: test.local
  tower_extra_volumes: |
                      - name: oke-fsspvc-awx-scratch
                        mountPath: /scratch
  tower_ee_extra_volume_mounts:  |
                      - name: oke-fsspvc-awx-scratch
                        mountPath: /scratch
```

![image](https://user-images.githubusercontent.com/13802820/121105799-c6f5f700-c7d2-11eb-85ba-39ecf80334f6.png)

**Comment by AndrewSav** [comment]
>  its actually mounted to the primary volume instead of the external one

What do you mean by that? FWIW it's working as expected for me. Also check your volume resource, volumes [do not have the mountPath field](https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/volume/).

**Comment by felipe4334** [comment]
@AndrewSav  I appreciate you SO MUCH for guiding me the right way. I was following AWX example on how to attach extra volumes but never stopped to realize that I could use other generic Kubernetes field. For anybody having issues in the future this is what the code I ended up doing.

Btw "mountPath:" did work. It's in the awx-operator I guess.

![image](https://user-images.githubusercontent.com/13802820/121371047-3bcc4c80-c90b-11eb-9bd9-750e8029aa87.png)

Previously /scratch would show under /dev/sda3 that's what I meant but "mounted to the primary volume"

```
  web_extra_volume_mounts: |
                      - name: oke-fsspvc-awx-scratch
                        persistentVolumeClaim:
                          claimName: oke-fsspvc-awx-scratch
                        mountPath: /scratch

```
