### ISSUE TITLE
Variable loadbalancer_annotations is ignored even when service_type is LoadBalancer

### ISSUE THREAD

**Issue by rantonmo** [ansible/tower-operator#381]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Variable loadbalancer_annotations is ignored even when service_type is LoadBalancer

##### ENVIRONMENT
* AWX version: 0.19.2
* Operator version: 0.10.0
* Kubernetes version: v1.19.11
* AWX install method: openshift

##### STEPS TO REPRODUCE

Using this CR:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: default
spec:
  service_type: LoadBalancer
  loadbalancer_port: 80
  loadbalancer_protocol: http
  loadbalancer_annotations: |
    environment: testing
    service.beta.kubernetes.io/azure-load-balancer-internal: true
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "voyager-subnet-aksnodes"
  service_labels: |
    environment: testing
```
The annotations configured by the operator are None:

```
# kubectl services
NAME                   TYPE           CLUSTER-IP    EXTERNAL-IP    PORT(S)             AGE
awx-operator-metrics   ClusterIP      10.0.31.41    <none>         8383/TCP,8686/TCP   64m
awx-postgres           ClusterIP      None          <none>         5432/TCP            118s
awx-service            LoadBalancer   10.0.185.63   20.82.85.243   80:31621/TCP        111s
kubernetes             ClusterIP      10.0.0.1      <none>         443/TCP             110m



# kubectl describe service awx-service
Name:                     awx-service
Namespace:                default
Labels:                   app.kubernetes.io/component=awx
                          app.kubernetes.io/managed-by=awx-operator
                          app.kubernetes.io/name=awx
                          app.kubernetes.io/operator-version=0.10.0
                          app.kubernetes.io/part-of=awx
                          environment=testing
Annotations:              <none>
Selector:                 app.kubernetes.io/component=awx,app.kubernetes.io/managed-by=awx-operator,app.kubernetes.io/name=awx
Type:                     LoadBalancer
IP Families:              <none>
IP:                       10.0.185.63
IPs:                      <none>
LoadBalancer Ingress:     20.82.85.243
Port:                     http  80/TCP
TargetPort:               8052/TCP
NodePort:                 http  31621/TCP
Endpoints:                10.244.1.9:8052
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age   From                Message
  ----     ------                  ----  ----                -------
  Warning  SyncLoadBalancerFailed  116s  service-controller  Error syncing load balancer: failed to ensure load balancer: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 412, RawError: {
  "error": {
    "code": "PreconditionFailed",
    "message": "Precondition failed.",
    "details": [
      {
        "code": "PreconditionFailedEtagMismatch",
        "message": "Etag provided in if-match header W/\"fff2d27a-7d2a-4fbb-a261-ecc34406e464\" does not match etag W/\"a9566774-8763-4f9a-aa17-789cf5378e88\" of resource /subscriptions/88faa96b-7603-4404-b28c-7ff6ada98495/resourceGroups/mc_rsg-voyager_aksdns-voyager_westeurope/providers/Microsoft.Network/loadBalancers/kubernetes in NRP data store."
      }
    ]
  }
}
  Normal  EnsuringLoadBalancer  111s (x2 over 2m)  service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   110s               service-controller  Ensured load balancer

```

##### EXPECTED RESULTS

Annotation field on the service should have the content of the variable

##### ACTUAL RESULTS

Annotation field value is <None>

##### ADDITIONAL INFORMATION

Looks like the problem is on the condition on line 14 of the file `roles/installer/templates/service.yaml.j2`:

```
{% if ingress_type | lower == 'loadbalancer' and loadbalancer_annotations %}
```

ingress_type var never can be loadbalancer, should it be service_type??

[possible patch](https://github.com/ansible/awx-operator/compare/devel...losarenio:patch-1)

##### AWX-OPERATOR LOGS

There is no error on the operator logs
