### ISSUE TITLE
K8S securityContext  / runAsNonRoot

### ISSUE THREAD

**Issue by m4r1u2** [ansible/tower-operator#383]
We have a policy of not running any containers as root. 
By default it looks like all awx and redis containers is starting as root and will fail/not start in our cluster do to default PSP in cluster. 

If i manually update deployment manifest with SecurityContext for container is looks like its working...
```
containers:
  - name: redis
    securityContext:
      runAsUser: 999
...
  - name: awx-ee
    securityContext:
      runAsUser: 1000
...
  - name: awx-web
    securityContext:
      runAsUser: 1000
      runAsGroup: 0
...
  - name: awx-task
    securityContext:
      runAsUser: 1000
      runAsGroup: 0
```

Running as root is general not a recommended practice. 

I also had to manually create file in container awx-task.:
```
bash-4.4$ touch /var/lib/awx/rsyslog/rsyslog.conf
```
log-output before fix.
Somehow this file was not generated.
```
rsyslogd: could not open config file '/var/lib/awx/rsyslog/rsyslog.conf': No such file or directory [v8.1911.0-7.el8 try https://www.rsyslog.com/e/2104 ]
rsyslogd: run failed with error -2104 (see rsyslog.h or try https://www.rsyslog.com/e/2104 to learn what that number means)
```

What about adding a SecurityContext or a general Spec in the crds to override this?
Or sync dockerimage + deployment with correct non-root user to allow read-write where its needed.
