### ISSUE TITLE
Publish bundle and catalog images for consumption via OLM

### ISSUE THREAD

**Issue by willhaines** [ansible/tower-operator#385]
##### ISSUE TYPE
 - Feature Request

##### SUMMARY
In our OKD cluster, we like to use the built-in OperatorHub functionality to keep track of our operators, rather than installing them with helm or direct manifests.

##### ENVIRONMENT
* AWX version: 19.2.0
* Operator version: 0.1.0
* Kubernetes version: 1.20
* AWX install method: openshift

##### DESIRED SOLUTION
I would like to be able to install the AWX operator on OKD/OpenShift by simply creating a CatalogSource that resembles the following 

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: awx-operator
  namespace: openshift-marketplace
spec:
  displayName: 'Ansible AWX Operator'
  image: "quay.io/ansible/awx-operator-catalog:latest"
  publisher: 'Ansible AWX Operator'
  sourceType: grpc
```
This could be implemented by executing [scripts/built.sh](https://github.com/ansible/awx-operator/blob/devel/scripts/build.sh) upon release, or simply adding steps to build+push `awx-operator-bundle` and `awx-operator-catalog` to [release.yaml](https://github.com/ansible/awx-operator/blob/devel/.github/workflows/release.yaml)

##### CURRENT ALTERNATIVES
Currently, I'm able to use [scripts/built.sh](https://github.com/ansible/awx-operator/blob/devel/scripts/build.sh) to build+push `awx-operator-bundle` and `awx-operator-catalog` containers to a private registry, then install using a CatalogSource as above. This is unfortunate as it requires me to manually keep track of updates and rebuild locally every time there is a new release.

##### ADDITIONAL INFORMATION
If you're amenable to making this change, I can work on a PR that implements it. However, my ability to test pushes against quay.io may be limited due to authentication.
