### ISSUE TITLE
Not able to write to NFS volume mount

### ISSUE THREAD

**Issue by felipe4334** [ansible/tower-operator#395]
Hello guys, I'm having an issue that seems to be easy to fix but somehow everything I try is not working. The NFS volumes are mounting properly but the awx user is not able to write to them only read. Even after running the pods in privileged mode I still can't write to the mount points. I tried using securityContext but AWX does not support it.
![image](https://user-images.githubusercontent.com/13802820/121926568-15901d80-cd0c-11eb-9958-5348131f733a.png)
![image](https://user-images.githubusercontent.com/13802820/121926724-41ab9e80-cd0c-11eb-8b2a-d3214511025f.png)

```
# storage.yml needs to be ran first
# database_import_secret.yml needs to be ran first as well
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  hostname: test
  old_postgres_configuration_secret: awx-old-postgres-configuration
  admin_email: test
  task_privileged: true
  projects_persistence: true
  projects_storage_class: oci
  projects_storage_size: 50gb
  projects_storage_access_mode: ReadWriteOnce
  projects_existing_claim: oke-ocipvc-awx-projects
  extra_volumes: |
                      - name: oke-fsspvc-awx-scratch
                        persistentVolumeClaim:
                          claimName: oke-fsspvc-awx-scratch
  ee_extra_volume_mounts:  |
                      - name: oke-fsspvc-awx-scratch
                        persistentVolumeClaim:
                          claimName: oke-fsspvc-awx-scratch
                        mountPath: /scratch
```

```
# Create Persistent Volume (PV) - For /scatch

apiVersion: v1
kind: PersistentVolume
metadata:
  name: oke-fsspv-awx-scratch
spec:
  storageClassName: oci-fss
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nosuid
  nfs:
    server: 10.50.132.5 #DNS names cant be used atm since pods are not able to resolve the dns
    path: "/inf_lower_awx_testing_scratch"
    readOnly: false

```

```
# Crate Persistent Volume Claim (PVC) - For /scratch

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oke-fsspvc-awx-scratch
  namespace: awx
spec:
  storageClassName: oci-fss
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # Although storage is provided here it is not used for FSS file systems
      storage: 10Gi
  volumeName: oke-fsspv-awx-scratch

```

**Comment by felipe4334** [comment]
![image](https://user-images.githubusercontent.com/13802820/121927073-a49d3580-cd0c-11eb-822d-c9343dc403d4.png)

**Comment by tchellomello** [comment]
@felipe4334 just to check something on your NFS share configuration. If you go to the actual host which exports this share and do:
```sh
$ chmod 777 /inf_lower_awx_testing_scratch
```
Then, try:
```sh
$ ls -lad /scratch
$ ls -laR /scratch
$ touch /scratch
```

Thanks!

**Comment by felipe4334** [comment]
@tchellomello This is all hosted on Oracle Cloud Kubernetes cluster I do not have access to ssh into the actual OKE host.

**Comment by felipe4334** [comment]
@tchellomello I created another normal linux pod on the cluster and that one is able to read and write to those NFS shares with no problems.

```
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: awx
spec:
  volumes:
    - name: oke-fsspvc-awx-scratch
      persistentVolumeClaim:
        claimName: oke-fsspvc-awx-scratch
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: oke-fsspvc-awx-scratch
```

**Comment by tchellomello** [comment]
@felipe4334 cool. So if you do the `touch`  command on that share, could you send us the output? What is the `effective user`  you are getting on this share? Is the NFS server mapping to `nobody`?

**Comment by felipe4334** [comment]
@tchellomello this is the output of touch
![image](https://user-images.githubusercontent.com/13802820/121941142-e7ffa000-cd1c-11eb-96c1-ac5fa81c4b9b.png)

What way would I be able to view the effective users and mapping, sorry for the dumb question

**Comment by tchellomello** [comment]
@felipe4334 can you do the same on your `nginx` testing pod? Please send also the other `ls`  output. 

For the `effective uid` you and do: `stat <FILENAME>`

**Comment by felipe4334** [comment]
![image](https://user-images.githubusercontent.com/13802820/121941862-c94dd900-cd1d-11eb-8cf4-5175d3e57943.png)

Let me spin up the nginx testing pod again

**Comment by felipe4334** [comment]
![image](https://user-images.githubusercontent.com/13802820/121942593-a839b800-cd1e-11eb-8761-320572197bf3.png)

The testing pod is letting me in as root so that might be why its working.
@tchellomello

**Comment by tchellomello** [comment]
@felipe4334 yup.. this is what I wanted to confirm. Now, since you got it working on this pod, what happens if you do:
```sh
$ mkdir /usr/share/nginx/html/testing_dir
$ chmod 777 /usr/share/nginx/html/testing_dir
```

Then destroy the testing pod and start the `awx` again. Once you have the awx running, you could do
```sh
$ ls -lad /scratch
$ ls -lad /scratch/testing_dir
$ touch /scratch/testing_dir/test-on-awx
$ ls -la /scratch/testing_dir/test-on-awx
```
Can you send that ^ for us?

**Comment by felipe4334** [comment]
![image](https://user-images.githubusercontent.com/13802820/121943785-eedbe200-cd1f-11eb-94de-3d5f56f0f0fe.png)

![image](https://user-images.githubusercontent.com/13802820/121949502-82181600-cd26-11eb-886f-75b2c9fcfa7d.png)

@tchellomello Sorry my cluster decided to not let AWX deploy for an hour.

**Comment by felipe4334** [comment]
How can I make the root nfs share have the same permissions as /scratch/testing_dir for all **new** files created

**Comment by tchellomello** [comment]
@felipe4334 thanks for providing all the details. Yes, we will need to address this at the `awx-operator`  level.

**Comment by tchellomello** [comment]
https://github.com/kubernetes/examples/issues/260 interesting (maybe via `InitContainer`)? I'll give a test on this stuff tonight

**Comment by felipe4334** [comment]
@tchellomello the issue seems to be happening with normal volume mounts as well not just NFS. I currently have " projects_existing_claim: oke-ocipvc-awx-projects" configured and when I try updating a project on AWX I get a Permissions denied error. I went into '/var/lib/awx' and can see that I do not have permissions to write to 'projects'
![image](https://user-images.githubusercontent.com/13802820/121954406-b5f63a00-cd2c-11eb-8dfc-f7cfdb695a66.png)


![image](https://user-images.githubusercontent.com/13802820/121954250-8ba47c80-cd2c-11eb-8c26-e3d8bf35f0ac.png)

**Comment by felipe4334** [comment]
@tchellomello Were you able to by any chance test InitContainer?

**Comment by tchellomello** [comment]
@felipe4334 I'll try to work on this tonight. In the meantime, I think this is related to https://github.com/ansible/awx-operator/issues/357#issuecomment-863732211. Can you test on your end to see if the `fsGroup` takes effect on the NFS share you have? According to some other k8s threads, it seems to not work, therefore, you will need to address this differently or we will have to extend the operator via `initContainer to change the permissions. There a few options we can explore.  Thanks!

**Comment by tchellomello** [comment]
So I tested a similar environment by creating a local NFS server on my environment and trying the `fsGroup` and as expected, it did not work. Basically these are the steps I followed:

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-testing
provisioner:  kubernetes.io/no-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-testing-nfs
spec:
  storageClassName: nfs-testing
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nosuid
  nfs:
    server: 192.168.111.46
    path: "/volume1/test-nfs-share"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-testing-nfs-claim
spec:
  storageClassName: nfs-testing
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: awx-testing-nfs
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-nfs
spec:
  ingress_type: none
  service_type: loadbalancer
  projects_existing_claim: awx-testing-nfs-claim
  projects_persistence: true
  web_resource_requirements:
    requests:
      cpu: 1m
      memory: 100Mi
    limits:
  task_resource_requirements:
    requests:
      cpu: 1m
      memory: 100Mi
  ee_resource_requirements:
    requests:
      cpu: 1m
      memory: 100Mi
```

Having said this, I have the `fsGroup` set however, still not able to write on that directory due to the NFS topology. `fsGroup` is still a good route to be followed, however, it does not apply for NFS shares. 

```sh
$  kubectl describe deploy awx-nfs                                                     15:07:36
Name:                   awx-nfs
Namespace:              default
CreationTimestamp:      Sat, 19 Jun 2021 14:56:58 -0400
[....SNIP...]
   awx-nfs-projects:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  awx-testing-nfs-claim
    ReadOnly:   false

$ kubectl get deploy/awx-nfs -o yaml  | kubectl neat
[....SNIP...]
      securityContext:
        fsGroup: 1000
[....SNIP...]
      - name: awx-nfs-projects
        persistentVolumeClaim:
          claimName: awx-testing-nfs-claim

kubectl iexec awx /bin/bash                                                               15:08:49
Namespace: default | Pod: ✔ awx-nfs-596f6cf8b7-lb4xq
Container: ✔ awx-nfs-web
bash-4.4$ ls -lahd /var/lib/awx/projects
d---------. 1 root root 14 Jun 19 18:43 /var/lib/awx/projects
bash-4.4$ df -h /var/lib/awx/projects
Filesystem                        Size  Used Avail Use% Mounted on
192.168.111.46:/volume1/test-nfs-share  3.5T  1.3T  2.3T  36% /var/lib/awx/projects
bash-4.4$ whoami
awx
bash-4.4$ id awx
uid=1000(awx) gid=0(root) groups=0(root)
bash-4.4$ touch /var/lib/awx/projects/testing
touch: cannot touch '/var/lib/awx/projects/testing': Permission denied
```
So one idea to address this problem would be something like this:

```diff
diff --git a/roles/installer/templates/deployment.yaml.j2 b/roles/installer/templates/deployment.yaml.j2
index 548bb06..28d78a1 100644
--- a/roles/installer/templates/deployment.yaml.j2
+++ b/roles/installer/templates/deployment.yaml.j2
@@ -33,7 +33,7 @@ spec:
       imagePullSecrets:
         - name: {{ image_pull_secret }}
 {% endif %}
-{% if bundle_ca_crt %}
+{% if bundle_ca_crt or projects_persistence|bool %}
       initContainers:
         - name: init
           image: '{{ init_container_image }}:{{ init_container_image_version }}'
@@ -42,15 +42,27 @@ spec:
             - /bin/sh
             - -c
             - |
+{% if bundle_ca_crt  %}
               mkdir -p /etc/pki/ca-trust/extracted/{java,pem,openssl,edk2}
               update-ca-trust
+{% endif %}
+{% if projects_persistence|bool %}
+              chmod 775 /var/lib/awx/projects
+              chgrp 1000 /var/lib/awx/projects
+{% endif %}
           volumeMounts:
+{% if bundle_ca_crt  %}
             - name: "ca-trust-extracted"
               mountPath: "/etc/pki/ca-trust/extracted"
             - name: "{{ meta.name }}-bundle-cacert"
               mountPath: /etc/pki/ca-trust/source/anchors/bundle-ca.crt
               subPath: bundle-ca.crt
               readOnly: true
+{% endif %}
+{% if projects_persistence|bool %}
+            - name: "{{ meta.name }}-projects"
+              mountPath: "/var/lib/awx/projects"
+{% endif %}
 {% endif %}
       containers:
         - image: '{{ redis_image }}:{{ redis_image_version }}'
@@ -283,8 +295,10 @@ spec:
       tolerations:
         {{ tolerations | indent(width=8) }}
 {% endif %}
+{% if projects_persistence|bool %}
       securityContext:
         fsGroup: 1000
+{% endif %}
       volumes:
 {% if bundle_ca_crt %}
         - name: "ca-trust-extracted"
```

Once the operator redeploys it, it should work as expected:

```sh
$ kubectl iexec awx /bin/bash                                                                   15:27:14
Namespace: default | Pod: ✔ awx-nfs-696dd649f5-zlqc4
Container: ✔ awx-nfs-web
bash-4.4$ df -h /var/lib/awx/projects/
Filesystem                        Size  Used Avail Use% Mounted on
192.168.111.46:/volume1/test-nfs-share  3.5T  1.3T  2.3T  36% /var/lib/awx/projects
bash-4.4$ whoami 
awx
bash-4.4$ id
uid=1000(awx) gid=0(root) groups=0(root),1000
bash-4.4$ touch /var/lib/awx/projects/testing-works-now
bash-4.4$ ls -la /var/lib/awx/projects/testing-works-now
-rw-rw-rw-. 1 awx root 0 Jun 19 19:23 /var/lib/awx/projects/testing-works-now
```

@felipe4334 can you give a shot on this approach? To make it easier I've published this test image for you at quay.io/tchellomello/awx-operator:fsGroup . Please let us know. Thanks

@shanemcd @rooftopcellist  @Spredzy  what your guys thoughts on this approach?

**Comment by felipe4334** [comment]
@tchellomello your approach worked like a charm. Would it be possible to do the same for ee_extra_volume_mounts, task_extra_volume_mounts and web_extra_volume_mounts? Thanks!
![image](https://user-images.githubusercontent.com/13802820/122690279-93fe2b00-d1f6-11eb-8ec7-aca963bd630e.png)
![image](https://user-images.githubusercontent.com/13802820/122690283-995b7580-d1f6-11eb-8dbc-1eecac922a3c.png)

I see that deployment.raml.j2 just gets the value the value of web_extra_volume_mounts and other mounts passed directly. Would it be possible to just do something similar on those mount even though we don't know what we don't know  the mountPath is going to be. For example /scratch /awx-shared /test-share?

```
{% if web_extra_volume_mounts -%}         
{{ web_extra_volume_mounts | indent(width=12, indentfirst=True) }}
{% endif %}
```

**Comment by felipe4334** [comment]
Thank you for providing the code. I was able to modify it and add permissions fixes for my other custom volume mounts.
```
{% if bundle_ca_crt or projects_persistence|bool %}
      initContainers:
        - name: init
          image: '{{ init_container_image }}:{{ init_container_image_version }}'
          spec:
            - /bin/sh
            - -c
            - |
{% if bundle_ca_crt  %}
               mkdir -p /etc/pki/ca-trust/extracted/{java,pem,openssl,edk2}
               update-ca-trust
{% endif %}
{% if projects_persistence|bool %}
               chmod 775 /var/lib/awx/projects
               chgrp 1000 /var/lib/awx/projects
{% endif %}
               chmod 775 /scratch
               chgrp 1000 /scratch
               chmod 775 /awx-shared
               chgrp 1000 /awx-shared
          volumeMounts:
{% if bundle_ca_crt  %}
            - name: "ca-trust-extracted"
              mountPath: "/etc/pki/ca-trust/extracted"
            - name: "{{ meta.name }}-bundle-cacert"
              mountPath: /etc/pki/ca-trust/source/anchors/bundle-ca.crt
              subPath: bundle-ca.crt
              readOnly: true
{% endif %}
{% if projects_persistence|bool %}
            - name: "{{ meta.name }}-projects"
              mountPath: "/var/lib/awx/projects"
{% endif %}
            - name: "{{ meta.name }}-scratch"
              mountPath: "/scratch"
            - name: "{{ meta.name }}-shared"
              mountPath: "/awx-shared"
```

**Comment by tchellomello** [comment]
Thanks for the feedback @felipe4334 We are still studying the best route to address this, but your feedback is very appreciated and we are happy it helped you.

**Comment by tchellomello** [comment]
> I see that deployment.raml.j2 just gets the value the value of web_extra_volume_mounts and other mounts passed directly. Would it be possible to just do something similar on those mount even though we don't know what we don't know the mountPath is going to be. For example /scratch /awx-shared /test-share?
> 
> ```
> {% if web_extra_volume_mounts -%}         
> {{ web_extra_volume_mounts | indent(width=12, indentfirst=True) }}
> {% endif %}
> ```

@felipe4334  I've included this ability on the PR https://github.com/ansible/awx-operator/pull/413. :+1:

**Comment by felipe4334** [comment]
@tchellomello I deployed devel version of awx-operator(kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml) and tried using init_container but it did not work, the init container was not even created with my deployment.

awx.yml
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  hostname: awx.test.com
  admin_email: test@test.com
  projects_persistence: true
  projects_storage_class: oci
  projects_storage_size: 50gb
  projects_storage_access_mode: ReadWriteOnce
  projects_existing_claim: oke-ocipvc-awx-projects
  extra_volumes: |
    - name: oke-fsspvc-awx-scratch
      persistentVolumeClaim:
        claimName: oke-fsspvc-awx-scratch
  ee_extra_volume_mounts: |
    - name: oke-fsspvc-awx-scratch
      mountPath: /scratch
  task_extra_volume_mounts: |
    - name: oke-fsspvc-awx-scratch
      mountPath: /scratch
  web_extra_volume_mounts: |
    - name: oke-fsspvc-awx-scratch
      mountPath: /scratch
  init_container_extra_volume_mounts: |
    - name: oke-fsspvc-awx-scratch
      mountPath: /scratch
  init_container_extra_commands: |
    chmod 775 /scratch
    chgrp 1000 /scratch
    date >> /scratch/been_here
```
Init container is not even starting.
![image](https://user-images.githubusercontent.com/13802820/129110016-e3a5968a-c43d-44b4-aab6-164c7d74e3df.png)
