### ISSUE TITLE
Ingress TLS not working (K8S rancher)

### ISSUE THREAD

**Issue by craph** [ansible/tower-operator#399]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I'm unable to configure correctly the ingress for HTTPS in AWX.

What am I doing wrong ?

##### ENVIRONMENT
* AWX version: 19.2.0
* Operator version: 0.10.0
* Kubernetes version: Kubernetes v1.20.6 
* AWX install method: k8s rancher

##### STEPS TO REPRODUCE

1. Create a secret certificate that contains private key and certificate with name "awx-certificate" (I'm using certificate issued by my entreprise CA / custom CA)
2. Create this yaml file : 
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  ingress_type: ingress
  ingress_tls_secret: awx-certificate
  hostname: awx.10.81.110.118.nip.io
  postgres_storage_class: longhorn
```
3. Run `kubectl apply -f myfile`

##### EXPECTED RESULTS

I want to be able to configure Ingress to use my tls secret configured in rancher and applied to my awx instance.

##### ACTUAL RESULTS

In my browser when I go to https://awx.10.81.110.118.nip.io and check the certificate I don't see mine BUT I see 
![image](https://user-images.githubusercontent.com/14820052/122047704-b9e39400-cde0-11eb-88ec-2b89e51dbf05.png)

##### ADDITIONAL INFORMATION

I don't know if my issue is linked to this one : https://github.com/ansible/awx-operator/issues/376
