### ISSUE TITLE
Add possibility to define "loadBalancerIP"

### ISSUE THREAD

**Issue by marcoatenway** [ansible/tower-operator#418]
Many production environments are using predefined public IP which are used to make load-balancers accessible from the internet on a persist Address, even if the cluster gets redeployed for any reason.

Beside the already available solution using annotations, there is also the "loadBalancerIP" which some hosters allow to set to configure a pre-registered public ip in a Loadbalancer object.
(see: https://kubernetes.io/docs/concepts/services-networking/service/)

Currently awx-operator does not support this setting.

To make use of this important feature, the possibility to set the public IP in the AWX Resource should be added.

**Comment by marcoatenway** [comment]
i've implemented the change but i'am unable to test it correctly to open a PR.
https://github.com/marcoatenway/awx-operator/tree/feature_loadbalancerIP

**Comment by tchellomello** [comment]
@marcoatenway could you provide YAML example of how an entry would look like?

**Comment by marcoatenway** [comment]
either:
```yaml
---
spec:
  ...
  service_type: LoadBalancer
  loadbalancer_protocol: https
  loadbalancer_loadBalancerIP: 198.51.100.23
  loadbalancer_port: 443
```

or

```yaml
---
spec:
  ...
  service_type: LoadBalancer
  loadbalancer_protocol: https
  loadbalancer_specs: |
    loadBalancerIP: 198.51.100.23
  loadbalancer_port: 443
```

the last one would be more flexible for other possible custom specs.
