### ISSUE TITLE
Ingress Path / Causes 404 when running eks + alb in aws

### ISSUE THREAD

**Issue by MrBones757** [ansible/tower-operator#455]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The default ingress config uses / for the path, when running in AWS/EKS using the aws-load-balancer-controller, it adds a listener with a rule:

IF
Host is awx.domain
Path is /

Any requests to not / paths (such as those fetching static resources) end in a 404.

##### ENVIRONMENT
* AWX version: 19.2.2
* Operator version: 0.12.0
* Kubernetes version: 1.19.x
* AWX install method: operator on eks

##### STEPS TO REPRODUCE

Provision awx into the following ingress annotations:

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  # Base Configuration
  replicas: 1
  # Connction Info
  hostname: <host>
  ingress_type: Ingress
  service_type: ClusterIP
  ingress_annotations: |
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/tags: Name=k8s-awx-ingress
    alb.ingress.kubernetes.io/inbound-cidrs: "<cidr>"
    alb.ingress.kubernetes.io/group.name: "k8s-awx-ingress"
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: <arn>
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-TLS-1-2-2017-01
```

##### EXPECTED RESULTS

AWX Deploys and is accessible via URL

##### ACTUAL RESULTS

AWX resolves by URL by all static content fails to load with 404s

##### ADDITIONAL INFORMATION

Solution:
Removing / from the ingress removes this rule from the ALB and allows awx to function.
Idea would be to add the ingress path as a configurable option, defaulting to / which would allow us in this case to use an empty string which removes the alb rule (verified manually)

##### AWX-OPERATOR LOGS
N/A
