### ISSUE TITLE
Improve documentation with additional steps to add TLS certs to a minikube style setup

### ISSUE THREAD

**Issue by karezza** [ansible/tower-operator#468]
##### ISSUE TYPE
 - Enhancement Request

##### SUMMARY
Existing AWX Operator getting started installation documentation mentions some variables associated with setting up TLS certificates, but does not give an example of how to get valid certificates working, or provided the necessary steps to get valid certificates working.  -- Given that the basic install is minikube, please provide the additional few steps needed to get certificates working and via a connection coming in from outside (e.g. to the IP of the VM, not an internal ip associated with minikube)

##### ENVIRONMENT
* AWX version: latest
* Operator version: latest
* Kubernetes version: minikube
* AWX install method: AWX Operator

##### STEPS TO REPRODUCE
- Install VM with clean Linux OS
- Install docker & minikube
- Follow provided steps to get AWX installed using AWX Operator
- Attempt to get certs working using information provided in the "Network and TLS Configuration" section of the documentation

##### EXPECTED RESULTS
- AWX Operator installed and AWX installed and running **with valid certificates**

##### ACTUAL RESULTS
- AWX Operator intalled and AWX installed but **unable to get valid certificates installed**

##### TROUBLESHOOTING
- Created a tls secret:  kubectl create secret tls itsawx-tls-secret --cert=certs/tls.crt --key=certs/tls.key
- Performed the following:  kubectl expose deployment itsawx --port 443
- Based on the documentation I have ended up with the following configuration to try and get provided TLS certs to work:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: itsawx
spec:
  service_type: LoadBalancer
  loadbalancer_protocol: https
  loadbalancer_port: 443
  loadbalancer_annotations: |
    environment: testing
  service_labels: |
    environment: testing
  ingress_type: ingress
  ingress_annotations: |
    environment: testing
  ingress_tls_secret: secret/itsawx-tls-secret
  hostname: itsawx.mydomain.com
```

**Comment by shanemcd** [comment]
Thank you for doing the hard work here. If you're able to open a PR that'd be great.

**Comment by karezza** [comment]
I would upload a suggested fix except that I wasn't able to figure out how to get it to work...

**Comment by karezza** [comment]
With minkube / kubernetes the certificates can be handled in a standardized way dealing with the SSL encoding/decoding outside of the app and the app need only implement the usual 80.  A reverse proxy can be used along with hostnames allowing for many apps which actually use different ports behind the scene to all appear to use 443.

What is unusual about the AWX install is that it is setting its own custom variables to pass the needed information along to minikube / kubernetes and this is where I could use just a little more help or better yet an example of how to set those variables so that the website can be reached from outside the host system.

**Comment by karezza** [comment]
I'm not positive at the moment, but I think it may be a requirement with minikube that you add a port forward rule to the firewall of the host system which forwards requrests on to minikube's internal ip such as:

```
sudo firewall-cmd --permanent --add-forward-port=port=443:proto=tcp:toport=443:toaddr=<minikube ip>
sudo firewall-cmd --reload
```

**Comment by karezza** [comment]
Still testing, but it appears the needed steps are:
1. Create a TLS secret with the website certs
```
minikube kubectl -- create secret tls awx-secret-tls \
      --cert=/home/pathto/certs/tls.crt \
      --key=/home/pathto/certs/tls.key
```
2. A possible CRD is the following:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  service_labels: |
    environment: testing
  ingress_type: ingress
  ingress_annotations: |
    environment: testing
  ingress_tls_secret: awx-secret-tls
  hostname: awx.domain.net
```
3. Enable port & forward port to minikube port (not sure if this is the right technique, but it works):
```
sudo firewall-cmd --permanent --add-port=443/tcp
sudo firewall-cmd --permanent --add-forward-port=port=443:proto=tcp:toport=443:toaddr=`minikube ip`
sudo firewall-cmd --reload
```

I will submit a PR with a documentation update.
