### ISSUE TITLE
pg_restore No connection to the server

### ISSUE THREAD

**Issue by mkayontour** [ansible/tower-operator#482]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I tried to migrate the data from the old awx docker environment and the operator tries to migrate the data before the postgres container is created. 

The error message is `pg_restore: error: could not execute query: no connection to the server`

##### ENVIRONMENT
* AWX version: 19.
* Operator version: 12
* Kubernetes version:  
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-13T02:40:46Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7+rke2r2", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-26T04:47:27Z", GoVersion:"go1.15.8b5", Compiler:"gc", Platform:"linux/amd64"}
```

##### AWX-OPERATOR LOGS
Excerpt
```
no connection to the server", "Command was: ALTER TABLE ONLY public.main_workflowjobtemplatenode_credentials", "    ADD CONSTRAINT main_workflowjobtemp_workflowjobtemplaten_b91efe86_fk_main_work FOREIGN KEY (workflowjobtemplatenode_id) REFERENCES public.main_workflowjobtemplatenode(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4884; 2606 29339 FK CONSTRAINT oauth2_provider_grant oauth2_provider_gran_application_id_81923564_fk_main_oaut awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.oauth2_provider_grant", "    ADD CONSTRAINT oauth2_provider_gran_application_id_81923564_fk_main_oaut FOREIGN KEY (application_id) REFERENCES public.main_oauth2application(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4885; 2606 30860 FK CONSTRAINT oauth2_provider_grant oauth2_provider_grant_user_id_e8f62af8_fk_auth_user_id awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.oauth2_provider_grant", "    ADD CONSTRAINT oauth2_provider_grant_user_id_e8f62af8_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4888; 2606 30948 FK CONSTRAINT oauth2_provider_refreshtoken oauth2_provider_refr_access_token_id_775e84e8_fk_main_oaut awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.oauth2_provider_refreshtoken", "    ADD CONSTRAINT oauth2_provider_refr_access_token_id_775e84e8_fk_main_oaut FOREIGN KEY (access_token_id) REFERENCES public.main_oauth2accesstoken(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4886; 2606 29358 FK CONSTRAINT oauth2_provider_refreshtoken oauth2_provider_refr_application_id_2d1c311b_fk_main_oaut awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.oauth2_provider_refreshtoken", "    ADD CONSTRAINT oauth2_provider_refr_application_id_2d1c311b_fk_main_oaut FOREIGN KEY (application_id) REFERENCES public.main_oauth2application(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4887; 2606 30899 FK CONSTRAINT oauth2_provider_refreshtoken oauth2_provider_refreshtoken_user_id_da837fce_fk_auth_user_id awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.oauth2_provider_refreshtoken", "    ADD CONSTRAINT oauth2_provider_refreshtoken_user_id_da837fce_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4919; 2606 31018 FK CONSTRAINT social_auth_usersocialauth social_auth_usersocialauth_user_id_17d28448_fk_auth_user_id awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.social_auth_usersocialauth", "    ADD CONSTRAINT social_auth_usersocialauth_user_id_17d28448_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4920; 2606 31072 FK CONSTRAINT sso_userenterpriseauth sso_userenterpriseauth_user_id_5982f0ef_fk_auth_user_id awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.sso_userenterpriseauth", "    ADD CONSTRAINT sso_userenterpriseauth_user_id_5982f0ef_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4608; 2606 16428 FK CONSTRAINT taggit_taggeditem taggit_taggeditem_content_type_id_9957a03c_fk_django_co awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.taggit_taggeditem", "    ADD CONSTRAINT taggit_taggeditem_content_type_id_9957a03c_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: from TOC entry 4609; 2606 16433 FK CONSTRAINT taggit_taggeditem taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id awx", "pg_restore: error: could not execute query: no connection to the server", "Command was: ALTER TABLE ONLY public.taggit_taggeditem", "    ADD CONSTRAINT taggit_taggeditem_tag_id_f4f5b767_fk_taggit_tag_id FOREIGN KEY (tag_id) REFERENCES public.taggit_tag(id) DEFERRABLE INITIALLY DEFERRED;", "", "", "pg_restore: error: could not execute query: no connection to the server", "Command was: --", "-- PostgreSQL database dump complete", "--", "", "pg_restore: warning: errors ignored on restore: 949"], "stdout": "", "stdout_lines": []}
```

### Kubernetes Config

```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/container-data"
---
apiVersion: v1
kind: Secret
metadata:
  name: custom-admin-password
  namespace: default
stringData:
  password: m*****
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: default
stringData:
  secret_key: S****
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-old-postgres-configuration
  namespace: default
stringData:
  host: "10.1.0.144"
  port: "5432"
  database: "awx"
  username: "awx"
  password: "a****"
  sslmode: "prefer"
  type: "unmanaged"
type: Opaque
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  ingress_type: none
  old_postgres_configuration_secret: awx-old-postgres-configuration
  postgres_storage_class: manual
  admin_password_secret: custom-admin-password
```
