### ISSUE TITLE
ansible.cfg located in project dir not working with inventory sync from git when vault_identity_list is set

### ISSUE THREAD

**Issue by Elyytscha** [ansible/tower-operator#488]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
It seems like its not possible to use ansible.cfg directly located in the ansible git repo within awx

##### ENVIRONMENT
* AWX version:19.2.2
* Operator version: 0.12.0
* Kubernetes version: openshift 4.7.19
* AWX install method: operator on openshift

##### STEPS TO REPRODUCE

setup awx.
configure 1 project with 1 inventory source from git
in the git repo which is configured is a ansible.cfg located with the following:
```
...
vault_identity_list=~/.vault_pass,~/.vault_pass_test
...
```

sync the project, error:
![image](https://user-images.githubusercontent.com/10408311/128146991-6f81fb90-f8f0-47fb-af05-f51890baa73b.png)

what i tried to do is mount those files via volumes into the pod:
/home/runner/.vault_pass
/home/runner/.vault_pass_test
is mounted in container

via this:
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
...
  extra_volumes: |
          - name: vault-pass
            secret:
              secretName: awx-int-vaultpass
              items:
                - key: .vault_pass
                  path: .vault_pass
          - name: vault-pass-test
            secret:
              items:
                - key: .vault_pass_test
                  path: .vault_pass_test
              secretName: awx-int-vaultpass
  ee_extra_volume_mounts: |
    - name: vault-pass-test
      mountPath: /home/runner/.vault_pass_test
      subPath: .vault_pass_test
    - name: vault-pass
      mountPath: /home/runner/.vault_pass
      subPath: .vault_pass

  task_extra_volume_mounts: |
    - name: vault-pass-test
      mountPath: /home/runner/.vault_pass_test
      subPath: .vault_pass_test
    - name: vault-pass
      mountPath: /home/runner/.vault_pass
      subPath: .vault_pass
```

##### EXPECTED RESULTS

i expect a solution to set in awx a vault to checkout the inventory source, or to be able to mount the vault pass files into the container.
##### AWX-OPERATOR LOGS
[awx-operator-79bc95f78-ph2ql-awx-operator.log](https://github.com/ansible/awx-operator/files/6929741/awx-operator-79bc95f78-ph2ql-awx-operator.log)

**Comment by wenottingham** [comment]
What is your goal? Do you truly want vaulted, encrypted, content to be decrypted and stored as plaintext in the API and fully viewable in the UI?

**Comment by wenottingham** [comment]
Also, those knobs (ee_extra...) are for mounting in the control plane EE. To modify the EE used for inventory updates, you'd modify the podspec.

**Comment by VasseurLaurent** [comment]
Hello @Elyytscha , 

I have faced the same issue while I tried to load a full inventory including vault files within AWX. 
Like @wenottingham  said, it is possible to do that but your password decrypted and readable on AWX UI/API. 

As a workaround, what I have done is that I have moved all my vault files to a dedicated ``secrets`` folder. Because AWX is not able to parse this folder, you won't have any error message (it is like hiding vault password to AWX when creating the inventory). This how my inventory looks like now : 

```
├── prod
│   ├── group_vars
│   ├── host_vars
│   ├── hosts
│   └── secrets => all prod secrets are here
└── stage
    ├── group_vars
    ├── host_vars
    ├── hosts
    └──  secrets => all stage secrets are here
``` 

In my inventory, if needed each variable will call a vault variable, for example : 
```
password = "{{ vault_password }}"
```

To finish you need to call these secrets in your playbook , for example : 

```
- hosts: "all"
  tasks:
    - name: Include secrets
      include_vars:
        dir: "../inventories/yourenvironment/secrets"
```

Then if you delete your ansible.cfg file (at least the part that specify your vault file) , and create a AWX credentials with your vault password , you will be able to create your inventory and launch template. 


I hope these information will be useful

**Comment by Elyytscha** [comment]
well the awx api/ui is protected by authentication, so where is the problem to see those credentials if you can login into awx and have the ldap groups for administrate awx?

i think you dont understand the problem, our inventorys looking like this:

```
all:
  children:
    hosts:
      hosts:
        awx71.prod.domain.com:
        awx71.test.domain.com:
    prod:
      hosts:
        awx71.prod.domain.com:
        awx@awx71.prod.domain.com:
        awx-config@awx71.prod.domain.com:
    test:
      hosts:
        awx71.test.domain.com:
        awx@awx71.test.domain.com:
        awx-config@awx71.test.domain.com:
        
    awx:
      hosts:
        awx71.prod.domain.com:
        awx@awx71.prod.domain.com:
        awx71.test.domain.com:
        awx@awx71.test.domain.com:
      vars:
        app_role: awx  
    awx-config:
      hosts:
        awx71.prod.domain.com:
        awx-config@awx71.prod.domain.com:
        awx71.test.domain.com:
        awx-config@awx71.test.domain.com:
      vars:
        app_role: awx-config
```

there is no encrypted data in our inventorys. but because our ansible.cfg, located in all of our (86!!) ansible repos has this line:
```
vault_identity_list=~/.vault_pass,~/.vault_pass_test
``` 
the inventory sync in awx wants this files to exist. in our deployment with docker compose vm based we where able to solve it like this:

```
  awx_task:
    image: "ansible/awx_task:${TAG:-latest}"
    user: root
    restart: always
    depends_on:
      - redis
      - memcached
      - awx_web
    env_file: ${ENVIRONMENT:-local.env}
    volumes:
...
      - "{{ docker_compose_systemd_service.project_src }}/etc/tower/.vault_pass:/var/lib/awx/.vault_pass:ro"
      - "{{ docker_compose_systemd_service.project_src }}/etc/tower/.vault_pass_test:/var/lib/awx/.vault_pass_test:ro"
...
```
we mount the secrets for our vaults in this location, so the awx_task container was able to pick them up, so the inventory sync started working.

we try the same thing with the operator but we dont get it to work

**Comment by Elyytscha** [comment]
> Also, those knobs (ee_extra...) are for mounting in the control plane EE. To modify the EE used for inventory updates, you'd modify the podspec.

well well well, so i need to mount our vault_pass files in this pod spec inside awx? did i understand this correctly?
![image](https://user-images.githubusercontent.com/10408311/128870350-b62cda1f-78e3-4c47-9f7f-5eceed8882f2.png)

**Comment by Elyytscha** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx-int
spec:
  containers:
    - image: 'quay.io/ansible/awx-ee:0.5.0'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      volumeMounts:
        - mountPath: "/var/run/secrets/vault/"
          name: vault-pass
          readOnly: true
      lifecycle:
        postStart:
          exec:
            command:
              - /bin/sh
              - -c
              - cp -a /var/run/secrets/vault/..data/vault_pass /home/runner/.vault_pass && cp -a /var/run/secrets/vault/..data/vault_pass_test /home/runner/.vault_pass_test
  volumes:
    - name: vault-pass
      secret:
        secretName: awx-int-vaultpass
```
yep, with this the inventory sync is working, thanks a ton!
