### ISSUE TITLE
init_container not working 

### ISSUE THREAD

**Issue by felipe4334** [ansible/tower-operator#496]
@tchellomello I deployed devel version of awx-operator(kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/devel/deploy/awx-operator.yaml) and tried using init_container but it did not work, the init container was not even created with my deployment.

awx.yml
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  hostname: awx.test.com
  admin_email: test@test.com
  projects_persistence: true
  projects_storage_class: oci
  projects_storage_size: 50gb
  projects_storage_access_mode: ReadWriteOnce
  projects_existing_claim: oke-ocipvc-awx-projects
  extra_volumes: |
    - name: oke-fsspvc-awx-scratch
      persistentVolumeClaim:
        claimName: oke-fsspvc-awx-scratch
  ee_extra_volume_mounts: |
    - name: oke-fsspvc-awx-scratch
      mountPath: /scratch
  task_extra_volume_mounts: |
    - name: oke-fsspvc-awx-scratch
      mountPath: /scratch
  web_extra_volume_mounts: |
    - name: oke-fsspvc-awx-scratch
      mountPath: /scratch
  init_container_extra_volume_mounts: |
    - name: oke-fsspvc-awx-scratch
      mountPath: /scratch
  init_container_extra_commands: |
    chmod 775 /scratch
    chgrp 1000 /scratch
    date >> /scratch/been_here
```
Init container is not even starting.
![image](https://user-images.githubusercontent.com/13802820/129110016-e3a5968a-c43d-44b4-aab6-164c7d74e3df.png)
