### ISSUE TITLE
A deploy demo on AWS with EKS and Route53

### ISSUE THREAD

**Issue by sk-cho-a** [ansible/tower-operator#506]
This is a [good demo](https://asciinema.org/a/416946) to install AWX on minikube.

But for production as install on AWS, there are many things to integrate.

# Load Balancer

The AWX document shows a load balancer example:

    ---
    spec:
      ...
      service_type: LoadBalancer
      loadbalancer_protocol: https
      loadbalancer_port: 443
      loadbalancer_annotations: |
        environment: testing
      service_labels: |
        environment: testing

I tried to run it in an EKS cluster, it created a classic type load balancer. If use NLB, can I choose LB type on AWS?

# Ingress

And, about ingress, its example is

    ---
    spec:
      ...
      ingress_type: ingress
      hostname: awx-demo.example.com
      ingress_annotations: |
        environment: testing

Is it necessary to install the ingress first then run this apply?

I didn't find a `service` type in its [manifest](https://raw.githubusercontent.com/ansible/awx-operator/0.13.0/deploy/awx-operator.yaml), but after apply the demo got an `awx-demo-service` with classic LB.
If need to set the service name to ingress(or AWX-operator do it?), is it create an ingress and set the name to it to ensure the service deployment?

# TLS

The third, about certificate, it provides

    ---
    spec:
      ...
      ldap_cacert_secret: <resourcename>-custom-certs
      bundle_cacert_secret: <resourcename>-custom-certs

There are 2 options:

- Use [cert-manager](https://cert-manager.io/)
- Use [AWS Certificate Manager](https://aws.amazon.com/certificate-manager/)

For both of these 2 types, does it need to create a CA first, the set the value to `bundle_cacert_secret`?

---

If integrate with real world cloud infrastructure automatically, about the install order, it seems something must be created first in AWS. Then set the necessary values to the `awx-operator` configuration.

Since it's a full customized `kind: AWX` resource, it's difficult to deploy as normal Kubernetes way. Is there a clear way for AWS?

**Comment by sk-cho-a** [comment]
@tchellomello Could you check it? Thank you.

**Comment by daenney** [comment]
For AWS, you need [the (A)LB controller on your cluster](https://kubernetes-sigs.github.io/aws-load-balancer-controller/), and then on the CRD:

```yaml
  tower_hostname: <the hostname your AWX should be reachable on>
  tower_ingress_annotations: |
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
  tower_ingress_type: Ingress
  tower_ingress_path: "/*"
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_route_tls_termination_mechanism: Edge
```

(drop the `tower_` prefixes if you're using operator v0.10+)

When using the (A)LB controller, you don't need to specify the cert for use with the ingress if you've issued it using ACM. The controller will find and use the right ACM cert itself.

**Comment by sk-cho-a** [comment]
@daenney Thank you very much for your answer.
I still have these questions:

- Isn't it necessary to add `service_type: LoadBalancer` to the spec if use ALB? I found the default service type is ClusterIP.
- `The controller will find and use the right ACM cert itself` -- Doesn't it need to add the created ACM's arn [alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:xxxx:certificate/xxxxxx](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/tasks/ssl_redirect/) to the `ingress_annotations`?
- From the [Load Balancer Controller Installation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/), it needs to setup a role for service account. Isn't it necessary to add the role arn to [service_account_annotations](https://github.com/ansible/awx-operator#service-account)?

**Comment by daenney** [comment]
> @daenney Thank you very much for your answer.
> I still have these questions:
> 
>     * Isn't it necessary to add `service_type: LoadBalancer` to the spec if use ALB? I found the default service type is ClusterIP.

Yes.

> 
>     * `The controller will find and use the right ACM cert itself` -- Doesn't it need to add the created ACM's arn [alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:xxxx:certificate/xxxxxx](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/tasks/ssl_redirect/) to the `ingress_annotations`?

You can, but you don't have to. See https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/cert_discovery/.

> 
>     * From the [Load Balancer Controller Installation](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/deploy/installation/), it needs to setup a role for service account. Isn't it necessary to add the role arn to [service_account_annotations](https://github.com/ansible/awx-operator#service-account)?

No. The ALB controller needs its own service account which lets it bind an IAM policy in AWS, so that it may create E|C|ALBs. The ALB controller's service account needs a role ARN, not the AWX operator service account. The AWX operator doesn't create the ALB, it just creates an ingress resource.

**Comment by sk-cho-a** [comment]
@daenney 

Do I need to deploy an ingress by myself? Here is what I deployed.

After deployed the awx-demo.yaml

```
    ---
    apiVersion: awx.ansible.com/v1beta1
    kind: AWX
    metadata:
      name: awx-demo
    spec:
      service_type: LoadBalancer
      hostname: awx.mydomain.com
      ingress_annotations: |
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        kubernetes.io/ingress.class: alb
      ingress_type: Ingress
      ingress_path: "/*"
      loadbalancer_port: 80
      loadbalancer_protocol: http
      route_tls_termination_mechanism: Edge
```

I also deployed an ingress to find the generated `awx-demo-service` service.

```
    # ingress.yaml
    ---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: awx
      annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
    spec:
      rules:
        - host: awx.mydomain.com
          http:
            paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: awx-demo-service
                    port:
                      name: http
```

When I check the ingress, I found two, why?

```
    $ kubectl get ing -A
    NAMESPACE   NAME              CLASS    HOSTS                  ADDRESS   PORTS   AGE
    default     awx               <none>   awx.mydomain.com                 80      18s
    default     awx-demo-ingress  <none>   awx.mydomain.com                 80      37s
```

**Comment by daenney** [comment]
You do not deploy an ingress. The AWX operator does it for you. Since you named your AWX `awx-demo`, it automatically created the `awx-demo-ingress` for you.

**Comment by sk-cho-a** [comment]
@daenney 
After a long time waiting, I redeployed the application again. This time the storage class issue happened.
Since I'm deploying the AWX on AWS, the default storage class gp2 can't work well because it needs ReadWriteMany, so I'm using [EFS](https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html) as sc.

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-12302048208123
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning" # optional

$ kubectl get storageclass
NAME            PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
efs-sc          efs.csi.aws.com         Delete          Immediate              false                  2d18h
```

I deployed AWX as

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  ...
  projects_persistence: true
  projects_storage_class: efs-sc
  postgres_storage_class: efs-sc
```

The resources:

```
$ kubectl get pvc
NAME                          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
awx-demo-projects-claim        Bound    pvc-40230231-4fba-4e08-b847-10ashjfdalas   20Gi       RWX            efs-sc         2m29s
postgres-awx-demo-postgres-0   Bound    pvc-01239812-bcf4-4a40-b5c7-1lafdjsaaals   8Gi        RWO            efs-sc         14m

$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS   REASON   AGE
pvc-40230231-4fba-4e08-b847-10ashjfdalas   20Gi       RWX            Delete           Bound    default/awx-demo-projects-claim        efs-sc                  6s
pvc-01239812-bcf4-4a40-b5c7-1lafdjsaaals   8Gi        RWO            Delete           Bound    default/postgres-awx-demo-postgres-0   efs-sc                  14m
```

Some AWX pods can't run successfully.

```
$ kubectl get po
NAME                            READY   STATUS                  RESTARTS   AGE
awx-demo-11a1111111-1abcd        0/4     Init:CrashLoopBackOff   4          2m54s
awx-demo-postgres-0              0/1     CrashLoopBackOff        8          17m
awx-operator-849b7d7d9d-8vnmq   1/1     Running                 0          18m
```

Their events

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  8m38s                   default-scheduler  Successfully assigned default/awx-demo-11a1111111-1abcd to ip-10-123-45-123.us-east-1.compute.internal
  Normal   Pulling    8m37s                   kubelet            Pulling image "quay.io/centos/centos:8"
  Normal   Pulled     8m34s                   kubelet            Successfully pulled image "quay.io/centos/centos:8" in 2.443279328s
  Normal   Created    7m8s (x5 over 8m34s)    kubelet            Created container init
  Normal   Started    7m8s (x5 over 8m34s)    kubelet            Started container init
  Normal   Pulled     7m8s (x4 over 8m33s)    kubelet            Container image "quay.io/centos/centos:8" already present on machine
  Warning  BackOff    3m31s (x25 over 8m32s)  kubelet            Back-off restarting failed container

Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  24m (x2 over 24m)     default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         24m                   default-scheduler  Successfully assigned default/awx-demo-postgres-0 to ip-10-123-45-123.us-east-1.compute.internal
  Normal   Pulled            23m (x5 over 24m)     kubelet            Container image "postgres:12" already present on machine
  Normal   Created           23m (x5 over 24m)     kubelet            Created container postgres
  Normal   Started           23m (x5 over 24m)     kubelet            Started container postgres
  Warning  BackOff           4m28s (x94 over 24m)  kubelet            Back-off restarting failed container
```

How to use storage in this case?
