### ISSUE TITLE
awx19.3 can't use external postgres

### ISSUE THREAD

**Issue by zznfly** [ansible/tower-operator#510]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

i use secrets to config an external postgres, and  i found there is no error of PG in the operator logs , but in the logs of awx-task show waiting for database migrations . 

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13.0
* Kubernetes version: 1.19.8
* AWX install method:  k8s 

##### STEPS TO REPRODUCE

Run the following commands one after another:

`kubectl apply -f awx-operator.yml`
`kubectl apply -f pg-secrets.yml`
`kubectl apply -f my-awx.yml`

##### EXPECTED RESULTS
awx connect to the exPG and awx is  up and running

##### ACTUAL RESULTS

the logs of awx-task shows waiting for database migrations

##### ADDITIONAL INFORMATION

```---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: 192.168.15.245
  port: "5432"
  database: awx
  username: awx
  password: Awx!2333
  sslmode: prefer
  type: unmanaged
type: Opaque

```

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  postgres_configuration_secret: awx-postgres-configuration
  service_type: LoadBalancer
  loadbalancer_protocol: http
  loadbalancer_port: 80 
  loadbalancer_annotations: |
    environment: awx
  service_labels: |
    environment: awx
  ee_images:
    - name: awx-ee
      image: artifactory.fly:80/quay-docker-remote/ansible/awx-ee
  image_pull_policy: IfNotPresent
  control_plane_ee_image: artifactory.fly:80/quay-docker-remote/ansible/awx-ee
  image: artifactory.fly:80/quay-docker-remote/ansible/awx
  image_pull_policy: IfNotPresent
  image_pull_secret: a9y
  redis_image: artifactory.fly:80/registry-docker-remote/redis
  image_pull_policy: IfNotPresent

```

##### AWX-OPERATOR LOGS
there are logs of awx-task 
![20210825143150](https://user-images.githubusercontent.com/52209993/130742490-3cb8d0cd-42b7-402f-bb85-b96bda466532.png)

**logs of operator**
[operator-logs.txt](https://github.com/ansible/awx-operator/files/7044448/operator-logs.txt)
