### ISSUE TITLE
AWX https access

### ISSUE THREAD

**Issue by nicolaibaralmueller** [ansible/tower-operator#513]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

The operator guide does not describe how to enable https

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13.0
* Kubernetes version: minikube
* AWX install method: docker on linux

##### STEPS TO REPRODUCE

Following this guide works by exposing a random port between 30000-33000 via [example] http://awx.domain.local:32520

[https://gist.github.com/dmccuk/93db22e9b30d1963b8fca0de96fc82f0](url)

However... no online guide exists that describes how to enable https access to kube host https://awx.domain.local

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  ingress_type: ingress
  ingress_tls_secret: awx-ingress-tls
  hostname: awx.local.domain
  service_type: LoadBalancer
  loadbalancer_protocol: https
  loadbalancer_port: 443  
  projects_persistence: true
  projects_storage_size: 15Gi
```

Exposing port 8080 and port forwarding to 32520 obviously does not work. 

Can someone please provide information on how to configure https access correctly?
