### ISSUE TITLE
Kerberos Auth failure on task execution

### ISSUE THREAD

**Issue by GeneralFox** [ansible/tower-operator#518]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Launching a job on AWX console generate an error on Kerberos authentication like this:

"Kerberos auth failure for principal PRINCIPAL with pexpect: Configuration file does not specify default realm when parsing name PRINCIPAL"

This was not expected as kinit on the pod works fine, the kerberos configuration was loaded with a config-map and volume mount.

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: tower
  namespace: awx
spec:
  old_postgres_configuration_secret: tower-old-postgres-configuration
spec:
  web_extra_volume_mounts: |
    - name: krb5-conf
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
  task_extra_volume_mounts: |
    - name: krb5-conf
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
  ee_extra_volume_mounts: |
    - name: krb5-conf
      mountPath: /etc/krb5.conf
      subPath: krb5.conf
  extra_volumes: |
    - name: krb5-conf
      configMap:
        defaultMode: 420
        items:
          - key: krb5.conf
            path: krb5.conf
        name: tower-extra-config

```
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: tower-extra-config
  namespace: awx
data:
  krb5.conf: |-
    # To opt out of the system crypto-policies configuration of krb5, remove the
    # symlink at /etc/krb5.conf.d/crypto-policies which will not be recreated.
    includedir /etc/krb5.conf.d/

    [logging]
        default = FILE:/var/log/krb5libs.log
        kdc = FILE:/var/log/krb5kdc.log
        admin_server = FILE:/var/log/kadmind.log

    [libdefaults]
        dns_lookup_realm = false
        ticket_lifetime = 24h
        renew_lifetime = 7d
        forwardable = true
        rdns = false
        pkinit_anchors = FILE:/etc/pki/tls/certs/ca-bundle.crt
        spake_preauth_groups = edwards25519
        default_realm = SWQA.TST
        default_ccache_name = KEYRING:persistent:%{uid}

    [realms]

    DOMAIN.TST = {
            kdc = dc01.domain.tst
            kdc = dc02.domain.tst
            kdc = dc03.domain.tst
        }

    [domain_realm]

    .domain.tst = DOMAIN.TST
    domain.tst = DOMAIN.TST

```

Some related issue are reported here:
https://groups.google.com/g/awx-project/c/g66X-FFICXA/m/K1ZHmQU4AgAJ
https://github.com/ansible/awx/issues/9807#issuecomment-819014975

Kinit output : 

bash-4.4$ hostname
tower-5bff769cc4-w2gkw
bash-4.4$ kinit user
Password for user@DOMAIN.TST: 
bash-4.4$ klist
Ticket cache: KEYRING:persistent:1000:1000
Default principal: user@DOMAIN.TST

Valid starting     Expires            Service principal
09/02/21 08:38:35  09/02/21 18:38:35  krbtgt/DOMAIN.TST@DOMAIN.TST
        renew until 09/09/21 08:38:29
bash-4.4$ 

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13.0
* Kubernetes version: 1.21.3
* AWX install method: rke2 + rancher / Openshift 4.7

##### STEPS TO REPRODUCE

Launch a job from the web console with a Windows target.

##### EXPECTED RESULTS

Job runs successfully.

##### ACTUAL RESULTS

Job fails.

##### ADDITIONAL INFORMATION

If you change the job credential and insert @DOMAIN.TST (uppercase) on the user name field, all runs.

**Comment by chrismeyersfsu** [comment]
@GeneralFox Can you try adding your kerberos configuration as a volume mount on the `podspec_override` field on the default container group? You can do this through the UI.

![image](https://user-images.githubusercontent.com/722880/134717082-473edba3-3931-4880-b294-820bf9438b99.png)

**Comment by cnukwas** [comment]
@GeneralFox , I am getting following error even with the domain added to the user name defined for the credential.
I do see that kinit command works from the task terminal when tested manually, so not sure what the issue is.

Error:
fatal: [windows_server_name.org.com]: UNREACHABLE! => {
    "changed": false,
    "msg": "Kerberos auth failure for principal windo...@CORP.ORG.COM with pexpect: KDC has no support for encryption type while getting initial credentials",
    "unreachable": true
}

Posted details here:
https://groups.google.com/g/awx-project/c/7UV0ZABsH_I

**Comment by cnukwas** [comment]
> @GeneralFox Can you try adding your kerberos configuration as a volume mount on the `podspec_override` field on the default container group? You can do this through the UI.
> 
> ![image](https://user-images.githubusercontent.com/722880/134717082-473edba3-3931-4880-b294-820bf9438b99.png)

@chrismeyersfsu , is there a reason to add it here since krb5.conf is already added as ConfigMap for the task container?

**Comment by chrismeyersfsu** [comment]
The task container `ConfigMap` has no relation to the pod(s) that we launch to run playbook(s).  The screenshot above is for the pods that we launch to run your playbook so the `ConfigMap` needs to be in it.

**Comment by gianmarco-mameli** [comment]
Hi, the solution indicated by @chrismeyersfsu solved the same problem for me, the pod specification looks like this 

```
apiVersion: v1
kind: Pod
metadata:
  namespace: awx
spec:
  containers:
    - image: 'quay.io/ansible/awx-ee:latest'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      volumeMounts:
       - name: krb5-conf
         mountPath: /etc/krb5.conf
         subPath: krb5.conf
  volumes:
    - name: krb5-conf
      configMap:
        name: <config-map-name>
```
