### ISSUE TITLE
awx deploys but never creates user

### ISSUE THREAD

**Issue by howardjones** [ansible/tower-operator#53]
awx operator from git (f4b619a185ac0cb5736b229c61e56ed91237d16a)
awx 15.0.1
kubernetes 1.18.8 (AKS)

If I create an awxs resource, the operator does create the postgres database and awx pod, but the task container doesn't seem to seed the database (even after allowing several hours, I still get errors like:

```
2020-11-11 09:38:10,649 WARNING  awx.main.dispatch.periodic periodic beat started
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedColumn: column main_instance.ip_address does not exist
LINE 1: SELECT (1) AS "a" FROM "main_instance" WHERE ("main_instance...
```

if I shell into the task container, and manually run migrate, it says there are no migrations pending, and that it can connect to the database.

```
bash-4.4$ awx-manage migrate
Operations to perform:
  Apply all migrations: auth, conf, contenttypes, main, oauth2_provider, sessions, sites, social_django, sso, taggit
Running migrations:
  No migrations to apply.
bash-4.4$ awx-manage check_db
Database Version: PostgreSQL 10.14 (Debian 10.14-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit
```

I don't see any errors (and very little at all) in the task containers logs regarding migration.

Funny thing is, this same configuration worked for me before, but I can't see where to troubleshoot it.

**Comment by howardjones** [comment]
One thing I have noticed is that the task container comes up before the database. Is the startup script smart enough to wait?

```
NAME                   READY   STATUS              RESTARTS   AGE
awx-69bf447555-9gr92   3/3     Running             0          20s
awx-postgres-0         0/1     ContainerCreating   0          27s
```

**Comment by howardjones** [comment]
Understanding a bit more now about the order of things, I can see that actually the database does get created by the operator, but that at the end of the process, the auth_user table is empty. I am defining tower_admin_user and tower_admin_password in my awx object.

**Comment by howardjones** [comment]
The only mention of tower_admin_user I can find is in roles/tasks/initialize.yml which looks like it _used_ to be included from main.yml, but isn't anymore since this "lint cleanup": https://github.com/ansible/awx-operator/commit/267741550f3de75a576b7feced0b7b8abf660a93

**Comment by howardjones** [comment]
After uncommenting the include line again, I get a user! But only sometimes. It seems that the operator doesn't actually wait or check if the database is available before trying to run the migrations:
```
django.db.utils.OperationalError: could not translate host name \"awx-postgres\" to address: Name or service not known"
```

**Comment by howardjones** [comment]
To make sure that postgres had actually started up, I added an addtional task to the `role/awx-operator/main.yml` near the end, before "Check if database is populated":

```yaml
- name: Verify database is available
  community.kubernetes.k8s_exec:
     namespace: "{{ meta.namespace }}"
     pod: "{{ tower_pod_name }}"
     container: "{{ meta.name }}-task"
     command: >-
       bash -c "awx-manage check_db"
  register: database_avail_check
  retries: 60
  delay: 5
  ignore_errors: true
  until: "'Database Version' in database_avail_check.stdout"
```
