### ISSUE TITLE
automation pod resources limit

### ISSUE THREAD

**Issue by beenje** [ansible/tower-operator#540]
##### ISSUE TYPE
 - New feature

##### SUMMARY
We upgraded AWX to version 19.2.2.
By default, AWX is now creating a new pod named "automation-job-xxxx" to run jobs.

Our OKD cluster require every containers to have some limits set.
We currently have to use a LimitRange to set those limits.
Would it be possible to have a variable, like `ee_resource_requirements`, that could be used to assign resources to this pod?

##### ENVIRONMENT
* AWX version: 19.2.2
* Operator version: 0.12.0 
* AWX install method: operator on OKD

Note that I created a PR to add a new variable for Redis: https://github.com/ansible/awx-operator/pull/505

**Comment by kimbernator** [comment]
`ee_resource_requirements` is a variable currently but it only applies to the EE container that runs in the AWX pod constantly. I would also not be against this option in the operator but it is possible to define these limits from within AWX - Under "Instance Groups", select "Default" and then edit it and "customize pod specification". I've got the following in mine for limits and node selection:

```YAML
apiVersion: v1
kind: Pod
metadata:
  namespace: default
spec:
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "awx-ee"
      effect: "NoSchedule"
  nodeSelector:
    dedicated: "awx-ee"
  containers:
    - image: 'my_repository.com/ansible/awx-ee:0.6.0'
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      resources:
        requests:
            cpu: 400m
            memory: 500Mi
        limits:
            cpu: 1000m
            memory: 1Gi
```
