### ISSUE TITLE
operator 0.13 awx 19.3.0 blank ui

### ISSUE THREAD

**Issue by jsalatiel** [ansible/tower-operator#553]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
After installing a clean 19.3.0 version using operator the URL returns a blank screen

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13
* Kubernetes version:  1.21
* AWX install method: kubernetes

##### STEPS TO REPRODUCE
deployed the operator ( changing the namespace references from default to awx )
Deployed this:
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: ClusterIP
  ingress_type: ingress
  hostname: awx.mydomain
  image_version: '19.3.0'
  image_pull_policy: IfNotPresent
  projects_persistence: false
```

##### EXPECTED RESULTS

awx acessible on http://awx.mydomain

##### ACTUAL RESULTS
Blank page. Showing source on the browser I get:
```
<!doctype html><html lang="en"><head><script nonce="82U/y5hwoX3OtviICXHGvz7BCFb4lD/qNcqmkjv5gaI=" type="text/javascript">window.NONCE_ID="82U/y5hwoX3OtviICXHGvz7BCFb4lD/qNcqmkjv5gaI="</script><meta http-equiv="Content-Security-Policy" content="default-src 'self'; connect-src 'self' ws: wss:; style-src 'self' 'unsafe-inline'; script-src 'self' 'nonce-82U/y5hwoX3OtviICXHGvz7BCFb4lD/qNcqmkjv5gaI=' *.pendo.io; img-src 'self' *.pendo.io data:;"/><link rel="shortcut icon" href="/static/media/favicon.ico"/><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="description" content="AWX"/><link href="/static/css/2.c75a8863.chunk.css" rel="stylesheet"><link href="/static/css/main.e189280d.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><style nonce="82U/y5hwoX3OtviICXHGvz7BCFb4lD/qNcqmkjv5gaI=">.app{height:100%}</style><div id="app" class="app"></div><script src="/static/js/runtime-main.0845111b.js"></script><script src="/static/js/2.11d97623.chunk.js"></script><script src="/static/js/main.11ca6dfe.chunk.js"></script></body></html>
```
