### ISSUE TITLE
Enhance documentation for Migrating data from an old AWX instance

### ISSUE THREAD

**Issue by craph** [ansible/tower-operator#557]
I was reading the documentation about "Migrating data from an old AWX instance" and I think something is missing in the Deploy part [here](https://github.com/ansible/awx-operator/blob/devel/docs/migration.md#deploy-awx)

In the spec `old_postgres_configuration_secret` is set but the `secret_key_secret` is not.

How AWX can get / know / retrieve the "Secret Key" if this is not mentioned in the below yaml file to deploy AWX like `old_postgres_configuration_secret` ?

Should we add : 
```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  old_postgres_configuration_secret: <resourcename>-old-postgres-configuration
  secret_key_secret: <resourcename>-secret-key
  ...
```

Would you like I open a PR for this ?

Thank you very much.

Best regards,
