### ISSUE TITLE
awx-pod stuck in pending state

### ISSUE THREAD

**Issue by slaurencelle** [ansible/tower-operator#558]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13.0
* Kubernetes version: 1.21.3
* AWX install method:  using the awx-operator on my kubernetes cluster with docker on linux

##### EXPECTED RESULTS

That everything install and be able to access my new awx service with awx pod running state
##### ACTUAL RESULTS

awx databse is install but no awx pod create, stuck in pending state
##### AWX-OPERATOR LOGS
nothing in the logs about what is happening 
only this on the awx pod 

Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  26m   default-scheduler  0/4 nodes are available: 2 Insufficient cpu, 2 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
  Warning  FailedScheduling  26m   default-scheduler  0/4 nodes are available: 2 Insufficient cpu, 2 node(s) had taint {node-role.kubernetes.io/master: }, that the pod didn't tolerate.
Hope you can help me with that because i am starting to find the way to install the awx with the operator unproductive, it took me less then an hour before and now i have been loosing more then a week trying to make this thing work.

Regards,

Stephane

**Comment by oliverf1** [comment]
Hello Stephane,

You usually get this error when you try to create pod with a cpu and/or memory reservation but you don't have enough resources.
In your case it's CPU only. You can use the `kubectl describe node` to check your available resources in your cluster.
To solve it, you can either add nodes to your cluster or modify the reservation so that your deployment fits in your cluster.
See https://github.com/ansible/awx-operator#containers-resource-requirements

On my testing cluster which is really small I'm adding the below value to disable all the reservations:
```
---
spec:
  ...
  web_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 2000m
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 1000m
      memory: 2Gi
  ee_resource_requirements:
    requests:
      cpu: "0"
      memory: "0"
    limits:
      cpu: 1000m
      memory: 2Gi   
 ```
Hope this helps.

-- 
Olivier
