### ISSUE TITLE
Redis pod crashloop with a permission error

### ISSUE THREAD

**Issue by oliverf1** [ansible/tower-operator#560]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Redis container crashloop with an error: `chown: changing ownership of '.': Operation not permitted`

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13.0
* Kubernetes version: k3s v1.19.3+k3s3
* AWX install method: operator

##### STEPS TO REPRODUCE

- Deploy a kubernetes cluster and create a PodSecurityPolicy that drops all privileges but NET_BIND_SERVICE, CHOWN, SETGID, SETUID like below
```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cis1.5
spec:
  privileged: false
  allowPrivilegeEscalation: false
  allowedCapabilities:
    - NET_BIND_SERVICE
    - CHOWN
    - SETGID
    - SETUID
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
     - min: 1
       max: 65535
  fsGroups:
    rule: 'MustRunAs'
    ranges:
     - min: 1
       max: 65535
  readOnlyRootFilesystem: false
```
- try to deploy AWX using the operator
- the redis pod will crashloop with the error message `chown: changing ownership of '.': Operation not permitted`

##### EXPECTED RESULTS

Redis pod  and all other AWX pods are deployed successfully

##### ACTUAL RESULTS

The redis pod crash loop with the error `chown: changing ownership of '.': Operation not permitted`
In order for the pod to start the CHOWN, SETGID, SETUID capabilities need to be added.
See #559 for a fix
