### ISSUE TITLE
Backup role failing if awx_postgres_pass contains exclamation mark

### ISSUE THREAD

**Issue by eherce** [ansible/tower-operator#565]
Hi all,

I believe there's an issue with the backup role of awx-operator (maybe extended to the restore role as well) when awx_postgres_pass contains an exclamation mark

The solution seems to be pretty easy on file roles/backuptasks/postgres.yml, task "Write pg_dump to backup on PVC", which is using single quotes on PGPASSWORD:
PGPASSWORD='{{ awx_postgres_pass }}' {{ pgdump }} > {{ backup_dir }}/tower.db

**Comment by jamesmarshall24** [comment]
@eherce 
I tried to replicate the same, but didn't see any issues running a backup or restoring with `!` in the password.

Here was my reproducer, can you let me know if I'm missing something? Maybe additional characters?
```
---
apiVersion: v1
kind: Secret
metadata:
  name: 'awx-demo-postgres-configuration'
  labels:
    app.kubernetes.io/name: 'awx-demo'
    app.kubernetes.io/part-of: 'awx-demo'
    app.kubernetes.io/managed-by: 'awx-operator'
    app.kubernetes.io/component: 'awx'
    app.kubernetes.io/operator-version: '0.13.0'
stringData:
  password: '!password'
  username: 'awx'
  database: 'awx-demo'
  port: '5432'
  host: awx-demo-postgres
  type: 'managed'
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  ingress_type: none
  hostname: awx-demo.example.com
  postgres_configuration_secret: awx-demo-postgres-configuration
  postgres_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: '1'
      memory: 2Gi
  postgres_storage_requirements:
    requests:
      storage: 8Gi
    limits:
      storage: 20Gi
```
