### ISSUE TITLE
Backup Role on Operator 0.13.0 does not create secrets.yml, where it does on 0.12.0. Causing Restores to fail.

### ISSUE THREAD

**Issue by abj03** [ansible/tower-operator#566]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When running the Backup Role on AWX Operator 0.13.0 it is not creating the secrets.yml in the PVC. When using AWX Operator 0.12.0  it does. This causes restores to fail.

##### ENVIRONMENT
* AWX version: 19.3.0
* Operator version: 0.13.0
* Kubernetes version:  1.22
* AWX install method: minikube on RHEL 8 with external postgres DB.

##### STEPS TO REPRODUCE

Backup role  (backup-awx.yml)
```
---
# Sample backup role file
apiVersion: awx.ansible.com/v1beta1
kind: AWXBackup
metadata:
  name: awxbackup-2021-04-22
  namespace: default
spec:
  deployment_name: awx-demo
  backup_pvc: backup-pvc
```
 awx-demo.yml
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
  ingress_type: ingress
  ingress_tls_secret: awx-demo-tls-secret
  hostname: awx-demo.example.com
  bundle_cacert_secret: awx-demo-custom-certs
```

AWX Operator deployment:

   Deployment with the issue:

 
`kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.13.0/deploy/awx-operator.yaml`
`kubectl apply -f awx-demo.yml`
`kubectl apply -f backup-awx.yml`

( using version 0.12.0 works fine.  `kubectl apply -f https://raw.githubusercontent.com/ansible/awx-operator/0.12.0/deploy/awx-operator.yaml`)

##### EXPECTED RESULTS

secrets.yml is in place

```
[root@host awx]# kubectl apply -f backup-awx.yml
awxbackup.awx.ansible.com/awxbackup-2021-04-22 created

[root@host awx]# ls -l /var/pvc/tower-openshift-backup-2021-09-28-01\:10\:25/
total 736
-rw-r--r--. 1 root             root    745 Sep 28 01:10 awx_object
-rw-r--r--. 1 root             root    613 Sep 28 01:10 secrets.yml
-rw-------. 1 systemd-coredump root 742743 Sep 28 01:10 tower.db
```

##### ACTUAL RESULTS
 
secrets.yml is missing
```
[root@host awx]# kubectl apply -f backup-awx.yml
awxbackup.awx.ansible.com/awxbackup-2021-04-22 created

[root@host awx]# ls -l /var/pvc/tower-openshift-backup-2021-09-28-00\:42\:51/
total 732
-rw-r--r--. 1 root             root    753 Sep 28 00:42 awx_object
-rw-------. 1 systemd-coredump root 742875 Sep 28 00:42 tower.db
```

##### AWX-OPERATOR LOG
[failedrestore.log](https://github.com/ansible/awx-operator/files/7241161/failedrestore.log)
[backuprole.log](https://github.com/ansible/awx-operator/files/7241162/backuprole.log)
