### ISSUE TITLE
First AWX deployment fails and then cannot use the service name anymore

### ISSUE THREAD

**Issue by malcolmohare** [ansible/tower-operator#584]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
The first AWX deployment after installing the 0.14.0 operator failed.  I was able to successfully spin up AWX clusters with other names, but I cannot successfully deploy AWX with the original name that originally failed.

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: unata-awx
spec:
  service_type: LoadBalancer
  ingress_type: none
```

##### ENVIRONMENT
* Operator version: 0.14.0
* Kubernetes version: 1.20.9-gke.1001
* AWX install method: make deploy -> GCP kube autopilot

##### STEPS TO REPRODUCE

install operator into the namespace awx
apply the manifest

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: unata-awx
spec:
  service_type: LoadBalancer
  ingress_type: none
```

##### EXPECTED RESULTS

AWX should successfully start up

##### ACTUAL RESULTS

Nothing is listening behind the load balancer, and service pod keeps restarting.

##### AWX-OPERATOR LOGS

I need to know what to search for in the operator logs, its quite verbose and seems to log a lot of stuff at the error level that doesn't look like errors.
