### ISSUE TITLE
nodeport_port isn't assigning specified port

### ISSUE THREAD

**Issue by 71Imapla** [ansible/tower-operator#597]
##### ISSUE TYPE
When using NotePort service type, and specifying a specific port using nodeport_port, the NodePort Service is not getting the specified port

### AWX kind yaml:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: dev-awx
  namespace: awxdev
spec:
  service_type: NodePort
  nodeport_port: 30080
  ingress_type: none
  admin_user: awxadmin
  admin_email: noone@nowhere.devnull
  admin_password_secret: dev-awx-admin-password
  postgres_configuration_secret: dev-awx-postgres-configuration

---
```

### Result:

```
NAME                                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.105.105.189   <none>        8443/TCP       18h
service/dev-awx-service                                   NodePort    10.108.117.254   <none>        80:30469/TCP   18h
```

The NodePort is not getting the specified port of 30080. 

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version:  1.22.2
* AWX install method:  K8

##### STEPS TO REPRODUCE

Use nodeport_port  specification in the AWX kind yaml.  I provided an example configuration above.

##### EXPECTED RESULTS

NodePort will get the specified port assignment

##### ACTUAL RESULTS

NodePort got some random port assignment. 

##### ADDITIONAL INFORMATION

See above.

**Comment by peurKe** [comment]
Hi!

I am new to kubernetes and minikube but wanted to test AWX.

I encountered the same problem as you @71Imapla.

I couldn't find any reference to the **nodeport_port** variable in the role **~/awx-operator/roles/installer** (except for its default declaration in **~/awx-operator/roles/installer/defaults/main.yml**).

Then, in order to test, I added the following lines to the very beginning of **spec.ports** (line 20) in the jinja2 template located under "**~/awx-operator/roles/installer/templates/service.yaml.j2**" :
```
{% if service_type | lower == "nodeport" %}
    - port: 80
      protocol: TCP
      targetPort: 8052
      nodePort: "{{ nodeport_port }}"
      name: http
{% elif service_type | lower != 'loadbalancer' and loadbalancer_protocol | lower != 'https' %}
```

But when I run ```kubectl apply -f awx-demo.yml```, that role **~/awx-operator/roles/installer** that I just cloned and modified is not used by k8s.
It looks like the role **/opt/ansible/roles/installer** hosted in the **quay.io/ansible/awx-operator:0.14.0** docker image is the one that is being executed.
So I can't test this code.

Does anyone know of a way to update the role **/opt/ansible/roles/installer** hosted in the **quay.io/ansible/awx-operator:0.14.0** docker image ?

Have a good day!

**Comment by rooftopcellist** [comment]
Hi @peurKe , the roles get run from inside the awx-operator container.  Unfortunately, that also means that you need to re-build the awx-operator image to test any changes you've made to the roles.  You can then push that new image to quay.io or the container registry of your choice and reference it from there.  

Since the recent operator-sdk 1.12.0 upgrade, building and deploying the awx-operator for 0.14+ looks like this:

```
# Build & Push Operator Image
TAG=test-dev make docker-build docker-push IMG=quay.io/username/awx-operator:$TAG


# Deploy Operator
TAG=test-dev NAMESPACE=your-namespace IMG=quay.io/username/awx-operator:$TAG make deploy
```

**Comment by peurKe** [comment]
Hello @rooftopcellist,

Thank you for your answer!

Unfortunately, I am not familiar (yet) with operator-sdk, but I will take a look at the information you gave me!
Can everybody push and deploy operator image into quay.io repository ?
Isn't there a test and validation process to follow before?
(Sorry, I'm asking these questions because I don't know the process at all)

1. In order to test my modification in my own environment, I rebuilt a customized image "quay.io/ansible/awx-operator:0.14.0" locally using this dockerfile 
[Dockerfile.txt](https://github.com/ansible/awx-operator/files/7347681/Dockerfile.txt)

```
cd <DIRECTORY_WITH_DOCKERFILE>
docker bulld . -f Dockerfile.txt -t quay.io/ansible/awx-operator-test:0.14.0
```

2. I saved the original image by modifying its tag :
```
docker image tag quay.io/ansible/awx-operator:0.14.0 quay.io/ansible/awx-operator-save:0.14.0
```

3. I removed the original image :

```
docker image rm quay.io/ansible/awx-operator:0.14.0
```

4. I modified the customized image giving it the name of the original image :
```
docker image tag quay.io/ansible/awx-operator-test:0.14.0 quay.io/ansible/awx-operator:0.14.0
```

5. I modified the deployment YML file so that it contained :
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: NodePort
  nodeport_port: 30018     👈
```

6. I deployed AWX using the YML file above :
```
kubectl apply -f awx-demo.yml
```

With this customization, the NodePort 30018 was well used during the deployment :
```
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
awx-demo-postgres   ClusterIP   None             <none>        5432/TCP          20m
awx-demo-service    NodePort    10.111.165.198   <none>        80:30018 👈/TCP   19m
```

I just hope k8s did not choose by chance this port out of the 2767 available 😅

have a good day!

.
.
[EDIT]
In order to be sure that the choice of the port by k8s was not an accident, I just redo a new deployment with a new 'nodeport_port' value (after having stopped and deleted my minikube instance) :

I modified the deployment YML file so that it contained :
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: NodePort
  nodeport_port: 31818     👈
```

Then I deployed AWX using the YML file above :
```
kubectl apply -f awx-demo.yml
```

And the result :
```
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
awx-demo-postgres   ClusterIP   None            <none>        5432/TCP         36s
awx-demo-service    NodePort    10.104.114.50   <none>        80:31818 👈/TCP  31s

```

**Comment by 71Imapla** [comment]
Looks like I need to make the same changes.  Thanks for the input !

**Comment by peurKe** [comment]
@71Imapla 
You're welcome.
I edited my previous comment because I made a small mistake when I copied/pasted one of the commands.

**Comment by chrismeyersfsu** [comment]
@71Imapla did @peurKe fix work for you?

**Comment by 71Imapla** [comment]
I have not had the time to test the solution yet.

**Comment by 71Imapla** [comment]
I found this reference:

https://github.com/ansible/awx-operator/issues/291

I updated accordingly:

#### AWX kind yaml:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: dev-awx
  namespace: awxdev
spec:
  service_type: ClusterIP
  ingress_type: none

-truncated-

```
#### Custom Nodeport Service yaml:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: dev-awx
    app.kubernetes.io/part-of: awx
  name: dev-awx-nodeport
  namespace: awxdev
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      targetPort: 8052
      name: http
  selector:
      app.kubernetes.io/component: awx
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/name: dev-awx
```

##### Works like a charm:

```
wget awx.example.com:300080
HTTP request sent, awaiting response... 200 OK
Length: 1190 (1.2K) [text/html]
Saving to: ‘index.html’

index.html                                                                100%[==================================================================================================================================================================================>]   1.16K  --.-KB/s    in 0s

2021-10-19 15:41:03 (60.5 MB/s) - ‘index.html’ saved [1190/1190]
```
