### ISSUE TITLE
Adding TOWER_URL_BASE to extra-settings causes AWX to fail to start

### ISSUE THREAD

**Issue by rbkaspr** [ansible/tower-operator#599]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Attempting to set TOWER_URL_BASE in the AWX CR results in a nonfunctional install

##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: 1.21.4
* AWX install method: Makefile to kubernetes cluster

##### STEPS TO REPRODUCE

I created the below AWX CR to deploy AWX:
```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  ingress_type: ingress
  hostname: <FQDN>
  ingress_tls_secret: <secretName>
  extra_settings:
    - setting: TOWER_URL_BASE
      value: https://<fqdn>
```
By default, the hostname in the CR doesn't appear to get used in the AWX install itself, which just uses the generic `towerhost` hostname, which is probably going to break things when I try enabling SSO. The setting can be changed via the UI, but I'd much rather have it be done declaratively via the CR
##### EXPECTED RESULTS
AWX should come online with the correct base URL.

##### ACTUAL RESULTS
AWX pod starts, reports no errors, but the web container is not serving on the expected port and the task and web containers log `waiting-for-migrations` messages until they eventually time out and stop logging altogether. Removing the extra_settings block from the CR allows AWX to boot but with the aforementioned default hostname.

**Comment by mick1627** [comment]
I had the same behavior when trying to set AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT
I had to add simple quote like below to be sure to have the double quote in the settings.py file

```yaml
spec:
  extra_settings:
    - setting: AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT
      value: '"10m"'
```


Check the content of the file settings.py :
```
$ tail -1 /etc/tower/settings.py
AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT = "10m"
```

Maybe you can have a try the same for the value => '"https://<fqdn>"'
