### ISSUE TITLE
Migrations failed with external database on upgrade

### ISSUE THREAD

**Issue by MichaelPak** [ansible/tower-operator#618]
##### ENVIRONMENT
* AWX version: 19.4.0
* Operator version: 0.14.0
* Kubernetes version: 1.21.1
* AWX install method: kind

##### SUMMARY
I am trying to update AWX from version 14 to the latest. In production, the application runs in a `docker-compose`. Raised a clean install locally through an operator in [kind](https://kind.sigs.k8s.io/), everything works. I got the idea to try installing with an old database to check that the migrations were successful. I installed the Postgresql locally, uploaded the backup there. I made it possible to connect to the local database through the [dockerhost](https://github.com/qoomon/docker-host).

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerhost
  labels:
    k8s-app: dockerhost
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: dockerhost
  template:
    metadata:
      labels:
        k8s-app: dockerhost
    spec:
      containers:
      - name: dockerhost
        image: qoomon/docker-host
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]

---
apiVersion: v1
kind: Service
metadata:
  name: dockerhost
spec:
  clusterIP: None
  selector:
    k8s-app: dockerhost
```

In PostgreSQL I created two databases: `awx` for the old backup and `awxnew` for the new installation.

```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: awx
stringData:
  secret_key: "awxsecret"
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: awx-old-postgres-configuration
  namespace: awx
stringData:
  host: dockerhost
  port: "5432"
  database: awx
  username: awx
  password: awx
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: dockerhost
  port: "5432"
  database: awxnew
  username: awxnew
  password: awxnew
  sslmode: disable
  type: unmanaged
type: Opaque

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: NodePort
  old_postgres_configuration_secret: awx-old-postgres-configuration
  postgres_configuration_secret: awx-postgres-configuration
  secret_key_secret: awx-secret-key
```

But during installation, the `manager` tries for some reason to get information about the old database pod:

```
TASK [installer : Look up details for this deployment] *************************
task path: /opt/ansible/roles/installer/tasks/database_configuration.yml:126
{"level":"info","ts":1635242083.4437785,"logger":"logging_event_handler","msg":"[playbook task start]","name":"awx","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"2756451339098450931","EventData.Name":"installer : Look up details for this deployment"}

-------------------------------------------------------------------------------
{"level":"info","ts":1635242085.9946275,"logger":"proxy","msg":"Read object from cache","resource":{"IsResourceRequest":true,"Path":"/apis/awx.ansible.com/v1beta1/namespaces/awx/awxs/awx","Verb":"get","APIPrefix":"apis","APIGroup":"awx.ansible.com","APIVersion":"v1beta1","Namespace":"awx","Resource":"awxs","Subresource":"","Name":"awx","Parts":["awxs","awx"]}}

--------------------------- Ansible Task StdOut -------------------------------

TASK [installer : Get the postgres pod information] ****************************
task path: /opt/ansible/roles/installer/tasks/migrate_data.yml:21

-------------------------------------------------------------------------------
{"level":"info","ts":1635242087.2295253,"logger":"logging_event_handler","msg":"[playbook task start]","name":"awx","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"playbook_on_task_start","job":"2756451339098450931","EventData.Name":"installer : Get the postgres pod information"}
{"level":"info","ts":1635242090.0569553,"logger":"proxy","msg":"Cache miss: /v1, Kind=Pod, awx/awx-postgres-0"}
{"level":"info","ts":1635242097.845907,"logger":"proxy","msg":"Cache miss: /v1, Kind=Pod, awx/awx-postgres-0"}
{"level":"info","ts":1635242105.4850993,"logger":"proxy","msg":"Cache miss: /v1, Kind=Pod, awx/awx-postgres-0"}
{"level":"info","ts":1635242113.091094,"logger":"proxy","msg":"Cache miss: /v1, Kind=Pod, awx/awx-postgres-0"}
{"level":"info","ts":1635242120.6829636,"logger":"proxy","msg":"Cache miss: /v1, Kind=Pod, awx/awx-postgres-0"}
...
```

I did not find any condition in the source code that the old database could be external and unmanaged:
```
# database_configuration.yml
- name: Migrate data from old Openshift instance
  import_tasks: migrate_data.yml
  when:
    - old_pg_config['resources'] is defined
    - old_pg_config['resources'] | length
    - this_awx['resources'][0]['status']['migratedFromSecret'] is not defined

# migrate_data.yml
- name: Get the postgres pod information
  k8s_info:
    kind: Pod
    namespace: '{{ ansible_operator_meta.namespace }}'
    name: '{{ ansible_operator_meta.name }}-postgres-0'  # using name to keep compatibility
    field_selectors:
      - status.phase=Running
  register: postgres_pod
  until:
    - "postgres_pod['resources'] | length"
    - "postgres_pod['resources'][0]['status']['phase'] == 'Running'"
  delay: 5
  retries: 60
```

Does the database have to be in kubernetes cluster as a pod?
