### ISSUE TITLE
awx unable to pull galaxy collections behind proxy

### ISSUE THREAD

**Issue by Nitish0292** [ansible/tower-operator#648]
{
  "changed": false,
  "stdout": "Starting galaxy collection install process\nProcess install dependency map",
  "stderr": "[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/. Got an\nunexpected error when getting available versions of collection awx.awx: Unknown\nerror when attempting to call Galaxy at 'https://galaxy.ansible.com/api/':\n<urlopen error [Errno 99] Cannot assign requested address>\nERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno 99] Cannot assign requested address>",
  "rc": 1,
  "cmd": [
    "ansible-galaxy",
    "collection",
    "install",
    "-r",
    "/var/lib/awx/projects/_8__ansiblegit/collections/requirements.yml",
    "--collections-path",
    "/var/lib/awx/projects/.__awx_cache/_8__ansiblegit/stage/requirements_collections"
  ],
  "start": "2021-11-11 10:16:22.769099",
  "end": "2021-11-11 10:17:23.944951",
  "delta": "0:01:01.175852",
  "msg": "non-zero return code",
  "invocation": {
    "module_args": {
      "chdir": "/var/lib/awx/projects/_8__ansiblegit",
      "_raw_params": "ansible-galaxy collection install -r /var/lib/awx/projects/_8__ansiblegit/collections/requirements.yml --collections-path /var/lib/awx/projects/.__awx_cache/_8__ansiblegit/stage/requirements_collections \n",
      "_uses_shell": false,
      "warn": false,
      "stdin_add_newline": true,
      "strip_empty_ends": true,
      "argv": null,
      "executable": null,
      "creates": null,
      "removes": null,
      "stdin": null
    }
  },
  "stdout_lines": [
    "Starting galaxy collection install process",
    "Process install dependency map"
  ],
  "stderr_lines": [
    "[WARNING]: Skipping Galaxy server https://galaxy.ansible.com/. Got an",
    "unexpected error when getting available versions of collection awx.awx: Unknown",
    "error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/':",
    "<urlopen error [Errno 99] Cannot assign requested address>",
    "ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno 99] Cannot assign requested address>"
  ],
  "_ansible_no_log": false,
  "item": "/var/lib/awx/projects/_8__ansiblegit/collections/requirements.yml",
  "ansible_loop_var": "item",
  "_ansible_item_label": "/var/lib/awx/projects/_8__ansiblegit/collections/requirements.yml"
}

**Comment by Nitish0292** [comment]
when I give open internet access to the server it works fine, but I have tried setting a proxy on AWX host, awx-web and awx-task container but it doesn't work
please guide me on how to make it work offline after minikube restart, I think collection is getting deleted and i don't want to fetch the galaxy collection whenever I run template
![Capture](https://user-images.githubusercontent.com/82095991/141299066-a8435a68-b976-49d4-93a0-16543eabc2c3.JPG)
![Capture](https://user-images.githubusercontent.com/82095991/141299087-7442cf6f-1511-4dde-a047-0e98783182d7.JPG)

**Comment by hungtran84** [comment]
you may also want to come up with building your own image (custom-ee) with that collection. By doing that, you are no longer need to come to Internet to download and install the collection required. Technically, it makes your awx execution environment more secure and immutable as well as saving execution time.

**Comment by Nitish0292** [comment]
> you may also want to come up with building your own image (custom-ee) with that collection. By doing that, you are no longer need to come to Internet to download and install the collection required. Technically, it makes your awx execution environment more secure and immutable as well as saving execution time.

Can you share some references on how to do it and if possible in a short point 
i am migrating stuff manually from awx4 to awx19.4 so I am not so comfortable yet with the latest awx19.4

**Comment by chrismeyersfsu** [comment]
@Nitish0292 https://docs.ansible.com/ansible-tower/3.6.2/html/administration/proxy-support.html#configure-known-proxies try settings the global configuration for job extra env vars.

**Comment by hungtran84** [comment]
There 2 ways to handle your case:
1. Setup proxy setting via extra environment variables like @chrismeyersfsu mentioned above. For example:

```yaml
  web_extra_env: |
    - name: GIT_SSL_NO_VERIFY
      value: "True"
    - name: HTTP_PROXY
      value: "http://your_proxy:proxy_port"
    - name: HTTPS_PROXY
      value: "http://your_proxy:proxy_port"
    - name: NO_PROXY
      value: "10.0.*.*,localhost,kubernetes.default.svc.cluster.local" 

  task_extra_env: |
    - name: GIT_SSL_NO_VERIFY
      value: "True"
    - name: HTTP_PROXY
      value: "http://your_proxy:proxy_port"
    - name: HTTPS_PROXY
      value: "http://your_proxy:proxy_port"
    - name: NO_PROXY
      value: "10.0.*.*,localhost,kubernetes.default.svc.cluster.local" 

  ee_extra_env: |
    - name: GIT_SSL_NO_VERIFY
      value: "True"
    - name: HTTP_PROXY
      value: "http://your_proxy:proxy_port"
    - name: HTTPS_PROXY
      value: "http://your_proxy:proxy_port"
    - name: NO_PROXY
      value: "10.0.*.*,localhost,kubernetes.default.svc.cluster.local" 
```

2. Build your custom EE
For the generic/common collections that are not updated frequently, you can build your own EE with the collections required and push image to your own (private/public) repo.

Refer this article for detailed:
https://www.linkedin.com/pulse/creating-custom-ee-awx-phil-griffiths/

For me, I use both ways, the first one for checking out my source code to awx project and connect to cloud API for dynamic inventory and the second one to build my EE with several collections that are not include in the default ee image.

Hope this help
