### ISSUE TITLE
Get AWX version from awx-operator repository

### ISSUE THREAD

**Issue by derhoeppi** [ansible/tower-operator#655]
##### ISSUE TYPE
 - Question

##### SUMMARY
To update awx to a specified version we look in every awx-operator release - under /roles/installer/defaults/main.yml. Until awx-operator version 0.13.0 we get the resulting awx version from the var image_version.
In awx-operator version 0.14.0 i can't find informations about the corresponding awx version. 

Is it possible to find the corresponding awx version from the awx-operator github repo?

**Comment by hungtran84** [comment]
@derhoeppi 
The process is:
- clone the repo and checkout `devel` branch
- checkout the specific release such as `git checkout tags/0.14.0`
- build the image locally if it doesn't exist with `make all`. Makefile with take the version value from your current tag.
- deploy the operator with `make deploy`, it will automatically deploy the operator deployment with the version as your tag

If you don't want to build your own operator image but using the existing one. You can change the value here to specify the version and use kustomize or kubectl -k to deploy the operator:

- Specify the operator image version
```yaml
# config/manager/kustomization.yaml
resources:
- manager.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: awx-manager-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: quay.io/ansible/awx-operator
  newTag: <your_version>
```

- Deploy with kustomize
```shell
kustomize build config/default | kubectl apply -f -
```
