### ISSUE TITLE
Respect setting `LOG_AGGREGATOR_LEVEL` for logs going to console

### ISSUE THREAD

**Issue by AlanCoding** [ansible/tower-operator#677]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Looking at the configuration here:

https://github.com/ansible/awx-operator/blob/ebe5d1e2f4afd7fd329c18420947ff5840670293/roles/installer/templates/config.yaml.j2#L64-L69

It appears that it will always send DEBUG logs. Both file-based logs and external log aggregators will decrease the logs they send based on that Configure-Tower-in-Tower setting. OCP installs should probably do the same, but I thought I should raise the question here.

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: X.Y.Z
* Kubernetes version: 
* AWX install method: openshift, minishift, docker on linux, docker for mac, boot2docker

##### STEPS TO REPRODUCE

Change that setting to INFO or WARN

##### EXPECTED RESULTS

expect fewer logs

##### ACTUAL RESULTS

DEBUG logs don't go away, I presume.

**Comment by Cubid** [comment]
Hello,

I managed to update the log level by setting `extra_settings`:

```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-main
spec:
  extra_settings:
    - setting: "LOGGING['handlers']['console']['level']"
      value: "'WARN'"

```
