### ISSUE TITLE
Scaling AWX environment

### ISSUE THREAD

**Issue by rhessing** [ansible/tower-operator#679]
With the new AWX Operator K8S deployment the reason for adding more Tower instances have been reduced to scalability and not high availability (K8S should take care of that). 

However, I've been searching the AWX Operator documentation but haven't found anything in regards to scaling the AWX Tower instances. Is this still possible and if so, how?

**Comment by marekzebro** [comment]
As far I understand from a code, additional AWX instance can be created by using key "replicas"

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  replicas: 2
```
