### ISSUE TITLE
Postgress and AWX wont be scheduled due to PVC 

### ISSUE THREAD

**Issue by indraneeldey1** [ansible/tower-operator#706]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
In trying to do a K8S installation (following the steps outlined [by ComputingForGeeks](https://computingforgeeks.com/how-to-install-ansible-awx-on-ubuntu-linux/) unable to deploy AWX due to a circular dependency like issue. The PVC is created, and is using local persistence to store data. Deploy AWX script and wait for Postgress ( `awx-kind-postgres-0`) to deploy but see this problem of `0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.`

Though I have the PVC built and the describe states `waiting for pod awx-kind-postgres-0 to be scheduled`. 

Also in deployment property `postgres_storage_class` wont override to different storage class.

##### ENVIRONMENT
* AWX version: 0.15.0
* Operator version: 19.5.0 (according to k8s deployment description)
* Kubernetes version: v1.23.1
* AWX install method: AWX makefile and custom K8s Kind AWX (awx.ansible.com/v1beta1)

##### STEPS TO REPRODUCE

1) Deploy AWX operator using make deploy onto K8s cluster under namespace `awx`
2) Create a file for storage class `awx-storage-class.yaml`
3) Create a file for persistence storage claim `awx-persistent-volume-claim.yaml`
4) Create an AWX deployment file `awx-deploy.yaml`

----
`awx-storage-class.yaml`
```yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

`awx-persistent-volume-claim.yaml`
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-data-pvc
  namespace: awx
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"
```

`awx-deploy.yaml`
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-kind
  namespace: awx
spec:
  service_type: nodeport
  projects_persistence: false
  projects_storage_class: local-storage
  projects_storage_access_mode: ReadWriteOnce
  web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/awx/public
  extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName: local-storage-pvc
  postgres_storage_class: local-storage
```

##### EXPECTED RESULTS

To be able to deploy and run all the needed pods

##### ACTUAL RESULTS

AWX 0/4 pods run
Postgress 0/1 pods run
Redis doesnt get deployed at all

##### ADDITIONAL INFORMATION

```text
kubectl get all -n awx
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/awx-kind-8b957d976-f5n88                           0/4     Pending   0          19m
pod/awx-kind-postgres-0                                0/1     Pending   0          19m
pod/awx-operator-controller-manager-7bf76b4c4c-m82hp   2/2     Running   0          21m

NAME                                                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
service/awx-kind-postgres                                 ClusterIP   None             <none>        5432/TCP       19m
service/awx-kind-service                                  NodePort    10.108.234.72    <none>        80:32258/TCP   19m
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.109.172.108   <none>        8443/TCP       21m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-kind                          0/1     1            0           19m
deployment.apps/awx-operator-controller-manager   1/1     1            1           21m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-kind-8b957d976                           1         1         0       19m
replicaset.apps/awx-operator-controller-manager-7bf76b4c4c   1         1         1       21m

NAME                                 READY   AGE
statefulset.apps/awx-kind-postgres   0/1     19m
```
---
```text
kubectl get pod awx-kind-postgres-0 -n awx
NAME                  READY   STATUS    RESTARTS   AGE
awx-kind-postgres-0   0/1     Pending   0          20m
neeld@neeld-test-server:~/tmp$ kubectl describe  pod awx-kind-postgres-0 -n awx
Name:           awx-kind-postgres-0
Namespace:      awx
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/component=database
                app.kubernetes.io/instance=postgres-awx-kind
                app.kubernetes.io/managed-by=awx-operator
                app.kubernetes.io/name=postgres
                app.kubernetes.io/part-of=awx-kind
                controller-revision-hash=awx-kind-postgres-78b96ffcd6
                statefulset.kubernetes.io/pod-name=awx-kind-postgres-0
Annotations:    <none>
Status:         Pending
IP:
IPs:            <none>
Controlled By:  StatefulSet/awx-kind-postgres
Containers:
  postgres:
    Image:      postgres:12
    Port:       5432/TCP
    Host Port:  0/TCP
    Environment:
      POSTGRESQL_DATABASE:        <set to the key 'database' in secret 'awx-kind-postgres-configuration'>  Optional: false
      POSTGRESQL_USER:            <set to the key 'username' in secret 'awx-kind-postgres-configuration'>  Optional: false
      POSTGRESQL_PASSWORD:        <set to the key 'password' in secret 'awx-kind-postgres-configuration'>  Optional: false
      POSTGRES_DB:                <set to the key 'database' in secret 'awx-kind-postgres-configuration'>  Optional: false
      POSTGRES_USER:              <set to the key 'username' in secret 'awx-kind-postgres-configuration'>  Optional: false
      POSTGRES_PASSWORD:          <set to the key 'password' in secret 'awx-kind-postgres-configuration'>  Optional: false
      PGDATA:                     /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS:       --auth-host=scram-sha-256
      POSTGRES_HOST_AUTH_METHOD:  scram-sha-256
    Mounts:
      /var/lib/postgresql/data from postgres (rw,path="data")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-rz4bd (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  postgres:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  postgres-awx-kind-postgres-0
    ReadOnly:   false
  kube-api-access-rz4bd:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  21m                   default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
  Warning  FailedScheduling  6m29s (x14 over 21m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't find available persistent volumes to bind.
```
---
```text
 kubectl get pvc -n awx
NAME                           STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS    AGE
awx-kind-projects-claim        Pending                                      local-storage   21m
postgres-awx-kind-postgres-0   Pending                                      local-storage   21m
static-data-pvc                Pending                                      local-storage   23m
```
---
```text
kubectl describe pvc postgres-awx-kind-postgres-0 -n awx
Name:          postgres-awx-kind-postgres-0
Namespace:     awx
StorageClass:  local-storage
Status:        Pending
Volume:
Labels:        app.kubernetes.io/component=database
               app.kubernetes.io/instance=postgres-awx-kind
               app.kubernetes.io/managed-by=awx-operator
               app.kubernetes.io/name=postgres
Annotations:   <none>
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       awx-kind-postgres-0
Events:
  Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  WaitForFirstConsumer  22m                   persistentvolume-controller  waiting for first consumer to be created before binding
  Normal  WaitForPodScheduled   2m16s (x81 over 22m)  persistentvolume-controller  waiting for pod awx-kind-postgres-0 to be scheduled
```
---
```text
kubectl describe storageclass local-storage
Name:            local-storage
IsDefaultClass:  No
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-storage"},"provisioner":"kubernetes.io/no-provisioner","volumeBindingMode":"WaitForFirstConsumer"}

Provisioner:           kubernetes.io/no-provisioner
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>
```

**Comment by FireDrunk** [comment]
Is the actual PVC up to date with the configuration inside your yml? I've just found this issue because I had (almost) the same issue upon changing some parameters regarding storage configuration.

After deleting the AWX Resoruce I've noticed that the Operator doesn't cleanup the PVC (for obvious reasons), and it also doesn't update the PVC when you change settings in the storage department.

This means that you have to undeploy the AWX resource, delete the PVC manually and redeploy the AWX Resource.

EDIT: Upon re-reading your issue, it seems that you also manually deploy your own PVC, to my understanding you cannot create the claim yourself for Postgres, only for the Projects storage using the `projects_existing_claim` parameter.

**Comment by kurokobo** [comment]
This is not an issue with AWX Operator, but an issue with the way Kubernetes is used.
If you define and use `StorageClass` that uses `kubernetes.io/no-provisioner`, just creating a PVC does not automatically create a PV.

Therefore you should create the appropriate PV that uses the `StorageClass` you defined to make the deployment works.

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  storageClassName: local-storage
  hostPath:
    path: /path/to/your/data/directory
```

**Comment by fredrikwarfvinge** [comment]
@indraneeldey1 Did you manage to solve this issue? I'm running into the same problem once I try and run it through RKE or K3s.

**Comment by indraneeldey1** [comment]
@elitswarfvinge So this is what I had to do to just get the main pods running with this deploy in particular:
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-kind
  namespace: awx
spec:
  service_type: nodeport
  projects_persistence: false
  projects_storage_class: local-storage-sc
  projects_storage_access_mode: ReadWriteMany
  web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/awx/public
  extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName: local-storage-pvc
  postgres_storage_class: local-storage-sc
  postgres_storage_requirements:
    requests:
      storage: 1Gi
    limits:
      storage: 4Gi
```

With this deploy I was able to get it running but then I ran into a second issue where the AWX pod as 4 containers inside of it, awx-web and awx-tasks, both of those were waiting for postgres to do some kind of migration effort, though I couldnt figure out what it was trying to do. I tried to make a secrets file for postgress.

If you do a ```kubectl describe pod [postgres]``` it talks about the secrets it needs. But even after doing so I am stumped on this so giving up for the time being. I'm getting a "Attempting migration" so for some reason it cannot connect to the postgres pod but I was unable to find out what I had to set exactly myself.

 I'm finding AWX Operator instructions are not really designed to be outside of a simple minikube set up,  which makes it difficult because I would like to have this as an internal system to running all the time as I have some good ideas as to what I can make it do. 

Hope this helps
