### ISSUE TITLE
Allow splitting postgres configuration / postgres_configuration_secret

### ISSUE THREAD

**Issue by Nold360** [ansible/tower-operator#754]
##### ISSUE TYPE
 - Bug Report / Feature Request

##### SUMMARY
When using the zalando postgres-operator, it generate a secret containing the username & password for the create database. ATM I can't use that secret with the AWX-Operator without manually modifing/copying it.

##### ENVIRONMENT
* AWX version: 19.5.0
* Operator version: 0.15.0
* Kubernetes version: 1.21
* AWX install method: k3s + operator

##### STEPS TO REPRODUCE

- create postgres db with zalando postgres-operator
- add the generated secret in awx-operators `postgres_configuration_secret`

##### EXPECTED RESULTS

IMHO Username/Password should be seperated from the other configuration options.

##### ACTUAL RESULTS

Doesn't work, because of missing options in the secret & there is no other way to configure the database host/port/...

**Comment by shanemcd** [comment]
Would be happy to review and chat about this more in a PR.

**Comment by jpuskar** [comment]
I just came to write this exact same feature request!

Fundamentally the issue is that the Zalando operator (which is amazing) generates secrets for the Postgres instance users, but the secret name doesn't contain all of the fields that the AWX operator's postges-configuration secret wants to see (hostname, post, type, etc).

I think this is because that often times the postgres fqdn and port are static, but the username and password are not.

Right now we have this property on the AWX CR object:
```yaml
# (under "spec")
postgres_configuration_secret:
    description: Secret where the database configuration can be found
    type: string
```

My preferred fix would be to see an additional (optional) property on the AWX CR object:
```yaml
# (under "spec")
postgres_configuration_secret:
    description: Secret where the database configuration can be found
    type: string
# ...
# New option below!
postgres_credentials_secret:
    description: (Optional) Secret where the database credentials (username and password) can be found
    type: string
```

Even better would be to support username and password keys, which is a relatively common pattern with Bitnami charts. It helps integrate with other operators along the same lines.
```yaml
# (under "spec")
postgres_credentials_secret:
    description: (Optional) Secret where the database credentials (username and password) can be found. If this is specified, it will override the username and password fields of the postgres_configuration_secret.
    type: string
postgres_credentials_secret_username_key:
    description: (Optional) The name of the key from which to read the postgres username. Requires postgres_credentials_secret.
    type: string
    default: "username"
postgres_credentials_secret_password_key:
    description: (Optional) The name of the key from which to read the postgres password. Requires postgres_credentials_secret.
    type: string
    default: "password"
```

The operator's ansible would do the following logic (pseudocode):
```python
If config.get('postgres_credentials_secret'):
    assert postgres_credentials_secret_username_key, \
        'when using postgres_credentials_secret, the config named postgres_credentials_secret_username_key cannot be empty'
    assert postgres_credentials_secret_username_key, \
        'when using postgres_credentials_secret, the config named postgres_credentials_secret_username_key cannot be empty'
    pg_creds_secret = get_k8s_secret(name=postgres_credentials_secret)
    pg_username = pg_creds_secret.data[postgres_credentials_secret_username_key]
    pg_password = pg_creds_secret.data[postgres_credentials_secret_password_key
else:
    do_original_logic()  # use creds from original awx-postgres-configuration secret.
```
