### ISSUE TITLE
[Minikube docker] http2: client connection lost

### ISSUE THREAD

**Issue by cilleain** [ansible/tower-operator#779]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Get an error: http2: client connection lost in _kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager_ when I apply the awx.yml file (_kubectl apply -f awx-demo.yml_).

##### ENVIRONMENT
* Operator version: 0.16.1
* Kubernetes version: 1.23.1
* AWX install method: docker on linux + minikube

##### STEPS TO REPRODUCE

Fallowing the awx-operator official documentation on https://github.com/ansible/awx-operator

```
minikube kubectl apply -f awx-demo.yml
minikube kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager
```
##### EXPECTED RESULTS

AWX working

##### ACTUAL RESULTS

`error: http2: client connection lost`

##### ADDITIONAL INFORMATION

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
```
