### ISSUE TITLE
Custom port for NodePort service is not working on 0.16.1

### ISSUE THREAD

**Issue by ubajze** [ansible/tower-operator#788]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I added the `nodeport_port` variable to the AWX manifest. But the AWX operator still assigns the random port.

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx-test
spec:
  service_type: NodePort
  nodeport_port: 8080
```
```
awx-demo-service                                  NodePort    10.104.220.226   <none>        80:31838/TCP   15m
```

I checked history on the `roles/installer/templates/service.yaml.j2` file.
https://github.com/ansible/awx-operator/commits/devel/roles/installer/templates/service.yaml.j2

It looks like the feature was added with this commit:
https://github.com/ansible/awx-operator/commit/9b072aa5490f46d6ceb437a42a49285d02cc2e17

But it was removed with the next commit:
https://github.com/ansible/awx-operator/commit/e97def44296aec7f1fd29e3e228e0671b946b34f

##### ENVIRONMENT
* AWX version: 19.5.1
* Operator version: 0.16.1
* Kubernetes version: 
* AWX install method: minikube

##### STEPS TO REPRODUCE

* Deploy AWX operator 0.16.1
* Create AWX manifest:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
  namespace: awx-test
spec:
  service_type: NodePort
  nodeport_port: 8080
```
* Check the service port

##### EXPECTED RESULTS

I expect that the service will be listening on the specified port.

##### ACTUAL RESULTS

Service is listening on the random port.

**Comment by DomPolizzi** [comment]
Also Dealing with this, thought this would be patched in version 0.17.0.

I thought my code was bad when this kept happening; but,  it seems like a well-known bug that has been in progress of being fixed(?)

I am curious of what Solutions other people are conducting. . .

For reference, my current code is:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: dev-awx-env
  labels:
    app: awx
  namespace: dev-awx
spec:
  replicas: 3
  service_type: nodeport
  nodeport_port: 30626
```

I did search heavily into the repo and I see it is defined in:
`awx-operator>config>crd>bases>awx.ansible.com_awxs.yaml`
with port `30080` set as default ( line 133)

No matter the value placed, I still get a random port assigned. At this stage, I am guessing this does not allow customization as intended.

I tried other code such as:
```
spec:
  ports:
  - port: 80
    targetPort: 30626
    nodePort: 30080
    protocol: TCP
```

No Dice :(
