### ISSUE TITLE
BUG: awx-operator ignores input values

### ISSUE THREAD

**Issue by guliaka** [ansible/tower-operator#794]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx-operator ignores input values. Here is my AWX instance deployment:

```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-tower
  namespace: awx
spec:
  service_type: LoadBalancer
  loadbalancer_protocol: https
  loadbalancer_port: 443
  ingress_type: none
  ldap_cacert_secret: awx-custom-certs
  bundle_cacert_secret: awx-custom-certs
  redis_image: vm-its-harbor.getty.edu/dokerhub/library/redis
  redis_image_version: latest

```
  
  
In Deployment for AWX instance still pulls redis image from Docker Hub.  
  
##### ENVIRONMENT
* AWX version: 19.5.1
* Operator version: 0.16.1
* Kubernetes version:  1.22.3
* AWX install method: openshift (OKD 4.9.0-0.okd-2022-02-12-140851)  
  
##### EXPECTED RESULTS

Expect redis image to be pulled from local repo  
  
##### ACTUAL RESULTS

It try to pull image from Docker Hub

**Comment by guliaka** [comment]
Any news or updates to this??

**Comment by rguhr** [comment]
@guliaka I'm not a dev of this project but I checked if it's working for me.

I was apply to change the redis image:
```
k get pods awx-test-6d8d57554-2ddb5 -oyaml | grep image -A1 | grep redis -A1
    image: vm-its-harbor.getty.edu/dokerhub/library/redis:latest
    imagePullPolicy: IfNotPresent
    name: redis
```

I use awx-operator:0.17.0 and awx:19.5.0
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-test
  namespace: awx-test
spec:
  image: "{{ _image }}" # Is needed otherwise image_version is ignored
  image_version: 19.5.0
  service_type: NodePort

  #replicas: 1

  web_resource_requirements:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  task_resource_requirements:
    requests:
      #cpu: 2000m -> Not supported with 19.5.0 awx image
      #memory: 8Gi -> Not supported with 19.5.0 awx image
      cpu: "2"
      memory: "8589934592"
    limits:
      #cpu: 2000m -> Not supported with 19.5.0 awx image
      #memory: 8Gi -> Not supported with 19.5.0 awx image
      cpu: "2"
      #memory: "8589934592" -> django.db.utils.DataError: integer out of range

  ee_images:
    - name: xxx
      image: <private-reg>/awx-ee:latest
  ee_pull_credentials_secret: awx-test-ee-pull-credentials
  redis_image: vm-its-harbor.getty.edu/dokerhub/library/redis
  redis_image_version: latest

```


Is `AWX version: 19.5.1` the first version you installed or did you come from an older version?  
If you came from an older release maybe some old stuff is messing around. There is section for upgrading from older releases: https://github.com/ansible/awx-operator#upgrading
