### ISSUE TITLE
Image version is ignored by operator

### ISSUE THREAD

**Issue by uznog** [ansible/tower-operator#805]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`image_version` spec is being ignored and operator is always installing 20.0.0 (or latest, perhaps).

##### ENVIRONMENT
* AWX version: 19.5.0 / 20.0.0
* Operator version: 0.17.0
* Kubernetes version: v1.21.1
* AWX install method: Kind

##### STEPS TO REPRODUCE

Kind cluster configuration:
```yaml
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
- role: worker
```

AWX object manifest:
```yaml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: NodePort
  nodeport_port: 30000
  image_pull_policy: Always
  image_version: 19.5.1
```

##### EXPECTED RESULTS

Operator installs version 19.5.1

##### ACTUAL RESULTS

20.0.0 is installed:
```
awx-app-74fb654997-xdzzr:       
docker.io/redis:latest
quay.io/ansible/awx:20.0.0
quay.io/ansible/awx:20.0.0
quay.io/ansible/awx-ee:latest
```

**Comment by uznog** [comment]
Might be a duplicate of #794

**Comment by MrBones757** [comment]
if you set image and image version it correctly accepts the values, just some re-work needed in the string generation by the looks :)
https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/resources_configuration.yml#L39

**Comment by nixocio** [comment]
hey @rooftopcellist, please, can you take a look at this when you have a minute?

**Comment by kurokobo** [comment]
@uznog 
In current implementation, both `image` and `image_version` have to be specified to take effect. This behavior came with following `when` statement.
https://github.com/ansible/awx-operator/blob/fbc2d3475c36a44c3d699303882c436a455b43cb/roles/installer/tasks/resources_configuration.yml#L39-L44

So you should specify like this:

```yaml
spec:
  ...
  image: quay.io/ansible
  image_version: 19.5.1
```

But in the first place, you shoud note that changing AWX version from default is currently not supported:
> Note: The `image` and `image_version` are intended for local mirroring scenarios. Please note that using a version of AWX other than the one bundled with the `awx-operator` is not supported.
> https://github.com/ansible/awx-operator#deploying-a-specific-version-of-awx
