### ISSUE TITLE
Operator first use: does not create database in unmanaged method

### ISSUE THREAD

**Issue by MaartenMol** [ansible/tower-operator#806]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Trying to install AWX 20.0.0 using Operator 17.0.0. Specifing all that is stated in the install documentation. It does not create the database in the PostgreSQL server. Even if I create the database myself, the operator won't provision the database so AWX does never start. Says it's waiting for migration, forever.

##### ENVIRONMENT
* AWX version: 20.0.0
* Operator version: 17.0.0
* Kubernetes version: 1.19.9
* AWX install method: Kubernetes deployed with Kubespray

##### STEPS TO REPRODUCE

Follow the guide from documentation. See config files below. All secret values are base64 encoded.

##### EXPECTED RESULTS

Operator to create or provision the database so AWX can actually start?

##### ACTUAL RESULTS

The operator log shows all ok and few changes, no errors. But the AWX web and task containers still say it's waiting for migration of the database.

##### ADDITIONAL INFORMATION

```
cat awx.yml
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-prod
  namespace: dhs-addcontrol-awx
spec:
  service_type: ClusterIP
  ingress_type: none
  postgres_configuration_secret: awx-prod-postgres-configuration
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-prod-postgres-configuration
  namespace: dhs-addcontrol-awx
stringData:
  #host: MTcyLjMxLjI1MC44NQ==
  host: MTcyLjI3LjcyLjY4
  port: NTQzMg==
  database: YXd4Mg==
  username: YXd4
  password: ******
  sslmode: YWxsb3c=
  type: dW5tYW5hZ2Vk
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-prod
    app.kubernetes.io/part-of: awx
  name: awx-prod-nodeport
  namespace: dhs-addcontrol-awx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      targetPort: 8052
      name: http
  selector:
      app.kubernetes.io/component: awx
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/name: awx-prod
```

##### AWX-OPERATOR LOGS

Please see: https://gist.github.com/MaartenMol/d2b1cab00d7e91da07fe343cb4ab277d
