### ISSUE TITLE
Deployment fails if the `service_type` is set to `NodePort`

### ISSUE THREAD

**Issue by kurokobo** [ansible/tower-operator#814]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

If the `NodePort` has specified as `service_type` field in AWX resource, its deployment will be failed.
This came with the PR #789 which released in 0.18.0.

##### ENVIRONMENT
* AWX version: 20.0.1
* Operator version: 0.18.0
* Kubernetes version: v1.22.6+k3s1
* AWX install method: K3s

##### STEPS TO REPRODUCE

1. Deploy AWX Operator 0.18.0
2. Deploy AWX which includes `service_type: nodeport`

##### EXPECTED RESULTS

AWX instance will be deployed.

##### ACTUAL RESULTS

AWX instance will never be deployed.

##### ADDITIONAL INFORMATION

I've made investigation by:

- removing `no_log: true`,
- adding new task to dump YAML [before applying](https://github.com/ansible/awx-operator/blob/0.18.0/roles/installer/tasks/resources_configuration.yml#L20-L33),
- building new image for operator and deploy with `IMG=registry.example.com/awx/awx-operator:0.18.0 make deploy`

and I found the `service.yaml` has been corrupted. This is the `service.yaml` generated by `installer` role in 0.18.0.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: 'awx-service'
  namespace: 'awx'
  labels:
    app.kubernetes.io/name: 'awx'
    app.kubernetes.io/part-of: 'awx'
    app.kubernetes.io/managed-by: 'awx-operator'
    app.kubernetes.io/component: 'awx'
    app.kubernetes.io/operator-version: ''
    
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8052
      name: http     👈👈👈
    - port: 30080
      protocol: TCP
      targetPort: 8052
      name: http     👈👈👈
  type: NodePort     👈👈👈
  selector:
    app.kubernetes.io/name: 'awx'
    app.kubernetes.io/managed-by: 'awx-operator'
    app.kubernetes.io/component: 'awx'
  type: ClusterIP     👈👈👈
```

There are two problems;

- The name `http` is duplicated. It's not allowed by API.
- The `type` is duplicated. `NodePort` will be ignored.
- In addition, there is no `nodePort` as mentioned in #535. `nodeport_port` won't be worked as expected.

In fact, this YAML can't be applyed manually.

```bash
$ kubectl -n awx apply -f service.yaml 
The Service "awx-service" is invalid: spec.ports[1].name: Duplicate value: "http"
```

##### AWX-OPERATOR LOGS

The Operator's log includes same `Duplicate value` error. This is the log after removing `no_log: true`.

```bash
=> {\"ansible_loop_var\": \"item\", \"changed\": false, \"error\": 422, \"item\": \"service\", \"msg\": \"Failed to apply object: 
b'{\\\"kind\\\":\\\"Status\\\",\\\"apiVersion\\\":\\\"v1\\\",\\\"metadata\\\":{},\\\"status\\\":\\\"Failure\\\",\\\"message\\\":\\\"Service 
\\\\\\\\\\\"awx-service\\\\\\\\\\\" is invalid: spec.ports[1].name: Duplicate value: 
\\\\\\\\\\\"http\\\\\\\\\\\"\\\",\\\"reason\\\":\\\"Invalid\\\",\\\"details\\\":{\\\"name\\\":\\\"awx-service\\\",\\\"kind\\\":\\\"Service\\\",\\\"cau
ses\\\":[{\\\"reason\\\":\\\"FieldValueDuplicate\\\",\\\"message\\\":\\\"Duplicate value: 
\\\\\\\\\\\"http\\\\\\\\\\\"\\\",\\\"field\\\":\\\"spec.ports[1].name\\\"}]},\\\"code\\\":422}\\\\n'\", \"reason\": \"Unprocessable Entity\", 
\"status\": 422}\nok: [localhost] => (item=ingress) => {\"ansible_loop_var\": \"item\", \"changed\": false, \"item\": \"ingress\", \"result\": 
{\"results\": []}}\n\r\nPLAY RECAP *********************************************************************\r\nlocalhost                  : ok=39   
changed=1    unreachable=0    failed=1    skipped=28   rescued=0    ignored=0   
\r\n\n","job":"6513666643038486040","name":"awx","namespace":"awx","error":"exit status 2"}
```

A bit hard to read, but there is `message\\\":\\\"Service \\\\\\\\\\\"awx-service\\\\\\\\\\\" is invalid: spec.ports[1].name: Duplicate value: \\\\\\\\\\\"http\\\\\\\\\\\"\\\"`

**Comment by moomin893** [comment]
@kurokobo 
I'm sorry.
Please tell me.

I suffer from the same problem.
I deleted the service type:nodeport and the AWX- service was started.
However, I would like to solve this problem because I want to use it with service type:nodeport.

I am using AWX-Operator 021.0
I prefer to use this version as much as possible.

awx.yml
```
---
apiVersion: awx.ansible.com/v1betal
kind: AWX
metadata:
  name: awx
spec:
   service_type: nodeport
   nodeport_port: 30080

```
