### ISSUE TITLE
Misleading variable name: control_plane_ee_image

### ISSUE THREAD

**Issue by rguhr** [ansible/tower-operator#821]
##### ISSUE TYPE
 - Documentation

##### SUMMARY
The name of the variable `control_plane_ee_image` suggests it would change the image for "Control Plane Execution Environment" within AWX. This seems not to be the case, it only changes the image for the bundled <resource-name>-ee container whose only purpose in life seems to be to download project updates (?).

Something is odd here. Either the updated image is not corretly displayed in AWX GUI or the variable name is misleading and should rename to something better to indicate that it has nothing to do with the "Control Plane Execution Environment" within AWX.
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-test
  namespace: awx-test
spec:
  image_pull_secret: awx-test-cp-pull-credentials
  control_plane_ee_image: <private-registry>/containers/awx-ee:latest
```
![Control Plane Execution Environment within AWX](https://i.imgur.com/VCtDtb0.png)

##### ENVIRONMENT
* AWX version: 20.0.0
* Operator version: 17.0.0
* Kubernetes version: v1.20.7
* AWX install method: k8s
