### ISSUE TITLE
image_version can't be used alone

### ISSUE THREAD

**Issue by rguhr** [ansible/tower-operator#829]
##### ISSUE TYPE
 - Feature request

##### SUMMARY

Because of current [bugs](https://github.com/ansible/awx/issues/11765) in upstream AWX we want to change the AWX version with `image_version`. But this will be ignored if `image` is not also set.

```
- name: Set user provided awx app image
  set_fact:
    _custom_image: "{{ image }}:{{ image_version }}"
  when:
    - image | default([]) | length
    - image_version is defined or image_version != ''
```
https://github.com/ansible/awx-operator/blob/devel/roles/installer/tasks/resources_configuration.yml#L42

##### ENVIRONMENT
* Operator version: 0.18.0

##### WORKAROUND
As workaround you can also defined `image` and point it to the default value:
```
[...]
spec:
  image: "{{ _image }}"
  image_version: 19.5.0
```
_(Yes, we know that only the awx version that comes bundled with the awx operator is supported)_
