### ISSUE TITLE
Upgrade AWX doesn't work because of Unable to attach or mount volumes error for [check-db-pvc]

### ISSUE THREAD

**Issue by auroraqin** [ansible/tower-operator#830]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 19.5.1
* Operator version: 0.16.1
* Kubernetes version: 1.20.8
* AWX install method: openshift

##### STEPS TO REPRODUCE

Installed AWX 19.5.1 with operator 0.16.1 by following the basic installation guide, database is managed postgres in cluster. Then want to upgrade AWX to the latest 20.0.0, the upgrade step is

oc delete deployment "awx-operator-controller-manager"
git clone the latest 0.17.0
export NAMESPACE=_myworkspace_
make deploy
upgdate the image version from awx deployment

Expect the AWX version can be upgraded to 20.0.0

##### ACTUAL RESULTS

The new awx operator controller manager is deployed, and another awx deployment generated with the new image version, but the pods hanging on init because of Unable to attach or mount volumes error for [check-db-pvc]

**Comment by ivladucu** [comment]
Hi, this should be fixed in 0.18.0, but until then, you can use node_selectors for postgres and tower, make sure to deploy them on the same node.
Here's an example from my deployment:
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: tower
  namespace: awx-staging
spec:
  service_type: nodeport
  postgres_storage_class: 'vsphere'
  postgres_selector: |
    kubernetes.io/hostname: awx-staging-2
  node_selector:  |
    kubernetes.io/hostname: awx-staging-2
```
