### ISSUE TITLE
awx-operator image is set to latest

### ISSUE THREAD

**Issue by kristiwedertz** [ansible/tower-operator#834]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
awx-manager container image is not pinned to the version of awx-operator deployed

##### ENVIRONMENT
* AWX version: 20.0.1
* Operator version: 0.18.0
* Kubernetes version: 1.18.20
* AWX install method: kubernetes cluster

##### STEPS TO REPRODUCE
1. Follow install instructions for existing cluster: https://github.com/ansible/awx-operator#basic-install-on-existing-cluster
2. Describe the awx-operator deployment. Image is set to quay.io/ansible/awx-operator:latest

This is causing unpredictable results when a failure occurs and pods are redeployed.

##### EXPECTED RESULTS
Expected output: awx-manager image is pinned to awx-operator version deployed
```
    spec:
      containers:
...
        image: quay.io/ansible/awx-operator:0.18.0
        name: awx-manager
```
##### ACTUAL RESULTS
Actual output: awx-manager image is pinned to latest
```
    spec:
      containers:
...
      - args:
        - --health-probe-bind-address=:6789
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        - --leader-election-id=awx-operator
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: ANSIBLE_DEBUG_LOGS
          value: "false"
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: quay.io/ansible/awx-operator:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 6789
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: awx-manager
```
