### ISSUE TITLE
Controller Deployment produced by Operator does not contain an initContainers: diction even with .spec.bundle_cacert_secret set

### ISSUE THREAD

**Issue by the-it-jaeger** [ansible/tower-operator#836]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
**Note:** I am using the AAP Operator 2.1.1, but the relevant code appears identical, so I am hoping to get some help here.

The AAP Controller Deployment created by the Operator does not contain an `.spec.template.spec.initContainers:` dictionary/section even when `bundle_cacert_secret` is set properly. This causes `/etc/pki/tls/certs/ca-bundle.crt` to point to nothing. The sub-directory creation in `/etc/pki/ca-trust/extracted` and the `update-ca-trust` command are not run by the `init` container, and external connections to Git servers with Custom CA certs fail causing project syncs to fail.

##### ENVIRONMENT
* AWX version: 4.1.1
* Operator version: 2.1.1
* Kubernetes version: 1.22.3
* AWX install method: openshift

##### STEPS TO REPRODUCE

Create an AutomationController CR:

```
---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  name: aap-controller
  namespace: ansible-automation-platform
spec:
  admin_user: admin
  bundle_cacert_secret: aap-controller-custom-certs
  create_preload_data: false
  garbage_collect_secrets: false
  image_pull_policy: IfNotPresent
  ldap_cacert_secret: aap-controller-custom-certs
  loadbalancer_port: 80
  loadbalancer_protocol: http
  nodeport_port: 30080  
  postgres_storage_class: ocs-storagecluster-cephfs
  projects_persistence: true
  projects_storage_access_mode: ReadWriteMany
  projects_storage_class: ocs-storagecluster-cephfs
  projects_storage_size: 8Gi
  replicas: 2
  route_tls_termination_mechanism: Edge
  task_privileged: false
```

##### EXPECTED RESULTS

I expect Project syncs to work when connecting to git servers employing certs signed by CAs contained in `bundle_cacert_secret: aap-controller-custom-certs`

##### ACTUAL RESULTS

Project sync failure:
```
  "stderr_lines": [
    "fatal: unable to access 'https://git.example.com/Aaron-Jaeger/scm-iris-deployment.git/': error setting certificate verify locations:",
    "  CAfile: /etc/pki/tls/certs/ca-bundle.crt",
    "  CApath: none"
  ]
```

##### ADDITIONAL INFORMATION

Strangely, the certs inside of `bundle_cacert_secret: aap-controller-custom-certs` show up when I get into the containers and run `trust list | grep ... `

If I go manually do the steps the `init` container is supposed to perform (create directories under /etc/pki/ca-trust/extracted and run update-ca-trust) Project syncs start working.
