### ISSUE TITLE
Add docs for proper kustomization installs

### ISSUE THREAD

**Issue by mac-chaffee** [ansible/tower-operator#840]
Currently, the docs recommend cloning the repo and running `make deploy`, which runs the `kustomize build` step.

For users who want to provide their own kustomizations, that is possible by just creating a `kustomization.yaml` file like the following, which avoids the need to clone the repo:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Note the ref points to a specific git tag
- github.com/ansible/awx-operator/config/default?ref=0.18.0
- awx.yaml

namespace: mynamespace

# put patches here
```

and the file awx.yaml:

```yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: my-awx
spec:
  ...
```

then running `kustomize build . | kubectl apply -f -` (may need to run twice for the CRD to be applied).

The kustomize docs are light on details about this kind of setup, but I believe it's the preferred way to do things, almost equivalent to creating an umbrella helm chart that includes the subchart as a dependency in Chart.yaml with custom values or other resources.

This approach has been working for [gatekeeper-library](https://github.com/open-policy-agent/gatekeeper-library#kustomize) and [metallb](https://metallb.org/installation/#installation-with-kustomize).

I can provide a PR if interested.

**Comment by bendews** [comment]
+1, this is what I have been doing for deployments rather than `make`.

I found that I also had to add a tag override for the image as otherwise it would default to `latest`, not what you want if you are running an old tag against a new operator image (I.E don't want to run 0.14.0 manifests and pull down a 0.18.0 operator image). My Kustomise looks like this:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx
generatorOptions:
  disableNameSuffixHash: true

resources:
  - github.com/ansible/awx-operator/config/default?ref=0.18.0
  - awx.yml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.18.0
```
