### ISSUE TITLE
unhealthy nodes with AWS ALB

### ISSUE THREAD

**Issue by RogerSik** [ansible/tower-operator#854]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I don't know to proceed with troubleshooting.

An existing (working) AWX will be now moved from m8kubernetes to AWS EKS 1.21

The 
![01_16-25-36-Target groups _ EC2 Management Console und 12 weitere Seiten - r sikorski@baseco](https://user-images.githubusercontent.com/165814/161283376-d5bd58ff-a4b0-47d6-9c77-9d141529a710.png)
nodes are reported by AWS Health not healthy (please ignore port 80, it was a manuel test by myself)

When open the site i get the "502 Bad Gateway" error website from AWS LB. 

Attach which files are used: 

**kustomization.yml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=0.20.0
  - awx.yml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: "0.20.0"

# Specify a custom namespace in which to install AWX
namespace: awx
```

**awx.yml**
```
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
stringData:
  host: "awx.xxxxxxx.eu-central-1.rds.amazonaws.com"
  port: "5432"
  database: "xxx"
  username: "xxx"
  password: "xxxxxxx"
  sslmode: disable
  type: unmanaged
type: Opaque

---
# AWX Secret Key
apiVersion: v1
kind: Secret
metadata:
  name: awx-secret-key
  namespace: awx
data:
  secret_key: xxxxxxxxx
type: Opaque

---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  # Connection Info
  hostname: "awx.example.org"
  ingress_type: Ingress
  ingress_path: "/"
  loadbalancer_protocol: http
  loadbalancer_port: 80
  # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/
  # https://github.com/ansible/awx-operator/issues/455
  ingress_annotations: |
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: awx
    alb.ingress.kubernetes.io/tags: Service=AWX
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30,stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
    alb.ingress.kubernetes.io/security-groups: sg-03d3fa2c89d23eff1

    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:3XXXXXXXXXXXXXX0d"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10

    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10

  node_selector: |
    Environment: AWX

  secret_key_secret: "awx-secret-key"
```

##### ENVIRONMENT
* AWX version: X.Y.Z
* Operator version: 0.20.0
* Kubernetes version: 1.21
* AWX install method: eks

##### EXPECTED RESULTS

A working awx website.

##### AWX-OPERATOR LOGS

https://gist.github.com/RogerSik/a3ab1c9d2a3ffe5e8e5ae82034b9f89d
