### ISSUE TITLE
Not able to expose service with Ingress - Service does not have any active Endpoint

### ISSUE THREAD

**Issue by prinzpi** [ansible/tower-operator#859]
ISSUE TYPE
- Bug Report / miss-configuration (not sure)

Components
- Ingress

ENVIRONMENT
- AWX version: 0.20.0
- kubernetes version: 1.23.3
- minikube version: v1.25.2 
- AWX install method: minikube

SUMMARY
I'm trying to expose the awx-operator service with ingress. I'm always receiving that there is no active endpoint, but there actually is?!

I'm using `awx.yaml`, `awx-ingress.yaml` file and build it with a `kustomization.yaml` file.

$ cat awx.yaml
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx-operator
spec:
  service_type: NodePort
  nodeport_port: 30080
  ingress_type: none
```

$ cat awx-ingress.yaml 
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-test-ingress
  namespace: awx-operator
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: awx.company.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: awx-service
                port:
                  number: 80

```

$ cat kustomization.yaml 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=0.20.0
  - awx.yaml
  - awx-ingress.yaml

images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.20.0

namespace: awx-operator
```

$ kubectl get svc
```
NAME                                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
awx-operator-controller-manager-metrics-service   ClusterIP   10.101.137.93    <none>        8443/TCP       24h
awx-postgres                                      ClusterIP   None             <none>        5432/TCP       24h
awx-service                                       NodePort    10.104.141.231   <none>        80:30080/TCP   24h
```

$ kubectl get ingress --all-namespaces
```
NAMESPACE      NAME               CLASS   HOSTS               ADDRESS        PORTS   AGE
awx-operator   awx-test-ingress   nginx   awx.company.com   192.168.49.2   80      5h4m

```

$ kubectl describe ingress
```
Name:             awx-test-ingress
Labels:           <none>
Namespace:     awx-operator
Address:          192.168.49.2
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host               Path  Backends
  ----               ----  --------
  awx.company.com  
                     /   awx-service:80 (172.17.0.5:8052)
Annotations:         nginx.ingress.kubernetes.io/rewrite-target: /
Events:
  Type    Reason  Age                   From                      Message
  ----    ------  ----                  ----                      -------
  Normal  Sync    28m (x12 over 4h13m)  nginx-ingress-controller  Scheduled for sync
```
--> The event regarding sync will be dissapear, regarding a lot of changes sometimes I can see this kind of event. 

$ kubectl get endpoints
```
NAME                                              ENDPOINTS         AGE
awx-operator-controller-manager-metrics-service   172.17.0.3:8443   24h
awx-postgres                                      172.17.0.6:5432   24h
awx-service                                       172.17.0.5:8052   24h
```

$ curl -vvv -I awx.company.com
```
*   Trying 192.168.49.2:80...
* TCP_NODELAY set
* Connected to awx.company.com (192.168.49.2) port 80 (#0)
> HEAD / HTTP/1.1
> Host: awx.company.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 502 Bad Gateway
HTTP/1.1 502 Bad Gateway
< Date: Tue, 05 Apr 2022 13:54:02 GMT
Date: Tue, 05 Apr 2022 13:54:02 GMT
< Content-Type: text/html
Content-Type: text/html
< Content-Length: 150
Content-Length: 150
< Connection: keep-alive
Connection: keep-alive

< 
* Connection #0 to host awx.company.com left intact
```

$ kubectl get pods -n ingress-nginx
```
NAME                                       READY   STATUS      RESTARTS        AGE
ingress-nginx-admission-create-wf7rs       0/1     Completed   0               3d22h
ingress-nginx-admission-patch-vx66f        0/1     Completed   0               3d22h
ingress-nginx-controller-cc8496874-2xnhj   1/1     Running     4 (4h18m ago)   3d22h
```

$ kubectl logs -n ingress-nginx ingress-nginx-controller-cc8496874-2xnhj
```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:       v1.1.1
  Build:         a17181e43ec85534a6fea968d95d019c5a4bc8cf
  Repository:    https://github.com/kubernetes/ingress-nginx
  nginx version: nginx/1.19.9

2022/04/05 13:54:02 [error] 2458#2458: *500475 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.49.1, server: awx.company.com, request: "HEAD / HTTP/1.1", upstream: "http://172.17.0.5:8052/", host: "awx.company.com"
2022/04/05 13:54:02 [error] 2458#2458: *500475 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.49.1, server: awx.company.com, request: "HEAD / HTTP/1.1", upstream: "http://172.17.0.5:8052/", host: "awx.company.com"
2022/04/05 13:54:02 [error] 2458#2458: *500475 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.49.1, server: awx.company.com, request: "HEAD / HTTP/1.1", upstream: "http://172.17.0.5:8052/", host: "awx.company.com"
192.168.49.1 - - [05/Apr/2022:13:54:02 +0000] "HEAD / HTTP/1.1" 502 0 "-" "curl/7.68.0" 82 0.001 [awx-operator-awx-service-80] [] 172.17.0.5:8052, 172.17.0.5:8052, 172.17.0.5:8052 0, 0, 0 0.000, 0.000, 0.000 502, 502, 502 11353031a312abdd5e7efe9aaba83379
W0405 13:54:13.091656       8 controller.go:1083] Service "awx-operator/awx-service" does not have any active Endpoint.
W0405 13:54:30.266952       8 controller.go:1083] Service "awx-operator/awx-service" does not have any active Endpoint.
```

--> the connect failed (111: connection refused) will be logged after executing a curl command on "awx.company.com" which is definied in the `/etc/hosts`:
`192.168.49.2 awx.company.com`

What I'm doing wrong here?
Spent a lot of time here and do not have any glue anymore what's wrong here.
