### ISSUE TITLE
security_context_settings won't work

### ISSUE THREAD

**Issue by PaulVerhoeven1** [ansible/tower-operator#890]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

In our network we have Open Policy Agent running which forces us to use non root containers. So we need to use non root containers or setting a custom security_context_settings parameter which overwrites the default user. 
In the following commit https://github.com/ansible/awx-operator/commit/138964f7ab6089628ecc3ab38699403b5a55cb7f and PR https://github.com/ansible/awx-operator/pull/645
i can see that there is a way to specify a custom runAsUser and runAsGroup variable 

example code from above:

```
security_context_settings:
  runAsUser: 1000
  runAsGroup: 1000
```

If i set these settings in my yaml op the awx-operator, it won't work
```
9m36s       Normal    Pulled                   pod/awx-postgres-0          Successfully pulled image "<private_registry>/centos/centos:stream8" in 15.126499374s
7m29s       Warning   Failed                   pod/awx-postgres-0          Error: container has runAsNonRoot and image will run as root (pod: "awx-postgres-0_awx(c2f22b67-a6eb-4a32-b35a-61ca7cc9905b)", container: database-check)
```

##### ENVIRONMENT
* AWX version: devel
* Operator version: devel
* Kubernetes version: v1.20.11-eks-f17b81
* AWX install method: kubernetes on EKS

##### STEPS TO REPRODUCE

Deploying the awx operator (based on the minikube steps)

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: nodeport
  postgres_image: <private_registry>/bitnami/postgresql
  postgres_image_version: "14.2.0"
  init_container_image: <private_registry>/centos/centos
  init_container_image_version: "stream8"
  redis_image: <private_registry>/bitnami/redis
  redis_image_version: "latest"
  task_privileged: false
  image: <private_registry>/ansible/awx-operator
  image_version: "devel"
  ee_images:
    - name: awx-ee
      image: <private_registry>/ansible/awx-ee:0.6.0
  security_context_settings:
    runAsUser: 1000
    runAsGroup: 1000

```

##### EXPECTED RESULTS

That the containers that the operator uses (such as the database-check) will use the custom runAsUser and runAsGroup variables 

##### ACTUAL RESULTS

It won't work beceause the containers still starts as root while i specify a custom user in the security_context_settings settings.
related issue: https://github.com/ansible/awx-operator/issues/383
