### ISSUE TITLE
AWX Kind not found by core.k8s module

### ISSUE THREAD

**Issue by aleksandar-kinanov** [ansible/tower-operator#898]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When using **kubernetes.core.k8s** to install AWX Operator as well as AWX itself, the following error gets thrown:
`FAILED! => {"changed": false, "msg": "Failed to find exact match for awx.ansible.com/v1beta1.AWX by [kind, name, singularName, shortNames]"}`

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 0.20.2
* Kubernetes version: 1.23.3
* AWX install method: minikube - baremetal

##### STEPS TO REPRODUCE

1. Start Minikube with the following command: `minikube start --network-plugin=cni --cni=flannel --driver=none`
2. Add CNI Plugin (Flannel) - `minikube kubectl -- apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml`
3. Enable ingress - `minikube addons enable ingress`

**kustomization.yaml**
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=0.20.2
  - awx.yaml
  - ingress.yaml

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.20.2

# Specify a custom namespace in which to install AWX
namespace: awx
```

**awx.yaml**
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-demo
spec:
  service_type: nodeport
```

**ingress.yaml**
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
spec:
  rules:
    - host: some-host.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: awx-demo-service
                port:
                  number: 80
```

Role used to apply the configuration
```
- name: Create a Service object from an inline definition
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('pipe', 'kustomize build {{ role_path }}/files/' ) }}"
    wait: yes
    wait_sleep: 10
    wait_timeout: 600
```

##### EXPECTED RESULTS

Successfully starting an AWX Instance

##### ACTUAL RESULTS

`fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to find exact match for awx.ansible.com/v1beta1.AWX by [kind, name, singularName, shortNames]"}`

##### ADDITIONAL INFORMATION

When run manually as per the guide with `kustomize build . | kubectl apply -f -`, the output is the following:
```
namespace/awx created
customresourcedefinition.apiextensions.k8s.io/awxbackups.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxrestores.awx.ansible.com created
customresourcedefinition.apiextensions.k8s.io/awxs.awx.ansible.com created
serviceaccount/awx-operator-controller-manager created
role.rbac.authorization.k8s.io/awx-operator-awx-manager-role created
role.rbac.authorization.k8s.io/awx-operator-leader-election-role created
clusterrole.rbac.authorization.k8s.io/awx-operator-metrics-reader created
clusterrole.rbac.authorization.k8s.io/awx-operator-proxy-role created
rolebinding.rbac.authorization.k8s.io/awx-operator-awx-manager-rolebinding created
rolebinding.rbac.authorization.k8s.io/awx-operator-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/awx-operator-proxy-rolebinding created
configmap/awx-operator-awx-manager-config created
service/awx-operator-controller-manager-metrics-service created
deployment.apps/awx-operator-controller-manager created
ingress.networking.k8s.io/example-ingress created
error: unable to recognize "STDIN": no matches for kind "AWX" in version "awx.ansible.com/v1beta1"
```

If rerun second time, everything is fine

##### AWX-OPERATOR LOGS
```
{"level":"info","ts":1651476687.8466725,"logger":"cmd","msg":"Version","Go Version":"go1.16.9","GOOS":"linux","GOARCH":"amd64","ansible-operator":"v1.12.0","commit":"d3b2761afdb78f629a7eaf4461b0fb8ae3b02860"}
{"level":"info","ts":1651476687.846885,"logger":"cmd","msg":"Watching single namespace.","Namespace":"awx"}
{"level":"info","ts":1651476688.000972,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":1651476688.0014596,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWX_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1651476688.0015314,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWXBACKUP_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1651476688.0015562,"logger":"watches","msg":"Environment variable not set; using default value","envVar":"ANSIBLE_VERBOSITY_AWXRESTORE_AWX_ANSIBLE_COM","default":2}
{"level":"info","ts":1651476688.0015833,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWX"}
{"level":"info","ts":1651476688.0016887,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWXBackup"}
{"level":"info","ts":1651476688.0017369,"logger":"ansible-controller","msg":"Watching resource","Options.Group":"awx.ansible.com","Options.Version":"v1beta1","Options.Kind":"AWXRestore"}
{"level":"info","ts":1651476688.0037973,"logger":"proxy","msg":"Starting to serve","Address":"127.0.0.1:8888"}
{"level":"info","ts":1651476688.0041904,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I0502 07:31:28.004149       7 leaderelection.go:243] attempting to acquire leader lease awx/awx-operator...
I0502 07:31:28.010355       7 leaderelection.go:253] successfully acquired lease awx/awx-operator
{"level":"info","ts":1651476688.0105393,"logger":"controller-runtime.manager.controller.awxrestore-controller","msg":"Starting EventSource","source":"kind source: awx.ansible.com/v1beta1, Kind=AWXRestore"}
{"level":"info","ts":1651476688.010627,"logger":"controller-runtime.manager.controller.awxrestore-controller","msg":"Starting Controller"}
{"level":"info","ts":1651476688.0106835,"logger":"controller-runtime.manager.controller.awxbackup-controller","msg":"Starting EventSource","source":"kind source: awx.ansible.com/v1beta1, Kind=AWXBackup"}
{"level":"info","ts":1651476688.0108988,"logger":"controller-runtime.manager.controller.awxbackup-controller","msg":"Starting Controller"}
{"level":"info","ts":1651476688.010821,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Starting EventSource","source":"kind source: awx.ansible.com/v1beta1, Kind=AWX"}
{"level":"info","ts":1651476688.0109332,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Starting Controller"}
{"level":"info","ts":1651476688.1118398,"logger":"controller-runtime.manager.controller.awxrestore-controller","msg":"Starting workers","worker count":4}
{"level":"info","ts":1651476688.1119316,"logger":"controller-runtime.manager.controller.awx-controller","msg":"Starting workers","worker count":4}
{"level":"info","ts":1651476688.1119802,"logger":"controller-runtime.manager.controller.awxbackup-controller","msg":"Starting workers","worker count":4}
```

Despite the above logs, the actual state of the environment is this:
```
NAMESPACE       NAME                                               READY   STATUS      RESTARTS      AGE
awx             awx-operator-controller-manager-64976659fc-6htrc   2/2     Running     0             96s
ingress-nginx   ingress-nginx-admission-create-nfv6h               0/1     Completed   0             14h
ingress-nginx   ingress-nginx-admission-patch-j2vcn                0/1     Completed   1             14h
ingress-nginx   ingress-nginx-controller-cc8496874-25pq4           1/1     Running     0             14h
kube-system     coredns-64897985d-bn6k2                            1/1     Running     1 (15h ago)   16h
kube-system     etcd-control-plane                                 1/1     Running     2 (15h ago)   16h
kube-system     kube-apiserver-control-plane                       1/1     Running     2 (15h ago)   16h
kube-system     kube-controller-manager-control-plane              1/1     Running     3 (15h ago)   16h
kube-system     kube-flannel-ds-amd64-bwj5f                        1/1     Running     1 (15h ago)   16h
kube-system     kube-flannel-ds-jgbpk                              1/1     Running     1 (15h ago)   16h
kube-system     kube-proxy-cl5hm                                   1/1     Running     2 (15h ago)   16h
kube-system     kube-scheduler-control-plane                       1/1     Running     2 (15h ago)   16h
kube-system     storage-provisioner                                1/1     Running     3 (15h ago)   16h
```
