### ISSUE TITLE
Instructions: Using AWX with an AWS ALB 

### ISSUE THREAD

**Issue by rust84** [ansible/tower-operator#903]
I am trying to get AWX to work using an ALB in AWS. We had this working in 19.3.0. Have tried various versions of the config below on 20.0.0 and 21.0.0 and am just getting a blank page. Any instructions or examples would be appreciated. Thanks.

![Capture](https://user-images.githubusercontent.com/23284108/166936732-5dcbcb38-c9fa-4b14-92ff-3e30c5793a7a.png)

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  control_plane_ee_image: quay.io/ansible/awx-ee:latest
  service_type: ClusterIP
  ingress_type: Ingress
  ingress_path: "/"
  loadbalancer_protocol: http
  loadbalancer_port: 80
  ingress_path_type: Prefix
  hostname: ansible.our.domain
  ingress_annotations: |
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/load-balancer-name: awx
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-xxxxx, subnet-xxxxxx
    alb.ingress.kubernetes.io/target-type: ip

    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":{ "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=30,stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=3600
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '60'
    service.beta.kubernetes.io/aws-load-balancer-ssl-negotiation-policy: ELBSecurityPolicy-FS-1-2-Res-2020-10
  ee_images:
    - name: gdes-awx-ee
      image: xxxxx.dkr.ecr.eu-west-1.amazonaws.com/awx-ee:5.5.0
  image_pull_policy: Always
  web_resource_requirements:
    requests:
      cpu: 100m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 4Gi
  task_resource_requirements:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  ee_resource_requirements:
    requests:
      cpu: 50m
      memory: 500Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  projects_persistence: true
  projects_existing_claim: awx-project-pvc

```
