### ISSUE TITLE
can't connect awx web interface in firefox

### ISSUE THREAD

**Issue by jskim096** [ansible/tower-operator#905]
**ISSUE TYPE**
- Bug Report

**SUMMARY**
- Unable to access the web interface of AWX, I get this message "Unalbe to connect" in firefox. 

**Here's some more information about my set up:**
- kubernetes version 1.23.6
- AWX Operator 0.21.0
- OS Ubuntu 20.04

**awx-deploy.yml**
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  service_type: nodeport
  nodeport_port: 31818
  projects_persistence: true
  projects_storage_access_mode: ReadWriteOnce
  web_extra_volume_mounts: |
    - name: static-data
      mountPath: /var/lib/projects
  extra_volumes: |
    - name: static-data
      persistentVolumeClaim:
        claimName: static-data-pvc
```
**kubectl get pods**
```
root@awx: /home/awx/awx-operator# kubectl get pods
NAME                                                READY          STATUS      RESTARTS         AGE
awx-operator-controller-manager-675865446d-cwvtp     2/2           Running     2 (102m ago)     3h9m
awx-postges-0                                        1/1           Running     0
awx-544f7bf9c4-zhdtt                                 4/4           Running     2 (11m ago)      23m
```
```
root@awx: /home/awx/awx-operator# kubectl get pods -l "app.kubernetes.io/managed-by=awx-operator"
NAME                   READY   STATUS    RESTARTS   AGE
awx-postgres-0         1/1     Running   0          32m
awx-544f7bf9c4-zhdtt   4/4     Running   4          31m
```
```
**kubectl get svc**
root@awx: /home/awx/awx-operator# kubectl get svc-l "app.kubernetes.io/managed-by=awx-operator"
NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
awx-postgres           ClusterIP   None            <none>        5432/TCP            63m
awx-service            NodePort    10.43.244.23    <none>        80:31818/TCP        62m
```

I think all the installations are complete. but, when I access [**host IP:31818**] in Firefox, can't access it.

I wonder if it's just me. Is there an error in the version?

Please help me.
