### ISSUE TITLE
Q: Does the awx-operator support multiple replicas (HA mode)?

### ISSUE THREAD

**Issue by chuegel** [ansible/tower-operator#917]
##### ISSUE TYPE
 - Question

##### SUMMARY

Does the awx-operator support a HA deployment of AWX with multiple replicas?

Thanks

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 21.0.0
* Kubernetes version: 1.21
* AWX install method: kustomize

**Comment by kladiv** [comment]
+1
What about user sessions (round-robin load balancer on top with no sticky session)?

**Comment by Michandrz** [comment]
I think all you need to add to your deployment yaml is replicas: {{ number_of_desired_instances }}

At least it appears to be working for me.

**Comment by JoseThen** [comment]
Hey @Michandrz , I am curious about user sessions. Have you seen any issues with increasing the replicas? 

I have been trying to increase my AWX instance capacity.

**Comment by Michandrz** [comment]
Yeah, I have. I think that is more related to the GKE LB not maintaining session concurrency.

**Comment by kladiv** [comment]
Hi @Michandrz,
so i guess the way to make it work is to use sticky sessions (session affinity).
- for GKE ingress maybe you can look here: https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#session_affinity
- for NGINX Ingress here: https://kubernetes.github.io/ingress-nginx/examples/affinity/cookie/
- for Traefik Ingress: https://doc.traefik.io/traefik/routing/services/#sticky-sessions

In scenario with external Application Load Balancer (L7), this must be configured on LB.

**Comment by Michandrz** [comment]
Finally had a chance to make that change and have my team looking out for the session tracing will report back with an update in a week or so.

**Comment by pat-s** [comment]
Setting replicas via

```yml
AWX:
  enabled: true
  name: awx
  spec:
    replicas: 2
```

and enabling sticky sessions in the ingress (e.g. NGINX):

```yml
AWX:
  spec:
    ingress_annotations: |
      nginx.ingress.kubernetes.io/affinity: "cookie"
      nginx.ingress.kubernetes.io/session-cookie-name: "AWX-SESSION-COOKIE-COM"
      nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
      nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
      nginx.ingress.kubernetes.io/affinity-mode: persistent
      nginx.ingress.kubernetes.io/session-cookie-hash: sha1
```

results in a stable UE so far for us.
