### ISSUE TITLE
can not execute kustomize build

### ISSUE THREAD

**Issue by tjanitsc** [ansible/tower-operator#919]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
can not execute kustomize build:
TJANITSC-M-66SF:~ tjanitsc$ kustomize build . | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from 'github.com/ansible/awx-operator/config/default?ref=<tag>': evalsymlink failure on '/Users/tjanitsc/github.com/ansible/awx-operator/config/default?ref=<tag>' : lstat /Users/tjanitsc/github.com: no such file or directory': git cmd = '/usr/bin/git fetch --depth=1 origin <tag>': exit status 128
error: no objects passed to apply
TJANITSC-M-66SF:~ tjanitsc$ 

##### ENVIRONMENT
* AWX version: -
* Operator version: -
* Kubernetes version: minikube v1.23.3
* AWX install method: minikube on mac

**Comment by CoffeeAddictGuy** [comment]
Hi, you need set version awx instead of <tag>

**Comment by angelos-se** [comment]
Hi, using kustomize from "microk8s kubectl", I'm seeing a similar error even with proper tag set:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=0.22.0

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.22.0

# Specify a custom namespace in which to install AWX
namespace: awx
```
```
$ kubectl kustomize
error: accumulating resources: accumulation err='accumulating resources from 'github.com/ansible/awx-operator/config/default?ref=0.22.0': evalsymlink failure on '~/awx-operator/github.com/ansible/awx-operator/config/default?ref=0.22.0' : lstat ~/awx-operator/github.com: no such file or directory': git cmd = '/snap/microk8s/3272/usr/bin/git fetch --depth=1 origin 0.22.0': exit status 128
```
Not sure if I'm making some very basic mistake since I'm complete noob to k8s...

**Comment by pipern** [comment]
I have similar error even when putting in the tag:

```
✦ ❯ kustomize build .
Error: accumulating resources: accumulation err='accumulating resources from 'github.com/ansible/awx-operator/config/default?ref=0.23.0': evalsymlink failure on '/home/user/small-demo/ansible-tower/github.com/ansible/awx-operator/config/default?ref=0.23.0' : lstat /home/user/small-demo/ansible-tower/github.com: no such file or directory': git cmd = '/snap/kustomize/31/usr/bin/git init': exit status 1
```

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=0.23.0

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.23.0

# Specify a custom namespace in which to install AWX
namespace: awx
```

```
✦ ❯ kustomize version
{Version:kustomize/v4.5.2 GitCommit:9091919699baf1c5a5bf71b32ca73a993e98088b BuildDate:2022-02-09T23:26:42Z GoOs:linux GoArch:amd64}
```

I thought maybe it needs https at the start of the github URL, otherwise it's looking on local disk? But then the error is even more confusing, since it complains it's a git repo, but indeed, it IS a git repo...

```
✦ ❯ kustomize build .
Error: accumulating resources: accumulation err='accumulating resources from 'https://github.com/ansible/awx-operator/config/default?ref=0.23.0': URL is a git repository': git cmd = '/snap/kustomize/31/usr/bin/git init': exit status 1
```

I'm not quite sure what is wrong, since it means that the first steps at https://github.com/ansible/awx-operator/tree/0.23.0#basic-install do not work. The tag is valid: https://github.com/ansible/awx-operator/releases/tag/0.23.0

**Comment by Korrd** [comment]
I am having this exact same issue.

While following the instructions [listed here](https://github.com/ansible/awx-operator/tree/0.23.0#basic-install), and replacing the <tag> placeholder with `0.23.0` as stated there, I get the same kustmize error: 

```text 
Error: accumulating resources: accumulation err='accumulating resources from 'github.com/ansible/awx-operator/config/default?ref=0.23.0': evalsymlink failure on '/home/ubuntu/awx-deploy/github.com/ansible/awx-operator/config/default?ref=0.23.0' : lstat /home/ubuntu/awx-deploy/github.com: no such file or directory': git cmd = '/snap/kustomize/31/usr/bin/git init': exit status 1
error: no objects passed to apply
```

This is how my `kustomization.yaml` file looks like: 

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Find the latest tag here: https://github.com/ansible/awx-operator/releases
  - github.com/ansible/awx-operator/config/default?ref=0.23.0

# Set the image tags to match the git version from above
images:
  - name: quay.io/ansible/awx-operator
    newTag: 0.23.0

# Specify a custom namespace in which to install AWX
namespace: awx
```
