### ISSUE TITLE
Modify awx-task image

### ISSUE THREAD

**Issue by fculpo** [ansible/tower-operator#921]
Hi,

I want to install pip packages (boto and botocore) and gpg on the awx-task image.
How can I tell the AWX operator to use my custom awx-task image ?

**Comment by PaulVerhoeven1** [comment]
The default image for awx-task is awx (quay.io/ansible/awx) 

You can modify this image by creating your own image that's using AWX as the base.
something like this:

`from quay.io/ansible/awxs:latest`

After this you need to build, tag and push this custom image to an registry and use that custom image in the operator. This can be done by overwriting the default AWX image: 


```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
    image: <your_registry>/<my_custom_image>
    image_version: <my_custom_version>
```

**Comment by fculpo** [comment]
would this work ?

```
FROM quay.io/ansible/awx:latest

USER root
RUN yum install gpg && yum clean all && rm -rf /var/cache/yum

USER 1000

RUN source /var/lib/awx/venv/awx/bin/activate && \
    umask 0022 && \
    pip install botocore boto3 && \
    deactivate
```

**Comment by PaulVerhoeven1** [comment]
@fculpo something like that could be working, that will be trial and error :) I see that AWX itself is based on CentOS (https://github.com/ansible/awx/blob/eec4f8dcc27428cd1aeb1c251d43052a3ea780e8/tools/ansible/roles/dockerfile/templates/Dockerfile.j2#L8) so installing packages with yum is correct. Good luck!

**Comment by fculpo** [comment]
Are you sure that awx image is used ?
Seems that the automation pod that is spawned uses awx-ee image

I get this error message:
```
"Failed to import the required Python library (botocore or boto3) on automation-job-28132-7v5jv's Python /usr/libexec/platform-python. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

The `/usr/libexec/platform-python` is weird

**Comment by fculpo** [comment]
using this seems to fix it
```
- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
```

Not sure why it was using `/usr/libexec/platform-python`
