### ISSUE TITLE
Persisting projects directory and missing gid inside awx pod

### ISSUE THREAD

**Issue by chuegel** [ansible/tower-operator#931]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

We are using [Kadalu ](https://github.com/kadalu/kadalu) through a storage class to provide local storage for our projects directory. 
```yaml
spec:
...
  projects_persistence: true
  projects_storage_class: kadalu-pool-1
  projects_storage_size: 10Gi
...
```
The awx operator runs the init container and changes the permissions and gid of `/var/lib/awx/projects` [here](https://github.com/ansible/awx-operator/blob/3ac0232e89e3fc5a1aa5358ad84d54bb3957d982/roles/installer/templates/deployment.yaml.j2#L61)

The issue is, the awx-web pod does not have a gid 1000:

```bash
bash-5.1$ cat /etc/group
root:x:0:
bin:x:1:
daemon:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mem:x:8:
kmem:x:9:
wheel:x:10:
cdrom:x:11:
mail:x:12:
man:x:15:
dialout:x:18:
floppy:x:19:
games:x:20:
tape:x:33:
video:x:39:
ftp:x:50:
lock:x:54:
audio:x:63:
users:x:100:
nobody:x:65534:
utmp:x:22:
utempter:x:35:
input:x:999:
kvm:x:36:
render:x:998:
systemd-journal:x:190:
systemd-coredump:x:997:
dbus:x:81:
tss:x:59:
sgx:x:996:
systemd-oom:x:995:
nginx:x:994:
ssh_keys:x:993:


bash-5.1$ df -h
Filesystem                          Size  Used Avail Use% Mounted on
overlay                              50G   37G   14G  74% /
tmpfs                                64M     0   64M   0% /dev
tmpfs                                16G     0   16G   0% /sys/fs/cgroup
/dev/mapper/vg00-lv_var             4.0G  2.5G  1.6G  61% /etc/hosts
/dev/mapper/vg00-lv_var_lib_docker   50G   37G   14G  74% /etc/hostname
shm                                  64M  240K   64M   1% /dev/shm
tmpfs                                16G  4.0K   16G   1% /etc/tower/SECRET_KEY
tmpfs                                16G   12K   16G   1% /etc/tower/conf.d/ldap.py
kadalu:kadula-pool-1                1.1G  120K  1.0G   1% /var/lib/awx/projects
tmpfs                                16G   12K   16G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs                                16G     0   16G   0% /proc/acpi
tmpfs                                16G     0   16G   0% /proc/scsi
tmpfs                                16G     0   16G   0% /sys/firmware
```
This results to a permission denied error and  awx fails to write to that volume provided by the Kadalu CSI plugin:

```bash
[2022-05-19 13:37:32.808616 +0000] I [MSGID: 115071] [server-rpc-fops_v2.c:1493:server4_create_cbk] 0-kadula-pool-1-server: CREATE info [{frame=76196}, {path=/subvol/ab/06/pvc-d80a3964-2866-45de-b893-461752a0d6e4/_10__test.lock}, {uuid_utoa=84b64a0e-2e8d-44dd-801b-4551b4342271}, {bname=_10__test.lock}, {client=CTX_ID:b42d0bee-11b4-4ef6-a666-f841aaaf5263-GRAPH_ID:0-PID:35-HOST:kadalu-csi-nodeplugin-9c6hf-PC_NAME:kadula-pool-1-client-0-RECON_NO:-0}, {error-xlator=kadula-pool-1-access-control}, {errno=13}, {error=Permission denied}]
```

##### ENVIRONMENT
* AWX version: 21.0.0
* Operator version: 21.0.0
* Kubernetes version: 1.21
* AWX install method: operator & kustomize

##### STEPS TO REPRODUCE

1. Create a LV and format it with mkfs.xfs
2. Install [Kadalu](https://kadalu.io/docs/k8s-storage/devel/quick-start/)
3. Install Kadalu manifests:

```yaml
apiVersion: kadalu-operator.storage/v1alpha1
kind: KadaluStorage
metadata:
  name: kadula-pool-1
  namespace: kadalu
spec:
  type: Replica3
  storage:
    - node: node1
      device: /dev/vg00/kadalu
    - node: node2
      device: /dev/vg00/kadalu
    - node: node3
      device: /dev/vg00/kadalu
```
4. Install storage class

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kadalu-pool-1
parameters:
  kadalu_format: native
  storage_name: kadalu-pool-1
provisioner: kadalu
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
```
Deploy awx operator with:

```yaml
spec:
...
  projects_persistence: true
  projects_storage_class: kadalu-pool-1
  projects_storage_size: 10Gi
...
```
5. Try to create a project and sync it

6. See the kadalu logs 

##### EXPECTED RESULTS

The gid 1000 should be present inside the awx-web pod  before running the init container mentioned [here](https://github.com/ansible/awx-operator/blob/3ac0232e89e3fc5a1aa5358ad84d54bb3957d982/roles/installer/templates/deployment.yaml.j2#L61)
##### ACTUAL RESULTS
AWX gets permission denied when trying to write project related files inside the volume

##### ADDITIONAL INFORMATION
When running the awx operator with additional information for the init container like:
```yaml
...
spec:
  init_container_extra_commands: |
   chmod 775 /var/lib/awx/projects
   chgrp 0 /var/lib/awx/projects
```
thus, chaging the gid to root, it works as expected and projects can be created and sync-ed within awx.
