### ISSUE TITLE
ldap_password_secret fails to work on deployment

### ISSUE THREAD

**Issue by leasley199** [ansible/tower-operator#937]
##### ISSUE TYPE
 - Unable to use secret to inject LDAP Bind Password.

##### SUMMARY
Unable to inject ldap password into awx deployment via secret, ldap authentication fails. 

##### ENVIRONMENT
* AWX version: 21.1.0
* Operator version: 0.22.0
* Kubernetes version: 1.21.0~
* AWX install method: helm awx operator

##### STEPS TO REPRODUCE

(https://github.com/ansible/awx-operator#enabling-ldap-integration-at-awx-bootstrap)
Create a secret for the LDAP Bind user prior to standing up the awx stack
```
apiVersion: v1
kind: Secret
metadata:
  name: awx-ldap-password
data:
  ldap-password: <VALUE_HERE>
```
Stand-up and source the created secret. 
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
...
spec:
  ldap_cacert_secret: awx-ldap-password
```

##### EXPECTED RESULTS

Expected LDAP Authentication to work.

##### ACTUAL RESULTS

LDAP login fails. 

##### ADDITIONAL INFORMATION

Can get the LDAP working if you add the value <code>AUTH_LDAP_BIND_PASSWORD</code>
to the awx.spec. value 

for example: 
```
apiVersion: awx.ansible.com/v1beta1
kind: AWX
...
spec:
  - setting: AUTH_LDAP_BIND_PASSWORD
    value: 'VALUE_HERE'
```

##### AWX-OPERATOR LOGS
```
2022-06-03 19:06:10,681 ERROR    [4f4822bf266e496fa3279f7ce63b9f81] django_auth_ldap search_s('DC=example,DC=com', 2, '(userprincipalname=username@lhi.com)') raised OPERATIONS_ERROR({'msgtype': 101, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C0907E9, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580'})

2022-06-03 19:06:10,681 DEBUG    [4f4822bf266e496fa3279f7ce63b9f81] django_auth_ldap search_s('DC=example,DC=com', 2, '(userprincipalname=%(user)s)') returned 0 objects:
```

**Comment by fosterseth** [comment]
adding AUTH_LDAP_BIND_PASSWORD as plaintext in the k8s yaml is not secure, so we definitely want to explore a different method for this

**Comment by Zokormazo** [comment]
The best secure approach to make this happen would be using a Secret to store a setting .py file and then mount it using extra volumes in awx containers.

First of all, you'll need to create a secret including a ldap.py settings file including all those sensitive vars you need, let say we call it `ldap`
After that, you can mount it in awx with something like this:

```
Kind: AWX
...
spec:
...
  extra_volumes:
    - name: ldap-config
      secret:
        secretName: ldap
  web_extra_volume_mounts:
    - name: ldap-py
      mountPath: /etc/tower/conf.d/ldap.py
      subPath: ldap.py
  task_extra_volume_mounts:
    - name: ldap-py
      mountPath: /etc/tower/conf.d/ldap.py
      subPath: ldap.py
```

**Comment by leasley199** [comment]
Thanks, I will go about configuring ldap with that path of action

**Comment by leasley199** [comment]
for those who stumble across the same issue as I; add this to your <code> kind:awx </code> file. You can keep all the bootstrap ldap stuff in the file and just pass the password via a secret this way. 
```
  extra_volumes: |
    - name: ldap-config
      secret:
        secretName: awx-ldap-config

  web_extra_volume_mounts: | 
    - name: ldap-config
      mountPath: /etc/tower/conf.d/extra-ldap.py
      subPath: extra-ldap.py
        
  task_extra_volume_mounts: |
    - name: ldap-config
      mountPath: /etc/tower/conf.d/extra-ldap.py
      subPath: extra-ldap.py
```

Create the secret part:
```
apiVersion: v1
kind: Secret
metadata:
  name: awx-ldap-config
  namespace: awx
data:
  extra-ldap.py: ${LDAP BIND PASSWORD HERE | BASE64 }
type: Opaque

```
 Many thanks @[Zokormazo](https://github.com/Zokormazo)

Closing
