### ISSUE TITLE
Metrics and Monitoring related question

### ISSUE THREAD

**Issue by rakesh561** [ansible/tower-operator#938]
What is the best way to monitor/get  awx metrics and status  deployed on kubernetes and send information to Prometheus ?.
Any help would be much appreciated i have been trying on this but not getting much information.
I dont see any information in README.

**Comment by fosterseth** [comment]
you can follow the setup guide here https://docs.ansible.com/automation-controller/4.2.0/html/administration/metrics.html

are there any specific metric you are looking to monitor?

**Comment by rakesh561** [comment]
I'm looking to monitor more around the postgres database health and also some thing like usage of persistent volume created for postgres because especially if file system gets filled up then its going to cause AWX to have issues like jobs going into pending/spinning state.

**Comment by mateuszdrab** [comment]
@fosterseth Am I right in thinking there is no support for a ServiceMonitor with the AWX operator?

**Comment by erlisb** [comment]
Hi @fosterseth,

I think you need to create one manually: 

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: awx-dev
  name: awx-dev-servicemonitor
  namespace: automate-dev
spec:
  endpoints:
  - interval: 30s
    path: /api/v2/metrics/
    port: http
    scheme: http
    scrapeTimeout: 25s
    tlsConfig:
      insecureSkipVerify: true
    bearerTokenSecret:
      key: "token"
      name: "awx-servicemonitor-secret"
  namespaceSelector:
    matchNames:
    - automate-dev
  selector:
    matchLabels:
      app.kubernetes.io/name: awx-dev
```
