### ISSUE TITLE
Company Image Repo because of Company Proxy

### ISSUE THREAD

**Issue by samweisgamdschie** [ansible/tower-operator#939]
##### ISSUE TYPE
 - awx-operator installation stops installing because it tries to pull `_init_container_image: quay.io/centos/centos` directly from quay.io.
 - We changed all images possible to configure but there are some images left in the operator directly.

##### SUMMARY
In our company, we have a 'very nice' proxy, where we need to jump over it. We also have an jfrog artifactory, where all container image sources are configured, where we do not need to configure a proxy, but to change all image repos. Sadly, in awx-operator it is not possible to change every image source, so it tries to pull at least the one above directly from quay.io.

##### ENVIRONMENT
* AWX version: not known since it does not finish to install.
* Operator version: 0.21.0
* Kubernetes version: Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

* AWX install method: awx-operator

**Comment by PaulVerhoeven1** [comment]
hi @samweisgamdschie,

You can override the default `init_container` by deploying this manifest:

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: NodePort
  init_container_image: <your_custom_init_container>
  init_container_image_version: <your_custom_init_container_version>


.....
```
