### ISSUE TITLE
awx gui not working with k8s ingress

### ISSUE THREAD

**Issue by gtamilse1** [ansible/tower-operator#966]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

When access the awx GUI through the ingress service I only see a blank screen with no application page rendered. I was able to check the logs on the awx-web container and do see the request come with response 200, however all i see is a blank screen no http error codes.

### AWX Operator version

0.23.0

### AWX version

21.2.0

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

1.20.2

### Modifications

no

### Steps to reproduce

 install operator, install awx pods, install ingress with provided config and try to access the gui at node ip and specified https/http port with awx path. 

AWX Deployment yml file
```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awxtc2
  namespace: awx

spec:

  projects_persistence: true
  projects_storage_access_mode: ReadWriteOnce

  admin_user: admin
  admin_password_secret: awx-admin-password

  # Execution Environment
  ee_extra_env: |
    - name: https_proxy
      value: ""
    - name: http_proxy
      value: ""
    - name: no_proxy
      value: ""
    - name: HTTPS_PROXY
      value: ""
    - name: HTTP_PROXY
      value: ""
    - name: NO_PROXY
      value: ""
```

AWX Ingress yml file
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awxtc2-ingress
  namespace: awx
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  # - host: sreawx.local
  - http:
      paths:
      - pathType: Prefix
        path: /awx
        backend:
          service:
            name: awxtc2-service
            port:
              number: 80
```

Captures:

Pod information
```
[root@master clusteriptest]# k get all -n awx
NAME                                                   READY   STATUS    RESTARTS   AGE
pod/awx-operator-controller-manager-64c49f59b8-zgwck   2/2     Running   0          5d1h
pod/awxtc2-7fc9c7bb-ftkkh                              4/4     Running   1          56m
pod/awxtc2-postgres-0                                  1/1     Running   0          57m

NAME                                                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/awx-operator-controller-manager-metrics-service   ClusterIP   10.109.212.39   <none>        8443/TCP   5d1h
service/awxtc2-postgres                                   ClusterIP   None            <none>        5432/TCP   57m
service/awxtc2-service                                    ClusterIP   10.106.1.53     <none>        80/TCP     57m

NAME                                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/awx-operator-controller-manager   1/1     1            1           5d1h
deployment.apps/awxtc2                            1/1     1            1           56m

NAME                                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/awx-operator-controller-manager-64c49f59b8   1         1         1       5d1h
replicaset.apps/awxtc2-7fc9c7bb                              1         1         1       56m

NAME                               READY   AGE
statefulset.apps/awxtc2-postgres   1/1     57m
```

K8s Ingress Nginx Setup
```
[root@master awx-operator]# k describe service/ingress-nginx-controller -n ingress-nginx
Name:                     ingress-nginx-controller
Namespace:                ingress-nginx
Labels:                   app.kubernetes.io/component=controller
                          app.kubernetes.io/instance=ingress-nginx
                          app.kubernetes.io/name=ingress-nginx
                          app.kubernetes.io/part-of=ingress-nginx
                          app.kubernetes.io/version=1.2.1
Annotations:              <none>
Selector:                 app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
Type:                     NodePort
IP Families:              <none>
IP:                       <hidden>
IPs:                      <hidden>
Port:                     http  80/TCP
TargetPort:               http/TCP
NodePort:                 http  30421/TCP
Endpoints:                <hidden>:80
Port:                     https  443/TCP
TargetPort:               https/TCP
NodePort:                 https  31647/TCP
Endpoints:                <hidden>:443
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
I checked the awx-task and awx-web contatiner logs and both have booted up normally, no errors seen.

### Expected results

To see awx login screen on accessing http://<hidden>:30421/awx or https://<hidden>:31647/awx

### Actual results

Blank screen with no error codes, inspection of the page shows CSS + JS not found

Captures from awx-web container when hitting the above url -> tried from different browsers still not working

```
[root@master awx-operator]# k -n awx logs -f awxtc2-7fc9c7bb-ftkkh -c awxtc2-web --tail=15
2022-06-27 17:40:22,760 DEBUG    [116af758c2ec420f900a280e41f5a442] awx.analytics.performance request: <WSGIRequest: GET '/'>, response_time: 0.031s
<hidden> - - [27/Jun/2022:17:40:22 +0000] "GET / HTTP/1.1" 200 1061 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36" "<hidden>"
[pid: 34|app: 0|req: 6/17] <hidden> () {64 vars in 1110 bytes} [Mon Jun 27 17:40:22 2022] GET / => generated 1061 bytes in 32 msecs (HTTP/1.1 200) 7 headers in 269 bytes (1 switches on core 0)

2022-06-27 17:41:19,340 DEBUG    [4a620cb1d57340e99479423c507b1698] awx.analytics.performance request: <WSGIRequest: GET '/'>, response_time: 0.131s
[pid: 35|app: 0|req: 2/18] <hidden> () {62 vars in 999 bytes} [Mon Jun 27 17:41:19 2022] GET / => generated 1061 bytes in 132 msecs (HTTP/1.1 200) 7 headers in 269 bytes (1 switches on core 0)
<hidden> - - [27/Jun/2022:17:41:19 +0000] "GET / HTTP/1.1" 200 1061 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0" "<hidden>"
```
