### ISSUE TITLE
Kubernetes 1.20 --> FailedToUpdateEndpoint

### ISSUE THREAD

**Issue by metabsd** [ansible/tower-operator#97]
Kubernetes version : `Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.1-34+e7db93d188d0d1", GitCommit:"e7db93d188d0d12f2fe5336d1b85cdb94cb909d3", GitTreeState:"clean", BuildDate:"2021-01-11T23:50:46Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}`

The ingress is not working properly. Everything else is ok.

![image](https://user-images.githubusercontent.com/7953470/107809083-8e6c7200-6d38-11eb-85d8-9d12a67ae9df.png)

**Comment by shanemcd** [comment]
Hello. Were you deploying the operator from devel, or did you use a specific tag?

**Comment by metabsd** [comment]
I used the one in the readme.md and I just see that is the devel. You recommended to use the release ?

**Comment by metabsd** [comment]
I also try the release 0.6.0 and I have the same problem. If you want me to try couple thing to identify the source of the problem, let me know. Thx in advance for your great work on this Operator.

**Comment by metabsd** [comment]
I think the problem come from the definition of the service with k8s 1.20. When I use 1.19 everything work fine. I will try to build my own operator and make it work with 1.20.

**Comment by metabsd** [comment]
Devel also point to release `quay.io/ansible/awx-operator:0.6.0`

**Comment by metabsd** [comment]
I have redeployed the cluster to K8s 1.19 and everything is fine. The problem is really related to 1.20

**Comment by tchellomello** [comment]
Adding on my plate to test it. I´ll upgrade my cluster to `1.20` tonight and test it.

**Comment by ilijamt** [comment]
I don't have this issue and I'm on k8s 1.20, worked for me with 0.6.0, 0.7.0 and 0.8.0 awx operator.

k8s setup with RKE.

I tried upgrade from 0.6.0 to 0.7.0 then to 0.8.0.
And also blank 0.8.0

**Comment by tchellomello** [comment]
I just tested locally and worked for me 
```yaml
kubectl get nodes                                                                                                                    22:07:07
NAME     STATUS                        ROLES                         AGE   VERSION
p50      Ready                         worker                        29h   v1.20.6
p70      Ready                         control-plane,master,worker   29h   v1.20.6
r610n1   NotReady,SchedulingDisabled   worker                        29h   v1.20.6
r610n2   NotReady,SchedulingDisabled   worker                        29h   v1.20.6
t470n1   Ready                         control-plane,master,worker   29h   v1.20.6
t470n2   Ready                         control-plane,master,worker   29h   v1.20.6
```

```yaml
# kubectl get pods
default                awx-operator-5f48c87dd6-sqc4c                                     0/1     Pending     0          0s      <none>           <none>   <none>           <none>
default                awx-operator-5f48c87dd6-sqc4c                                     0/1     Pending     0          0s      <none>           p70      <none>           <none>
default                awx-operator-5f48c87dd6-sqc4c                                     0/1     ContainerCreating   0          0s      <none>           p70      <none>           <none>
default                awx-operator-5f48c87dd6-sqc4c                                     1/1     Running             0          17s     10.233.64.104    p70      <none>           <none>
```

```yaml
 kubectl images awx                                                                                                                   22:07:25
[Summary]: 1 namespaces, 1 pods, 1 containers and 1 different images
+-------------------------------+---------------+-----------------------------------------------+
|            PodName            | ContainerName |                ContainerImage                 |
+-------------------------------+---------------+-----------------------------------------------+
| awx-operator-5f48c87dd6-sqc4c | awx-operator  | registry.tatu.home/ansible/awx-operator:devel |
+-------------------------------+---------------+-----------------------------------------------+
```

Deployed a fresh `awx`  and worked fined. 
```yaml
kubectl get awx awx-special -o yaml | kubectl neat 
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  labels:
    app.kubernetes.io/component: awx
    app.kubernetes.io/managed-by: awx-operator
    app.kubernetes.io/name: awx-special
    app.kubernetes.io/part-of: awx-special
  name: awx-special
  namespace: default
spec:
  tower_admin_user: admin
  tower_create_preload_data: true
  tower_garbage_collect_secrets: true
  tower_image_pull_policy: IfNotPresent
  tower_loadbalancer_port: 80
  tower_loadbalancer_protocol: http
  tower_projects_persistence: false
  tower_projects_storage_access_mode: ReadWriteMany
  tower_projects_storage_size: 8Gi
  tower_replicas: 1
  tower_route_tls_termination_mechanism: Edge
  tower_task_privileged: false

default                awx-special-5854c7766f-rfpp6                                      0/4     Pending             0          0s      <none>           <none>   <none>           <none>
default                awx-special-5854c7766f-rfpp6                                      0/4     Pending             0          0s      <none>           t470n1   <none>           <none>
default                awx-special-5854c7766f-rfpp6                                      0/4     ContainerCreating   0          1s      <none>           t470n1   <none>           <none>
default                awx-special-5854c7766f-rfpp6                                      4/4     Running             0          24s     10.233.65.36     t470n1   <none>           <none>
```

Closing since it worked for me. If you still are hitting this issue, please reopen with more details so we can investigate it further. Thanks!
