### ISSUE TITLE
Pulling EE from Gitlab

### ISSUE THREAD

**Issue by DomPolizzi** [ansible/tower-operator#974]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx-operator/issues) for duplicates.
- [X] I understand that the AWX Operator is open source software provided for free and that I might not receive a timely response.

### Bug Summary

In an attempt to optimize my environment, I have attempted to add a custom EE variable to my AWX deployment.
I am using ansible Builder in a CI Gitlab pipeline which pulls the latest AWX version when run.
I have tested this EE locally and have successfully pulled the image from Gitlab to the AWX application when spun up.

My issue however is when I attempt to use this image in my deployment, my operator only deploys the Redis container successfully. The other containers fail.

Is this a configuration issue or is there an actual bug with pulling EEs?

### AWX Operator version

0.22.0, 0.23.0

### AWX version

latest

### Kubernetes platform

kubernetes

### Kubernetes/Platform version

v1.23.7

### Modifications

no

### Steps to reproduce

AWX EE Container is created as follows: 
```
ansible-builder:
  image: docker:20.10-dind
  services:
    - docker:20.10-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - apk add --update python3 && ln -sf python3 /usr/bin/python
    - ./create-container.sh # installs ansible and ansible builder 1.1.0
    - . builder/bin/activate
    - ansible-builder build --tag $CI_REGISTRY_IMAGE --container-runtime docker -v 3
    - docker push $CI_REGISTRY_IMAGE
```

pulled into Kubernetes with a secret as follows:
```
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-pull-dev
  namespace: awx
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: #base64 dockerconfigjson
```

With the following deployment

```
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: dev-awx-env-app
  namespace: awx
spec:
  replicas: 1
  no_log: "false"
  #  auto_upgrade: false
  hostname: dev-awx.kube.my-domain.com
  service_type: nodeport
  nodeport_port: 30626
  ### Custom Image: # Pull works, but I think there is a versioning issue, today awx-operator v.23 was released
  image: registry.gitlab.com/my-domain.com/devops/r_and_ds/awx-kube-deploy
  image_pull_policy: Always
  image_version: latest
  ee_pull_credentials_secret: gitlab-pull-dev
  image_pull_secrets:
    - gitlab-pull-dev # from container-registry.yml which is base64 .dockerconfigjson
  ee_images:
    - name: awx-custom-ee
      image: registry.gitlab.com/my-domain.com/devops/r_and_ds/awx-kube-deploy
  control_plane_ee_image: registry.gitlab.com/my-domain.com/devops/r_and_ds/awx-kube-deploy
  ### Postgres Config:
  postgres_image: postgres:12
  postgres_storage_requirements:
    requests:
      storage: 8Gi
  ### Storage Class Config:
  projects_storage_access_mode: ReadWriteMany
  projects_storage_class: dev-awx-env-sc
  ### Web App Kubelet Config:
  web_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
  ### Task Kubelet Config:
  task_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
  ### EE Kubelet Config:
  ee_resource_requirements:
    requests:
      cpu: 500m
      memory: 1Gi
---
```

### Expected results

Custom EE is the EE in my Pod

### Actual results

Failure initializing

```
  Normal   Scheduled  48s                default-scheduler  Successfully assigned awx/dev-awx-env-app-7fb9c96674-pg9tz to worker-node-01
  Normal   Pulling    48s                kubelet            Pulling image "docker.io/redis:latest"
  Normal   Pulled     47s                kubelet            Successfully pulled image "docker.io/redis:latest" in 129.876983ms
  Normal   Created    47s                kubelet            Created container redis
  Normal   Started    47s                kubelet            Started container redis
  Normal   Pulled     27s                kubelet            Successfully pulled image "registry.gitlab.com/my-domain.com//devops/r_and_ds/awx-kube-deploy:latest" in 20.05207404s
  Normal   Pulling    19s                kubelet            Pulling image "registry.gitlab.com/my-domain.com//devops/r_and_ds/awx-kube-deploy"
  Normal   Pulled     19s                kubelet            Successfully pulled image "registry.gitlab.com/my-domain.com//devops/r_and_ds/awx-kube-deploy:latest" in 8.44779278s
  Normal   Pulled     18s                kubelet            Successfully pulled image "registry.gitlab.com/my-domain.com//devops/r_and_ds/awx-kube-deploy" in 358.876026ms
  Normal   Created    18s                kubelet            Created container dev-awx-env-app-ee
  Normal   Started    18s                kubelet            Started container dev-awx-env-app-ee
  Normal   Pulling    18s (x2 over 47s)  kubelet            Pulling image "registry.gitlab.com/my-domain.com//devops/r_and_ds/awx-kube-deploy:latest"
  Normal   Pulled     13s                kubelet            Successfully pulled image "registry.gitlab.com/my-domain.com//devops/r_and_ds/awx-kube-deploy:latest" in 4.533269679s
  Normal   Started    13s (x2 over 27s)  kubelet            Started container dev-awx-env-app-web
  Normal   Pulling    13s (x2 over 27s)  kubelet            Pulling image "registry.gitlab.com/my-domain.com//devops/r_and_ds/awx-kube-deploy:latest"
  Normal   Created    13s (x2 over 27s)  kubelet            Created container dev-awx-env-app-web
  Normal   Started    8s (x2 over 19s)   kubelet            Started container dev-awx-env-app-task
  Normal   Created    8s (x2 over 19s)   kubelet            Created container dev-awx-env-app-task
  Normal   Pulled     8s                 kubelet            Successfully pulled image "registry.gitlab.com/my-domain.com//devops/r_and_ds/awx-kube-deploy:latest" in 5.658320816s
  Warning  BackOff    7s                 kubelet            Back-off restarting failed container
```

**Comment by kurokobo** [comment]
The container images that for EE and for AWX are completely different. Only EE images can be built with Ansible Builder, and in most use cases you do not need to build AWX images yourself.

Thus, following lines are correct to use your custom EE,

```yaml
  ee_images:
    - name: awx-custom-ee
      image: registry.gitlab.com/my-domain.com/devops/r_and_ds/awx-kube-deploy
  control_plane_ee_image: registry.gitlab.com/my-domain.com/devops/r_and_ds/awx-kube-deploy
```

but `image` has to refer AWX image instead of EE image.

```yaml
  image: registry.gitlab.com/my-domain.com/devops/r_and_ds/awx-kube-deploy
  ...
  image_version: latest
```

Simply remove `image` and `image_version` to use default AWX image, or specify an image from `quay.io/ansible/awx:<tag>`.
